### ISSUE TITLE
UnknownHostException in ChromeDriverManager.getInstance().setup();

### ISSUE THREAD

**Issue by smtripathi99** [bonigarcia/webdrivermanager#10]
I am not able to get the latest chrome driver using ChromeDriverManager:

FAILED CONFIGURATION: @BeforeClass setUp
java.lang.RuntimeException: java.net.UnknownHostException: chromedriver.storage.googleapis.com
	at io.github.bonigarcia.wdm.BrowserManager.manage(BrowserManager.java:206)
	at io.github.bonigarcia.wdm.BrowserManager.setup(BrowserManager.java:88)
	at io.github.bonigarcia.wdm.BrowserManager.setup(BrowserManager.java:73)
	at test.java.base.Base.startDriver(Base.java:75)
	at test.java.base.Base.launchUrl(Base.java:85)
	at test.java.tests.LoginTest.setUp(LoginTest.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.in

**Comment by smtripathi99** [comment]
pom:

<dependency>
			<groupId>io.github.bonigarcia</groupId>
			<artifactId>webdrivermanager</artifactId>
			<version>RELEASE</version>
		</dependency>

**Comment by bonigarcia** [comment]
It seems a DNS problem solving the address "chromedriver.storage.googleapis.com", in which chromedriver binaries are hosted. This site (http://chromedriver.storage.googleapis.com/) seems up and running to me, and webdrivermanager is working properly.

It might be a problem of your DNS setup. Could you please confirm that?

**Comment by smtripathi99** [comment]
Yes, Thanks it was due to network issue.
