### ISSUE TITLE
Could not start a new session. Using Gradle on GitHub actions

### ISSUE THREAD

**Issue by nsowers20** [bonigarcia/webdrivermanager#1003]
I am currently trying to write Selenium tests that are run using Gradle with Github actions. I am running these on a local server. I am able to get the tests to run just fine locally but can not get them to work in the GitHub actions

**Chrome: 110.0.5481.105**

**Windows 10 locally, I am not sure what version of ubuntu the server is running on**
**5.3.2**:

```
public class CIHomePage {

    private WebDriver driver;

    @BeforeClass
    public static void setupWebdriverChromeDriver() {
        WebDriverManager.chromedriver().setup();
    }

    @Before
    public void setup() {
        ChromeOptions options = new ChromeOptions();
        options.addArguments("--headless", "--disable-gpu", "--window-size=1920,1200","--ignore-certificate-errors","--disable-extensions","--no-sandbox","--disable-dev-shm-usage");
        driver = new ChromeDriver(options);
        driver.manage().window().maximize();
        driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
    }

    @After
    public void teardown() {
        if (driver != null) {
            driver.quit();
        }
    }

    @Test
    public void homePageTitle() throws InterruptedException{
        driver.get("https://devcontinuousimprovement.vermeer.com/index.html");
        driver.findElement(By.id("Ecom_Password")).sendKeys("a password");
        driver.findElement(By.id("Ecom_User_ID")).sendKeys("a username");
        driver.findElement(By.id("loginButton2")).click();
        new WebDriverWait(driver, Duration.ofSeconds(10)).until(ExpectedConditions.titleIs(("Continuous Improvement - Event Name Overview")));
    }
```

```
org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure. 
 at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:60) 
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:561)	
at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:229)	
at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:157)	
at org.openqa.selenium.chromium.ChromiumDriver.<init>(ChromiumDriver.java:101)	
at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:82)	
at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:71)	
at CIHomePage.setup(CIHomePage.java:49)	
at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)	
at java.lang.reflect.Method.invoke(Method.java:578)	
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)	
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)	
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)	
at org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33)	
at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)	
at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)	
at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)	
at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)	
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)	
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)	
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)	
at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)	
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)	
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)	
at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)	
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)	
at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)	
at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)	
at org.junit.runners.ParentRunner.run(ParentRunner.java:413)	
at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:108)	
at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)	
at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:40)	
at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:60)	
at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:52)	
at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)	
at java.lang.reflect.Method.invoke(Method.java:578)	
at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)	
at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)	
at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)	
at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)	
at jdk.proxy1.$Proxy2.processTestClass(Unknown Source)	
at org.gradle.api.internal.tasks.testing.worker.TestWorker$2.run(TestWorker.java:176)	
at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)	
at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)	
at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)	
at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)	
at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:113)	
at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:65)	
at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)	
at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)

Caused by: org.openqa.selenium.WebDriverException: Driver server process died prematurely. 
  Build info: version: '4.8.0', revision: '267030adea' 
  System info: os.name: 'Linux', os.arch: 'amd64', os.version: '4.18.0-372.9.1.el8.x86_64', java.version: '19.0.2' 
  Driver info: driver.version: ChromeDriver

at org.openqa.selenium.remote.service.DriverService.start(DriverService.java:244)	
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:98)	
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)	
at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:229)	
at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:157)	
at org.openqa.selenium.chromium.ChromiumDriver.<init>(ChromiumDriver.java:101)	
at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:82)	
at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:71)	
at CIHomePage.setup(CIHomePage.java:49)	
at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)	
at java.lang.reflect.Method.invoke(Method.java:578)	
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)	
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)	
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)	
at org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33)	
at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)	
at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)	
at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)	
at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)	
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)	
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)	
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)	
at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)	
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)	
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)	
at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)	
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)	
at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)	
at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)	
at org.junit.runners.ParentRunner.run(ParentRunner.java:413)	
at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:108)	
at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)	
at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:40)	
at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:60)	
at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:52)	
at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)	
at java.lang.reflect.Method.invoke(Method.java:578)	
at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)	
at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)	
at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)	
at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)	
at jdk.proxy1.$Proxy2.processTestClass(Unknown Source)	
at org.gradle.api.internal.tasks.testing.worker.TestWorker$2.run(TestWorker.java:176)	
at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)	
at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)	
at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)	
at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)	
at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:113)	
at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:65)	
at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)	
at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
```

```
/home/docker/.cache/selenium/chromedriver/linux64/110.0.5481.77/chromedriver: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory
```

**Comment by bonigarcia** [comment]
This is not a issue due to WebDriverManager. It seems you need to install some dependencies in your Ubuntu machine to solve the `libnss3.so` (see for instance [here](https://stackoverflow.com/questions/58134793/error-while-loading-shared-libraries-libnss3-so-while-running-gtlab-ci-job-to)).
