### ISSUE TITLE
v5.3.2 and ClassNotFoundException: org.apache.hc.client5.http.config.ConnectionConfig

### ISSUE THREAD

**Issue by emeraldjava** [bonigarcia/webdrivermanager#1019]
**Description of the problem**: 

Running the 5.3.2 WebDriverManager on setup() and we get this missing apache http client class is missing.  Using java 11.

Could it be there is an extra dependency which 5.3.2 needs and we have to add to our pom? 

Reveting to 5.2.3 and the issue resolves its self.

**Browser and version**: 

headless

**Operating system**: 

Windows

**WebDriverManager version**: 

<dependency>
            <groupId>io.github.bonigarcia</groupId>
            <artifactId>webdrivermanager</artifactId>
            <version>5.3.2</version>

**WebDriverManager call**: 

WebDriverManager.getInstance(DriverManagerType.CHROME).setup();

**WebDriverManager traces**:

Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/hc/client5/http/config/ConnectionConfig
	at io.github.bonigarcia.wdm.online.HttpClient.<init>(HttpClient.java:121)
	at io.github.bonigarcia.wdm.WebDriverManager.setup(WebDriverManager.java:405)
	at com.mc..message.util.ControlPanelWebDriver.<init>(AxonControlPanelWebDriver.java:71)
	at com.mc.message.util.ControlPanelWebDriver.main(AxonControlPanelWebDriver.java:57)
Caused by: java.lang.ClassNotFoundException: org.apache.hc.client5.http.config.ConnectionConfig
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)

**Error log**:

**Comment by emeraldjava** [comment]
Could i make a PR and update the https://github.com/bonigarcia/webdrivermanager-spring-boot/ README to include the details above, as a sub-section?

**Comment by bonigarcia** [comment]
The best place to document this is in the [known issues](https://bonigarcia.dev/webdrivermanager/#known-issues) section in the WebDriverManager doc. Please send your PR to include it there. You simply need to change the [asciidoc source](https://github.com/bonigarcia/webdrivermanager/blob/master/src/doc/asciidoc/index.adoc).

**Comment by editrocchio** [comment]
The fix didn't work for my Spring boot project. I added the dependency:

        <dependency>
            <groupId>org.apache.httpcomponents.client5</groupId>
            <artifactId>httpclient5</artifactId>
            <version>5.2.1</version>
            <scope>test</scope>
        </dependency>

But I get this error when WebDriverManager.firefoxdriver() is called:

Caused by: java.lang.NoClassDefFoundError: org/apache/hc/core5/http/ClassicHttpRequest
	at com.service.snapshot.util.SeleniumUtil.initFirefoxWebDriver(SeleniumUtil.java:101) ~[classes/:na]
	at com.hive.service.snapshot.util.SeleniumUtil.initializeWebDriver(SeleniumUtil.java:222) ~[classes/:na]
	at com.hive.service.snapshot.util.SeleniumUtil.build(SeleniumUtil.java:65) ~[classes/:na]
	at com.hive.service.snapshot.util.SeleniumUtil.build(SeleniumUtil.java:58) ~[classes/:na]
	at com.hive.service.snapshot.Snapshot.<init>(Snapshot.java:29) ~[classes/:na]
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)

**Comment by neblung** [comment]
I also had classloading problems after adding a new module to a spring-boot-2.6 project.

    java.lang.NoClassDefFoundError: org/openqa/selenium/internal/Require

Inspecting the Effective POM I found out, that inherited transitive dependencies were too old.
Adjusting following versions in the module's pom.xml solved the problem.

    <properties>
      <selenium.version>4.10.0</selenium.version>
      <webdrivermanager.version>5.3.3</webdrivermanager.version>
      <httpclient5.version>5.2.1</httpclient5.version>
      <httpcore5.version>5.2.1</httpcore5.version>
    </properties>

    <dependencies>
      <dependency>
        <groupId>org.seleniumhq.selenium</groupId>
        <artifactId>selenium-java</artifactId>
        <version>${selenium.version}</version>
        <scope>test</scope>
      </dependency>
      <dependency>
        <groupId>io.github.bonigarcia</groupId>
        <artifactId>webdrivermanager</artifactId>
        <version>${webdrivermanager.version}</version>
      </dependency>
      ...
