### ISSUE TITLE
Problem fetching web driver behind a Proxy. 

### ISSUE THREAD

**Issue by cicaD** [bonigarcia/webdrivermanager#1023]
Hi. 
I have problem fetching web driver on system behind a proxy.
When configure WebDriverManager usind proxy host name and port everithing works fine:
WebDriverManager.chromedriver().proxy("proxyHost:proxyPort").setup(); 

But when I 
am using Java  ProxySelector to discover configured proxy URL + port, making code more generic:

System.setProperty("java.net.useSystemProxies", "true");
			List<Proxy> proxyList = ProxySelector.getDefault().select(new URI(testURI));

Tying then to fetch web driver using proxy data get from ProxySelector (data was same as when I did it directly, in first place)
WebDriverManager.chromedriver().proxy("proxyHost:proxyPort").setup(); 

results in : 

io.github.bonigarcia.wdm.config.WebDriverManagerException: io.github.bonigarcia.wdm.config.WebDriverManagerException: java.net.SocketException: Malformed reply from SOCKS server
	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:1423)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:1204)
	at io.github.bonigarcia.wdm.WebDriverManager.fallback(WebDriverManager.java:1439)
	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:1420)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:1204)
	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:1413)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:1204)
	at io.github.bonigarcia.wdm.WebDriverManager.setup(WebDriverManager.java:419)
	at com.folksam.selenium.proxyTest.ProxyDetectTest.proxyDetectionTest3(ProxyDetectTest.java:197)
Caused by: io.github.bonigarcia.wdm.config.WebDriverManagerException: java.net.SocketException: Malformed reply from SOCKS server
	at io.github.bonigarcia.wdm.WebDriverManager.getDriversFromXml(WebDriverManager.java:1577)
	at io.github.bonigarcia.wdm.managers.ChromeDriverManager.getDriverUrls(ChromeDriverManager.java:106)

I have noticed that as soon as I set :  
System.setProperty("java.net.useSystemProxies", "true");

I get WebDriverManagerException as above.

What could  cause this problem?

OS: Windows
Using Java implementation of WDM:

<dependency>
			<groupId>io.github.bonigarcia</groupId>
			<artifactId>webdrivermanager</artifactId>
			<version>5.3.2</version>
		</dependency>

**Comment by bonigarcia** [comment]
Hello, I don't know what is the cause of the problem, sorry. I suppose is something related to your proxy setup, but for sure it is not on the WebDriverManager side.
