### ISSUE TITLE
Exception reading resolution cache as a properties file

### ISSUE THREAD

**Issue by githubist16** [bonigarcia/webdrivermanager#1040]
**Description of the problem**: Unable to start a browser session due to webdriver management issues. Tried downgrading browser to match 113.0.5672.63, tried upgrading webdriver version, tried manually creating cache path and resolutions.properties (this gave a malformed url exception), among other things and simply cant get this to work. Is something wrong with the webdrivermanager instantiation I have?

**Browser and version**:
Browser version: Google Chrome 113.0.5672.92
Chromedriver version: 113.0.5672.63

**Operating system**: Amazon Linux AMI release 2018.03 (Amazon linux 2)

**WebDriverManager version**: 5.3.2

**WebDriverManager traces**: None

**WebDriverManager call**: 
                   
      WebDriverManager.chromedriver().driverVersion("113.0.5672.63").forceDownload().cachePath("~/.cache/selenium").setup();
      ChromeOptions options = new ChromeOptions();
      String osName = ThreadProp.getInstance().getProperty("os.name");
      options.setPageLoadStrategy(PageLoadStrategy.NORMAL);
      if(osName != null && osName.contains("nux")) {
            options.addArguments("--no-sandbox", "--start-maximized", "--headless=new", "--disable-gpu", "window-size=1920,1080");
            options.setExperimentalOption("prefs", prefs);

       }else {
           options.addArguments("--no-sandbox", "--start-maximized", "window-size=1920,1080");
           options.setExperimentalOption("prefs", prefs);
      }
      
     webDriver = new ChromeDriver(options);
     webDriver.manage().window();
     webDriver.manage().window().maximize();

**Error log**: 
io.github.bonigarcia.wdm.config.WebDriverManagerException: Exception reading resolution cache as a properties file
        at io.github.bonigarcia.wdm.cache.ResolutionCache.<init>(ResolutionCache.java:86)
        at io.github.bonigarcia.wdm.WebDriverManager.lambda$getResolutionCache$2(WebDriverManager.java:1650)
        at java.util.Optional.orElseGet(Optional.java:267)
        at io.github.bonigarcia.wdm.WebDriverManager.getResolutionCache(WebDriverManager.java:1649)
        at io.github.bonigarcia.wdm.WebDriverManager.clearResolutionCache(WebDriverManager.java:831)
        at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:1409)
        at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:1204)
        at io.github.bonigarcia.wdm.WebDriverManager.setup(WebDriverManager.java:419)
        at com.automation.Utilities.General.Driver.createBrowserDriver(Driver.java:218)
        at 
Caused by: java.io.FileNotFoundException: /home/ec2-user/.cache/selenium (Is a directory)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at io.github.bonigarcia.wdm.cache.ResolutionCache.<init>(ResolutionCache.java:81)
        at io.github.bonigarcia.wdm.WebDriverManager.lambda$getResolutionCache$2(WebDriverManager.java:1650)
        at java.util.Optional.orElseGet(Optional.java:267)
        at io.github.bonigarcia.wdm.WebDriverManager.getResolutionCache(WebDriverManager.java:1649)
        at io.github.bonigarcia.wdm.WebDriverManager.clearResolutionCache(WebDriverManager.java:831)
        at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:1409)
        at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:1204)
        at io.github.bonigarcia.wdm.WebDriverManager.setup(WebDriverManager.java:419)
        at com.automation.Utilities.General.Driver.createBrowserDriver(Driver.java:218)

**Comment by sela55** [comment]
Any solution?
I'm also cant run anything because of this mismatch.

**Comment by bryanvaldellonsdet** [comment]
I solved this issue by upgrading webdriver manger to` 5.2.0 `and adding maven run options below. resolutionCachePath and resolutionCachePath directories will be the storage of the drivers and resolutions rather than using the default paths. I choose to store it on the project folder. For some reason, the default path is not available on our Linux runners causing our error.

```
"-Dwdm.cachePath={pathToProjectDir}/seleniumCache" \
"-Dwdm.resolutionCachePath={pathToProjectDir}/resolutionCachePath"
```
