### ISSUE TITLE
Unable to download the chrome webdriver within a proxy environment(VPN) while using the managed WebDriver

### ISSUE THREAD

**Issue by poojaBjAcharya** [bonigarcia/webdrivermanager#1044]
We get an error like below when we run the test with the managed driver inside the company VPN. 

**Logs**

May 19, 2023 9:57:41 AM org.openqa.selenium.remote.service.DriverService findExecutable
WARNING: Unable to obtain driver using Selenium Manager: Unsuccessful command executed: [C:\Users\nishiveg\AppData\Local\Temp\selenium-manager864406660971009152018627625866544\selenium-manager.exe, --driver, chromedriver]
ERROR error sending request for url (https://chromedriver.storage.googleapis.com/113.0.5672.63/chromedriver_win32.zip): error trying to connect: tcp connect error: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (os error 10060)

Build info: version: '4.8.1', revision: '8ebccac989'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_332'
Driver info: driver.version: ChromeDriver
09:57:19.846 [main] INFO n.s.c.w.d.ChromeDriverProvider - Starting Chrome driver instance with capabilities:
09:57:19.849 [main] INFO n.s.c.w.d.ChromeDriverProvider - Capabilities {acceptInsecureCerts: true, browserName: chrome, goog:chromeOptions: {args: [remote-allow-origins=, test-type, no-sandbox, ignore-certificate-errors, --window-size=1000,800, incognito, disable-infobars, disable-gpu, disable-default-apps, disable-popup-blocking, remote-allow-origins=, test-type, no-sandbox, ignore-certificate-errors, --window-size=1000,800, incognito, disable-infobars, disable-gpu, disable-default-apps, disable-popup-blocking, remote-allow-origins=*], extensions: []}}
[31mGiven [0m[31mUser navigates to SA url[0m [90m# com.fireflink.automation.stepdefinitions.LoginScreen.user_navigates_to_sa_url()[0m
[31mnet.thucydides.core.webdriver.DriverConfigurationError: Could not instantiate class org.openqa.selenium.chrome.ChromeDriver
at net.thucydides.core.webdriver.WebDriverFacade.newDriverInstance(WebDriverFacade.java:164)
at net.thucydides.core.webdriver.WebDriverFacade.newProxyDriver(WebDriverFacade.java:152)
at net.thucydides.core.webdriver.WebDriverFacade.getProxiedDriver(WebDriverFacade.java:122)
at net.thucydides.core.webdriver.WebDriverFacade.get(WebDriverFacade.java:192)
at net.serenitybdd.core.pages.PageObject.openPageAtUrl(PageObject.java:982)
at net.serenitybdd.core.pages.PageObject.open(PageObject.java:880)
at net.serenitybdd.core.pages.PageObject.open(PageObject.java:868)
at com.fireflink.automation.navigation.BaseFile.navigateToSaUrl(BaseFile.java:24)
at com.fireflink.automation.stepdefinitions.LoginScreen.user_navigates_to_sa_url(LoginScreen.java:22)
at âœ½.User navigates to SA url(file:///C:/Pooja_Data/workspace/serenity-cucumber-starter/src/test/resources/features/search/search_by_keyword.feature:4)
Caused by: net.thucydides.core.webdriver.DriverConfigurationError: WebDriver was unable to create a new instance of type class org.openqa.selenium.chrome.ChromeDriver
WebDriver reported the following message: The path to the driver executable The path to the driver executable must be set by the webdriver.chrome.driver system property; for more information, see https://chromedriver.chromium.org/. The latest version can be downloaded from https://chromedriver.chromium.org/downloads
See below for more details.

**Comment by bonigarcia** [comment]
This is a [Selenium Manager](https://www.selenium.dev/documentation/selenium_manager/) problem, not WebDriverManager. In the latest version of Selenium you can specify your proxy settings to be used in Selenium Manager.
