### ISSUE TITLE
org.openqa.selenium.SessionNotCreatedException: Could not start a new session. 

### ISSUE THREAD

**Issue by els-ashish** [bonigarcia/webdrivermanager#1067]
**Description of the problem**: While running my test suite I see some times the browser driver is not created. I am using WebDriverManager when I use the driver binaries directly I don't see any issues. Note that the issues occurs only sometimes, but I was unable to resolve this.

**Browser and version**: 

**Operating system**: MAC OS Ventura

**WebDriverManager version**: 5.3.0

**WebDriverManager call**: 
```
public class LocalDriverManager implements IDriver {
	protected OptionsManager optionsManager = new OptionsManager();
	@Override
	public WebDriver createInstance(String browser) {
		WebDriver driverInstance = null;
		try {
			if(browser.equalsIgnoreCase("chrome")) 
			{
				WebDriverManager.chromedriver().setup();
				driverInstance= new ChromeDriver(optionsManager.getChromeOptions());	
			}else if(browser.equalsIgnoreCase("firefox")) 
			{
				System.setProperty(FirefoxDriver.SystemProperty.BROWSER_LOGFILE,"/dev/null");
				FirefoxOptions options = new FirefoxOptions();
				options.setHeadless(configuration().isHeadless());
				WebDriverManager.firefoxdriver().setup();
				Map<String, String> environment = new HashMap<>();
				environment.put("DISPLAY", ":90");
				GeckoDriverService service = new GeckoDriverService.Builder()
				        .usingAnyFreePort()
				        .withEnvironment(environment)
				        .build();
				driverInstance= new FirefoxDriver(service,options);	
			}else if(browser.equalsIgnoreCase("edge")) 
			{
				WebDriverManager.edgedriver().setup();
				driverInstance= new EdgeDriver();
			}else if(browser.equalsIgnoreCase("safari")) 
			{
				WebDriverManager.safaridriver().setup();
				driverInstance= new SafariDriver();
			}else
			{
				throw new Exception("Unexpected Value: "+browser);
			}
		}catch (Exception e) 
		{
			e.printStackTrace();
			logs.info(">>>>>Unable to instansiate WebDriver :" +e.getMessage());
		}
		return driverInstance;
		
	}

}

```
**WebDriverManager traces**: 

**Error log**: 
```
org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: '4.3.0', revision: 'a4995e2c09*'
System info: host: 'ip-10-156-170-202.us-east-2.compute.internal', ip: '10.156.170.202', os.name: 'Linux', os.arch: 'amd64', os.version: '5.10.179-168.710.amzn2.x86_64', java.version: '1.8.0_352'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Command: [null, newSession {capabilities=[Capabilities {acceptInsecureCerts: true, browserName: firefox, moz:debuggerAddress: true, moz:firefoxOptions: {args: [-headless]}}], desiredCapabilities=Capabilities {acceptInsecureCerts: true, browserName: firefox, moz:debuggerAddress: true, moz:firefoxOptions: {args: [-headless]}}}]
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:587)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:264)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:179)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:110)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:106)
	at com.qa.driver.LocalDriverManager.createInstance(LocalDriverManager.java:42)
	at com.qa.driver.DriverFactory.createInstance(DriverFactory.java:15)
	at com.qa.base.TestBase.setUpBase(TestBase.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
	at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
	at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
	at org.testng.internal.TestInvoker.runConfigMethods(TestInvoker.java:700)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:527)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.testng.TestRunner.privateRun(TestRunner.java:794)
	at org.testng.TestRunner.run(TestRunner.java:596)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
	at org.testng.SuiteRunner.run(SuiteRunner.java:276)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
	at org.testng.TestNG.runSuites(TestNG.java:1063)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:284)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:119)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
Caused by: java.io.UncheckedIOException: java.net.ConnectException: Connection refused: localhost/127.0.0.1:37794
	at org.openqa.selenium.remote.http.netty.NettyHttpHandler.makeCall(NettyHttpHandler.java:73)
	at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
	at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)
	at org.openqa.selenium.remote.http.netty.NettyHttpHandler.execute(NettyHttpHandler.java:49)
	at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
	at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)
	at org.openqa.selenium.remote.http.netty.NettyClient.execute(NettyClient.java:98)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:120)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:102)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:67)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:156)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:167)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:142)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:569)
	... 43 more
Caused by: java.net.ConnectException: Connection refused: localhost/127.0.0.1:37794
	at org.asynchttpclient.netty.channel.NettyConnectListener.onFailure(NettyConnectListener.java:179)
	at org.asynchttpclient.netty.channel.NettyChannelConnector$1.onFailure(NettyChannelConnector.java:108)
	at org.asynchttpclient.netty.SimpleChannelFutureListener.operationComplete(SimpleChannelFutureListener.java:28)
	at org.asynchttpclient.netty.SimpleChannelFutureListener.operationComplete(SimpleChannelFutureListener.java:20)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:571)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:550)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:609)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:321)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:337)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:710)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:750)
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:37794
Caused by: java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:716)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:337)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:710)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:750)
Jul 04, 2023 8:29:35 AM com.qa.driver.LocalDriverManager createInstance
INFO: >>>>>Unable to instansiate WebDriver :Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: '4.3.0', revision: 'a4995e2c09*'
System info: host: 'ip-10-156-170-202.us-east-2.compute.internal', ip: '10.156.170.202', os.name: 'Linux', os.arch: 'amd64', os.version: '5.10.179-168.710.amzn2.x86_64', java.version: '1.8.0_352'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Command: [null, newSession {capabilities=[Capabilities {acceptInsecureCerts: true, browserName: firefox, moz:debuggerAddress: true, moz:firefoxOptions: {args: [-headless]}}], desiredCapabilities=Capabilities {acceptInsecureCerts: true, browserName: firefox, moz:debuggerAddress: true, moz:firefoxOptions: {args: [-headless]}}}]
```

**Comment by dastanshokimov** [comment]
> **Description of the problem**: While running my test suite I see some times the browser driver is not created. I am using WebDriverManager when I use the driver binaries directly I don't see any issues. Note that the issues occurs only sometimes, but I was unable to resolve this.
> 
> **Browser and version**:
> 
> **Operating system**: MAC OS Ventura
> 
> **WebDriverManager version**: 5.3.0
> 
> **WebDriverManager call**:
> 
> ```
> public class LocalDriverManager implements IDriver {
> 	protected OptionsManager optionsManager = new OptionsManager();
> 	@Override
> 	public WebDriver createInstance(String browser) {
> 		WebDriver driverInstance = null;
> 		try {
> 			if(browser.equalsIgnoreCase("chrome")) 
> 			{
> 				WebDriverManager.chromedriver().setup();
> 				driverInstance= new ChromeDriver(optionsManager.getChromeOptions());	
> 			}else if(browser.equalsIgnoreCase("firefox")) 
> 			{
> 				System.setProperty(FirefoxDriver.SystemProperty.BROWSER_LOGFILE,"/dev/null");
> 				FirefoxOptions options = new FirefoxOptions();
> 				options.setHeadless(configuration().isHeadless());
> 				WebDriverManager.firefoxdriver().setup();
> 				Map<String, String> environment = new HashMap<>();
> 				environment.put("DISPLAY", ":90");
> 				GeckoDriverService service = new GeckoDriverService.Builder()
> 				        .usingAnyFreePort()
> 				        .withEnvironment(environment)
> 				        .build();
> 				driverInstance= new FirefoxDriver(service,options);	
> 			}else if(browser.equalsIgnoreCase("edge")) 
> 			{
> 				WebDriverManager.edgedriver().setup();
> 				driverInstance= new EdgeDriver();
> 			}else if(browser.equalsIgnoreCase("safari")) 
> 			{
> 				WebDriverManager.safaridriver().setup();
> 				driverInstance= new SafariDriver();
> 			}else
> 			{
> 				throw new Exception("Unexpected Value: "+browser);
> 			}
> 		}catch (Exception e) 
> 		{
> 			e.printStackTrace();
> 			logs.info(">>>>>Unable to instansiate WebDriver :" +e.getMessage());
> 		}
> 		return driverInstance;
> 		
> 	}
> 
> }
> ```
> 
> **WebDriverManager traces**:
> 
> **Error log**:
> 
> ```
> org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
> Build info: version: '4.3.0', revision: 'a4995e2c09*'
> System info: host: 'ip-10-156-170-202.us-east-2.compute.internal', ip: '10.156.170.202', os.name: 'Linux', os.arch: 'amd64', os.version: '5.10.179-168.710.amzn2.x86_64', java.version: '1.8.0_352'
> Driver info: org.openqa.selenium.firefox.FirefoxDriver
> Command: [null, newSession {capabilities=[Capabilities {acceptInsecureCerts: true, browserName: firefox, moz:debuggerAddress: true, moz:firefoxOptions: {args: [-headless]}}], desiredCapabilities=Capabilities {acceptInsecureCerts: true, browserName: firefox, moz:debuggerAddress: true, moz:firefoxOptions: {args: [-headless]}}}]
> 	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:587)
> 	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:264)
> 	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:179)
> 	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:110)
> 	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:106)
> 	at com.qa.driver.LocalDriverManager.createInstance(LocalDriverManager.java:42)
> 	at com.qa.driver.DriverFactory.createInstance(DriverFactory.java:15)
> 	at com.qa.base.TestBase.setUpBase(TestBase.java:61)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
> 	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
> 	at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
> 	at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
> 	at org.testng.internal.TestInvoker.runConfigMethods(TestInvoker.java:700)
> 	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:527)
> 	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
> 	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
> 	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
> 	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
> 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
> 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
> 	at java.util.ArrayList.forEach(ArrayList.java:1259)
> 	at org.testng.TestRunner.privateRun(TestRunner.java:794)
> 	at org.testng.TestRunner.run(TestRunner.java:596)
> 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
> 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
> 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
> 	at org.testng.SuiteRunner.run(SuiteRunner.java:276)
> 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
> 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
> 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
> 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
> 	at org.testng.TestNG.runSuites(TestNG.java:1063)
> 	at org.testng.TestNG.run(TestNG.java:1031)
> 	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:284)
> 	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
> 	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:119)
> 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
> 	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
> 	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
> 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
> Caused by: java.io.UncheckedIOException: java.net.ConnectException: Connection refused: localhost/127.0.0.1:37794
> 	at org.openqa.selenium.remote.http.netty.NettyHttpHandler.makeCall(NettyHttpHandler.java:73)
> 	at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
> 	at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)
> 	at org.openqa.selenium.remote.http.netty.NettyHttpHandler.execute(NettyHttpHandler.java:49)
> 	at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
> 	at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)
> 	at org.openqa.selenium.remote.http.netty.NettyClient.execute(NettyClient.java:98)
> 	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:120)
> 	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:102)
> 	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:67)
> 	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:156)
> 	at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:167)
> 	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:142)
> 	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:569)
> 	... 43 more
> Caused by: java.net.ConnectException: Connection refused: localhost/127.0.0.1:37794
> 	at org.asynchttpclient.netty.channel.NettyConnectListener.onFailure(NettyConnectListener.java:179)
> 	at org.asynchttpclient.netty.channel.NettyChannelConnector$1.onFailure(NettyChannelConnector.java:108)
> 	at org.asynchttpclient.netty.SimpleChannelFutureListener.operationComplete(SimpleChannelFutureListener.java:28)
> 	at org.asynchttpclient.netty.SimpleChannelFutureListener.operationComplete(SimpleChannelFutureListener.java:20)
> 	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
> 	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:571)
> 	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:550)
> 	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
> 	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
> 	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:609)
> 	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
> 	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:321)
> 	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:337)
> 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:710)
> 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
> 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
> 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
> 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
> 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
> 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
> 	at java.lang.Thread.run(Thread.java:750)
> Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:37794
> Caused by: java.net.ConnectException: Connection refused
> 	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
> 	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:716)
> 	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:337)
> 	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
> 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:710)
> 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
> 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
> 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
> 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
> 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
> 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
> 	at java.lang.Thread.run(Thread.java:750)
> Jul 04, 2023 8:29:35 AM com.qa.driver.LocalDriverManager createInstance
> INFO: >>>>>Unable to instansiate WebDriver :Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
> Build info: version: '4.3.0', revision: 'a4995e2c09*'
> System info: host: 'ip-10-156-170-202.us-east-2.compute.internal', ip: '10.156.170.202', os.name: 'Linux', os.arch: 'amd64', os.version: '5.10.179-168.710.amzn2.x86_64', java.version: '1.8.0_352'
> Driver info: org.openqa.selenium.firefox.FirefoxDriver
> Command: [null, newSession {capabilities=[Capabilities {acceptInsecureCerts: true, browserName: firefox, moz:debuggerAddress: true, moz:firefoxOptions: {args: [-headless]}}], desiredCapabilities=Capabilities {acceptInsecureCerts: true, browserName: firefox, moz:debuggerAddress: true, moz:firefoxOptions: {args: [-headless]}}}]
> ```

Hello! I am using AndroidDriver and having the similar issue. Have you solved your issue? My "Command" also contains null for url, I am wondering why.
