### ISSUE TITLE
webdriver.opera.driver system property is not set automatically

### ISSUE THREAD

**Issue by kriegaex** [bonigarcia/webdrivermanager#1069]
When trying to create an `OperaDriver`, not only do I need to set `options.binary` manually and dependent on OS, but also suddenly, in contrast to older versions, WDM 5.4.0 with latest Opera 100 complains that it cannot find the driver binary. For other browser types, those two properties are set automatically.

```text
13:46:14.956 [main] INFO  i.g.bonigarcia.wdm.WebDriverManager - Exporting webdriver.chrome.driver as C:\Users\XYZ\.cache\selenium\operadriver\win64\114.0.5735.110\operadriver.exe

java.lang.IllegalStateException: The path to the driver executable must be set by the webdriver.opera.driver system property; for more information, see https://github.com/operasoftware/operachromiumdriver. The latest version can be downloaded from https://github.com/operasoftware/operachromiumdriver/releases

	at com.google.common.base.Preconditions.checkState(Preconditions.java:847)
	at org.openqa.selenium.remote.service.DriverService.findExecutable(DriverService.java:134)
	at org.openqa.selenium.opera.OperaDriverService.access$000(OperaDriverService.java:35)
	at org.openqa.selenium.opera.OperaDriverService$Builder.findDefaultExecutable(OperaDriverService.java:141)
	at org.openqa.selenium.remote.service.DriverService$Builder.build(DriverService.java:355)
	at org.openqa.selenium.opera.OperaDriverService.createDefaultService(OperaDriverService.java:85)
	at org.openqa.selenium.opera.OperaDriver.<init>(OperaDriver.java:149)
	at GebConfig$_run_closure2.closure9$_closure17(GebConfig.groovy:85)
	at groovy.lang.Closure.call(Closure.java:405)
	at groovy.lang.Closure.call(Closure.java:421)
	at groovy.lang.GString.writeTo(GString.java:188)
	at groovy.lang.GString.toString(GString.java:151)
	at geb.error.GebException.<init>(GebException.groovy:24)
```

I need something like this in my code (Geb configuration):

```groovy
  opera {
    driver = {
      WebDriverManager.operadriver().browserVersion('100').setup()
      def os = OperatingSystem.current
      def operaBinary = os.windows
        ? new FileNameByRegexFinder().getFileNames("c:\\Program Files\\Opera", "opera.exe\$").sort().last()
        : os.macOs
          ? "/Applications/Opera.app/Contents/MacOS/Opera"
          : "/usr/bin/opera"
      OperaOptions options = new OperaOptions()
      options.binary = operaBinary
      System.setProperty('webdriver.opera.driver', 'C:\\Users\\XYZ\\.cache\\selenium\\operadriver\\win64\\114.0.5735.110\\operadriver.exe')
      // Explicitly ask for permission to show push notifications
      options.addArguments("--disable-notifications")
      new OperaDriver(options)
    }
  }
```

This is quite tedious.

**Comment by kriegaex** [comment]
Update: I ended up doing something like this for the moment:

```groovy
  opera {
    driver = {
      def webDriverManager = WebDriverManager.operadriver()
      webDriverManager.setup()
      OperaOptions options = new OperaOptions()
      // Somehow WDM does not set this property automatically for Opera,
      // see https://github.com/bonigarcia/webdrivermanager/issues/1069
      System.setProperty('webdriver.opera.driver', webDriverManager.downloadedDriverPath)
      // Explicitly ask for permission to show push notifications
      options.addArguments("--disable-notifications")
      new OperaDriver(options)
    }
```

In this snippet, I omitted setting `options.binary`, because on my Windows box it is no longer necessary. Not sure about Linux and MacOS, though.

As you can see, I am retaining a reference to `WebDriverManager.operadriver()` in order to determine `webDriverManager.downloadedDriverPath` (Groovy shorthand for `getDownloadedDriverPath()`) after having called `setup()`. This way, I do not have to use the hard-coded path to the cache subdirectory anymore.

**Comment by bonigarcia** [comment]
This is not directly a WebDriverManager issue. Nevertheless, here you have some info. 

I'm afraid driving Opera is impossible, at least for the latest versions of Opera and Selenium. 

As of Selenium 4, the protocol to communicate Selenium and the drivers is only the W3C WebDriver specification. The problem is that operadriver does not support this specification. As a result, [Opera is not supported](https://github.com/SeleniumHQ/selenium/issues/10835), to the best of my knowledge.

In any case, the following [test](https://github.com/bonigarcia/webdrivermanager/blob/master/src/test/java/io/github/bonigarcia/wdm/test/opera/OperaTest.java) worked not so long ago, but it is not anymore. But I have just tested it (for Opera 99, Selenium 4.10.0, and WebDriverManager 5.4.0), and it fails due to:

```
org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Handshake response does not match any supported protocol. Response payload: {"sessionId":"7a665c1a80ab23789e679a7e5b93729f","status":33,"value":{"message":"session not created: Missing or invalid capabilities\n  (Driver info: operadriver=113.0.5672.127 (8da0c060b24fe8c84cb753bd0659e49fc290d3e8-refs/branch-heads/5672@{#1203}),platform=Windows NT 10.0.19044 x86_64)"}} 
Host info: host: 'DESKTOP-2KE0PTJ', ip: '192.168.56.1'
Build info: version: '4.10.0', revision: 'c14d967899'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.15'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [null, newSession {capabilities=[Capabilities {browserName: chrome, goog:chromeOptions: {args: [--remote-allow-origins=*], extensions: []}}]}]
```

When downgrading the Selenium version to 4.8.0, at least Opera appears, but the test also fails:

```
org.openqa.selenium.remote.http.ConnectionFailedException: Unable to establish websocket connection to http://localhost:49759/devtools/browser/4b0c345e-166b-4c62-be97-1c91938d1376
Build info: version: '4.8.0', revision: '267030adea'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.15'
Driver info: driver.version: ChromeDriver
```

**Comment by kriegaex** [comment]
Well, my older project for now is still on Selenium 3.141.59, and with it I can easily use the latest OperaDriver with Opera 100. The only problem is that the correct property is not set. The same problem would still apply to Selenium 4, so it makes sense to reopen this issue and fix it.
