### ISSUE TITLE
Chrome 116.0.5845.96 fails to start on Linux

### ISSUE THREAD

**Issue by batabek** [bonigarcia/webdrivermanager#1098]
**Description of the problem**: 
Chrome is crashing after ChromeDriver was started

**Browser and version**: Chrome 116.0.5845.96

**Operating system**: Linux 64 bits(4.14.291-218.527.amzn2.x86_64)

**WebDriverManager version**: 5.4.1

**WebDriverManager call**:  WebDriverManager.chromedriver().setup();

**Error log**: 
Starting ChromeDriver 116.0.5845.96 (1a391816688002153ef791ffe60d9e899a71a037-refs/branch-heads/5845@{#1382}) on port 49147
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
[SEVERE]: bind() failed: Cannot assign requested address (99)

org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /opt/google/chrome/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Build info: version: '4.1.1', revision: 'e8fcc2cecf'
System info: host: 'c463f471f0d8', ip: '172.17.0.2', os.name: 'Linux', os.arch: 'amd64', os.version: '4.14.291-218.527.amzn2.x86_64', java.version: '11.0.18'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [null, newSession {capabilities=[Capabilities {browserName: chrome, goog:chromeOptions: {args: [--headless, --start-maximized, chrome.switches, --disable-extensions, --disable-notifications, disable-infobars, --enable-smooth-scrolling, window-size=1920,1080, --use-fake-ui-for-media-stream, --use-fake-device-for-media..., --remote-allow-origins=*], extensions: [], prefs: {credentials_enable_service: false, download.default_directory: /codebuild/output/src397949..., profile.default_content_settings.popups: 0, profile.password_manager_enabled: false}}}], desiredCapabilities=Capabilities {browserName: chrome, goog:chromeOptions: {args: [--headless, --start-maximized, chrome.switches, --disable-extensions, --disable-notifications, disable-infobars, --enable-smooth-scrolling, window-size=1920,1080, --use-fake-ui-for-media-stream, --use-fake-device-for-media..., --remote-allow-origins=*], extensions: [], prefs: {credentials_enable_service: false, download.default_directory: /codebuild/output/src397949..., profile.default_content_settings.popups: 0, profile.password_manager_enabled: false}}}}]
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:126)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:84)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:62)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:156)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:167)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:142)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:230)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:151)
	at org.openqa.selenium.chromium.ChromiumDriver.<init>(ChromiumDriver.java:108)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:104)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:91)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:80)
	at main.java.core.BrowserFactory.chromeBrowser(BrowserFactory.java:70)
	at main.java.core.BrowserFactory.browserConfiguration(BrowserFactory.java:30)
	at main.java.core.BaseUITest.startBrowser(BaseUITest.java:65)
	at main.java.core.BaseUITest.beforeMethod(BaseUITest.java:36)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:523)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:224)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:599)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:383)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:344)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:417)

**Comment by jnchen** [comment]
the newest chrome webdriver avaiable at https://googlechromelabs.github.io/chrome-for-testing/#stable not in https://chromedriver.storage.googleapis.com/index.html，maybe when release version not found, go check testing list?

**Comment by patrick-hally** [comment]
> It seams like they changed the place to download from. ![image](https://user-images.githubusercontent.com/57982572/261243599-c24bf127-ea81-4376-944f-16379dc17b68.png)
> 
> So changes in webdrivermanager are required

Can anyone help in identifying what changes need to be made?

**Comment by thc202** [comment]
The WebDriverManager was already changed to use CfT endpoints https://github.com/bonigarcia/webdrivermanager/blob/master/CHANGELOG.md#540---2023-06-21

**Comment by batabek** [comment]
so is this a compatibility issue? Chrome v.116 not supported yet?

**Comment by crusy** [comment]
[Issue 116](https://github.com/bonigarcia/webdrivermanager/issues/1097) says

> This is already supported in WebDriverManager 5.4.1

But I can confirm it does not. btw, I would suggest to add some kind of "supported browsers" section to the README and/or documentation to avoid such multiple issues of the same problem. If it's there, I wasn't able to find it.

**Comment by hongiaher** [comment]
The download url for the new chromedrivers have been migrated.  I think the updates been made.  I did run into an issue on a mac though.  The resolution.properties wasn't properly updating the chrome116 value to be the 116 driver version, which caused the webdrivermanager to continue to use 114 (the previous version I was using).  I simply updated this value to the latest 116 version (116.0.5845.96).  I am able to run tests now.

**Comment by bonigarcia** [comment]
I have confirmed that WebDriverManager 5.4.1 works appropriately with Chrome 116 and Linux. Here it is the traces I see:

```
2023-08-17 15:27:49 [main] DEBUG i.g.b.wdm.versions.VersionDetector.getBrowserVersionFromTheShell(245) - Detecting chrome version using online commands.properties
2023-08-17 15:27:49 [main] DEBUG i.g.bonigarcia.wdm.versions.Shell.runAndWaitArray(65) - Running command on the shell: [google-chrome, --version]
2023-08-17 15:27:50 [main] DEBUG i.g.bonigarcia.wdm.versions.Shell.runAndWaitArray(69) - Result: Google Chrome 116.0.5845.96
2023-08-17 15:27:50 [main] INFO  i.g.bonigarcia.wdm.WebDriverManager.resolveDriverVersion(1212) - Using chromedriver 116.0.5845.96 (resolved driver for Chrome 116)
2023-08-17 15:27:50 [main] DEBUG i.g.b.wdm.cache.ResolutionCache.putValueInResolutionCacheIfEmpty(119) - Storing resolution chrome=116 in cache (valid until 16:27:50 17/08/2023 CEST)
2023-08-17 15:27:50 [main] DEBUG i.g.b.wdm.cache.ResolutionCache.putValueInResolutionCacheIfEmpty(119) - Storing resolution chrome116=116.0.5845.96 in cache (valid until 15:27:50 18/08/2023 CEST)
2023-08-17 15:27:50 [main] INFO  i.g.bonigarcia.wdm.WebDriverManager.logSeekRepo(1564) - Reading https://chromedriver.storage.googleapis.com/ to seek chromedriver
2023-08-17 15:27:50 [main] DEBUG i.g.bonigarcia.wdm.WebDriverManager.createUrlHandler(1449) - Driver to be downloaded chromedriver 116.0.5845.96
2023-08-17 15:27:50 [main] DEBUG i.g.bonigarcia.wdm.WebDriverManager.buildUrl(156) - Using URL built from repository pattern: https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/116.0.5845.96/linux64/chromedriver-linux64.zip
2023-08-17 15:27:50 [main] INFO  i.g.bonigarcia.wdm.online.Downloader.downloadAndExtract(131) - Downloading https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/116.0.5845.96/linux64/chromedriver-linux64.zip
2023-08-17 15:27:52 [main] INFO  i.g.bonigarcia.wdm.online.Downloader.extract(192) - Extracting driver from compressed file chromedriver-linux64.zip
2023-08-17 15:27:52 [main] INFO  i.g.bonigarcia.wdm.WebDriverManager.exportDriver(1265) - Exporting webdriver.chrome.driver as /home/user/.cache/selenium/chromedriver/linux64/116.0.5845.96/chromedriver
```

@batabek: The first traces you reported are the following:

```
Starting ChromeDriver 116.0.5845.96 (1a391816688002153ef791ffe60d9e899a71a037-refs/branch-heads/5845@{#1382}) on port 49147
```

That means chromedriver 116 is in your system, so WebDriverManager is properly downloading it. Then, the browser seems to crash. You are using an old version of Selenium, so I recommend you update to the latest (4.11.0). And if the error persists, it will be a problem related to Chrome or chromedriver but not WebDriverManager.
