### ISSUE TITLE
Why webdrivermanager can't setup latest chrome driver?

### ISSUE THREAD

**Issue by erdemkiiliic** [bonigarcia/webdrivermanager#1102]
**Description of the problem**: The setup method is unable to install the latest Chrome driver. Since it can only install version 114, I am unable to run my tests.

I also tried updating the webdriver manager, but using the latest version does not yield a reliable result due to a compatibility issue with my project's Java version.

**Browser and version**: Chrome 116

**Operating system**: macOS latest - 13.5

**WebDriverManager version**: 5.1.0

**WebDriverManager call**: WebDriverManager.chromedriver().setup();

**Error log/traces**: Message: org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: session not created: This version of ChromeDriver only supports Chrome version 114
Current browser version is 116.0.5845.96 with binary path /Applications/Google Chrome.app/Contents/MacOS/Google Chrome 
Host info: host: 'Erdems-MacBook-Air.local', ip: 'fe80:0:en0'
Build info: version: '4.8.3', revision: 'e5e76298c3'
System info: os.name: 'Mac OS X', os.arch: 'aarch64', os.version: '13.5', java.version: '1.8.0_372'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Command: [null, newSession {capabilities=[Capabilities {browserName: chrome, goog:chromeOptions: {args: [--remote-allow-origins=*, --test-type, --disable-popup-blocking, --disable-headless, --disable-notifications, --no-sandbox, --lang=tr, --disable-web-security], excludeSwitches: [enable-automation], extensions: [], prefs: {browser.helperApps.neverAsk.saveToDisk: text/csv, credentials_enable_service: false, intl.accept_languages: tr_TR, profile.password_manager_enabled: false}, useAutomationExtension: true}}], desiredCapabilities=Capabilities {browserName: chrome, goog:chromeOptions: {args: [--remote-allow-origins=*, --test-type, --disable-popup-blocking, --disable-headless, --disable-notifications, --no-sandbox, --lang=tr, --disable-web-security], excludeSwitches: [enable-automation], extensions: [], prefs: {browser.helperApps.neverAsk.saveToDisk: text/csv, credentials_enable_service: false, intl.accept_languages: tr_TR, profile.password_manager_enabled: false}, useAutomationExtension: true}}}]
Capabilities {browserName: chrome, goog:chromeOptions: {args: [--remote-allow-origins=*, --test-type, --disable-popup-blocking, --disable-headless, --disable-notifications, --no-sandbox, --lang=tr, --disable-web-security], excludeSwitches: [enable-automation], extensions: [], prefs: {browser.helperApps.neverAsk.saveToDisk: text/csv, credentials_enable_service: false, intl.accept_languages: tr_TR, profile.password_manager_enabled: false}, useAutomationExtension: true}}
Stack Trace:
org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: session not created: This version of ChromeDriver only supports Chrome version 114
Current browser version is 116.0.5845.96 with binary path /Applications/Google Chrome.app/Contents/MacOS/Google Chrome 
Host info: host: 'Erdems-MacBook-Air.local', ip: 'fe80:0:0:0:40d5:aeec%en0'
Build info: version: '4.8.3', revision: 'e5e76298c3'
System info: os.name: 'Mac OS X', os.arch: 'aarch64', os.version: '13.5', java.version: '1.8.0_372'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Command: [null, newSession {capabilities=[Capabilities {browserName: chrome, goog:chromeOptions: {args: [--remote-allow-origins=*, --test-type, --disable-popup-blocking, --disable-headless, --disable-notifications, --no-sandbox, --lang=tr, --disable-web-security], excludeSwitches: [enable-automation], extensions: [], prefs: {browser.helperApps.neverAsk.saveToDisk: text/csv, credentials_enable_service: false, intl.accept_languages: tr_TR, profile.password_manager_enabled: false}, useAutomationExtension: true}}], desiredCapabilities=Capabilities {browserName: chrome, goog:chromeOptions: {args: [--remote-allow-origins=*, --test-type, --disable-popup-blocking, --disable-headless, --disable-notifications, --no-sandbox, --lang=tr, --disable-web-security], excludeSwitches: [enable-automation], extensions: [], prefs: {browser.helperApps.neverAsk.saveToDisk: text/csv, credentials_enable_service: false, intl.accept_languages: tr_TR, profile.password_manager_enabled: false}, useAutomationExtension: true}}}]
Capabilities {browserName: chrome, goog:chromeOptions: {args: [--remote-allow-origins=*, --test-type, --disable-popup-blocking, --disable-headless, --disable-notifications, --no-sandbox, --lang=tr, --disable-web-security], excludeSwitches: [enable-automation], extensions: [], prefs: {browser.helperApps.neverAsk.saveToDisk: text/csv, credentials_enable_service: false, intl.accept_languages: tr_TR, profile.password_manager_enabled: false}, useAutomationExtension: true}}
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:148)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:106)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:67)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:165)
	at org.openqa.selenium.remote.TracedCommandExecutor.execute(TracedCommandExecutor.java:51)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:229)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:157)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:139)
	at joi.driver_manager.WebDriverManager.startTheTestOnLocalWithSpecificBrowser(WebDriverManager.java:78)
	at joi.driver_manager.WebDriverManager.startTheTest(WebDriverManager.java:53)
	at joi.base.BaseTest.startBrowser(BaseTest.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.thoughtworks.gauge.execution.MethodExecutor.execute(MethodExecutor.java:30)
	at com.thoughtworks.gauge.execution.StepExecutionStage.executeStepMethod(StepExecutionStage.java:66)
	at com.thoughtworks.gauge.execution.StepExecutionStage.executeStep(StepExecutionStage.java:59)
	at com.thoughtworks.gauge.execution.StepExecutionStage.execute(StepExecutionStage.java:41)
	at com.thoughtworks.gauge.execution.AbstractExecutionStage.executeNext(AbstractExecutionStage.java:14)
	at com.thoughtworks.gauge.execution.HookExecutionStage.execute(HookExecutionStage.java:33)
	at com.thoughtworks.gauge.execution.ExecutionPipeline.start(ExecutionPipeline.java:19)
	at com.thoughtworks.gauge.processor.ExecuteStepProcessor.process(ExecuteStepProcessor.java:44)
	at com.thoughtworks.gauge.RunnerServiceHandler.lambda$executeStep$7(RunnerServiceHandler.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

**Comment by bonigarcia** [comment]
Bump to WebDriverManager 5.4.1.
