### ISSUE TITLE
I have added all the jar files but still getting this error 

### ISSUE THREAD

**Issue by BKTGM** [bonigarcia/webdrivermanager#111]
System.setProperty("WebDriver.Chrome.Driver","C:\\Chrome Driver\\chromedriver.exe");
		WebDriver driver = new ChromeDriver();
		driver.get("https://www.flipkart.com/");

Error Received:
Exception in thread "main" java.lang.IllegalStateException: The path to the driver executable must be set by the webdriver.chrome.driver system property; for more information, see https://github.com/SeleniumHQ/selenium/wiki/ChromeDriver. The latest version can be downloaded from http://chromedriver.storage.googleapis.com/index.html
	at com.google.common.base.Preconditions.checkState(Preconditions.java:738)
	at org.openqa.selenium.remote.service.DriverService.findExecutable(DriverService.java:111)
	at org.openqa.selenium.chrome.ChromeDriverService.access$000(ChromeDriverService.java:32)
	at org.openqa.selenium.chrome.ChromeDriverService$Builder.findDefaultExecutable(ChromeDriverService.java:137)
	at org.openqa.selenium.remote.service.DriverService$Builder.build(DriverService.java:302)
	at org.openqa.selenium.chrome.ChromeDriverService.createDefaultService(ChromeDriverService.java:88)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:124)
	at Flipkart.main(Flipkart.java:11)

**Comment by anilreddy** [comment]
@BKTGM  If you are using webdrivermanager dependency you can simple do like this:

In Properties file: [application.properties]
```java
wdm.chromeDriverUrl=https://chromedriver.storage.googleapis.com/
wdm.chromeDriverExport=webdriver.chrome.driver
wdm.chromeDriverVersion=LATEST
```

```java
ChromeDriverManager.getInstance().setup();
driver = new ChromeDriver();
```

**Comment by BKTGM** [comment]
Where are you exactly referring when you say 'properties file'.
I am very new to selenium . could you please elaborate

**Comment by anilreddy** [comment]
@BKTGM Just create application.properties file in resources folder and add above config details that it.

**Comment by hennr** [comment]
Since 1.5.0 you should use webdrivermanager.properties in favour of application.properties

**Comment by BKTGM** [comment]
[error.xlsx](https://github.com/bonigarcia/webdrivermanager/files/853984/error.xlsx)

Still getting the same error , pls find attached screens for reference.

**Comment by anilreddy** [comment]
![image](https://cloud.githubusercontent.com/assets/3746781/24141550/cb371a78-0df1-11e7-95ca-54f030c997d0.png)

@BKTGM As per above image add properties in application.properties file and code in where ever you are initializing the driver.

**Comment by bonigarcia** [comment]
Java environment variables are case sensitive (export `webdriver.chrome.driver` instead of `WebDriver.Chrome.Driver`):

`System.setProperty("webdriver.chrome.driver", "C:\\Chrome Driver\\chromedriver.exe");`

**Comment by BKTGM** [comment]
Finally ...it worked ...Thank you all for your support.
I just changed the environment variables from capital to small letters as advised above and it worked.
Thank you all :)

**Comment by Taimaks** [comment]
Please I have a similar issue and I have made the changes @BKTGM made but issues still persist.
Kindly assist please

Exception in thread "main" java.lang.IllegalStateException: The path to the driver executable must be set by the webdriver.chrome.driver system property; for more information, see https://github.com/SeleniumHQ/selenium/wiki/ChromeDriver. The latest version can be downloaded from http://chromedriver.storage.googleapis.com/index.html
	at com.google.common.base.Preconditions.checkState(Preconditions.java:847)
	at org.openqa.selenium.remote.service.DriverService.findExecutable(DriverService.java:125)
	at org.openqa.selenium.chrome.ChromeDriverService.access$000(ChromeDriverService.java:35)
	at org.openqa.selenium.chrome.ChromeDriverService$Builder.findDefaultExecutable(ChromeDriverService.java:156)
	at org.openqa.selenium.remote.service.DriverService$Builder.build(DriverService.java:346)
	at org.openqa.selenium.chrome.ChromeDriverService.createDefaultService(ChromeDriverService.java:91)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:123)
	at Testcase1.main(Testcase1.java:13)

**Comment by bhaskerreddyvade** [comment]
To fix this error

webdriver.chrome.driver ( should be in small letters )

have to give correct chromedriver.exe ( correct path )

Import all Selenium jars under class Path

**Comment by kalyanieee** [comment]
Exception in thread "main" java.lang.IllegalStateException: The path to the driver executable must be set by the webdriver.chrome.driver system property; for more information, see https://github.com/SeleniumHQ/selenium/wiki/ChromeDriver. The latest version can be downloaded from http://chromedriver.storage.googleapis.com/index.html
	at com.google.common.base.Preconditions.checkState(Preconditions.java:847)
	at org.openqa.selenium.remote.service.DriverService.findExecutable(DriverService.java:134)
	at org.openqa.selenium.chrome.ChromeDriverService.access$000(ChromeDriverService.java:35)
	at org.openqa.selenium.chrome.ChromeDriverService$Builder.findDefaultExecutable(ChromeDriverService.java:159)
	at org.openqa.selenium.remote.service.DriverService$Builder.build(DriverService.java:355)
	at org.openqa.selenium.chrome.ChromeDriverService.createDefaultService(ChromeDriverService.java:94)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:123)
	at sample.demo.main(demo.java:11)
Iam getting this error, i have tried all your tips, but not working

**Comment by kirkpabk** [comment]
Having the same issue as #kalyanieee   

Using ANT and JUnit Jupiter with the latest Selenium drivers in Java.

**Comment by ayya86** [comment]
PRogram:
package seleniumfeb20;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
public class chromeexample {
	public static void main(String[] args) {
		// TODO Auto-generated method stub
		 System.out.println("hi"); 
	System.setProperty("webdriver.chrome.driver", "C:\\chromedriver.exe");
		WebDriver driver= new ChromeDriver();
		driver.get("https://www.facebook.com");		
	}
}

ERRORS
hi
Exception in thread "main" java.lang.NoClassDefFoundError: okhttp3/ConnectionPool
	at org.openqa.selenium.remote.internal.OkHttpClient$Factory.<init>(OkHttpClient.java:116)
	at org.openqa.selenium.remote.http.HttpClient$Factory.createDefault(HttpClient.java:66)
	at org.openqa.selenium.remote.HttpCommandExecutor.<clinit>(HttpCommandExecutor.java:47)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:181)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:168)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:123)
	at seleniumfeb20.chromeexample.main(chromeexample.java:13)
Caused by: java.lang.ClassNotFoundException: okhttp3.ConnectionPool
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 7 more

I am still getting the same error, can you kindly help
