### ISSUE TITLE
WebDriverManager Exception: latest geckodriver version not found for MAC64

### ISSUE THREAD

**Issue by michael-kainos** [bonigarcia/webdrivermanager#1114]
# ISSUE

## Description of the problem: 
When trying to setup a firefox browser, i am getting an error that geckodriver is not found in the default mirror url location for my OS architecture.

**Expected result:**
A firefox driver is started for my test

**Actual results:**
A stacktrace is shown that the geckodriver is not available at the default location for my OS architecture.

## Browser and version: 
Firefox browser, latest version as no specific version has been specified.

## Operating system: 
**OS Version:** macOS Ventura 13.5, 
**Architecture:** 64 bit

## WebDriverManager version: 
webdrivermanager:5.5.0

## WebDriverManager call: 
MY code implementation of WebDriverManager is as follows:

```
WebDriverManager.firefoxdriver().proxy(urlProperties.getProperty(PROXY_URL));
 WebDriverManager.firefoxdriver().setup();
 this.webDriver = new FirefoxDriver();
```

## WebDriverManager traces: 
TRACE 2023-08-23 11:19:18,840 [main] io.github.bonigarcia.wdm.WebDriverManager: Using preferences true
DEBUG 2023-08-23 11:19:18,931 [main] io.github.bonigarcia.wdm.WebDriverManager: The proper geckodriver version for your Mozilla Firefox is unknown ... trying with the latest
TRACE 2023-08-23 11:19:18,932 [main] io.github.bonigarcia.wdm.WebDriverManager: Managing geckodriver arch=64 version= getLatest=true cache=false
INFO  2023-08-23 11:19:18,933 [main] io.github.bonigarcia.wdm.WebDriverManager: Reading https://api.github.com/repos/mozilla/geckodriver/releases to seek geckodriver
ERROR 2023-08-23 11:19:18,967 [main] io.github.bonigarcia.wdm.HttpClient: Error HTTP 501 executing GET https://api.github.com/repos/mozilla/geckodriver/releases HTTP/1.1
WARN  2023-08-23 11:19:18,968 [main] io.github.bonigarcia.wdm.WebDriverManager: There was an error managing geckodriver (latest version) (Error HTTP 501 executing GET https://api.github.com/repos/mozilla/geckodriver/releases HTTP/1.1) ... trying again using mirror
TRACE 2023-08-23 11:19:18,972 [main] io.github.bonigarcia.wdm.WebDriverManager: Using preferences true
DEBUG 2023-08-23 11:19:19,057 [main] io.github.bonigarcia.wdm.WebDriverManager: The proper geckodriver version for your Mozilla Firefox is unknown ... trying with the latest
TRACE 2023-08-23 11:19:19,058 [main] io.github.bonigarcia.wdm.WebDriverManager: Managing geckodriver arch=64 version= getLatest=true cache=true
TRACE 2023-08-23 11:19:19,058 [main] io.github.bonigarcia.wdm.WebDriverManager: Checking if geckodriver exists in cache
TRACE 2023-08-23 11:19:19,064 [main] io.github.bonigarcia.wdm.WebDriverManager: geckodriver not found in cache
INFO  2023-08-23 11:19:19,065 [main] io.github.bonigarcia.wdm.WebDriverManager: Reading http://npm.taobao.org/mirrors/geckodriver to seek geckodriver
TRACE 2023-08-23 11:19:19,065 [main] io.github.bonigarcia.wdm.WebDriverManager: [Recursive call] Crawling driver list from mirror http://npm.taobao.org/mirrors/geckodriver
TRACE 2023-08-23 11:19:19,125 [main] io.github.bonigarcia.wdm.WebDriverManager: All URLs: []
TRACE 2023-08-23 11:19:19,125 [main] io.github.bonigarcia.wdm.WebDriverManager: Checking the lastest version of geckodriver with URL list []
INFO  2023-08-23 11:19:19,125 [main] io.github.bonigarcia.wdm.WebDriverManager: Latest version of geckodriver is null
TRACE 2023-08-23 11:19:19,125 [main] io.github.bonigarcia.wdm.WebDriverManager: Candidate URLs: []
ERROR 2023-08-23 11:19:19,125 [main] io.github.bonigarcia.wdm.WebDriverManager: geckodriver (latest version) for MAC64 not found in http://npm.taobao.org/mirrors/geckodriver
WARN  2023-08-23 11:19:19,126 [main] io.github.bonigarcia.wdm.WebDriverManager: There was an error managing geckodriver (latest version) (geckodriver (latest version) for MAC64 not found in http://npm.taobao.org/mirrors/geckodriver) ... trying again using latest from cache
TRACE 2023-08-23 11:19:19,129 [main] io.github.bonigarcia.wdm.WebDriverManager: Managing geckodriver arch=64 version= getLatest=true cache=true
TRACE 2023-08-23 11:19:19,129 [main] io.github.bonigarcia.wdm.WebDriverManager: Checking if geckodriver exists in cache
TRACE 2023-08-23 11:19:19,129 [main] io.github.bonigarcia.wdm.WebDriverManager: geckodriver not found in cache
INFO  2023-08-23 11:19:19,130 [main] io.github.bonigarcia.wdm.WebDriverManager: Reading http://npm.taobao.org/mirrors/geckodriver to seek geckodriver
TRACE 2023-08-23 11:19:19,130 [main] io.github.bonigarcia.wdm.WebDriverManager: [Recursive call] Crawling driver list from mirror http://npm.taobao.org/mirrors/geckodriver
TRACE 2023-08-23 11:19:19,154 [main] io.github.bonigarcia.wdm.WebDriverManager: All URLs: []
TRACE 2023-08-23 11:19:19,154 [main] io.github.bonigarcia.wdm.WebDriverManager: Checking the lastest version of geckodriver with URL list []
INFO  2023-08-23 11:19:19,154 [main] io.github.bonigarcia.wdm.WebDriverManager: Latest version of geckodriver is null
TRACE 2023-08-23 11:19:19,154 [main] io.github.bonigarcia.wdm.WebDriverManager: Candidate URLs: []
ERROR 2023-08-23 11:19:19,154 [main] io.github.bonigarcia.wdm.WebDriverManager: geckodriver (latest version) for MAC64 not found in http://npm.taobao.org/mirrors/geckodriver
ERROR 2023-08-23 11:19:19,155 [main] io.github.bonigarcia.wdm.WebDriverManager: There was an error managing geckodriver (latest version) (geckodriver (latest version) for MAC64 not found in http://npm.taobao.org/mirrors/geckodriver)

## Error log: 

io.github.bonigarcia.wdm.WebDriverManagerException: io.github.bonigarcia.wdm.WebDriverManagerException: geckodriver (latest version) for MAC64 not found in http://npm.taobao.org/mirrors/geckodriver
	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:776)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:550)
	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:773)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:550)
	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:766)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:550)
	at io.github.bonigarcia.wdm.WebDriverManager.setup(WebDriverManager.java:260)
	at com.automation.common.web_driver.WebDriverActions.startWebDriver(WebDriverActions.java:40)
	at com.automation.step_definitions.CommonStepDefs.beforeScenarioExecution(CommonStepDefs.java:20)
Caused by: io.github.bonigarcia.wdm.WebDriverManagerException: geckodriver (latest version) for MAC64 not found in http://npm.taobao.org/mirrors/geckodriver
	at io.github.bonigarcia.wdm.WebDriverManager.downloadAndExport(WebDriverManager.java:575)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:547)
	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:773)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:550)
	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:766)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:550)
	at io.github.bonigarcia.wdm.WebDriverManager.setup(WebDriverManager.java:260)
	at com.automation.common.web_driver.WebDriverActions.startWebDriver(WebDriverActions.java:40)
	at com.automation.step_definitions.CommonStepDefs.beforeScenarioExecution(CommonStepDefs.java:20)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at io.cucumber.java.Invoker.invoke(Invoker.java:27)
	at io.cucumber.java.JavaHookDefinition.execute(JavaHookDefinition.java:61)
	at io.cucumber.core.runner.CoreHookDefinition.execute(CoreHookDefinition.java:31)
	at io.cucumber.core.runner.HookDefinitionMatch.runStep(HookDefinitionMatch.java:20)
	at io.cucumber.core.runner.TestStep.executeStep(TestStep.java:64)
	at io.cucumber.core.runner.TestStep.run(TestStep.java:49)
	at io.cucumber.core.runner.TestCase.run(TestCase.java:47)
	at io.cucumber.core.runner.Runner.runPickle(Runner.java:66)
	at io.cucumber.core.runtime.Runtime.lambda$null$2(Runtime.java:100)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at io.cucumber.core.runtime.Runtime$SameThreadExecutorService.execute(Runtime.java:243)
	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:118)
	at io.cucumber.core.runtime.Runtime.lambda$run$3(Runtime.java:100)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.SliceOps$1$1.accept(SliceOps.java:199)
	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1602)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at io.cucumber.core.runtime.Runtime.run(Runtime.java:101)
	at io.cucumber.core.cli.Main.run(Main.java:73)
	at io.cucumber.core.cli.Main.main(Main.java:31)

**Comment by bonigarcia** [comment]
That log does not correspond to WebDriverManager 5.5.0. You are getting an error when connecting to  https://api.github.com/repos/mozilla/geckodriver/releases, but that URL is not used to discover geckodriver versions since version 5.3.0.

**Comment by michael-kainos** [comment]
I have reindexed and cleaned all cache registries to be certain of the version.

See the gradle build reference that this is version 5.5.0 being used with the issue still present: 
![Screenshot 2023-08-24 at 08 00 17](https://github.com/bonigarcia/webdrivermanager/assets/56648591/b170bd51-d7f0-4476-b825-dd8914fa4b40)

**Comment by bonigarcia** [comment]
Maybe you have different versions of WebDriverManager in  your classpath. With WebDriverMangaer 5.5.2 (just released) you should see something like the following:

```
2023-08-25 15:05:11 [main] DEBUG i.g.bonigarcia.wdm.WebDriverManager.clearDriverCache(817) - Clearing driver cache at /home/boni/.cache/selenium
2023-08-25 15:05:11 [main] DEBUG i.g.b.wdm.cache.ResolutionCache.<init>(77) - Created new resolution cache file at /home/boni/.cache/selenium/resolution.properties
2023-08-25 15:05:11 [main] DEBUG i.g.b.wdm.versions.VersionDetector.getBrowserVersionFromTheShell(258) - Detecting chrome version using online commands.properties
2023-08-25 15:05:11 [main] DEBUG i.g.bonigarcia.wdm.versions.Shell.runAndWaitArray(65) - Running command on the shell: [google-chrome, --version]
2023-08-25 15:05:11 [main] DEBUG i.g.bonigarcia.wdm.versions.Shell.runAndWaitArray(69) - Result: Google Chrome 116.0.5845.96
2023-08-25 15:05:11 [main] INFO  i.g.bonigarcia.wdm.WebDriverManager.resolveDriverVersion(1217) - Using chromedriver 116.0.5845.96 (resolved driver for Chrome 116)
2023-08-25 15:05:11 [main] DEBUG i.g.b.wdm.cache.ResolutionCache.putValueInResolutionCacheIfEmpty(119) - Storing resolution chrome=116 in cache (valid until 16:05:11 25/08/2023 CEST)
2023-08-25 15:05:11 [main] DEBUG i.g.b.wdm.cache.ResolutionCache.putValueInResolutionCacheIfEmpty(119) - Storing resolution chrome116=116.0.5845.96 in cache (valid until 15:05:11 26/08/2023 CEST)
2023-08-25 15:05:11 [main] INFO  i.g.bonigarcia.wdm.WebDriverManager.logSeekRepo(1568) - Reading https://chromedriver.storage.googleapis.com/ to seek chromedriver
2023-08-25 15:05:12 [main] DEBUG i.g.bonigarcia.wdm.WebDriverManager.createUrlHandler(1453) - Driver to be downloaded chromedriver 116.0.5845.96
2023-08-25 15:05:12 [main] DEBUG i.g.bonigarcia.wdm.WebDriverManager.buildUrl(156) - Using URL built from repository pattern: https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/116.0.5845.96/linux64/chromedriver-linux64.zip
2023-08-25 15:05:12 [main] INFO  i.g.bonigarcia.wdm.online.Downloader.downloadAndExtract(131) - Downloading https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/116.0.5845.96/linux64/chromedriver-linux64.zip
2023-08-25 15:05:13 [main] INFO  i.g.bonigarcia.wdm.online.Downloader.extract(192) - Extracting driver from compressed file chromedriver-linux64.zip
2023-08-25 15:05:13 [main] INFO  i.g.bonigarcia.wdm.WebDriverManager.exportDriver(1270) - Exporting webdriver.chrome.driver as /home/boni/.cache/selenium/chromedriver/linux64/116.0.5845.96/chromedriver
Aug 25, 2023 3:05:14 PM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
WARNING: Unable to find an exact match for CDP version 116, so returning the closest version found: 115
2023-08-25 15:05:15 [main] DEBUG i.g.bonigarcia.wdm.test.ChromeTest.test(59) - The title of https://bonigarcia.dev/selenium-webdriver-java/ is Hands-On Selenium WebDriver with Java

```

**Comment by michael-kainos** [comment]
resolved, this was due to outdated gradle build clean required on latest version to correct remove classpath build
