### ISSUE TITLE
Zip is not a valid Win32 Application

### ISSUE THREAD

**Issue by highlycaffeinatedcode** [bonigarcia/webdrivermanager#112]
After calling setup for PhantomJS, the downloaded zip file does not appear to be getting extracted.

`PhantomJsDriverManager.getInstance().setup();`

`Mar 17, 2017 6:11:31 PM org.openqa.selenium.phantomjs.PhantomJSDriverService <init>
INFO: executable: C:\webdriver\phantomjs\windows\2.5.0\phantomjs-2.5.0-windows.zip`

Creating the WebDriver then fails: 

`Mar 17, 2017 6:11:51 PM org.openqa.selenium.os.UnixProcess checkForError
SEVERE: org.apache.commons.exec.ExecuteException: Execution failed (Exit value: -559038737. Caused by java.io.IOException: Cannot run program "C:\webdriver\phantomjs\windows\2.5.0\phantomjs-2.5.0-windows.zip" (in directory "."): CreateProcess error=193, %1 is not a valid Win32 application)
`

**Comment by bonigarcia** [comment]
Which version of WebDriverManager are you using?

**Comment by highlycaffeinatedcode** [comment]
Sorry:

weddrivermanager 1.6.1
selenium 3.3.1
phnatonjs 1.4.0

**Comment by bonigarcia** [comment]
I am not able to reproduce this problem using the [example repository](https://github.com/bonigarcia/webdrivermanager-examples) (I'm using this [test](https://github.com/bonigarcia/webdrivermanager-examples/blob/master/src/test/java/io/github/bonigarcia/wdm/test/PhatomJsTest.java)) with the same setup (Windows 10 etc.):

```
[2017-03-21 14:33:41:047] [main] INFO BrowserManager - Crawling driver list from mirror https://bitbucket.org/ariya/phantomjs/downloads/
[2017-03-21 14:33:42:079] [main] INFO BrowserManager - Latest version of [phantomjs] is 2.5.0
[2017-03-21 14:33:42:081] [main] INFO Downloader - Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.5.0-beta-windows.zip to C:\Users\boni\.m2\repository\webdriver\phantomjs\windows\2.5.0\phantomjs-2.5.0-windows.zip
[2017-03-21 14:33:53:801] [main] INFO BrowserManager - Exporting phantomjs.binary.path as C:\Users\boni\.m2\repository\webdriver\phantomjs\windows\2.5.0\phantomjs.exe
mar 21, 2017 2:33:53 PM org.openqa.selenium.phantomjs.PhantomJSDriverService <init>
INFORMACIÓN: executable: C:\Users\boni\.m2\repository\webdriver\phantomjs\windows\2.5.0\phantomjs.exe
mar 21, 2017 2:33:53 PM org.openqa.selenium.phantomjs.PhantomJSDriverService <init>
INFORMACIÓN: port: 23843
mar 21, 2017 2:33:53 PM org.openqa.selenium.phantomjs.PhantomJSDriverService <init>
INFORMACIÓN: arguments: [--webdriver=23843, --webdriver-logfile=D:\projects\webdrivermanager-examples\phantomjsdriver.log]
mar 21, 2017 2:33:53 PM org.openqa.selenium.phantomjs.PhantomJSDriverService <init>
INFORMACIÓN: environment: {}
[INFO  - 2017-03-21T13:33:55.790Z] GhostDriver - Main - running on port 23843
[INFO  - 2017-03-21T13:33:56.313Z] Session [084b2050-0e3b-11e7-b185-150ab711f2b7] - page.settings - {"XSSAuditingEnabled":false,"dpi":96,"javascriptCanCloseWindows":true,"javascriptCanOpenWindows":true,"javascriptEnabled":true,"loadImages":true,"localToRemoteUrlAccessEnabled":false,"userAgent":"Mozilla/5.0 (Windows NT 6.2; Win64; x64) AppleWebKit/602.1 (KHTML, like Gecko) PhantomJS/2.5.0-development Version/9.0 Safari/602.1","webSecurityEnabled":true}
[INFO  - 2017-03-21T13:33:56.314Z] Session [084b2050-0e3b-11e7-b185-150ab711f2b7] - page.customHeaders:  - []
[INFO  - 2017-03-21T13:33:56.314Z] Session [084b2050-0e3b-11e7-b185-150ab711f2b7] - Session.negotiatedCapabilities - {"browserName":"phantomjs","version":"2.5.0","driverName":"ghostdriver","driverVersion":"1.2.0","platform":"windows-10-64bit","javascriptEnabled":true,"takesScreenshot":true,"handlesAlerts":false,"databaseEnabled":false,"locationContextEnabled":false,"applicationCacheEnabled":false,"browserConnectionEnabled":false,"cssSelectorsEnabled":true,"webStorageEnabled":false,"rotatable":false,"acceptSslCerts":false,"nativeEvents":true,"proxy":{"proxyType":"direct"}}
[INFO  - 2017-03-21T13:33:56.314Z] SessionManagerReqHand - _postNewSessionCommand - New Session Created: 084b2050-0e3b-11e7-b185-150ab711f2b7
mar 21, 2017 2:33:56 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFORMACIÓN: Detected dialect: OSS
[INFO  - 2017-03-21T13:33:59.569Z] ShutdownReqHand - _handle - About to shutdown

```

Please try to clean your local repository. In your case, it seems to be `C:\webdriver\phantomjs\` (delete completely that folder and try again).

**Comment by xtwmx** [comment]
Same problem:

`java.lang.IllegalStateException: The driver is not executable: /opt/app/tcity/.m2/repository/webdriver/chromedriver/linux64/2.28/chromedriver_linux64.zip
    at com.google.common.base.Preconditions.checkState(Preconditions.java:518)
    at org.openqa.selenium.remote.service.DriverService.checkExecutable(DriverService.java:127)
    at org.openqa.selenium.remote.service.DriverService.findExecutable(DriverService.java:118)
    at org.openqa.selenium.chrome.ChromeDriverService.access$000(ChromeDriverService.java:32)
    at org.openqa.selenium.chrome.ChromeDriverService$Builder.findDefaultExecutable(ChromeDriverService.java:137)
    at org.openqa.selenium.remote.service.DriverService$Builder.build(DriverService.java:302)
    at org.openqa.selenium.chrome.ChromeDriverService.createDefaultService(ChromeDriverService.java:88)
    at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:142)
    at com.codeborne.selenide.webdriver.WebDriverFactory.createChromeDriver(WebDriverFactory.java:168)
    at com.codeborne.selenide.webdriver.WebDriverFactory.createWebDriver(WebDriverFactory.java:48)
    at com.codeborne.selenide.impl.WebDriverThreadLocalContainer.createDriver(WebDriverThreadLocalContainer.java:240)
    at com.codeborne.selenide.impl.WebDriverThreadLocalContainer.getAndCheckWebDriver(WebDriverThreadLocalContainer.java:113)
    at com.codeborne.selenide.WebDriverRunner.getAndCheckWebDriver(WebDriverRunner.java:136)
    at com.codeborne.selenide.impl.Navigator.navigateToAbsoluteUrl(Navigator.java:68)
    at com.codeborne.selenide.impl.Navigator.open(Navigator.java:31)
    at com.codeborne.selenide.Selenide.open(Selenide.java:81)
    at com.codeborne.selenide.Selenide.open(Selenide.java:55)`

**Comment by xtwmx** [comment]
```
fail: -rw-r--r-- 1 tcity tcity 7358910 Mar 17 10:49 chromedriver
pass: -rwxr--r-- 1 tcity tcity 7673176 Mar 21 08:49 chromedriver
```

**Comment by bonigarcia** [comment]
You said you were using Windows 10 and that path is a Linux or Mac file system.

**Comment by bonigarcia** [comment]
This is not the same problem. This issue is about Windows and PhamtomJS.

**Comment by xtwmx** [comment]
OK, I presumed it is a generic file extract problem.
I will create a new issue, sorry.

**Comment by bonigarcia** [comment]
@xtwmx in any case, try to clean your cache and try again.

**Comment by highlycaffeinatedcode** [comment]
Thanks. 
Deleting the cached zip did it - looks like it was corrupted/incomplete when downloaded and therefore extracting it failed.
