### ISSUE TITLE
 REQ Help L0030  ERROR: No such driver version 

### ISSUE THREAD

**Issue by lolminerxmrig** [bonigarcia/webdrivermanager#1123]
Hi
plz help me for Fixed Error:

2023-09-06 11:41:23,265  gmap-scraper L0030  ERROR: Traceback (most recent call last):
NoneType: None
2023-09-06 11:41:23,268  gmap-scraper L0030  ERROR:   File "C:\Users\TEST\Downloads\scraper\app.py", line 416, in <module>
    scraper = Scraper(headless=True)
              ^^^^^^^^^^^^^^^^^^^^^^
NoneType: None
2023-09-06 11:41:23,269  gmap-scraper L0030  ERROR:   File "C:\Users\TEST\Downloads\scraper\app.py", line 63, in __init__
    service=Service(ChromeDriverManager().install()),
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
NoneType: None
2023-09-06 11:41:23,270  gmap-scraper L0030  ERROR:   File "C:\Python311\Lib\site-packages\webdriver_manager\chrome.py", line 39, in install
    driver_path = self._get_driver_binary_path(self.driver)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
NoneType: None
2023-09-06 11:41:23,271  gmap-scraper L0030  ERROR:   File "C:\Python311\Lib\site-packages\webdriver_manager\core\manager.py", line 33, in _get_driver_binary_path
    file = self._download_manager.download_file(driver.get_driver_download_url())
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
NoneType: None
2023-09-06 11:41:23,272  gmap-scraper L0030  ERROR:   File "C:\Python311\Lib\site-packages\webdriver_manager\drivers\chrome.py", line 59, in get_driver_download_url
    modern_version_url = self.get_url_for_version_and_platform(driver_version_to_download, os_type)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
NoneType: None
2023-09-06 11:41:23,274  gmap-scraper L0030  ERROR:   File "C:\Python311\Lib\site-packages\webdriver_manager\drivers\chrome.py", line 94, in get_url_for_version_and_platform
    raise Exception(f"No such driver version {browser_version} for {platform}")
NoneType: None
2023-09-06 11:41:23,275  gmap-scraper L0030  ERROR: Exception: No such driver version 116.0.5845.180 for win32
NoneType: None
2023-09-06 11:41:23,276  gmap-scraper L0030  ERROR: No such driver version 116.0.5845.180 for win32
NoneType: None

**Comment by bonigarcia** [comment]
This repo is WebDriverManager (Java). You are using webdriver-manager (Python). See: https://pypi.org/project/webdriver-manager/
