### ISSUE TITLE
[BUG] Error creating WebDriver object for Chrome version(117.0.5938.xxx) from WebDriverManager

### ISSUE THREAD

**Issue by Mahee17** [bonigarcia/webdrivermanager#1137]
Description of the problem:  Chrome updated automatically to the latest version 117.0.5938.xxx and WebDriver creation failed. It was working fine before the update

Browser and version: 117.0.5938.xxx

Operating system and architecture: Its not working both in Windows Server 2019, Mac Ventura 13.3.1(a)

Selenium version: 4.9.1

WebDriverManager version: 5.5.3

WebDriverManager call: 

String strBrowser = properties.getProperty("Browser");
        System.setProperty("webdriver.http.factory", "jdk-http-client");
        if(strBrowser.equals("Chrome")){
            ChromeOptions chromeOptions = new ChromeOptions();
            chromeOptions.addArguments("incognito");
//            chromeOptions.addArguments("--remote-allow-origins=*");
            WebDriverManager.chromedriver().clearDriverCache().setup();
            driver = WebDriverManager.chromedriver().capabilities(chromeOptions).create();
//            driver = WebDriverManager.chromedriver().create();
        }
        else if(strBrowser.equals("Safari")){
            driver = WebDriverManager.safaridriver().create();
        }
        else{
            driver = WebDriverManager.edgedriver().create();
        }

WebDriverManager traces: 

io.github.bonigarcia.wdm.config.WebDriverManagerException: There was an error creating WebDriver object for Chrome

	at io.github.bonigarcia.wdm.WebDriverManager.instantiateDriver(WebDriverManager.java:1760)
	at io.github.bonigarcia.wdm.WebDriverManager.create(WebDriverManager.java:431)
	at org.nrii.myimportal.MyIMPortalBaseTest.invokeMyIMPortal(MyIMPortalBaseTest.java:67)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:361)
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:296)
	at org.testng.internal.invokers.TestInvoker.runConfigMethods(TestInvoker.java:823)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:590)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.testng.TestRunner.privateRun(TestRunner.java:829)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
	at org.testng.SuiteRunner.run(SuiteRunner.java:330)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
	at org.testng.TestNG.runSuites(TestNG.java:1099)
	at org.testng.TestNG.run(TestNG.java:1067)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:79)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:484)
	at io.github.bonigarcia.wdm.webdriver.WebDriverCreator.createLocalWebDriver(WebDriverCreator.java:61)
	at io.github.bonigarcia.wdm.WebDriverManager.createLocalWebDriver(WebDriverManager.java:1939)
	at io.github.bonigarcia.wdm.WebDriverManager.instantiateDriver(WebDriverManager.java:1749)
	... 31 more
Caused by: java.lang.NoSuchMethodError: 'java.io.OutputStream org.openqa.selenium.chrome.ChromeDriverService$Builder.getLogOutput(java.lang.String)'
	at org.openqa.selenium.chrome.ChromeDriverService$Builder.createDriverService(ChromeDriverService.java:425)
	at org.openqa.selenium.chrome.ChromeDriverService$Builder.createDriverService(ChromeDriverService.java:203)
	at org.openqa.selenium.remote.service.DriverService$Builder.build(DriverService.java:498)
	at org.openqa.selenium.chrome.ChromeDriverService.createServiceWithConfig(ChromeDriverService.java:187)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:73)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
	... 36 more

**Comment by ManoharKrishnaBoppe** [comment]
@Mahee17 @bonigarcia  When an particular version is not found we are downloading the latest version available as an fallback. But when we are doing we are only taking the versions from the https://chromedriver.storage.googleapis.com/  which will return only upto 114. so the latest version like 115, 116, 117 are listed so it is not being downloaded at the moment so the executions are failing. 

<img width="1329" alt="image" src="https://github.com/bonigarcia/webdrivermanager/assets/86585218/3d3f4fc5-99a5-4946-a4a3-abeecaa7cda4">

**Comment by patmagee** [comment]
@ManoharKrishnaBoppe is there a plant to fix this?

**Comment by ManoharKrishnaBoppe** [comment]
Yes, @patmagee I have fixed it once tested will raise PR for the same.

**Comment by patmagee** [comment]
Thanks @ManoharKrishnaBoppe! We will keep our eyes open for a new release.

**Comment by bonigarcia** [comment]
I have just committed a patch to avoid fallback to the old chromedriver version (i.e., version 114 and below) when CfT fails. It will available for next version.
