### ISSUE TITLE
Request URI authority contains deprecated userinfo componenеt.

### ISSUE THREAD

**Issue by IvanKvashnin** [bonigarcia/webdrivermanager#1150]
Hello !

**Stack:**
```
allureVersion = '2.20.1'
junitVersion = '5.9.3'
selenideVersion = '6.19.0'
wdmVersion = '5.5.3'
```

I use a mirror to download a web driver from my company's private repository. Because I don't have access to the external Internet. And I get the error "Request URI authority contains deprecated userinfo componenеt."

I tried passing the authorization token in two ways.
**Via webdrivermanager.properties:**

```
wdm.cachePath=~/.cache/selenium
wdm.resolutionCache=resolution.properties

wdm.forceDownload=false
wdm.avoidExport=false
wdm.avoidBrowserDetection=false
wdm.useBetaVersions=false
wdm.avoidResolutionCache=false
wdm.avoidTmpFolder=false

wdm.timeout=30
wdm.ttl=86400
wdm.ttlForBrowsers=3600

wdm.browserVersionDetectionRegex=[^\\d^\\.]

wdm.defaultBrowser=chrome
wdm.chromeDriverExport=webdriver.chrome.driver
wdm.chromeDriverMirrorUrl= scheme://userInfo@host:port/path <- where UserInfo is token:yourToken
wdm.chromeDriverUrl=scheme://userInfo@host:port/path <- where UserInfo is token:yourToken
```

**Via webdriverManager:**
```
chromedriver()
  .clearDriverCache()
  .driverVersion("version")
  .driverRepositoryUrl(URIBuilder()
                .setScheme("yourScheme")
                .setUserInfo("*yourUserInfo") <- where UserInfo is token:yourToken
                .setHost("yourHost")
                .setPort("yourPort")
                .setPath("yourPath")
                .build().toURL())
                .setUp();
```

**StackTrace:**
```
INFO io.github.bonigarcia.wdm.WebDriverManager - scheme://userInfo@host:port/path to seek chromedriver
[ForkJoinPool-1-worker-1] ERROR io.github.bonigarcia.wdm.WebDriverManager - There was an error managing chromedriver (latest version) (org.apache.hc.client5.http.ClientProtocolException: Request URI authority contains deprecated userinfo component)
io.github.bonigarcia.wdm.config.WebDriverManagerException: org.apache.hc.client5.http.ClientProtocolException: Request URI authority contains deprecated userinfo component
 at io.github.bonigarcia.wdm.WebDriverManager.getDriversFromXml(WebDriverManager.java:1577)
 at io.github.bonigarcia.wdm.managers.ChromeDriverManager.getDriverUrls(ChromeDriverManager.java:103)
 at io.github.bonigarcia.wdm.WebDriverManager.createUrlHandler(WebDriverManager.java:1444)
 at io.github.bonigarcia.wdm.WebDriverManager.download(WebDriverManager.java:1279)
 at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:1198)
 at io.github.bonigarcia.wdm.WebDriverManager.fallback(WebDriverManager.java:1439)
 at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:1420)
 at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:1204)
 at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:1413)
 at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:1204)
 at io.github.bonigarcia.wdm.WebDriverManager.setup(WebDriverManager.java:419)
 at com.codeborne.selenide.webdriver.ChromeDriverFactory.setupWebdriverBinary(ChromeDriverFactory.java:32)
 at com.codeborne.selenide.webdriver.WebDriverFactory.createWebDriverInstance(WebDriverFactory.java:116)
 at com.codeborne.selenide.webdriver.WebDriverFactory.createWebDriver(WebDriverFactory.java:67)
 at com.codeborne.selenide.drivercommands.CreateDriverCommand.lambda$createDriver$0(CreateDriverCommand.java:76)
 at com.codeborne.selenide.logevents.SelenideLogger.get(SelenideLogger.java:118)
 at com.codeborne.selenide.drivercommands.CreateDriverCommand.createDriver(CreateDriverCommand.java:52)
 at com.codeborne.selenide.impl.WebDriverThreadLocalContainer.createDriver(WebDriverThreadLocalContainer.java:180)
 at com.codeborne.selenide.impl.WebDriverThreadLocalContainer.getAndCheckWebDriver(WebDriverThreadLocalContainer.java:149)
 at com.codeborne.selenide.WebDriverRunner.getAndCheckWebDriver(WebDriverRunner.java:130)
 at com.codeborne.selenide.impl.StaticDriver.getAndCheckWebDriver(StaticDriver.java:65)
 at com.codeborne.selenide.SelenideDriver.getAndCheckWebDriver(SelenideDriver.java:220)
 at com.codeborne.selenide.drivercommands.Navigator.lambda$navigateTo$0(Navigator.java:72)
 at com.codeborne.selenide.logevents.SelenideLogger.run(SelenideLogger.java:105)
 at com.codeborne.selenide.drivercommands.Navigator.navigateTo(Navigator.java:70)
 at com.codeborne.selenide.drivercommands.Navigator.open(Navigator.java:32)
 at com.codeborne.selenide.SelenideDriver.open(SelenideDriver.java:101)
 at com.codeborne.selenide.Selenide.open(Selenide.java:52)
 at autotests.card.gkm.ChangeGkmActiveTest.testUiGkmChangeNameTypePersonalNumberStatusEdit(ChangeGkmActiveTest.java:95)
 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
 at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.base/java.lang.reflect.Method.invoke(Method.java:568)
 at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)
 at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
 at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
 at org.junit.jupiter.api.extension.InvocationInterceptor.interceptTestMethod(InvocationInterceptor.java:118)
 at

org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(InterceptingExecutableInvoker.java:103)
 at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)
 at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
 at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:156)
 at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:147)
 at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:86)
 at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(InterceptingExecutableInvoker.java:103)
 at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)
 at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
 at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
 at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
 at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
 at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:92)
 at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:86)
 at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:217)
 at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
 at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:213)
 at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:138)
 at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:68)
 at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
 at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
 at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
 at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
 at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
 at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
 at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
 at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
 at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService$ExclusiveTask.compute(ForkJoinPoolHierarchicalTestExecutorService.java:202)
 at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService.invokeAll(ForkJoinPoolHierarchicalTestExecutorService.java:146)
 at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
 at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
 at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
 at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
 at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
 at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
 at

org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
 at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
 at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService$ExclusiveTask.compute(ForkJoinPoolHierarchicalTestExecutorService.java:202)
 at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService.invokeAll(ForkJoinPoolHierarchicalTestExecutorService.java:146)
 at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
 at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
 at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
 at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
 at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
 at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
 at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
 at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
 at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService$ExclusiveTask.compute(ForkJoinPoolHierarchicalTestExecutorService.java:202)
 at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
 at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
 at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
 at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
 at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
 at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: org.apache.hc.client5.http.ClientProtocolException: Request URI authority contains deprecated userinfo component
 at org.apache.hc.client5.http.impl.classic.InternalHttpClient.doExecute(InternalHttpClient.java:173)
 at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:123)
 at io.github.bonigarcia.wdm.online.HttpClient.execute(HttpClient.java:158)
 at io.github.bonigarcia.wdm.WebDriverManager.getDriversFromXml(WebDriverManager.java:1562)
 ... 90 more
Caused by: org.apache.hc.core5.http.ProtocolException: Request URI authority contains deprecated userinfo component
 at org.apache.hc.client5.http.impl.classic.ProtocolExec.execute(ProtocolExec.java:145)
 at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
 at org.apache.hc.client5.http.impl.classic.HttpRequestRetryExec.execute(HttpRequestRetryExec.java:96)
 at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
 at org.apache.hc.client5.http.impl.classic.ContentCompressionExec.execute(ContentCompressionExec.java:152)
 at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
 at org.apache.hc.client5.http.impl.classic.RedirectExec.execute(RedirectExec.java:115)
 at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
 at org.apache.hc.client5.http.impl.classic.InternalHttpClient.doExecute(InternalHttpClient.java:170)
 ... 93 more

```

This happens at - org.apache.httpcomponents.client5:httpclient5, on version 5.2.1.

On Selenide version 6.9.0 - everything works because:
webDriverManager(wdm) is included in the selenide dependency pool, and wdm includes the dependency org.apache.httpcomponents.client5:httpclient5 version 5.1.4

Starting with selenide ver 6.10, which still has the wdm dependency, but this wdm no longer has org.apache.httpcomponents.client5. This dependency is placed in the general selenide dependency pool and has version 5.2.1, in which it is forbidden to pass userInfo.

RFC 7230: treat presence of userinfo in authority component in request URI as an HTTP protocol violation.  Contributed by Oleg Kalnichevski <olegk at apache.org> 
https://github.com/apache/httpcomponents-client/blob/master/RELEASE_NOTES.txt

![image](https://github.com/bonigarcia/webdrivermanager/assets/60319507/ffc8d01b-5db6-4e94-904f-06bcd6582d69)
![image](https://github.com/bonigarcia/webdrivermanager/assets/60319507/48a97ed9-a9bc-4e45-9ef4-a5454ef4a526)
![image](https://github.com/bonigarcia/webdrivermanager/assets/60319507/12e46b75-9cf2-4abf-bbcb-067ea2ce6499)

On the last screen, in version 6.19 wdm was removed and now selenide maneger is replaced. I know this, so I installed the webdrivermanager 5.5.3 dependency separately and use it.u

**Comment by bonigarcia** [comment]
Starting in some version (I cannot remember which one), Selenide stopped using WebDriverManager and began to use [Selenium Manager](https://www.selenium.dev/documentation/selenium_manager/). On the other side, the mirror support in WebDriverManager does not change. In conclusion, I think you should report this problem to Selenide. Maybe they need to use the mirror support of Selenium Manager (which will be available for the next Selenium version).
