### ISSUE TITLE
Error HTTP 404 executing https://raw.githubusercontent.com/bonigarcia/webdrivermanager/master/docs/mirror/geckodriver

### ISSUE THREAD

**Issue by kazurayam** [bonigarcia/webdrivermanager#1154]
I have mac M1 chip, 8GB memory, macOS 12.9, JDK 17, Gradle 8.4, Firefox 119.0

**Description of the problem**: 

I have cloned the https://github.com/bonigarcia/selenium-webdriver-java master branch. 

I ran https://github.com/kazurayam/selenium-webdriver-java/blob/master/selenium-webdriver-junit4/src/test/java/io/github/bonigarcia/webdriver/junit4/ch02/helloworld/HelloWorldFirefoxJUnit4Test.java

As you see in the [build.gradle](https://github.com/kazurayam/selenium-webdriver-java/blob/master/selenium-webdriver-junit4/build.gradle), Selenium-java version is 4.13.0 ([I intentionally downgraded from 4.14.1](https://github.com/bonigarcia/selenium-webdriver-java/pull/733)), WebDriverManager version is 5.5.3.

I got the following error:

```
io.github.bonigarcia.wdm.config.WebDriverManagerException: io.github.bonigarcia.wdm.config.WebDriverManagerException: Error HTTP 404 executing https://raw.githubusercontent.com/bonigarcia/webdrivermanager/master/docs/mirror/geckodriver" type="io.github.bonigarcia.wdm.config.WebDriverManagerException">io.github.bonigarcia.wdm.config.WebDriverManagerException: io.github.bonigarcia.wdm.config.WebDriverManagerException: Error HTTP 404 executing https://raw.githubusercontent.com/bonigarcia/webdrivermanager/master/docs/mirror/geckodriver
	at app//io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:1409)
	at app//io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:1183)
	at app//io.github.bonigarcia.wdm.WebDriverManager.fallback(WebDriverManager.java:1425)
	at app//io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:1402)
	at app//io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:1183)
	at app//io.github.bonigarcia.wdm.WebDriverManager.setup(WebDriverManager.java:425)
	at app//io.github.bonigarcia.webdriver.junit4.ch02.helloworld.HelloWorldFirefoxJUnit4Test.setupClass(HelloWorldFirefoxJUnit4Test.java:41)
	at java.base@17.0.8/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@17.0.8/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base@17.0.8/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@17.0.8/java.lang.reflect.Method.invoke(Method.java:568)
	at app//org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at app//org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at app//org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at app//org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33)
	at app//org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at app//org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at app//org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:112)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:40)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:60)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:52)
	at java.base@17.0.8/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@17.0.8/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base@17.0.8/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@17.0.8/java.lang.reflect.Method.invoke(Method.java:568)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at jdk.proxy1/jdk.proxy1.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$2.run(TestWorker.java:176)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:113)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:65)
	at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
Caused by: io.github.bonigarcia.wdm.config.WebDriverManagerException: Error HTTP 404 executing https://raw.githubusercontent.com/bonigarcia/webdrivermanager/master/docs/mirror/geckodriver
	at app//io.github.bonigarcia.wdm.online.HttpClient.execute(HttpClient.java:177)
	at app//io.github.bonigarcia.wdm.WebDriverManager.openGitHubConnection(WebDriverManager.java:1592)
	at app//io.github.bonigarcia.wdm.WebDriverManager.getDriversFromGitHub(WebDriverManager.java:1606)
	at app//io.github.bonigarcia.wdm.managers.FirefoxDriverManager.getDriverUrls(FirefoxDriverManager.java:102)
	at app//io.github.bonigarcia.wdm.WebDriverManager.createUrlHandler(WebDriverManager.java:1430)
	at app//io.github.bonigarcia.wdm.WebDriverManager.download(WebDriverManager.java:1258)
	at app//io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:1177)
	... 39 more
```

I tried to open the https://raw.githubusercontent.com/bonigarcia/webdrivermanager/master/docs/mirror/geckodriver using Firefox browser. I successfull see the following:

```
[
  {
    "tag_name": "v0.33.0",
    "assets": [
      {
        "browser_download_url": "https://github.com/mozilla/geckodriver/releases/download/v0.33.0/geckodriver-v0.33.0-linux-aarch64.tar.gz"
      },
      {
        "browser_download_url": "https://github.com/mozilla/geckodriver/releases/download/v0.33.0/geckodriver-v0.33.0-linux32.tar.gz"
      },
      {
        "browser_download_url": "https://github.com/mozilla/geckodriver/releases/download/v0.33.0/geckodriver-v0.33.0-linux32.tar.gz.asc"
      },
      {
        "browser_download_url": "https://github.com/mozilla/geckodriver/releases/download/v0.33.0/geckodriver-v0.33.0-linux64.tar.gz"
      },
      {
        "browser_download_url": "https://github.com/mozilla/geckodriver/releases/download/v0.33.0/geckodriver-v0.33.0-linux64.tar.gz.asc"
      },
      {
        "browser_download_url": "https://github.com/mozilla/geckodriver/releases/download/v0.33.0/geckodriver-v0.33.0-macos-aarch64.tar.gz"
      },
      {
        "browser_download_url": "https://github.com/mozilla/geckodriver/releases/download/v0.33.0/geckodriver-v0.33.0-macos.tar.gz"
      },
      {
        "browser_download_url": "https://github.com/mozilla/geckodriver/releases/download/v0.33.0/geckodriver-v0.33.0-win-aarch64.zip"
      },
      {
        "browser_download_url": "https://github.com/mozilla/geckodriver/releases/download/v0.33.0/geckodriver-v0.33.0-win32.zip"
      },
      {
        "browser_download_url": "https://github.com/mozilla/geckodriver/releases/download/v0.33.0/geckodriver-v0.33.0-win64.zip"
      }
    ]
  },
  {
    "tag_name": "v0.32.2",
    "assets": [
....
```

Also using Chrome browser with DevTool I tried to get  https://raw.githubusercontent.com/bonigarcia/webdrivermanager/master/docs/mirror/geckodriver

<img width="1072" alt="Screenshot 2023-10-30 at 7 47 28" src="https://github.com/bonigarcia/webdrivermanager/assets/4467417/40d88abc-8d93-4739-bf0e-33797ee03ee5">

I got no problem.

QUESTION: Why do I get the HTTP 404 error from WebDriverManager?

------

In the commandline, I tried this:
```
$ curl https://raw.githubusercontent.com/bonigarcia/webdrivermanager/master/docs/mirror/geckodriver
```
this responded a JSON just the same as above. Therefore I believe I don't have any network issue.

**Comment by kazurayam** [comment]
I read the instruction by @bonigarcia in the https://github.com/bonigarcia/webdrivermanager/issues/891

so I modified the HelloWorldFirefoxJUnit4Test.java slightly


```
    @BeforeClass
    public static void setupClass() {
        //WebDriverManager.firefoxdriver().setup();
        WebDriverManager.firefoxdriver().useMirror().setup();
    }
```

https://github.com/kazurayam/selenium-webdriver-java/blob/kazurayam14/selenium-webdriver-junit4/src/test/java/io/github/bonigarcia/webdriver/junit4/ch02/helloworld/HelloWorldFirefoxJUnit4Test.java

Then the test ran successfully without "Error HTTP 404".

I do not yet see what's going on with the `useMirror()` part.

**Comment by kazurayam** [comment]
I experienced this "Error HTTP 404" on my MacBook Air with Chip Apple M1 , mac OS 12.7.

I have one more MacBook Air (Retina, 130inch, 2018) with Chip X86-64, mac OS 12.6.8. I tried to execute the same Test : https://github.com/kazurayam/selenium-webdriver-java/blob/kazurayam14/selenium-webdriver-junit4/src/test/java/io/github/bonigarcia/webdriver/junit4/ch02/helloworld/HelloWorldFirefoxJUnit4Test.java

It silently passed without "Error HTTP 404" error on another MacBook Air X86-64! 

Very interesting.

**Comment by kazurayam** [comment]
On my MacBook Air with Apple M1 chip, macOS 12.6.8 I updated Firefox from v118.0.2 to v119.0, then tried the same test  : https://github.com/kazurayam/selenium-webdriver-java/blob/kazurayam14/selenium-webdriver-junit4/src/test/java/io/github/bonigarcia/webdriver/junit4/ch02/helloworld/HelloWorldFirefoxJUnit4Test.java

The result: worked OK

```
> Task :selenium-webdriver-junit4:test
2023-10-30 10:26:49 [Test worker] DEBUG i.g.bonigarcia.wdm.WebDriverManager.<init>(225) - Using WebDriverManager 5.5.3
2023-10-30 10:26:50 [Test worker] DEBUG i.g.b.wdm.cache.ResolutionCache.checkKeyInResolutionCache(186) - Resolution firefox=118 in cache (valid until 10:59:08 30/10/2023 JST)
2023-10-30 10:26:50 [Test worker] DEBUG i.g.b.wdm.cache.ResolutionCache.checkKeyInResolutionCache(186) - Resolution firefox118=0.33.0 in cache (valid until 09:59:08 31/10/2023 JST)
2023-10-30 10:26:50 [Test worker] INFO  i.g.bonigarcia.wdm.WebDriverManager.resolveDriverVersion(1217) - Using geckodriver 0.33.0 (resolved driver for Firefox 118)
2023-10-30 10:26:50 [Test worker] DEBUG i.g.bonigarcia.wdm.WebDriverManager.manage(1172) - Driver geckodriver 0.33.0 found in cache
2023-10-30 10:26:50 [Test worker] INFO  i.g.bonigarcia.wdm.WebDriverManager.exportDriver(1270) - Exporting webdriver.gecko.driver as /Users/kazuakiurayama/.cache/selenium/geckodriver/mac64/0.33.0/geckodriver
2023-10-30 10:27:00 [Test worker] DEBUG i.g.b.w.j.c.h.HelloWorldFirefoxJUnit4Test.test(60) - The title of https://bonigarcia.dev/selenium-webdriver-java/ is Hands-On Selenium WebDriver with Java
io.github.bonigarcia.webdriver.junit4.ch02.helloworld.HelloWorldFirefoxJUnit4Test > test PASSED
Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.
You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
For more on this, please refer to https://docs.gradle.org/8.4/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.
BUILD SUCCESSFUL in 1m 51s
5 actionable tasks: 5 executed
10:27:03: Execution finished ':selenium-webdriver-junit4:test --tests "io.github.bonigarcia.webdriver.junit4.ch02.helloworld.HelloWorldFirefoxJUnit4Test"'.

```

This experiment implies 2 factors as a possible cause of the "Error HTTP 404" error:

1. Apple X86-64 Chip vs M1 Chip
2. macOS 12.68 vs 12.70

... umn, highly unlikely

**Comment by kazurayam** [comment]
I want to see all the HTTP request and response exchanged between the test class and the target URL. I would use BrowserMobProxy.

**Comment by kazurayam** [comment]
I found this:

https://bonigarcia.dev/webdrivermanager/#known-issues

><h2 id="known-issues" style="box-sizing: border-box; margin: 0.5em 0px; padding: 0px; direction: ltr; font-family: &quot;Titillium Web&quot;, Verdana, Arial, sans-serif; font-weight: normal; font-style: normal; color: rgb(97, 99, 102); text-rendering: geometricprecision; line-height: 1.4; font-size: 2.3125em; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">7. Known Issues</h2><div class="sectionbody" style="box-sizing: border-box; margin: 0px; padding: 0px; direction: ltr; color: rgb(34, 34, 34); font-family: &quot;Helvetica Neue&quot;, Helvetica, Helvetica, Arial, sans-serif; font-size: 20px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="sect2" style="box-sizing: border-box; margin: 0px; padding: 0px; direction: ltr;"><h3 id="http-response-code-403" style="box-sizing: border-box; margin: 0.5em 0px; padding: 0px; direction: ltr; font-family: &quot;Titillium Web&quot;, Verdana, Arial, sans-serif; font-weight: normal; font-style: normal; color: rgb(97, 99, 102); text-rendering: geometricprecision; line-height: 1.4; font-size: 1.6875em;"><a class="anchor" href="https://bonigarcia.dev/webdrivermanager/#http-response-code-403" style="box-sizing: border-box; color: rgb(41, 132, 169); text-decoration: none; line-height: inherit; position: absolute; width: 1em; margin-left: -1em; display: block; visibility: hidden; text-align: center; font-weight: normal;"></a>7.1. HTTP response code 403</h3><div class="paragraph" style="box-sizing: border-box; margin: 0px; padding: 0px; direction: ltr;"><p style="box-sizing: border-box; margin: 0px 0px 0.9375em; padding: 0px; direction: ltr; font-family: inherit; font-weight: normal; font-size: 1em; line-height: 1.5; text-rendering: geometricprecision;">Some of the drivers (e.g., geckodriver or operadriver) are hosted on GitHub. When external clients (like WebDriverManager) make many consecutive requests to GitHub, and due to its traffic rate limit, it eventually responds with an HTTP 403 error (<em style="box-sizing: border-box; font-style: italic; line-height: inherit;">forbidden</em>), as follows:</p></div><div class="listingblock" style="box-sizing: border-box; margin: 0px 0px 1.25em; padding: 0px; direction: ltr;"><div class="content" style="box-sizing: border-box; margin: 0px; padding: 0px; direction: ltr; position: relative;"><pre class="CodeRay highlight" style="box-sizing: border-box; font-family: monospace, serif; font-size: 0.8em; white-space: pre-wrap; margin: 0px; padding: 15px; direction: ltr; line-height: 1.6; color: inherit; font-weight: normal; background: rgb(247, 247, 248); border-width: 0px 0px 1px; border-style: solid; border-color: rgb(240, 240, 240); border-radius: 5px; overflow-wrap: break-word; box-shadow: rgb(174, 185, 182) 0px 1px 4px inset;"><code style="box-sizing: border-box; font-family: monospace, serif; font-size: 1em; font-weight: normal; color: inherit; line-height: 1.6; display: block;">io.github.bonigarcia.wdm.config.WebDriverManagerException: Error HTTP 403 executing https://api.github.com/repos/mozilla/geckodriver/releases
    at io.github.bonigarcia.wdm.online.HttpClient.execute(HttpClient.java:172)
    at io.github.bonigarcia.wdm.WebDriverManager.openGitHubConnection(WebDriverManager.java:1266)
    at io.github.bonigarcia.wdm.WebDriverManager.getDriversFromGitHub(WebDriverManager.java:1280)
    at io.github.bonigarcia.wdm.managers.FirefoxDriverManager.getDriverUrls(FirefoxDriverManager.java:95)
    at io.github.bonigarcia.wdm.WebDriverManager.createUrlHandler(WebDriverManager.java:1111)
    at io.github.bonigarcia.wdm.WebDriverManager.download(WebDriverManager.java:959)
    at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:877)
    at io.github.bonigarcia.wdm.WebDriverManager.fallback(WebDriverManager.java:1106)
    at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:1083)
    at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:883)
    at io.github.bonigarcia.wdm.WebDriverManager.setup(WebDriverManager.java:328)</code></pre></div></div><div class="paragraph" style="box-sizing: border-box; margin: 0px; padding: 0px; direction: ltr;"><p style="box-sizing: border-box; margin: 0px 0px 0.9375em; padding: 0px; direction: ltr; font-family: inherit; font-weight: normal; font-size: 1em; line-height: 1.5; text-rendering: geometricprecision;">To avoid this problem, WebDriverManager can make authenticated requests using a<span> </span><a href="https://docs.github.com/en/github/authenticating-to-github/keeping-your-account-and-data-secure/creating-a-personal-access-token" style="box-sizing: border-box; color: rgb(41, 132, 169); text-decoration: none; line-height: inherit;">personal access token</a>. See the<span> </span><a href="https://bonigarcia.dev/webdrivermanager/#advanced-configuration" style="box-sizing: border-box; color: rgb(41, 132, 169); text-decoration: none; line-height: inherit;">advanced configuration</a><span> </span>section to discover how to set up this token in WebDriverManager.</p></div><div class="admonitionblock tip" style="box-sizing: border-box; margin: 0px; padding: 0px; direction: ltr;">

  | As of WebDriverManager 5.3.0, this issue should not happen anymore (even without a GitHub token). To avoid the 403 error, an automated job in GitHub Actions mirrors the GitHub API responses twice a day. This mirror is used internally by WebDriverManager instead of querying the GitHub API.
-- | --


</div></div></div>7. Known Issues
7.1. HTTP response code 403
Some of the drivers (e.g., geckodriver or operadriver) are hosted on GitHub. When external clients (like WebDriverManager) make many consecutive requests to GitHub, and due to its traffic rate limit, it eventually responds with an HTTP 403 error (forbidden), as follows:

io.github.bonigarcia.wdm.config.WebDriverManagerException: Error HTTP 403 executing https://api.github.com/repos/mozilla/geckodriver/releases
    at io.github.bonigarcia.wdm.online.HttpClient.execute(HttpClient.java:172)
    at io.github.bonigarcia.wdm.WebDriverManager.openGitHubConnection(WebDriverManager.java:1266)
    at io.github.bonigarcia.wdm.WebDriverManager.getDriversFromGitHub(WebDriverManager.java:1280)
    at io.github.bonigarcia.wdm.managers.FirefoxDriverManager.getDriverUrls(FirefoxDriverManager.java:95)
    at io.github.bonigarcia.wdm.WebDriverManager.createUrlHandler(WebDriverManager.java:1111)
    at io.github.bonigarcia.wdm.WebDriverManager.download(WebDriverManager.java:959)
    at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:877)
    at io.github.bonigarcia.wdm.WebDriverManager.fallback(WebDriverManager.java:1106)
    at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:1083)
    at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:883)
    at io.github.bonigarcia.wdm.WebDriverManager.setup(WebDriverManager.java:328)
To avoid this problem, WebDriverManager can make authenticated requests using a [personal access token](https://docs.github.com/en/github/authenticating-to-github/keeping-your-account-and-data-secure/creating-a-personal-access-token). See the [advanced configuration](https://bonigarcia.dev/webdrivermanager/#advanced-configuration) section to discover how to set up this token in WebDriverManager.

As of WebDriverManager 5.3.0, this issue should not happen anymore (even without a GitHub token). To avoid the 403 error, an automated job in GitHub Actions mirrors the GitHub API responses twice a day. This mirror is used internally by WebDriverManager instead of querying the GitHub API.

**Comment by kazurayam** [comment]
I should study more on my side. 
I would close this issue.

**Comment by kazurayam** [comment]
One idea for workaround could be to use `useMirror()`.

**Comment by kazurayam** [comment]
I found that my MacBook has the environment variable `GITHUB_TOKEN`. However the value of the envVar was invalid. Possibly I created a valid GitHub Personal Access Token months ago and gave the PAT as the `$GITHUB_TOKEN` value. And later the PAT had expired, or maybe I removed it from my GitHub account, but the envVar stayed as was created. 

When the envVar `GITHUB_TOKEN` is defined but the value is invalid, then WebDriverManager throws an error "Error HTTP 404 executing https://raw.githubusercontent.com/bonigarcia/webdrivermanager/master/docs/mirror/geckodriver".

When I searched Google with keyword

**Comment by kazurayam** [comment]
When I searched Google with keyword "Error HTTP 404 executing https://raw.githubusercontent.com/bonigarcia/webdrivermanager/master/docs/mirror/geckodriver", I got nothing relevant to it. So I got at a loss what to do. 

The WebDriverManager's document https://bonigarcia.dev/webdrivermanager/#known-issues should exlicitly mention the error message "Error HTTP 404 executing https://raw.githubusercontent.com/bonigarcia/webdrivermanager/master/docs/mirror/geckodriver" so that users can easily find a clue to solve the problem.

They should do either of the following 2:

1. create a new valid GitHub Personal Access Token, and specify it to the envVar `GITHUB_TOKEN`
2. remove the envVar `GITHUB_TOKEN` with invalid value; then WebDriverManager will look at the Mirror URL

**Comment by kazurayam** [comment]
I wrote:

>It seems that HttpClient class of the WebDriverManager works wrong on Mac as you see ... but the same code works fine on Windows.

On 2 Mac I had the envVar `GITHUB_TOKEN` with invalid value. On Windows I did not have the envVar `GITHUB_TOKEN`. This explains well what I saw.

**Comment by bonigarcia** [comment]
As of version 5.3.0, you don't need to use `GITHUB_TOKEN` anymore, so you can remove that env var (especially if it has a wrong value).
