### ISSUE TITLE
FileNotFoundException if /etc/upstream-release is a directory

### ISSUE THREAD

**Issue by rtack** [bonigarcia/webdrivermanager#116]
On my system /etc/upstream-release is a directory and not a file but the code assumes that there are only files found.

See also http://unix.stackexchange.com/questions/270199/which-version-of-ubuntu-is-my-linux-mint-installation-based-on  for the folder/file structure.

![image](https://cloud.githubusercontent.com/assets/5379/24368591/46012904-1321-11e7-857e-3f3a8b9870c7.png)

java.lang.RuntimeException: java.io.FileNotFoundException: /etc/upstream-release (Is a directory)
	at io.github.bonigarcia.wdm.BrowserManager.manage(BrowserManager.java:244)
	at io.github.bonigarcia.wdm.BrowserManager.setup(BrowserManager.java:733)
	at io.github.bonigarcia.wdm.BrowserManager.setup(BrowserManager.java:693)
	at org.xyz.test.setupDriver(SeleniumSetup.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: java.io.FileNotFoundException: /etc/upstream-release (Is a directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileReader.<init>(FileReader.java:72)
	at io.github.bonigarcia.wdm.BrowserManager.getDistroName(BrowserManager.java:417)
	at io.github.bonigarcia.wdm.BrowserManager.manage(BrowserManager.java:208)
	... 18 more

**Comment by bonigarcia** [comment]
It should be fixed now. It will be available in version 1.6.2.
