### ISSUE TITLE
Better error reporting for situation where JSON isn't JSON

### ISSUE THREAD

**Issue by paul-hammant** [bonigarcia/webdrivermanager#1167]
Attempting to mirror Google's chromedriver bit and pieces inside a corporate infra, cos of corporate rules:

```
[main] INFO io.github.bonigarcia.wdm.cache.ResolutionCache - Clearing WebDriverManager resolution cache
[main] WARN io.github.bonigarcia.wdm.WebDriverManager - There was an error managing chromedriver (latest version) (java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 7 column 1 path $) ... trying again avoiding reading release from repository
[main] WARN io.github.bonigarcia.wdm.WebDriverManager - There was an error managing chromedriver (latest version) (java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 7 column 1 path $) ... trying again using latest driver stored in cache
[main] ERROR io.github.bonigarcia.wdm.WebDriverManager - There was an error managing chromedriver (latest version) (java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 7 column 1 path $)
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 7 column 1 path $
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:397)
        at com.google.gson.Gson.fromJson(Gson.java:1227)
        at com.google.gson.Gson.fromJson(Gson.java:1137)
        at com.google.gson.Gson.fromJson(Gson.java:1075)
        at io.github.bonigarcia.wdm.online.Parser.parseJson(Parser.java:53)
        at io.github.bonigarcia.wdm.managers.ChromeDriverManager.getDriverUrls(ChromeDriverManager.java:119)
        at io.github.bonigarcia.wdm.WebDriverManager.createUrlHandler(WebDriverManager.java:1456)
        at io.github.bonigarcia.wdm.WebDriverManager.download(WebDriverManager.java:1277)
        at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:1189)
        at io.github.bonigarcia.wdm.WebDriverManager.fallback(WebDriverManager.java:1451)
        at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:1432)
        at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:1195)
        at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:1425)
        at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:1195)
        at io.github.bonigarcia.wdm.WebDriverManager.setup(WebDriverManager.java:427)
        at mypackage.MyTestNgTestBase.initTestSuite(TestNgTestBase.java:31)
```

https://github.com/bonigarcia/webdrivermanager/blob/master/src/main/java/io/github/bonigarcia/wdm/managers/ChromeDriverManager.java#L119  is getting a resource (from an internal GitHub-Enterprise 'pages' hosting). But whatever it is getting back that should be JSON isn't JSON according the the gson lib.  On closer inspection there was a "must login" HTML page being sent back instead. Yes, with a .json suffix.

Granted the end user could probably do some trial and error to see with WGET, that but it might be useful to say more in the error handling? Thoughts?

Maybe I can make a pull request to catch JsonSyntaxException **rethrow** it with extra what-was-the-url and what-was-the-first the content (say the first 500 lines if not binary)?

**Comment by bonigarcia** [comment]
> Maybe I can make a pull request to catch JsonSyntaxException **rethrow** it with extra what-was-the-url and what-was-the-first the content (say the first 500 lines if not binary)?

Sure, please go ahead with that PR; thanks.

**Comment by paul-hammant** [comment]
There you go, Mr

**Comment by bonigarcia** [comment]
Thanks for contributing, merged
