### ISSUE TITLE
It download chromedriver 114 when it's Chrome 119

### ISSUE THREAD

**Issue by python012** [bonigarcia/webdrivermanager#1169]
**Description of the problem**: it doesn't support Chrome 119, and it would download chromedriver 114, as a result the driver would fail to launch Chrome 119

**Browser and version**: Chrome 119 on Windows 10

**Operating system and architecture**: Windows 10 Enterprise

**Selenium version**: 3.141.59

**WebDriverManager version**: 5.3.3

**WebDriverManager call**: 
```
String Browser = prop.getProperty("browser");
		if (Browser.equals("chrome")) {
			WebDriverManager.chromedriver().setup();
			driver = new ChromeDriver();
		} else if (Browser.equals("firefox")) {
			WebDriverManager.firefoxdriver().setup();
			driver = new FirefoxDriver();
		}
```

**WebDriverManager traces**: 
```
```

**Error log**: 
```
2023-11-08T16:57:23.1011550Z  T E S T S
2023-11-08T16:57:23.1012064Z -------------------------------------------------------
2023-11-08T16:57:23.4989363Z Running TestSuite
2023-11-08T16:57:26.0353971Z [main] INFO io.github.bonigarcia.wdm.WebDriverManager - Reading https://chromedriver.storage.googleapis.com/ to seek chromedriver
2023-11-08T16:57:26.7390786Z [main] INFO io.github.bonigarcia.wdm.online.Downloader - Downloading https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_win32.zip
2023-11-08T16:57:26.9441001Z [main] INFO io.github.bonigarcia.wdm.online.Downloader - Extracting driver from compressed file chromedriver_win32.zip
2023-11-08T16:57:27.0306664Z [main] INFO io.github.bonigarcia.wdm.WebDriverManager - Exporting webdriver.chrome.driver as C:\Users\AzDevOps\.cache\selenium\chromedriver\win32\114.0.5735.90\chromedriver.exe
2023-11-08T16:57:27.4847637Z Starting ChromeDriver 114.0.5735.90 (386bc09e8f4f2e025eddae123f36f6263096ae49-refs/branch-heads/5735@{#1052}) on port 18408
2023-11-08T16:57:27.4849848Z Only local connections are allowed.
2023-11-08T16:57:27.4852450Z Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
2023-11-08T16:57:27.4938409Z ChromeDriver was started successfully.
2023-11-08T16:57:28.3161859Z 
2023-11-08T16:57:28.3162603Z Results :
2023-11-08T16:57:28.3162724Z 
2023-11-08T16:57:28.3200651Z Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
2023-11-08T16:57:28.3201092Z 
2023-11-08T16:57:28.3256362Z [INFO] ------------------------------------------------------------------------
2023-11-08T16:57:28.3256993Z [INFO] BUILD FAILURE
2023-11-08T16:57:28.3257332Z [INFO] ------------------------------------------------------------------------
2023-11-08T16:57:28.3273740Z [INFO] Total time:  19.095 s
2023-11-08T16:57:28.3274464Z [INFO] Finished at: 2023-11-08T16:57:28Z
2023-11-08T16:57:28.3275146Z [INFO] ------------------------------------------------------------------------
2023-11-08T16:57:28.3289164Z [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project LOCJO: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test failed: There was an error in the forked process
2023-11-08T16:57:28.3291382Z [ERROR] org.testng.TestNGException: 
2023-11-08T16:57:28.3291820Z [ERROR] 
2023-11-08T16:57:28.3292338Z [ERROR] An error occurred while instantiating class loginTest.LoginToEMS: null
2023-11-08T16:57:28.3293592Z [ERROR] 	at org.testng.internal.objects.SimpleObjectDispenser.createInstance(SimpleObjectDispenser.java:99)
2023-11-08T16:57:28.3295026Z [ERROR] 	at org.testng.internal.objects.SimpleObjectDispenser.dispense(SimpleObjectDispenser.java:40)
2023-11-08T16:57:28.3296383Z [ERROR] 	at org.testng.internal.objects.GuiceBasedObjectDispenser.dispense(GuiceBasedObjectDispenser.java:28)
2023-11-08T16:57:28.3299806Z [ERROR] 	at org.testng.internal.ClassImpl.getDefaultInstance(ClassImpl.java:106)
2023-11-08T16:57:28.3303033Z [ERROR] 	at org.testng.internal.ClassImpl.getInstances(ClassImpl.java:136)
2023-11-08T16:57:28.3305272Z [ERROR] 	at org.testng.TestClass.getInstances(TestClass.java:129)
2023-11-08T16:57:28.3306964Z [ERROR] 	at org.testng.TestClass.initTestClassesAndInstances(TestClass.java:109)
2023-11-08T16:57:28.3309341Z [ERROR] 	at org.testng.TestClass.init(TestClass.java:101)
2023-11-08T16:57:28.3310494Z [ERROR] 	at org.testng.TestClass.<init>(TestClass.java:66)
2023-11-08T16:57:28.3312306Z [ERROR] 	at org.testng.TestRunner.initMethods(TestRunner.java:464)
2023-11-08T16:57:28.3313139Z [ERROR] 	at org.testng.TestRunner.init(TestRunner.java:336)
2023-11-08T16:57:28.3313864Z [ERROR] 	at org.testng.TestRunner.init(TestRunner.java:289)
2023-11-08T16:57:28.3314649Z [ERROR] 	at org.testng.TestRunner.<init>(TestRunner.java:179)
2023-11-08T16:57:28.3315533Z [ERROR] 	at org.testng.SuiteRunner$DefaultTestRunnerFactory.newTestRunner(SuiteRunner.java:643)
2023-11-08T16:57:28.3316458Z [ERROR] 	at org.testng.SuiteRunner.init(SuiteRunner.java:225)
2023-11-08T16:57:28.3317159Z [ERROR] 	at org.testng.SuiteRunner.<init>(SuiteRunner.java:115)
2023-11-08T16:57:28.3317921Z [ERROR] 	at org.testng.TestNG.createSuiteRunner(TestNG.java:1349)
2023-11-08T16:57:28.3318706Z [ERROR] 	at org.testng.TestNG.createSuiteRunners(TestNG.java:1325)
2023-11-08T16:57:28.3319457Z [ERROR] 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1167)
2023-11-08T16:57:28.3320142Z [ERROR] 	at org.testng.TestNG.runSuites(TestNG.java:1099)
2023-11-08T16:57:28.3320952Z [ERROR] 	at org.testng.TestNG.run(TestNG.java:1067)
2023-11-08T16:57:28.3321824Z [ERROR] 	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
2023-11-08T16:57:28.3322881Z [ERROR] 	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
2023-11-08T16:57:28.3323935Z [ERROR] 	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
2023-11-08T16:57:28.3325098Z [ERROR] 	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
2023-11-08T16:57:28.3326289Z [ERROR] 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
2023-11-08T16:57:28.3327291Z [ERROR] 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
2023-11-08T16:57:28.3328042Z [ERROR] Caused by: java.lang.ExceptionInInitializerError
2023-11-08T16:57:28.3328608Z [ERROR] 	at loginTest.LoginToEMS.<clinit>(LoginToEMS.java:21)
2023-11-08T16:57:28.3329433Z [ERROR] 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
2023-11-08T16:57:28.3330655Z [ERROR] 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
2023-11-08T16:57:28.3332169Z [ERROR] 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
2023-11-08T16:57:28.3333670Z [ERROR] 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
2023-11-08T16:57:28.3334862Z [ERROR] 	at org.testng.internal.objects.InstanceCreator.newInstance(InstanceCreator.java:38)
2023-11-08T16:57:28.3335905Z [ERROR] 	at org.testng.ITestObjectFactory.newInstance(ITestObjectFactory.java:18)
2023-11-08T16:57:28.3337178Z [ERROR] 	at org.testng.internal.objects.SimpleObjectDispenser.instantiateUsingDefaultConstructor(SimpleObjectDispenser.java:178)
2023-11-08T16:57:28.3338666Z [ERROR] 	at org.testng.internal.objects.SimpleObjectDispenser.createInstance(SimpleObjectDispenser.java:87)
2023-11-08T16:57:28.3339530Z [ERROR] 	... 26 more
2023-11-08T16:57:28.3340164Z [ERROR] Caused by: org.openqa.selenium.WebDriverException: unknown error: cannot find Chrome binary
2023-11-08T16:57:28.3342055Z [ERROR] Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
2023-11-08T16:57:28.3345855Z [ERROR] System info: host: 'ms0001E4', ip: '10.0.0.8', os.name: 'Windows Server 2022', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.16.1'
2023-11-08T16:57:28.3347056Z [ERROR] Driver info: driver.version: ChromeDriver
2023-11-08T16:57:28.3348253Z [ERROR] remote stacktrace: Backtrace:
2023-11-08T16:57:28.3349762Z [ERROR] 	GetHandleVerifier [0x007AA813+48355]
2023-11-08T16:57:28.3350756Z [ERROR] 	(No symbol) [0x0073C4B1]
2023-11-08T16:57:28.3351416Z [ERROR] 	(No symbol) [0x00645358]
2023-11-08T16:57:28.3351817Z [ERROR] 	(No symbol) [0x00661A9E]
2023-11-08T16:57:28.3352843Z [ERROR] 	(No symbol) [0x00660579]
2023-11-08T16:57:28.3353278Z [ERROR] 	(No symbol) [0x00690C55]
2023-11-08T16:57:28.3353647Z [ERROR] 	(No symbol) [0x0069093C]
2023-11-08T16:57:28.3354409Z [ERROR] 	(No symbol) [0x0068A536]
2023-11-08T16:57:28.3354774Z [ERROR] 	(No symbol) [0x006682DC]
2023-11-08T16:57:28.3357635Z [ERROR] 	(No symbol) [0x006693DD]
2023-11-08T16:57:28.3358091Z [ERROR] 	GetHandleVerifier [0x00A0AABD+2539405]
2023-11-08T16:57:28.3358791Z [ERROR] 	GetHandleVerifier [0x00A4A78F+2800735]
2023-11-08T16:57:28.3359309Z [ERROR] 	GetHandleVerifier [0x00A4456C+2775612]
2023-11-08T16:57:28.3359841Z [ERROR] 	GetHandleVerifier [0x008351E0+616112]
2023-11-08T16:57:28.3362880Z [ERROR] 	(No symbol) [0x00745F8C]
2023-11-08T16:57:28.3363274Z [ERROR] 	(No symbol) [0x00742328]
2023-11-08T16:57:28.3363624Z [ERROR] 	(No symbol) [0x0074240B]
2023-11-08T16:57:28.3364007Z [ERROR] 	(No symbol) [0x00734FF7]
2023-11-08T16:57:28.3364408Z [ERROR] 	BaseThreadInitThunk [0x77076A39+25]
2023-11-08T16:57:28.3364902Z [ERROR] 	RtlGetFullPathName_UEx [0x77867E4D+173]
2023-11-08T16:57:28.3365602Z [ERROR] 	RtlGetFullPathName_UEx [0x77867E1B+123]
```

**Comment by python012** [comment]
I tried to add this line to support Chrome 119(see https://github.com/python012/webdrivermanager/blob/91739a172ec930e73a611e4dc8b3f363969bb0ff/src/main/resources/versions.properties#L5C1-L5C25), my test passed in local, but looks the new code with my commit cannot pass, see(https://github.com/python012/webdrivermanager/actions), so I didn't raise the PR

**Comment by bonigarcia** [comment]
This is a known issue of old versions of WebDriverManager, see [doc](https://bonigarcia.dev/webdrivermanager/#support-for-chromedriver-115). The solution is to use the latest version of WebDriverManager (5.6.2 at the time of this writing).

**Comment by Jamalludeen** [comment]
Hi Guys;
How can I download chromeDriver version 119 for selenium module of python?
Plz help me!

**Comment by osenyuk** [comment]
I am using the latest versions of WebdriverManager and Selenium with Java Maven project and still get the same error. org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: session not created: This version of ChromeDriver only supports Chrome version 114
Current browser version is 121.0.6167.185 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe 
Reading the https://chromedriver.chromium.org/downloads seems this will never be fixed, right?

**Comment by CarlosValero1990** [comment]
I had this error a week ago @osenyuk, everything changed from the build, properties, cache, etc. and nothing works so far

**Comment by CarlosValero1990** [comment]
I ran the automation from SERENITY.PROPERTIES. Do you know what change I should make?
