### ISSUE TITLE
Can not download file via proxy server that needs authentication

### ISSUE THREAD

**Issue by kazuki43zoo** [bonigarcia/webdrivermanager#118]
In my company, we need to access a download site (and download file) via proxy server that needs authentication.
Unfortunately, the `WebDriverManager` seems it does not support. I will hope to support it. 

* Setup

```java
@BeforeClass
public static void setupWebDriverManager() {
	Authenticator.setDefault(new Authenticator() {
		@Override
		protected PasswordAuthentication getPasswordAuthentication() {
			return new PasswordAuthentication("test", "test".toCharArray()); // ### a user for test
		}
	});
	FirefoxDriverManager.getInstance().proxy("http://localhost:9999"); // ### Proxy url that need authentication
	FirefoxDriverManager.getInstance().setup();
}
```

* Stack Trace

```
...
java.lang.RuntimeException: java.io.IOException: Unable to tunnel through proxy. Proxy returns "HTTP/1.1 407 Proxy Authentication Required"

	at io.github.bonigarcia.wdm.BrowserManager.manage(BrowserManager.java:244)
	at io.github.bonigarcia.wdm.BrowserManager.setup(BrowserManager.java:733)
	at io.github.bonigarcia.wdm.BrowserManager.setup(BrowserManager.java:693)
...
Caused by: java.io.IOException: Unable to tunnel through proxy. Proxy returns "HTTP/1.1 407 Proxy Authentication Required"
	at sun.net.www.protocol.http.HttpURLConnection.doTunneling(HttpURLConnection.java:2124)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:183)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:153)
	at io.github.bonigarcia.wdm.BrowserManager.openGitHubConnection(BrowserManager.java:653)
...
```

* Access logs on Proxy Server

```
...
172.17.0.1 - - [28/Mar/2017:18:34:55 +0000] "CONNECT api.github.com:443 HTTP/1.1" 407 415 "-" "Java/1.8.0_112"
172.17.0.1 - - [28/Mar/2017:18:35:31 +0000] "CONNECT api.github.com:443 HTTP/1.1" 407 415 "-" "Java/1.8.0_112"
...
```

**A credentials has not been submitted.**

---

This behavior occurred by **HTTPS** access. I've tried **HTTP** access as follow:

```properties
wdm.geckoDriverUrl=http://api.github.com/repos/mozilla/geckodriver/releases
```

As result, "407 Proxy Authentication Required" is not occurred.

* Stack Trace

```
java.lang.RuntimeException: java.lang.NullPointerException

	at io.github.bonigarcia.wdm.BrowserManager.manage(BrowserManager.java:244)
	at io.github.bonigarcia.wdm.BrowserManager.setup(BrowserManager.java:733)
...
Caused by: java.lang.NullPointerException
	at io.github.bonigarcia.wdm.FirefoxDriverManager.getVersion(FirefoxDriverManager.java:89)
	at io.github.bonigarcia.wdm.FirefoxDriverManager.getDrivers(FirefoxDriverManager.java:68)
	at io.github.bonigarcia.wdm.BrowserManager.manage(BrowserManager.java:175)
...
```

* Access Logs on Proxy Server

```
...
172.17.0.1 - - [28/Mar/2017:18:36:47 +0000] "GET http://api.github.com/repos/mozilla/geckodriver/releases HTTP/1.1" 407 415 "-" "Mozilla/5.0"
172.17.0.1 - test [28/Mar/2017:18:36:47 +0000] "GET http://api.github.com/repos/mozilla/geckodriver/releases HTTP/1.1" 301 - "-" "Mozilla/5.0"
...
```

**A credentials has been submitted.**

**Comment by kazuki43zoo** [comment]
I've tried using proxy feature of Apache.

See https://github.com/kazuki43zoo/apache-proxy-server.

**Comment by bonigarcia** [comment]
I've been checking it but unfortunately it is difficult for me to test a possible solution. I invite you to make a PR to solve this issue.

**Comment by kazuki43zoo** [comment]
This issue can resolve using the [Http Components HttpClient](https://hc.apache.org/).

**Comment by bonigarcia** [comment]
Your PR looks nice. Merged.

**Comment by kazuki43zoo** [comment]
Thanks for merging !!

**Comment by hyfzur** [comment]
Can a working example be provided for this implementation?
