### ISSUE TITLE
Exception on setting up Internet Explorer driver

### ISSUE THREAD

**Issue by jakimcho** [bonigarcia/webdrivermanager#1189]
# Description of the problem: 
During the iedriver setup and exception ` java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 1 column 1 path $` is thrown

**Browser and version:** Internet Explorer 1809

**Operating system:** Windows 10

**WebDriverManager version:** 5.6.2

## **WebDriverManager call:** 

``` 
WebDriverManager.iedriver()
                .proxy(CONFIG_FILE_READER.getProxyUrl())
                .proxyUser(CONFIG_FILE_READER.getProxyUser())
                .proxyPass(CONFIG_FILE_READER.getProxyPass())
                .arch32()
                .setup();
```

## **Exception:**
```
io.github.bonigarcia.wdm.config.WebDriverManagerException: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 1 column 1 path $
	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:1435)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:1195)
	at io.github.bonigarcia.wdm.WebDriverManager.fallback(WebDriverManager.java:1451)
	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:1428)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:1195)
	at io.github.bonigarcia.wdm.WebDriverManager.setup(WebDriverManager.java:427)
	at eqtest.sirius.utils.DriverManager.setWebDriver(DriverManager.java:92)
	at eqtest.sirius.utils.DriverManager.getWebDriver(DriverManager.java:30)
	at eqtest.sirius.steps.base.BaseSteps.Setup(BaseSteps.java:54)
```

**Comment by bonigarcia** [comment]
I have just checked this is working properly. In you enable the [WebDriverManager logs](https://bonigarcia.dev/webdrivermanager/#troubleshooting), you should see something like the following:

```
2023-12-22 13:22:00 [main] DEBUG i.g.bonigarcia.wdm.WebDriverManager.<init>(227) -- Using WebDriverManager 5.6.2
2023-12-22 13:22:00 [main] DEBUG i.g.bonigarcia.wdm.WebDriverManager.resolveDriverVersion(1259) -- The driver version for IEXPLORER is unknown ... trying with latest
2023-12-22 13:22:00 [main] INFO  i.g.bonigarcia.wdm.WebDriverManager.logSeekRepo(1597) -- Reading https://raw.githubusercontent.com/bonigarcia/webdrivermanager/master/docs/mirror/selenium to seek IEDriverServer
2023-12-22 13:22:01 [main] DEBUG i.g.bonigarcia.wdm.WebDriverManager.createUrlHandler(1484) -- Driver to be downloaded IEDriverServer 4.14.0
2023-12-22 13:22:01 [main] INFO  i.g.bonigarcia.wdm.online.Downloader.downloadAndExtract(132) -- Downloading https://github.com/SeleniumHQ/selenium/releases/download/selenium-4.14.0/IEDriverServer_Win32_4.14.0.zip
2023-12-22 13:22:02 [main] INFO  i.g.bonigarcia.wdm.online.Downloader.extract(193) -- Extracting driver from compressed file iedriverserver_win32_4.14.0.zip
2023-12-22 13:22:02 [main] INFO  i.g.bonigarcia.wdm.WebDriverManager.exportDriver(1296) -- Exporting webdriver.ie.driver as C:\Users\boni\.cache\selenium\IEDriverServer\win32\4.14.0\IEDriverServer.exe
2023-12-22 13:22:02 [main] DEBUG i.g.b.w.t.i.IExplorerArchTest.assertIEDriver(56) -- Path for IEDriverServer C:\Users\boni\.cache\selenium\IEDriverServer\win32\4.14.0\IEDriverServer.exe
```

If the issue persist, it should be a connectivy issue when reading https://raw.githubusercontent.com/bonigarcia/webdrivermanager/master/docs/mirror/selenium

**Comment by jakimcho** [comment]
@bonigarcia thank you for the tips on how to troubleshoot. 
I test it on two machines, one is with proxy and the other is not. 
On the one that is not behind a proxy everything works just fine, but the other with proxy is giving the problem:

```
"C:\Program Files\Zulu\zulu-17\bin\java.exe" "-javaagent:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2023.2.5\lib\idea_rt.jar=61152:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2023.2.5\bin" -Dfile.encoding=UTF-8 -classpath C:\Users\r001-rachev\IdeaProjects\DriverManager\target\classes;C:\Users\r001-rachev\.m2\repository\org\seleniumhq\selenium\selenium-java\4.9.0\selenium-java-4.9.0.jar;C:\Users\r001-rachev\.m2\repository\org\seleniumhq\selenium\selenium-api\4.9.0\selenium-api-4.9.0.jar;C:\Users\r001-rachev\.m2\repository\org\seleniumhq\selenium\selenium-chrome-driver\4.9.0\selenium-chrome-driver-4.9.0.jar;C:\Users\r001-rachev\.m2\repository\com\google\auto\service\auto-service-annotations\1.0.1\auto-service-annotations-1.0.1.jar;C:\Users\r001-rachev\.m2\repository\com\google\auto\service\auto-service\1.0.1\auto-service-1.0.1.jar;C:\Users\r001-rachev\.m2\repository\com\google\auto\auto-common\1.2\auto-common-1.2.jar;C:\Users\r001-rachev\.m2\repository\com\google\guava\guava\31.1-jre\guava-31.1-jre.jar;C:\Users\r001-rachev\.m2\repository\com\google\guava\failureaccess\1.0.1\failureaccess-1.0.1.jar;C:\Users\r001-rachev\.m2\repository\com\google\guava\listenablefuture\9999.0-empty-to-avoid-conflict-with-guava\listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar;C:\Users\r001-rachev\.m2\repository\com\google\code\findbugs\jsr305\3.0.2\jsr305-3.0.2.jar;C:\Users\r001-rachev\.m2\repository\org\checkerframework\checker-qual\3.12.0\checker-qual-3.12.0.jar;C:\Users\r001-rachev\.m2\repository\com\google\errorprone\error_prone_annotations\2.11.0\error_prone_annotations-2.11.0.jar;C:\Users\r001-rachev\.m2\repository\com\google\j2objc\j2objc-annotations\1.3\j2objc-annotations-1.3.jar;C:\Users\r001-rachev\.m2\repository\org\seleniumhq\selenium\selenium-chromium-driver\4.9.0\selenium-chromium-driver-4.9.0.jar;C:\Users\r001-rachev\.m2\repository\org\seleniumhq\selenium\selenium-json\4.9.0\selenium-json-4.9.0.jar;C:\Users\r001-rachev\.m2\repository\org\seleniumhq\selenium\selenium-manager\4.9.0\selenium-manager-4.9.0.jar;C:\Users\r001-rachev\.m2\repository\org\seleniumhq\selenium\selenium-devtools-v110\4.9.0\selenium-devtools-v110-4.9.0.jar;C:\Users\r001-rachev\.m2\repository\org\seleniumhq\selenium\selenium-devtools-v111\4.9.0\selenium-devtools-v111-4.9.0.jar;C:\Users\r001-rachev\.m2\repository\org\seleniumhq\selenium\selenium-devtools-v112\4.9.0\selenium-devtools-v112-4.9.0.jar;C:\Users\r001-rachev\.m2\repository\org\seleniumhq\selenium\selenium-devtools-v85\4.9.0\selenium-devtools-v85-4.9.0.jar;C:\Users\r001-rachev\.m2\repository\org\seleniumhq\selenium\selenium-edge-driver\4.9.0\selenium-edge-driver-4.9.0.jar;C:\Users\r001-rachev\.m2\repository\org\seleniumhq\selenium\selenium-firefox-driver\4.9.0\selenium-firefox-driver-4.9.0.jar;C:\Users\r001-rachev\.m2\repository\org\seleniumhq\selenium\selenium-http\4.9.0\selenium-http-4.9.0.jar;C:\Users\r001-rachev\.m2\repository\dev\failsafe\failsafe\3.3.1\failsafe-3.3.1.jar;C:\Users\r001-rachev\.m2\repository\org\seleniumhq\selenium\selenium-ie-driver\4.9.0\selenium-ie-driver-4.9.0.jar;C:\Users\r001-rachev\.m2\repository\org\seleniumhq\selenium\selenium-remote-driver\4.9.0\selenium-remote-driver-4.9.0.jar;C:\Users\r001-rachev\.m2\repository\com\beust\jcommander\1.82\jcommander-1.82.jar;C:\Users\r001-rachev\.m2\repository\io\netty\netty-buffer\4.1.91.Final\netty-buffer-4.1.91.Final.jar;C:\Users\r001-rachev\.m2\repository\io\netty\netty-codec-http\4.1.91.Final\netty-codec-http-4.1.91.Final.jar;C:\Users\r001-rachev\.m2\repository\io\netty\netty-codec\4.1.91.Final\netty-codec-4.1.91.Final.jar;C:\Users\r001-rachev\.m2\repository\io\netty\netty-handler\4.1.91.Final\netty-handler-4.1.91.Final.jar;C:\Users\r001-rachev\.m2\repository\io\netty\netty-common\4.1.91.Final\netty-common-4.1.91.Final.jar;C:\Users\r001-rachev\.m2\repository\io\netty\netty-transport-classes-epoll\4.1.91.Final\netty-transport-classes-epoll-4.1.91.Final.jar;C:\Users\r001-rachev\.m2\repository\io\netty\netty-transport-classes-kqueue\4.1.91.Final\netty-transport-classes-kqueue-4.1.91.Final.jar;C:\Users\r001-rachev\.m2\repository\io\netty\netty-transport-native-epoll\4.1.91.Final\netty-transport-native-epoll-4.1.91.Final.jar;C:\Users\r001-rachev\.m2\repository\io\netty\netty-transport-native-kqueue\4.1.91.Final\netty-transport-native-kqueue-4.1.91.Final.jar;C:\Users\r001-rachev\.m2\repository\io\netty\netty-transport-native-unix-common\4.1.91.Final\netty-transport-native-unix-common-4.1.91.Final.jar;C:\Users\r001-rachev\.m2\repository\io\netty\netty-transport\4.1.91.Final\netty-transport-4.1.91.Final.jar;C:\Users\r001-rachev\.m2\repository\io\netty\netty-resolver\4.1.91.Final\netty-resolver-4.1.91.Final.jar;C:\Users\r001-rachev\.m2\repository\io\opentelemetry\opentelemetry-api\1.25.0\opentelemetry-api-1.25.0.jar;C:\Users\r001-rachev\.m2\repository\io\opentelemetry\opentelemetry-context\1.25.0\opentelemetry-context-1.25.0.jar;C:\Users\r001-rachev\.m2\repository\io\opentelemetry\opentelemetry-exporter-logging\1.25.0\opentelemetry-exporter-logging-1.25.0.jar;C:\Users\r001-rachev\.m2\repository\io\opentelemetry\opentelemetry-sdk-metrics\1.25.0\opentelemetry-sdk-metrics-1.25.0.jar;C:\Users\r001-rachev\.m2\repository\io\opentelemetry\opentelemetry-sdk-logs\1.25.0-alpha\opentelemetry-sdk-logs-1.25.0-alpha.jar;C:\Users\r001-rachev\.m2\repository\io\opentelemetry\opentelemetry-api-logs\1.25.0-alpha\opentelemetry-api-logs-1.25.0-alpha.jar;C:\Users\r001-rachev\.m2\repository\io\opentelemetry\opentelemetry-api-events\1.25.0-alpha\opentelemetry-api-events-1.25.0-alpha.jar;C:\Users\r001-rachev\.m2\repository\io\opentelemetry\opentelemetry-sdk-common\1.25.0\opentelemetry-sdk-common-1.25.0.jar;C:\Users\r001-rachev\.m2\repository\io\opentelemetry\opentelemetry-sdk-extension-autoconfigure-spi\1.25.0\opentelemetry-sdk-extension-autoconfigure-spi-1.25.0.jar;C:\Users\r001-rachev\.m2\repository\io\opentelemetry\opentelemetry-sdk-extension-autoconfigure\1.25.0-alpha\opentelemetry-sdk-extension-autoconfigure-1.25.0-alpha.jar;C:\Users\r001-rachev\.m2\repository\io\opentelemetry\opentelemetry-sdk-trace\1.25.0\opentelemetry-sdk-trace-1.25.0.jar;C:\Users\r001-rachev\.m2\repository\io\opentelemetry\opentelemetry-sdk\1.25.0\opentelemetry-sdk-1.25.0.jar;C:\Users\r001-rachev\.m2\repository\io\opentelemetry\opentelemetry-semconv\1.25.0-alpha\opentelemetry-semconv-1.25.0-alpha.jar;C:\Users\r001-rachev\.m2\repository\io\ous\jtoml\2.0.0\jtoml-2.0.0.jar;C:\Users\r001-rachev\.m2\repository\net\bytebuddy\byte-buddy\1.14.4\byte-buddy-1.14.4.jar;C:\Users\r001-rachev\.m2\repository\org\apache\commons\commons-exec\1.3\commons-exec-1.3.jar;C:\Users\r001-rachev\.m2\repository\org\asynchttpclient\async-http-client\2.12.3\async-http-client-2.12.3.jar;C:\Users\r001-rachev\.m2\repository\org\asynchttpclient\async-http-client-netty-utils\2.12.3\async-http-client-netty-utils-2.12.3.jar;C:\Users\r001-rachev\.m2\repository\io\netty\netty-codec-socks\4.1.60.Final\netty-codec-socks-4.1.60.Final.jar;C:\Users\r001-rachev\.m2\repository\io\netty\netty-handler-proxy\4.1.60.Final\netty-handler-proxy-4.1.60.Final.jar;C:\Users\r001-rachev\.m2\repository\io\netty\netty-transport-native-epoll\4.1.60.Final\netty-transport-native-epoll-4.1.60.Final-linux-x86_64.jar;C:\Users\r001-rachev\.m2\repository\io\netty\netty-transport-native-kqueue\4.1.60.Final\netty-transport-native-kqueue-4.1.60.Final-osx-x86_64.jar;C:\Users\r001-rachev\.m2\repository\org\reactivestreams\reactive-streams\1.0.3\reactive-streams-1.0.3.jar;C:\Users\r001-rachev\.m2\repository\com\typesafe\netty\netty-reactive-streams\2.0.4\netty-reactive-streams-2.0.4.jar;C:\Users\r001-rachev\.m2\repository\com\sun\activation\jakarta.activation\1.2.2\jakarta.activation-1.2.2.jar;C:\Users\r001-rachev\.m2\repository\org\seleniumhq\selenium\selenium-safari-driver\4.9.0\selenium-safari-driver-4.9.0.jar;C:\Users\r001-rachev\.m2\repository\org\seleniumhq\selenium\selenium-support\4.9.0\selenium-support-4.9.0.jar;C:\Users\r001-rachev\.m2\repository\io\github\bonigarcia\webdrivermanager\5.6.2\webdrivermanager-5.6.2.jar;C:\Users\r001-rachev\.m2\repository\com\google\code\gson\gson\2.10.1\gson-2.10.1.jar;C:\Users\r001-rachev\.m2\repository\com\github\docker-java\docker-java\3.3.4\docker-java-3.3.4.jar;C:\Users\r001-rachev\.m2\repository\com\github\docker-java\docker-java-core\3.3.4\docker-java-core-3.3.4.jar;C:\Users\r001-rachev\.m2\repository\com\github\docker-java\docker-java-api\3.3.4\docker-java-api-3.3.4.jar;C:\Users\r001-rachev\.m2\repository\com\fasterxml\jackson\core\jackson-annotations\2.10.3\jackson-annotations-2.10.3.jar;C:\Users\r001-rachev\.m2\repository\commons-io\commons-io\2.13.0\commons-io-2.13.0.jar;C:\Users\r001-rachev\.m2\repository\com\fasterxml\jackson\core\jackson-databind\2.10.3\jackson-databind-2.10.3.jar;C:\Users\r001-rachev\.m2\repository\com\fasterxml\jackson\core\jackson-core\2.10.3\jackson-core-2.10.3.jar;C:\Users\r001-rachev\.m2\repository\org\bouncycastle\bcpkix-jdk18on\1.76\bcpkix-jdk18on-1.76.jar;C:\Users\r001-rachev\.m2\repository\org\bouncycastle\bcprov-jdk18on\1.76\bcprov-jdk18on-1.76.jar;C:\Users\r001-rachev\.m2\repository\org\bouncycastle\bcutil-jdk18on\1.76\bcutil-jdk18on-1.76.jar;C:\Users\r001-rachev\.m2\repository\org\slf4j\jcl-over-slf4j\1.7.30\jcl-over-slf4j-1.7.30.jar;C:\Users\r001-rachev\.m2\repository\com\github\docker-java\docker-java-transport-httpclient5\3.3.4\docker-java-transport-httpclient5-3.3.4.jar;C:\Users\r001-rachev\.m2\repository\com\github\docker-java\docker-java-transport\3.3.4\docker-java-transport-3.3.4.jar;C:\Users\r001-rachev\.m2\repository\net\java\dev\jna\jna\5.13.0\jna-5.13.0.jar;C:\Users\r001-rachev\.m2\repository\org\brotli\dec\0.1.2\dec-0.1.2.jar;C:\Users\r001-rachev\.m2\repository\org\apache\commons\commons-lang3\3.13.0\commons-lang3-3.13.0.jar;C:\Users\r001-rachev\.m2\repository\org\apache\commons\commons-compress\1.24.0\commons-compress-1.24.0.jar;C:\Users\r001-rachev\.m2\repository\org\apache\httpcomponents\client5\httpclient5\5.2.1\httpclient5-5.2.1.jar;C:\Users\r001-rachev\.m2\repository\org\apache\httpcomponents\core5\httpcore5\5.2\httpcore5-5.2.jar;C:\Users\r001-rachev\.m2\repository\org\apache\httpcomponents\core5\httpcore5-h2\5.2\httpcore5-h2-5.2.jar;C:\Users\r001-rachev\.m2\repository\ch\qos\logback\logback-classic\1.2.6\logback-classic-1.2.6.jar;C:\Users\r001-rachev\.m2\repository\ch\qos\logback\logback-core\1.2.6\logback-core-1.2.6.jar;C:\Users\r001-rachev\.m2\repository\org\projectlombok\lombok\1.18.30\lombok-1.18.30.jar;C:\Users\r001-rachev\.m2\repository\org\slf4j\slf4j-api\1.7.32\slf4j-api-1.7.32.jar org.example.Main
2023-12-23 15:21:37 [main] DEBUG i.g.bonigarcia.wdm.WebDriverManager.<init>(227) - Using WebDriverManager 5.6.2
2023-12-23 15:21:38 [main] DEBUG i.g.bonigarcia.wdm.WebDriverManager.resolveDriverVersion(1254) - The driver version for IEXPLORER is unknown ... trying with latest
2023-12-23 15:21:38 [main] INFO  i.g.bonigarcia.wdm.WebDriverManager.logSeekRepo(1592) - Reading https://raw.githubusercontent.com/bonigarcia/webdrivermanager/master/docs/mirror/selenium to seek IEDriverServer
2023-12-23 15:21:38 [main] WARN  i.g.bonigarcia.wdm.WebDriverManager.fallback(1445) - There was an error managing IEDriverServer (latest version) (java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 1 column 1 path $) ... trying again using latest driver stored in cache
2023-12-23 15:21:38 [main] DEBUG i.g.bonigarcia.wdm.WebDriverManager.resolveDriverVersion(1254) - The driver version for IEXPLORER is unknown ... trying with latest
2023-12-23 15:21:39 [main] INFO  i.g.bonigarcia.wdm.WebDriverManager.logSeekRepo(1592) - Reading https://raw.githubusercontent.com/bonigarcia/webdrivermanager/master/docs/mirror/selenium to seek IEDriverServer
2023-12-23 15:21:39 [main] ERROR i.g.bonigarcia.wdm.WebDriverManager.handleException(1434) - There was an error managing IEDriverServer (latest version) (java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 1 column 1 path $)
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 1 column 1 path $
	at com.google.gson.Gson.fromJson(Gson.java:1238)
	at com.google.gson.Gson.fromJson(Gson.java:1137)
	at com.google.gson.Gson.fromJson(Gson.java:1075)
	at io.github.bonigarcia.wdm.WebDriverManager.getDriversFromGitHub(WebDriverManager.java:1634)
	at io.github.bonigarcia.wdm.managers.InternetExplorerDriverManager.getDriverUrls(InternetExplorerDriverManager.java:98)
	at io.github.bonigarcia.wdm.WebDriverManager.createUrlHandler(WebDriverManager.java:1456)
	at io.github.bonigarcia.wdm.WebDriverManager.download(WebDriverManager.java:1277)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:1189)
	at io.github.bonigarcia.wdm.WebDriverManager.fallback(WebDriverManager.java:1451)
	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:1428)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:1195)
	at io.github.bonigarcia.wdm.WebDriverManager.setup(WebDriverManager.java:427)
	at io.github.bonigarcia.wdm.WebDriverManager.create(WebDriverManager.java:432)
	at org.example.Main.main(Main.java:20)
Caused by: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 1 column 1 path $
	at com.google.gson.stream.JsonReader.beginArray(JsonReader.java:358)
	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:70)
	at com.google.gson.Gson.fromJson(Gson.java:1227)
	... 13 common frames omitted
Exception in thread "main" io.github.bonigarcia.wdm.config.WebDriverManagerException: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 1 column 1 path $
	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:1435)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:1195)
	at io.github.bonigarcia.wdm.WebDriverManager.fallback(WebDriverManager.java:1451)
	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:1428)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:1195)
	at io.github.bonigarcia.wdm.WebDriverManager.setup(WebDriverManager.java:427)
	at io.github.bonigarcia.wdm.WebDriverManager.create(WebDriverManager.java:432)
	at org.example.Main.main(Main.java:20)
Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 1 column 1 path $
	at com.google.gson.Gson.fromJson(Gson.java:1238)
	at com.google.gson.Gson.fromJson(Gson.java:1137)
	at com.google.gson.Gson.fromJson(Gson.java:1075)
	at io.github.bonigarcia.wdm.WebDriverManager.getDriversFromGitHub(WebDriverManager.java:1634)
	at io.github.bonigarcia.wdm.managers.InternetExplorerDriverManager.getDriverUrls(InternetExplorerDriverManager.java:98)
	at io.github.bonigarcia.wdm.WebDriverManager.createUrlHandler(WebDriverManager.java:1456)
	at io.github.bonigarcia.wdm.WebDriverManager.download(WebDriverManager.java:1277)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:1189)
	... 6 more
Caused by: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 1 column 1 path $
	at com.google.gson.stream.JsonReader.beginArray(JsonReader.java:358)
	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:70)
	at com.google.gson.Gson.fromJson(Gson.java:1227)
	... 13 more

Process finished with exit code 1
```

My conclusions is that the proxy is messing up that things some how, but it is strange since the chrome driver works just fine on the same machine using the same proxy.

```
2023-12-24 06:43:02 [main] DEBUG i.g.bonigarcia.wdm.WebDriverManager.<init>(227) - Using WebDriverManager 5.6.2
2023-12-24 06:43:03 [main] WARN  o.a.h.c.h.i.auth.HttpAuthenticator.addAuthResponse(341) - ex-0000000001 Negotiate{FAILED } authentication error: No valid credentials provided (Mechanism level: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt))
2023-12-24 06:43:03 [main] DEBUG i.g.b.wdm.versions.VersionDetector.getBrowserVersionFromTheShell(262) - Detecting chrome version using online commands.properties
2023-12-24 06:43:03 [main] DEBUG i.g.b.wdm.versions.VersionDetector.getBrowserVersionFromTheShell(270) - Browser version for chrome not detected using online properties (using local commands.properties)
2023-12-24 06:43:03 [main] DEBUG i.g.bonigarcia.wdm.WebDriverManager.resolveDriverVersion(1254) - The driver version for CHROME is unknown ... trying with latest
2023-12-24 06:43:04 [main] DEBUG i.g.bonigarcia.wdm.WebDriverManager.buildUrl(184) - Using URL built from repository pattern: https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/120.0.6099.109/win32/chromedriver-win32.zip
2023-12-24 06:43:04 [main] DEBUG i.g.bonigarcia.wdm.WebDriverManager.createUrlHandler(1479) - Driver to be downloaded chromedriver 120.0.6099.109
2023-12-24 06:43:04 [main] INFO  i.g.bonigarcia.wdm.online.Downloader.downloadAndExtract(132) - Downloading https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/120.0.6099.109/win32/chromedriver-win32.zip
2023-12-24 06:43:04 [main] INFO  i.g.bonigarcia.wdm.online.Downloader.extract(193) - Extracting driver from compressed file chromedriver-win32.zip
2023-12-24 06:43:04 [main] INFO  i.g.bonigarcia.wdm.WebDriverManager.exportDriver(1291) - Exporting webdriver.chrome.driver as C:\Users\r001-rachev\.cache\selenium\chromedriver\win32\120.0.6099.109\chromedriver.exe
Starting ChromeDriver 120.0.6099.109 (3419140ab665596f21b385ce136419fde0924272-refs/branch-heads/6099@{#1483}) on port 37580
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
```

**Comment by bonigarcia** [comment]
Indeed, this issue seems related to the proxy itself but not WebDriverManager.
