### ISSUE TITLE
Error while trying to use ChromeDriver with a proxy

### ISSUE THREAD

**Issue by sidshenoy08** [bonigarcia/webdrivermanager#1194]
**Description of the problem**: I have been using webdrivermanager for my application for quite some time and have faced no issues. Now, I am trying to use the ChromeDriver with a proxy and I am observing a couple of issues. I have tried the documented ways of setting up ChromeDriver with a proxy but no luck. This is the first time I am trying to use the webdrivermanager with a proxy so I would like to know if I am doing something wrong or if it is a genuine issue. The proxy password is a combination of uppercase and lowercase characters, numbers, and special characters. Are there any restrictions on special characters?

**Browser and version**: Chrome 120

**Operating system and architecture**: Windows Server 2016 (64-bit)

**Selenium version**: 4.15.0

**WebDriverManager version**: 5.6.3

**WebDriverManager call**: 
Case 1: WebDriverManager.chromedriver().proxyUser("username").proxyPass("password").proxy("proxy:port").setup();

Case 2: WebDriverManager.chromedriver().proxy("username:password@proxy:port").setup();

**Error log**: 
Case 1: (Squid Error Page)
org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Unable to parse remote response: <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html><head>
<meta type="copyright" content="Copyright (C) 1996-2019 The Squid Software Foundation and contributors">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>ERROR: Cache Access Denied</title>
</head><body id=ERR_CACHE_ACCESS_DENIED>
<div id="titles">
<h1>ERROR</h1>
<h2>Cache Access Denied.</h2>
</div>
<hr>

<div id="content">
<p>The following error was encountered while trying to retrieve the URL: <a href="http://localhost:8877/session">http://localhost:8877/session</a></p>

<blockquote id="error">
<p><b>Cache Access Denied.</b></p>
</blockquote>

<p>Sorry, you are not currently allowed to request http://localhost:8877/session from this cache until you have authenticated yourself.</p>

<p>Please contact the <a href="mailto:webmaster?subject=CacheErrorInfo%20-%20ERR_CACHE_ACCESS_DENIED&amp;body=CacheHost%3A%20vl-pun-ubu-vm04%0D%0AErrPage%3A%20ERR_CACHE_ACCESS_DENIED%0D%0AErr%3A%20%5Bnone%5D%0D%0ATimeStamp%3A%20Fri,%2005%20Jan%202024%2004%3A41%3A41%20GMT%0D%0A%0D%0AClientIP%3A%2010.133.187.248%0D%0A%0D%0AHTTP%20Request%3A%0D%0APOST%20%2Fsession%20HTTP%2F1.1%0AContent-Length%3A%20417%0D%0AContent-Type%3A%20application%2Fjson%3B%20charset%3Dutf-8%0D%0AUser-Agent%3A%20selenium%2F4.15.0%20(java%20windows)%0D%0AHost%3A%20localhost%3A8877%0D%0A%0D%0A%0D%0A">cache administrator</a> if you have difficulties authenticating yourself.</p>

<br>
</div>

<hr> 
<div id="footer">
<p>Generated Fri, 05 Jan 2024 04:41:41 GMT by (squid/4.10)</p>

</div>
</body></html>
 
Host info: host: '', ip: ''
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:126) ~[selenium-remote-driver-4.15.0.jar:?]
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:96) ~[selenium-remote-driver-4.15.0.jar:?]
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:68) ~[selenium-remote-driver-4.15.0.jar:?]
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:163) ~[selenium-remote-driver-4.15.0.jar:?]
	at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:200) ~[selenium-remote-driver-4.15.0.jar:?]
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:175) ~[selenium-remote-driver-4.15.0.jar:?]
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:607) ~[selenium-remote-driver-4.15.0.jar:?]
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:241) ~[selenium-remote-driver-4.15.0.jar:?]
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:168) ~[selenium-remote-driver-4.15.0.jar:?]
	at org.openqa.selenium.chromium.ChromiumDriver.<init>(ChromiumDriver.java:108) ~[selenium-chromium-driver-4.15.0.jar:?]
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:89) ~[selenium-chrome-driver-4.15.0.jar:?]
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:84) ~[selenium-chrome-driver-4.15.0.jar:?]
Caused by: org.openqa.selenium.json.JsonException: Unable to parse: <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html><head>
<meta type="copyright" content="Copyright (C) 1996-2019 The Squid Software Foundation and contributors">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>ERROR: Cache Access Denied</title>
<style type="text/css">
</div>
</body></html>

	at org.openqa.selenium.json.Json.toType(Json.java:169) ~[selenium-json-4.15.0.jar:?]
	at org.openqa.selenium.json.Json.toType(Json.java:152) ~[selenium-json-4.15.0.jar:?]
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:122) ~[selenium-remote-driver-4.15.0.jar:?]
	... 17 more
Caused by: org.openqa.selenium.json.JsonException: Unable to determine type from: <. Last 1 characters read: <
Build info: version: '4.15.0', revision: '1d14b5521b'
System info: os.name: 'Windows Server 2016', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.2'
Driver info: driver.version: SRDriver
	at org.openqa.selenium.json.JsonInput.peek(JsonInput.java:166) ~[selenium-json-4.15.0.jar:?]
	at org.openqa.selenium.json.JsonTypeCoercer.lambda$buildCoercer$6(JsonTypeCoercer.java:167) ~[selenium-json-4.15.0.jar:?]
	at org.openqa.selenium.json.JsonTypeCoercer.coerce(JsonTypeCoercer.java:146) ~[selenium-json-4.15.0.jar:?]
	at org.openqa.selenium.json.Json.toType(Json.java:206) ~[selenium-json-4.15.0.jar:?]
	at org.openqa.selenium.json.Json.toType(Json.java:167) ~[selenium-json-4.15.0.jar:?]
	at org.openqa.selenium.json.Json.toType(Json.java:152) ~[selenium-json-4.15.0.jar:?]
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:122) ~[selenium-remote-driver-4.15.0.jar:?]
	... 17 more

Case 2: io.github.bonigarcia.wdm.config.WebDriverManagerException: java.net.MalformedURLException: Error at index 0 in: Password
	at io.github.bonigarcia.wdm.online.HttpClient.<init>(HttpClient.java:138) ~[webdrivermanager-5.6.3.jar:?]
	at io.github.bonigarcia.wdm.WebDriverManager.setup(WebDriverManager.java:413) ~[webdrivermanager-5.6.3.jar:?]
Caused by: java.net.MalformedURLException: Error at index 0 in: "<Password>"
	at java.net.URL.<init>(URL.java:708) ~[?:?]
	at java.net.URL.<init>(URL.java:569) ~[?:?]
	at java.net.URL.<init>(URL.java:516) ~[?:?]
	at io.github.bonigarcia.wdm.online.HttpClient.determineProxyUrl(HttpClient.java:217) ~[webdrivermanager-5.6.3.jar:?]
	at io.github.bonigarcia.wdm.online.HttpClient.createProxy(HttpClient.java:196) ~[webdrivermanager-5.6.3.jar:?]
	at io.github.bonigarcia.wdm.online.HttpClient.createProxyHttpHost(HttpClient.java:224) ~[webdrivermanager-5.6.3.jar:?]
	at io.github.bonigarcia.wdm.online.HttpClient.setupProxyIfRequired(HttpClient.java:180) ~[webdrivermanager-5.6.3.jar:?]
	at io.github.bonigarcia.wdm.online.HttpClient.<init>(HttpClient.java:96) ~[webdrivermanager-5.6.3.jar:?]
	... 7 more
Caused by: java.lang.NumberFormatException: Error at index 0 in: Password
	at java.lang.NumberFormatException.forCharSequence(NumberFormatException.java:83) ~[?:?]
	at java.lang.Integer.parseInt(Integer.java:751) ~[?:?]
	at java.net.URLStreamHandler.parseURL(URLStreamHandler.java:237) ~[?:?]
	at java.net.URL.<init>(URL.java:703) ~[?:?]
	at java.net.URL.<init>(URL.java:569) ~[?:?]
	at java.net.URL.<init>(URL.java:516) ~[?:?]
	at io.github.bonigarcia.wdm.online.HttpClient.determineProxyUrl(HttpClient.java:217) ~[webdrivermanager-5.6.3.jar:?]
	at io.github.bonigarcia.wdm.online.HttpClient.createProxy(HttpClient.java:196) ~[webdrivermanager-5.6.3.jar:?]
	at io.github.bonigarcia.wdm.online.HttpClient.createProxyHttpHost(HttpClient.java:224) ~[webdrivermanager-5.6.3.jar:?]
	at io.github.bonigarcia.wdm.online.HttpClient.setupProxyIfRequired(HttpClient.java:180) ~[webdrivermanager-5.6.3.jar:?]
	at io.github.bonigarcia.wdm.online.HttpClient.<init>(HttpClient.java:96) ~[webdrivermanager-5.6.3.jar:?]
	... 7 more
```
```

**Comment by bonigarcia** [comment]
Case 1 is ok for WebDriverManager. But you get an error in Selenium, not in WebDriverManager. I believe you need to setup your proxy also in Selenium. See:

https://www.selenium.dev/documentation/webdriver/drivers/options/#proxy
