### ISSUE TITLE
Not used a cached driver when network disconnected on 1.6.2-SNAPSHOT

### ISSUE THREAD

**Issue by kazuki43zoo** [bonigarcia/webdrivermanager#121]
I've installed the 1.6.2-SNAPSHOT into local repository and tried following operations:

* Install the 1.6.2-SNAPSHOT into local repository

```
$ git clone https://github.com/bonigarcia/webdrivermanager.git
$ cd webdrivermanager
$ mvn install -DskipTests=true
```

* Remove cache directory

```
$ rm -rf $HOME/.m2/repository/webdriver
$ tree $HOME/.m2/repository/webdriver
/Users/xxx/.m2/repository/webdriver [error opening dir]

0 directories, 0 files
```

* Perform tests on network connected

A webdriver execution file has been cached into local repository !!

```
...
22:02:46.233 [main] INFO io.github.bonigarcia.wdm.BrowserManager - Reading https://api.github.com/repos/mozilla/geckodriver/releases to seek [wires, geckodriver]
22:02:47.626 [main] DEBUG io.github.bonigarcia.wdm.BrowserManager - Using [wires, geckodriver] 0.14.0
22:02:48.067 [main] INFO io.github.bonigarcia.wdm.Downloader - Downloading https://github.com/mozilla/geckodriver/releases/download/v0.14.0/geckodriver-v0.14.0-macos.tar.gz to /Users/xxx/.m2/repository/webdriver/geckodriver/macos/0.14.0/geckodriver-v0.14.0-macos.tar.gz
22:02:49.999 [main] DEBUG io.github.bonigarcia.wdm.Downloader - Response HTTP 200
22:02:51.845 [main] INFO io.github.bonigarcia.wdm.BrowserManager - Exporting webdriver.gecko.driver as /Users/xxx/.m2/repository/webdriver/geckodriver/macos/0.14.0/geckodriver
...
```

```
$ tree $HOME/.m2/repository/webdriver
/Users/xxx/.m2/repository/webdriver
└── geckodriver
    └── macos
        └── 0.14.0
            └── geckodriver
```

* Disconnect my network and perform tests again.

The following exception is occurred because an webdriver execution file does not found ...

```
...
22:35:26.815 [main] WARN io.github.bonigarcia.wdm.BrowserManager - Network not available. Forcing the use of cache
...
java.lang.RuntimeException: java.io.FileNotFoundException: geckodriver (No such file or directory)

	at io.github.bonigarcia.wdm.BrowserManager.manage(BrowserManager.java:251)
	at io.github.bonigarcia.wdm.BrowserManager.setup(BrowserManager.java:765)
	at io.github.bonigarcia.wdm.BrowserManager.setup(BrowserManager.java:725)
	at com.kazuki43zoo.jpetstore.JpetstoreApplicationTests.setupWebDriverManager(JpetstoreApplicationTests.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:191)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:237)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: java.io.FileNotFoundException: geckodriver (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at io.github.bonigarcia.wdm.BrowserManager.isExecutable(BrowserManager.java:337)
	at io.github.bonigarcia.wdm.BrowserManager.forceCache(BrowserManager.java:270)
	at io.github.bonigarcia.wdm.BrowserManager.manage(BrowserManager.java:167)
	... 25 more
```

I've checked a local repository again and run execution file by manually. It work file.

```
$ tree $HOME/.m2/repository/webdriver
/Users/xxx/.m2/repository/webdriver
└── geckodriver
    └── macos
        └── 0.14.0
            └── geckodriver
$ $HOME/.m2/repository/webdriver/geckodriver/macos/0.14.0/geckodriver 
1491052616942	geckodriver	INFO	Listening on 127.0.0.1:4444
```

## Expected result

I will expected that it is used a cached webdriver execution file when network disconnected. As actually, 1.6.1 is work fine !!

```
...
22:24:56.483 [main] WARN io.github.bonigarcia.wdm.BrowserManager - Network not available. Forcing the use of cache
22:24:56.505 [main] INFO io.github.bonigarcia.wdm.BrowserManager - Found geckodriver in cache: /Users/xxx/.m2/repository/webdriver/geckodriver/macos/0.14.0/geckodriver 
22:24:56.506 [main] DEBUG io.github.bonigarcia.wdm.BrowserManager - Driver for [wires, geckodriver] 0.14.0 found in cache /Users/xxx/.m2/repository/webdriver/geckodriver/macos/0.14.0/geckodriver
22:24:56.507 [main] INFO io.github.bonigarcia.wdm.BrowserManager - Exporting webdriver.gecko.driver as /Users/xxx/.m2/repository/webdriver/geckodriver/macos/0.14.0/geckodriver
...
```

## Environment

* Mac 10.10.5

## Related Issues

* #109

**Comment by kazuki43zoo** [comment]
It has been broken by a3b461e0782f40762b35d69ea13e9b3012c80a55. I've tried using 6c3f5370d2c0f21a2ade00a15ab3b25473797f6d (previous commit), it work file.

```
$ git checkout 6c3f5370d2c0f21a2ade00a15ab3b25473797f6d
$ mvn install -DskipTests=true
```

**Comment by bonigarcia** [comment]
It should be fixed now.

**Comment by kazuki43zoo** [comment]
@bonigarcia Thanks for your working ! However I think it is not completed. I've submitted an another [PR](https://github.com/bonigarcia/webdrivermanager/pull/122) related with this.
