### ISSUE TITLE
I am unable to open browser.

### ISSUE THREAD

**Issue by jayastory** [bonigarcia/webdrivermanager#1232]
Exception in thread "main" io.github.bonigarcia.wdm.config.WebDriverManagerException: java.lang.NumberFormatException: For input string: "public"
	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:1445)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:1205)
	at io.github.bonigarcia.wdm.WebDriverManager.fallback(WebDriverManager.java:1461)
	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:1442)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:1205)
	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:1435)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:1205)
	at io.github.bonigarcia.wdm.WebDriverManager.setup(WebDriverManager.java:427)
	at JayaBhartipractice.Selenium.CompleteTest.main(CompleteTest.java:12)
Caused by: java.lang.NumberFormatException: For input string: "public"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
	at java.base/java.lang.Integer.parseInt(Integer.java:668)
	at java.base/java.lang.Integer.parseInt(Integer.java:786)
	at io.github.bonigarcia.wdm.managers.ChromeDriverManager.buildUrl(ChromeDriverManager.java:178)
	at io.github.bonigarcia.wdm.managers.ChromeDriverManager.buildUrl(ChromeDriverManager.java:155)
	at io.github.bonigarcia.wdm.WebDriverManager.download(WebDriverManager.java:1282)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:1199)
	... 7 more

**Comment by bonigarcia** [comment]
See #1226.

**Comment by jayastory** [comment]
Can you tell how to fix this?
