### ISSUE TITLE
Getting NumberFormatException: For input string: "public"  error while running webdrivermanager in Azure pipeline

### ISSUE THREAD

**Issue by jaydjana** [bonigarcia/webdrivermanager#1237]
I am running my selenium code with WebDriverManager latest version in Azure pipeline where execution is failing with below error 

2024-02-22T16:05:48.0356432Z       **io.github.bonigarcia.wdm.config.WebDriverManagerException: java.lang.NumberFormatException: For input string: "public"**
2024-02-22T16:05:48.0357793Z 	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:1414)
2024-02-22T16:05:48.0359589Z 	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:1189)
2024-02-22T16:05:48.0360563Z 	at io.github.bonigarcia.wdm.WebDriverManager.fallback(WebDriverManager.java:1430)
2024-02-22T16:05:48.0361831Z 	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:1408)
2024-02-22T16:05:48.0363062Z 	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:1189)
2024-02-22T16:05:48.0365803Z 	at io.github.bonigarcia.wdm.WebDriverManager.setup(WebDriverManager.java:426)

I am using  below version 

webdrivermanager  : 5.7.0
Selenium: 4.14.1

**Comment by bonigarcia** [comment]
Clean your cache. See #1226 and [doc](https://bonigarcia.dev/webdrivermanager/#support-for-chromedriver-115).

**Comment by jaydjana** [comment]
Working fine now after clearing cache one time using below command. CLosing the issue

WebDriverManager.chromedriver().clearDriverCache().setup();
