### ISSUE TITLE
mirror repository for chrome driver version later than 115 not work

### ISSUE THREAD

**Issue by yu-chun-kit** [bonigarcia/webdrivermanager#1264]
**Description of the problem**: 
mirror repository of chrome driver version after 115 is using [https://registry.npmmirror.com/-/binary/chrome-for-testing/](https://registry.npmmirror.com/-/binary/chrome-for-testing) instead of [https://registry.npmmirror.com/-/binary/chromedriver](https://registry.npmmirror.com/-/binary/chromedriver) to provide chromedriver, 

**Browser and version**: Chrome 122

**Operating system and architecture**: Windows 10 64 bits

**Selenium version**: 4.18.1

**WebDriverManager version**: 5.5.3

**WebDriverManager call**: 
```java
WebDriverManager
	.chromedriver()
	.useMirror() // <-- this line of code
	.setup();
```

**WebDriverManager traces**: 
```shell
2024-03-19 09:24:54.581  INFO 5260 --- [ool-13-thread-1] i.g.bonigarcia.wdm.WebDriverManager      : Using chromedriver 122.0.6261.128 (resolved driver for Chrome 122)
2024-03-19 09:24:55.015 ERROR 5260 --- [ool-13-thread-1] i.g.bonigarcia.wdm.online.HttpClient     : Error HTTP 404 executing https://registry.npmmirror.com/-/binary/chromedriver/122.0.6261.128/
2024-03-19 09:24:55.016  INFO 5260 --- [ool-13-thread-1] i.g.b.wdm.cache.ResolutionCache          : Clearing WebDriverManager resolution cache
2024-03-19 09:24:55.019  WARN 5260 --- [ool-13-thread-1] i.g.bonigarcia.wdm.WebDriverManager      : There was an error managing chromedriver 122.0.6261.128 (Error HTTP 404 executing https://registry.npmmirror.com/-/binary/chromedriver/122.0.6261.128/) ... trying again avoiding reading release from repository
2024-03-19 09:27:53.673  INFO 5260 --- [ool-13-thread-1] i.g.bonigarcia.wdm.online.Downloader     : Downloading https://registry.npmmirror.com/-/binary/chromedriver/114.0.5735.90/chromedriver_win32.zip
2024-03-19 09:27:58.018  INFO 5260 --- [ool-13-thread-1] i.g.bonigarcia.wdm.online.Downloader     : Extracting driver from compressed file chromedriver_win32.zip
2024-03-19 09:27:58.234  INFO 5260 --- [ool-13-thread-1] i.g.bonigarcia.wdm.WebDriverManager      : Exporting webdriver.chrome.driver as C:\Users\myusername\.cache\selenium\chromedriver\win32\114.0.5735.90\chromedriver.exe
org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: session not created: This version of ChromeDriver only supports Chrome version 114
Current browser version is 122.0.6261.129 with binary path C:\Program Files (x86)\Google\Chrome\Application\chrome.exe 
Host info: host: 'hostname', ip: '10.31.101.116'
Build info: version: '4.18.1', revision: 'b1d3319b48'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.6'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [null, newSession {capabilities=[Capabilities {browserName: chrome, goog:chromeOptions: {args: [], extensions: [], prefs: {download.default_directory: D:\Bulk Upload\Download}}, goog:loggingPrefs: org.openqa.selenium.logging..., pageLoadStrategy: eager, unhandledPromptBehavior: accept and notify}]}]
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:139)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:95)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:67)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:162)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:216)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:174)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:519)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:233)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:162)
	at org.openqa.selenium.chromium.ChromiumDriver.<init>(ChromiumDriver.java:114)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:89)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:84)
...
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Error log**: 
```shell
same as above
```

**Comment by bonigarcia** [comment]
Indeed, the WebDriverManager does not support chromedriver 115+ when using the NPM mirror. I have just committed a patch to support it. It will be available in the next release of WebDriverManager.

**Comment by bonigarcia** [comment]
WebDriverManager 5.8.0 is out.
