### ISSUE TITLE
Error running Firefox headless

### ISSUE THREAD

**Issue by javydreamercsw** [bonigarcia/webdrivermanager#1273]
**Description of the problem**: 
Error running Firefox on Linux.

**Browser and version**: 
Firefox 124

**Operating system and architecture**: 
Linux 64

**Selenium version**: 
3.141.59

**WebDriverManager version**: 
5.8.0

**WebDriverManager call**: 
```
WebDriverManager.firefoxdriver().clearDriverCache().setup();
        FirefoxOptions options = new FirefoxOptions();
        options.setHeadless(IS_HEADLESS);
```

**WebDriverManager traces**: 
```
[2024-04-10 15:50:19.716] [INFO] Using geckodriver 0.34.0 (resolved driver for Firefox 124)

[2024-04-10 15:50:19.759] [INFO] Reading https://raw.githubusercontent.com/bonigarcia/webdrivermanager/master/docs/mirror/geckodriver to seek geckodriver

[2024-04-10 15:50:19.835] [INFO] Downloading https://github.com/mozilla/geckodriver/releases/download/v0.34.0/geckodriver-v0.34.0-linux64.tar.gz

[2024-04-10 15:50:20.561] [INFO] Extracting driver from compressed file geckodriver-v0.34.0-linux64.tar.gz

```

**Error log**: 
```
Caused by: java.lang.NoSuchMethodError: 'org.apache.commons.compress.archivers.tar.TarArchiveEntry org.apache.commons.compress.archivers.tar.TarArchiveInputStream.getNextEntry()'

	at io.github.bonigarcia.wdm.online.Downloader.unTarGz(Downloader.java:280)

	at io.github.bonigarcia.wdm.online.Downloader.extract(Downloader.java:192)

	at io.github.bonigarcia.wdm.online.Downloader.downloadAndExtract(Downloader.java:139)

	at io.github.bonigarcia.wdm.online.Downloader.download(Downloader.java:91)

	at io.github.bonigarcia.wdm.WebDriverManager.download(WebDriverManager.java:1273)

	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:1184)

	at io.github.bonigarcia.wdm.WebDriverManager.setup(WebDriverManager.java:427)
```

**Comment by bonigarcia** [comment]
WebDriverManager 5.8.0 uses this dependency:

```
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-compress</artifactId>
            <version>1.26.1</version>
        </dependency>
```

Probably, you have an old version in your classpath which makes this error to happen. You should resolve it in your project setup (e.g., Maven, Gradle).

**Comment by javydreamercsw** [comment]
I was excluding that dependency for some reason and removing that made it work. It is weird that it worked fine locally. Thanks!
