### ISSUE TITLE
Facing issue when executing jar in jenkins pipeline

### ISSUE THREAD

**Issue by Parshwa1812** [bonigarcia/webdrivermanager#1277]
Hello Team,

I am using webdrivermanager 5.6.0 dependency in maven project and when we are executing the project jar in jenkins pipeline. At time of execution we are getting below exception. Kindly provide solution for this like which URLs/APIs should be whitelisted to resolve below exception.

Exception -
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.medline.framework.Test_Grid.runTestCase(Test_Grid.java:19)
	at com.medline.framework.DriverParallel_Grid.lambda$start$0(DriverParallel_Grid.java:78)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: io.github.bonigarcia.wdm.config.WebDriverManagerException: org.apache.hc.client5.http.HttpHostConnectException: Connect to [https://googlechromelabs.github.io:443](https://googlechromelabs.github.io/) [googlechromelabs.github.io/185.199.110.153, googlechromelabs.github.io/185.199.111.153, googlechromelabs.github.io/185.199.108.153, googlechromelabs.github.io/185.199.109.153] failed: Connection timed out: no further information

**Comment by bonigarcia** [comment]
Please follow the issue template to report any issue.

**Comment by bonigarcia** [comment]
Also, take a look to the [doc](https://bonigarcia.dev/webdrivermanager/#connectivity-issues) since this problem seems related with some connectivity problem at your end.

**Comment by partha069** [comment]
Please help me i'm getting this exception

io.github.bonigarcia.wdm.config.WebDriverManagerException: org.apache.hc.client5.http.HttpHostConnectException: Connect to https://googlechromelabs.github.io:443 [googlechromelabs.github.io/185.199.108.153, googlechromelabs.github.io/185.199.109.153, googlechromelabs.github.io/185.199.111.153, googlechromelabs.github.io/185.199.110.153] failed: Connection timed out: connect
	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:1421)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:1190)
	at io.github.bonigarcia.wdm.WebDriverManager.fallback(WebDriverManager.java:1437)
	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:1415)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:1190)
	at io.github.bonigarcia.wdm.WebDriverManager.setup(WebDriverManager.java:427)
	at com.driverfactory.manager.ChromeDriverManager.createDriver(ChromeDriverManager.java:37)
	at com.driverfactory.DriverFactory.getDriver(DriverFactory.java:29)
	at parallel.Hooks.launchBrowser(Hooks.java:30)
Caused by: org.apache.hc.client5.http.HttpHostConnectException: Connect to https://googlechromelabs.github.io:443 [googlechromelabs.github.io/185.199.108.153, googlechromelabs.github.io/185.199.109.153, googlechromelabs.github.io/185.199.111.153, googlechromelabs.github.io/185.199.110.153] failed: Connection timed out: connect
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:81)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:476)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:218)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:200)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:162)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:394)
	at java.net.Socket.connect(Socket.java:606)
	at org.apache.hc.client5.http.ssl.SSLConnectionSocketFactory.lambda$connectSocket$0(SSLConnectionSocketFactory.java:232)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.apache.hc.client5.http.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:231)
	at org.apache.hc.client5.http.impl.io.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:181)
	at org.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:447)
	at org.apache.hc.client5.http.impl.classic.InternalExecRuntime.connectEndpoint(InternalExecRuntime.java:162)
	at org.apache.hc.client5.http.impl.classic.InternalExecRuntime.connectEndpoint(InternalExecRuntime.java:172)
	at org.apache.hc.client5.http.impl.classic.ConnectExec.execute(ConnectExec.java:142)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.ProtocolExec.execute(ProtocolExec.java:192)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.HttpRequestRetryExec.execute(HttpRequestRetryExec.java:96)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.ContentCompressionExec.execute(ContentCompressionExec.java:152)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.RedirectExec.execute(RedirectExec.java:115)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.InternalHttpClient.doExecute(InternalHttpClient.java:170)
	at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:87)
	at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:55)
	at org.apache.hc.client5.http.classic.HttpClient.executeOpen(HttpClient.java:183)
	at io.github.bonigarcia.wdm.online.HttpClient.execute(HttpClient.java:157)
	at io.github.bonigarcia.wdm.online.Parser.parseJson(Parser.java:54)
	at io.github.bonigarcia.wdm.managers.ChromeDriverManager.getDriverUrls(ChromeDriverManager.java:117)
	at io.github.bonigarcia.wdm.WebDriverManager.createUrlHandler(WebDriverManager.java:1442)
	at io.github.bonigarcia.wdm.WebDriverManager.download(WebDriverManager.java:1268)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:1184)
	at io.github.bonigarcia.wdm.WebDriverManager.fallback(WebDriverManager.java:1437)
	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:1415)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:1190)
	at io.github.bonigarcia.wdm.WebDriverManager.setup(WebDriverManager.java:427)
	at com.driverfactory.manager.ChromeDriverManager.createDriver(ChromeDriverManager.java:37)
	at com.driverfactory.DriverFactory.getDriver(DriverFactory.java:29)
	at parallel.Hooks.launchBrowser(Hooks.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.cucumber.java.Invoker.doInvoke(Invoker.java:66)
	at io.cucumber.java.Invoker.invoke(Invoker.java:24)
	at io.cucumber.java.AbstractGlueDefinition.invokeMethod(AbstractGlueDefinition.java:47)
	at io.cucumber.java.JavaHookDefinition.execute(JavaHookDefinition.java:59)
	at io.cucumber.core.runner.CoreHookDefinition.execute(CoreHookDefinition.java:46)
	at io.cucumber.core.runner.HookDefinitionMatch.runStep(HookDefinitionMatch.java:21)
	at io.cucumber.core.runner.ExecutionMode$1.execute(ExecutionMode.java:10)
	at io.cucumber.core.runner.TestStep.executeStep(TestStep.java:92)
	at io.cucumber.core.runner.TestStep.run(TestStep.java:64)
	at io.cucumber.core.runner.TestCase.run(TestCase.java:98)
	at io.cucumber.core.runner.Runner.runPickle(Runner.java:71)
	at io.cucumber.junit.PickleRunners$NoStepDescriptions.run(PickleRunners.java:151)
	at io.cucumber.junit.FeatureRunner.runChild(FeatureRunner.java:135)
	at io.cucumber.junit.FeatureRunner.runChild(FeatureRunner.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at io.cucumber.junit.Cucumber.runChild(Cucumber.java:199)
	at io.cucumber.junit.Cucumber.runChild(Cucumber.java:90)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at io.cucumber.junit.Cucumber$RunCucumber.evaluate(Cucumber.java:234)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at org.testng.junit.JUnit4TestRunner.start(JUnit4TestRunner.java:80)
	at org.testng.junit.JUnit4TestRunner.run(JUnit4TestRunner.java:65)
	at org.testng.TestRunner$1.run(TestRunner.java:650)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.testng.TestRunner.runJUnitWorkers(TestRunner.java:841)
	at org.testng.TestRunner.privateRunJUnit(TestRunner.java:679)
	at org.testng.TestRunner.run(TestRunner.java:583)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.runSuites(TestNG.java:1069)
	at org.testng.TestNG.run(TestNG.java:1037)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:112)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:383)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:344)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:417)

**Comment by partha069** [comment]
Using webdrivermanager : 5.8.0 & selenium java: 4.11.0

**Comment by partha069** [comment]
@bonigarcia please help
