### ISSUE TITLE
Problems D/Ling IE/Firefox Drivers

### ISSUE THREAD

**Issue by Evleky** [bonigarcia/webdrivermanager#130]
I'm getting some issues with version 1.6.2 in that I cannot successfully pull down the IEDriverServer or the geckodriver. chromedriver seems to pull down fine. I also am not having problems if the drivers are cached as then there is no attempt to download them. The issue is strictly when it tries to pull down.

I think this issue is due to the WmdHttpClient stuff that was added for the proxy in ticket #118/#120. I reverted back to 1.6.1 and I have no issues pulling down the drivers.

From what I can tell from IE, the Content-Coding of 'None' shows an invalid response from the website or something to that effect. A Content-Coding that is unused should be 'identity'. Changing the Content-Coding to 'identity' at run-time (hotswapping in debug) gave me the ability to download successfully and continue using the driver just fine.

Am I missing something additional I need to be doing now? These are the calls and traces I'm making/getting.

InternetExplorerDriverManager.getInstance().arch32().version("3.3").setup();
FirefoxDriverManager.getInstance().setup();

----Trace from IE failure
Caused by: org.apache.http.client.ClientProtocolException
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:186)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at io.github.bonigarcia.wdm.WdmHttpClient.execute(WdmHttpClient.java:81)
	at io.github.bonigarcia.wdm.Downloader.download(Downloader.java:109)
	at io.github.bonigarcia.wdm.BrowserManager.manage(BrowserManager.java:255)
	... 11 more
Caused by: org.apache.http.HttpException: Unsupported Content-Coding: None
	at org.apache.http.client.protocol.ResponseContentEncoding.process(ResponseContentEncoding.java:130)
	at org.apache.http.protocol.ImmutableHttpProcessor.process(ImmutableHttpProcessor.java:141)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:189)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)

----Trace from Firefox/Gecko
2017-04-24 19:29:55,532 WARN  [protocol.ResponseProcessCookies:main] - <Invalid cookie header: "Set-Cookie: logged_in=no; domain=.github.com; path=/; expires=Sat, 25 Apr 2037 00:29:55 -0000; secure; HttpOnly". Invalid 'expires' attribute: Sat, 25 Apr 2037 00:29:55 -0000>

Caused by: javax.net.ssl.SSLPeerUnverifiedException: Host name 'github-cloud.s3.amazonaws.com' does not match the certificate subject provided by the peer (CN=*.s3.amazonaws.com, O=Amazon.com Inc., L=Seattle, ST=Washington, C=US)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.verifyHostname(SSLConnectionSocketFactory.java:465)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:395)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:353)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:134)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at io.github.bonigarcia.wdm.WdmHttpClient.execute(WdmHttpClient.java:81)
	at io.github.bonigarcia.wdm.Downloader.download(Downloader.java:109)
	at io.github.bonigarcia.wdm.BrowserManager.manage(BrowserManager.java:255)

**Comment by bonigarcia** [comment]
I'm including the author of PR #120 (@kazuki43zoo) in this issue.

Do you know something about this?

**Comment by medy75** [comment]
Same issue here with Firefox driver:
017-05-12 11:54:53.201 3607 [main] INFO  Downloader:104 - Downloading https://github.com/mozilla/geckodriver/releases/download/v0.16.1/geckodriver-v0.16.1-macos.tar.gz to /Users/jaroslavmedek/.m2/repository/webdriver/geckodriver/macos/0.16.1/geckodriver-v0.16.1-macos.tar.gz
2017-05-12 11:54:54.857 5263 [main] WARN  ResponseProcessCookies:130 - Invalid cookie header: "Set-Cookie: logged_in=no; domain=.github.com; path=/; expires=Tue, 12 May 2037 09:54:54 -0000; secure; HttpOnly". Invalid 'expires' attribute: Tue, 12 May 2037 09:54:54 -0000

**Comment by bonigarcia** [comment]
I am not able to reproduce this issue.

@Evleky and @medy75 I need the exact test conditions to reproduce it, otherwise I cannot try to solve it.

**Comment by kazuki43zoo** [comment]
> I am not able to reproduce this issue.

me too... It work fine in  my machine on Windows 7. I will try this on Mac at later.

**Comment by Evleky** [comment]
OS is Windows 10. Running via Eclipse Neon 3.0.  webdrivermanager is brought in using Maven. Using selenium-server 3.0.1, httpclient 4.5.2, httpcore 4.4.4

**Comment by bonigarcia** [comment]
@Evleky  The test code would help.

**Comment by Evleky** [comment]
I believe these are the only setup/offending lines.

InternetExplorerDriverManager.getInstance().arch32().version("3.3").setup();

FirefoxDriverManager.getInstance().setup();

**Comment by kazuki43zoo** [comment]
It work fine in my local machine on Windows 10.

**Comment by kazuki43zoo** [comment]
Could you provide a reproduce project on GitHub ?

**Comment by Evleky** [comment]
Since it looks like HTTPClient/Core is the issue, which versions of these are you using?

**Comment by kazuki43zoo** [comment]
I used following configuration:

```xml
<dependency>
	<groupId>org.apache.httpcomponents</groupId>
	<artifactId>httpclient</artifactId>
	<version>4.5.2</version>
</dependency>

<dependency>
	<groupId>org.apache.httpcomponents</groupId>
	<artifactId>httpcore</artifactId>
	<version>4.4.4</version>
</dependency>
``

**Comment by Evleky** [comment]
And it's not being overridden by a newer version? If so I'm out of ideas, our project is pretty massive to attempt recreating.

**Comment by kazuki43zoo** [comment]
???

> Could you provide a reproduce project on GitHub ?

Please provide this !

**Comment by Evleky** [comment]
Got it, so the dependency we were using was older than I thought, I was checking the project above it on accident. We were using httpclient and core 4.4.1. Added exclusions to keep from pulling those in, and everything works fine.

**Comment by bonigarcia** [comment]
@kazuki43zoo Thank you very much for your help.
