### ISSUE TITLE
No proper candidate URL to download geckodriver 0.35.0

### ISSUE THREAD

**Issue by valfirst** [bonigarcia/webdrivermanager#1329]
**Steps to reproduce**
```java
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;

import io.github.bonigarcia.wdm.WebDriverManager;

class FirefoxTest {

    WebDriver driver;

    @BeforeAll
    static void setupAll() {
        WebDriverManager.firefoxdriver().setup();
    }

    @BeforeEach
    void setup() {
        driver = new FirefoxDriver();
    }

    @AfterEach
    void teardown() {
        driver.quit();
    }

    @Test
    void test() {
        // Your test logic here
    }
}
```

**Error log**
```
18:55:11.048 [main] ERROR io.github.bonigarcia.wdm.WebDriverManager - There was an error managing geckodriver 0.35.0 (No proper candidate URL to download geckodriver 0.35.0)
io.github.bonigarcia.wdm.config.WebDriverManagerException: No proper candidate URL to download geckodriver 0.35.0
	at io.github.bonigarcia.wdm.online.UrlHandler.getCandidateUrl(UrlHandler.java:287) ~[webdrivermanager-5.9.2.jar:?]
	at io.github.bonigarcia.wdm.WebDriverManager.download(WebDriverManager.java:1269) ~[webdrivermanager-5.9.2.jar:?]
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:1184) ~[webdrivermanager-5.9.2.jar:?]
	at io.github.bonigarcia.wdm.WebDriverManager.fallback(WebDriverManager.java:1437) ~[webdrivermanager-5.9.2.jar:?]
	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:1415) ~[webdrivermanager-5.9.2.jar:?]
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:1190) ~[webdrivermanager-5.9.2.jar:?]
	at io.github.bonigarcia.wdm.WebDriverManager.setup(WebDriverManager.java:427) ~[webdrivermanager-5.9.2.jar:?]
	at FirefoxTest.setupAll(FirefoxTest.java:16) ~[main/:?]
	...

Test ignored.

io.github.bonigarcia.wdm.config.WebDriverManagerException: io.github.bonigarcia.wdm.config.WebDriverManagerException: No proper candidate URL to download geckodriver 0.35.0

	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:1421)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:1190)
	at io.github.bonigarcia.wdm.WebDriverManager.fallback(WebDriverManager.java:1437)
	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:1415)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:1190)
	at io.github.bonigarcia.wdm.WebDriverManager.setup(WebDriverManager.java:427)
	at FirefoxTest.setupAll(FirefoxTest.java:16)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: io.github.bonigarcia.wdm.config.WebDriverManagerException: No proper candidate URL to download geckodriver 0.35.0
	at io.github.bonigarcia.wdm.online.UrlHandler.getCandidateUrl(UrlHandler.java:287)
	at io.github.bonigarcia.wdm.WebDriverManager.download(WebDriverManager.java:1269)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:1184)
	... 7 more

```

**Comment by ForwardQA** [comment]
I ran into this as well this a.m. (PDT)

**Comment by bonigarcia** [comment]
That was a transitory problem caused by the lack of sync of an online metadata file containing the URLs to download the geckodriver releases (geckodriver 0.35.0 has been released today). It should be fixed now, so you can rerun your test suite, and it should work without any change from your side.

**Comment by valfirst** [comment]
Thanks, it works now
