### ISSUE TITLE
Not working when Test Suite are running in Parallel

### ISSUE THREAD

**Issue by sumit-global** [bonigarcia/webdrivermanager#138]
Throws **SEVERE: org.apache.commons.exec.ExecuteException: Execution failed (Exit value: -559038737. Caused by java.io.IOException, The process cannot access the file because it is being used by another process**, when cases are running in Parallel.

For parallel execution using ThreadLocal<WebDriver> and testNG
Please suggest how to proceed.

**Comment by bonigarcia** [comment]
That information is not enough to find out what exactly is the problem. If you want support you need to provide precise information about your problem, including assets (i.e. source code of your test and environment) to reproduce it.

**Comment by sumit-global** [comment]
I have a base class as follow:

public abstract class BaseClass {
ThreadLocal<WebDriver> driver = new ThreadLocal<WebDriver>();
public WebDriver webDriver;

@BeforeClass(alwaysRun = true)
public synchronized void setUp() {
			webDriver = getWebDriver();
			setWebDriver(webDriver);
			getDriver();
		}
static void setWebDriver(WebDriver d) 
{ driver.set(d); }
public static WebDriver getDriver() 
{ return driver.get();	}

public WebDriver getWebDriver(){
ChromeDriverManager.getInstance().version("2.27").setup();
}

Now every TestCase(Each testcase have individual class) extends BaseClass and have individual WebDriver instance (that helps to run parallel) , when i ran it parallel it gives me **SEVERE: org.apache.commons.exec.ExecuteException: Execution failed (Exit value: -559038737. Caused by java.io.IOException, The process cannot access the file because it is being used by another process**

Please let me know incase of any other info required

**Comment by bonigarcia** [comment]
Please provide the full exception stack.

**Comment by sumit-global** [comment]
java.lang.RuntimeException: java.lang.IllegalStateException: Connection pool shut down
	at io.github.bonigarcia.wdm.BrowserManager.manage(BrowserManager.java:262)
	at io.github.bonigarcia.wdm.BrowserManager.setup(BrowserManager.java:765)
	at io.github.bonigarcia.wdm.BrowserManager.setup(BrowserManager.java:725)
	at com.autofusion.InitializeWebDriver.getWebDriver(InitializeWebDriver.java:57)
	at com.autofusion.BaseClass.getWebDriver(BaseClass.java:418)
	at com.autofusion.BaseClass.setUp(BaseClass.java:187)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:217)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:144)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:169)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: Connection pool shut down
	at org.apache.http.util.Asserts.check(Asserts.java:34)
	at org.apache.http.pool.AbstractConnPool.lease(AbstractConnPool.java:189)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.requestConnection(PoolingHttpClientConnectionManager.java:257)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:176)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at io.github.bonigarcia.wdm.WdmHttpClient.execute(WdmHttpClient.java:81)
	at io.github.bonigarcia.wdm.BrowserManager.getDriversFromXml(BrowserManager.java:630)
	at io.github.bonigarcia.wdm.ChromeDriverManager.getDrivers(ChromeDriverManager.java:46)
	at io.github.bonigarcia.wdm.BrowserManager.manage(BrowserManager.java:193)
	... 18 more

**Comment by tharakadesilva** [comment]
https://github.com/bonigarcia/webdrivermanager/pull/140 should fix it. Check it out.

**Comment by sumit-global** [comment]
Thanks Tharaka De Silva, hoping it get resolved in latest build

**Comment by bonigarcia** [comment]
Merged. I'll be available on the next release.

**Comment by sumit-global** [comment]
Thanks Boni García, when it will be available?

**Comment by bonigarcia** [comment]
There is still pending open bugs and I need to check, but I'm not sure when I'll be able to do it.

**Comment by sumit-global** [comment]
It would be really grateful if you release your api with this fix over the weekend :) 
Btw great work :+1:

**Comment by bonigarcia** [comment]
Not happening this weekend for sure

**Comment by sumit-global** [comment]
Okay :) But please do it ASAP :)
Thanks! :)

**Comment by sumit-global** [comment]
Hi, 
Just want to confirm (1.7.0) contains this fix?
