### ISSUE TITLE
Download Failure for Geckodriver

### ISSUE THREAD

**Issue by ITAKEB** [bonigarcia/webdrivermanager#1398]
**Description of the problem**: When geckodriver is not cached and needs to be downloaded, an error occurs that prevents it from being successfully downloaded and executed.

**Browser and version**:  Firefox - 133.0

**Operating system and architecture**:  macos-aarch64

**Selenium version**: 4.20.0

**WebDriverManager version**: 5.9.2

**WebDriverManager call**: 
```
WebDriverManager.firefoxdriver().setup();
```

**WebDriverManager traces**: 
```
2024-12-03 15:06:54 [ForkJoinPool-2-worker-1] INFO  i.g.bonigarcia.wdm.WebDriverManager.resolveDriverVersion(1220) - Using geckodriver 0.35.0 (resolved driver for Firefox 133)
2024-12-03 15:06:54 [ForkJoinPool-2-worker-1] INFO  i.g.bonigarcia.wdm.WebDriverManager.logSeekRepo(1594) - Reading https://raw.githubusercontent.com/bonigarcia/webdrivermanager/master/docs/mirror/geckodriver to seek geckodriver
2024-12-03 15:06:54 [ForkJoinPool-2-worker-1] INFO  i.g.bonigarcia.wdm.online.Downloader.downloadAndExtract(128) - Downloading https://github.com/mozilla/geckodriver/releases/download/v0.35.0/geckodriver-v0.35.0-macos-aarch64.tar.gz
2024-12-03 15:06:55 [ForkJoinPool-2-worker-1] INFO  i.g.bonigarcia.wdm.online.Downloader.extract(189) - Extracting driver from compressed file geckodriver-v0.35.0-macos-aarch64.tar.gz
```

**Error log**: 
```

java.lang.NoSuchMethodError: 'long org.apache.commons.io.IOUtils.skip(java.io.InputStream, long, java.util.function.Supplier)'
	at org.apache.commons.compress.utils.IOUtils.skip(IOUtils.java:282)
	at org.apache.commons.compress.archivers.tar.TarArchiveInputStream.getNextTarEntry(TarArchiveInputStream.java:409)
	at org.apache.commons.compress.archivers.tar.TarArchiveInputStream.getNextEntry(TarArchiveInputStream.java:389)
	at io.github.bonigarcia.wdm.online.Downloader.unTarGz(Downloader.java:280)
	at io.github.bonigarcia.wdm.online.Downloader.extract(Downloader.java:192)
	at io.github.bonigarcia.wdm.online.Downloader.downloadAndExtract(Downloader.java:139)
	at io.github.bonigarcia.wdm.online.Downloader.download(Downloader.java:91)
	at io.github.bonigarcia.wdm.WebDriverManager.download(WebDriverManager.java:1273)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:1184)
	at io.github.bonigarcia.wdm.WebDriverManager.setup(WebDriverManager.java:427)
```

**Comment by ITAKEB** [comment]
Hi @bonigarcia! Thanks for responding!

According to the WebDriverManager `pom.xml`: [WebDriverManager pom.xml](https://github.com/bonigarcia/webdrivermanager/blob/webdrivermanager-5.9.2/pom.xml#L15), it currently uses `org.apache.commons:commons-compress:1.26.2`. Is there a possibility to update it?

**Comment by ITAKEB** [comment]
That's the version I'm using according to IntelliJ, and it's the one causing the error

![image](https://github.com/user-attachments/assets/b8e68b3a-d8cf-4ee4-986d-76ac677d5cd9)

**Comment by ITAKEB** [comment]
Got it! I'm going to check it!

Thank you!!
