### ISSUE TITLE
detect chrome path with wmic  is deprecated

### ISSUE THREAD

**Issue by rxxy** [bonigarcia/webdrivermanager#1407]
https://github.com/bonigarcia/webdrivermanager/blob/7a70df443154872e4473f85c7d591e234ae5ab75/src/main/java/io/github/bonigarcia/wdm/versions/VersionDetector.java#L200C32-L200C47

wmic is deprecated in win11, I have no wmic command in win11, so I detected chrome nothing
see [https://learn.microsoft.com/en-us/windows/win32/wmisdk/wmic](https://learn.microsoft.com/en-us/windows/win32/wmisdk/wmic)

**Comment by bonigarcia** [comment]
Yes, I'm aware WMIC is going to be removed in the future. See: https://techcommunity.microsoft.com/blog/windows-itpro-blog/wmi-command-line-wmic-utility-deprecation-next-steps/4039242

But it continues working in Windows 11, to the best of my knowledge. And in any case, WebDriverManager also uses the registry information to discover browser versions (see [here](https://github.com/bonigarcia/webdrivermanager/blob/master/src/main/resources/commands.properties)).

In any case, I plan to change the WMIC commands used in WebDriverManager with the equivalent PowerShell commands in the short future.

**Comment by Kelvao** [comment]
Nope, is not working. Im using the latest version and browserpath always come null.

```
[JavaFX Application Thread] INFO io.github.bonigarcia.wdm.WebDriverManager - Exporting webdriver.chrome.driver as C:\Users\Kelvao\.cache\selenium\chromedriver\win64\133.0.6943.141\chromedriver.exe
Exception in thread "JavaFX Application Thread" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at javafx.fxml@21/javafx.fxml.FXMLLoader$MethodHandler.invoke(FXMLLoader.java:1858)
	at javafx.fxml@21/javafx.fxml.FXMLLoader$ControllerMethodEventHandler.handle(FXMLLoader.java:1726)
	at javafx.base@21/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at javafx.base@21/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:232)
	at javafx.base@21/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:189)
	at javafx.base@21/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at javafx.base@21/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at javafx.base@21/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@21/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base@21/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@21/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base@21/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@21/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at javafx.base@21/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
	at javafx.base@21/javafx.event.Event.fireEvent(Event.java:198)
	at javafx.graphics@21/javafx.scene.Node.fireEvent(Node.java:8875)
	at javafx.controls@21/javafx.scene.control.Button.fire(Button.java:203)
	at javafx.controls@21/com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(ButtonBehavior.java:207)
	at javafx.controls@21/com.sun.javafx.scene.control.inputmap.InputMap.handle(InputMap.java:274)
	at javafx.base@21/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:247)
	at javafx.base@21/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at javafx.base@21/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:232)
	at javafx.base@21/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:189)
	at javafx.base@21/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at javafx.base@21/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at javafx.base@21/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@21/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base@21/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@21/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base@21/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@21/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at javafx.base@21/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.base@21/javafx.event.Event.fireEvent(Event.java:198)
	at javafx.graphics@21/javafx.scene.Scene$MouseHandler.process(Scene.java:3984)
	at javafx.graphics@21/javafx.scene.Scene.processMouseEvent(Scene.java:1890)
	at javafx.graphics@21/javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2708)
	at javafx.graphics@21/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:411)
	at javafx.graphics@21/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:301)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at javafx.graphics@21/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:450)
	at javafx.graphics@21/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:424)
	at javafx.graphics@21/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:449)
	at javafx.graphics@21/com.sun.glass.ui.View.handleMouseEvent(View.java:551)
	at javafx.graphics@21/com.sun.glass.ui.View.notifyMouse(View.java:937)
	at javafx.graphics@21/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics@21/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:185)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at com.sun.javafx.reflect.Trampoline.invoke(MethodUtil.java:72)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at javafx.base@21/com.sun.javafx.reflect.MethodUtil.invoke(MethodUtil.java:270)
	at javafx.fxml@21/com.sun.javafx.fxml.MethodHelper.invoke(MethodHelper.java:84)
	at javafx.fxml@21/javafx.fxml.FXMLLoader$MethodHandler.invoke(FXMLLoader.java:1855)
	... 46 more
Caused by: org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: session not created
from unknown error: cannot find Chrome binary 
Host info: host: 'CARNAGE', ip: '192.168.1.6'
Build info: version: '4.29.0', revision: '5fc1ec94cb'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '21.0.5'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [null, newSession {capabilities=[Capabilities {browserName: chrome, goog:chromeOptions: {args: [--headless, --disable-gpu, --no-sandbox, --disable-dev-shm-usage], extensions: []}}]}]
	at org.seleniumhq.selenium.remote_driver/org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:114)
	at org.seleniumhq.selenium.remote_driver/org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:75)
	at org.seleniumhq.selenium.remote_driver/org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:61)
	at org.seleniumhq.selenium.remote_driver/org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:187)
	at org.seleniumhq.selenium.remote_driver/org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:216)
	at org.seleniumhq.selenium.remote_driver/org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:174)
	at org.seleniumhq.selenium.remote_driver/org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:545)
	at org.seleniumhq.selenium.remote_driver/org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:245)
	at org.seleniumhq.selenium.remote_driver/org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:174)
	at org.seleniumhq.selenium.chromium_driver/org.openqa.selenium.chromium.ChromiumDriver.<init>(ChromiumDriver.java:110)
	at org.seleniumhq.selenium.chrome_driver/org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:88)
	at org.seleniumhq.selenium.chrome_driver/org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:83)
	at org.seleniumhq.selenium.chrome_driver/org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:72)
	at io.github.kelvao.chordproconverter/io.github.kelvao.chordproconverter.selenium.SeleniumScraper.selenium(SeleniumScraper.kt:25)
	at io.github.kelvao.chordproconverter/io.github.kelvao.chordproconverter.MainController.onHelloButtonClick(MainController.kt:13)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	... 53 more

```

My code:

```

object SeleniumScraper {
    private lateinit var driver: WebDriver
    private var listener: StateListener = {}

    fun selenium(block: SeleniumScraper.() -> Unit) {
        WebDriverManager.chromedriver().setup()
        Thread.sleep(2000)
        val options = ChromeOptions().apply {
            addArguments("--headless")
            addArguments("--disable-gpu")
            addArguments("--no-sandbox")
            addArguments("--disable-dev-shm-usage")
        }
        driver = ChromeDriver(options)
        this.apply(block)
    }

    fun loadUrl(url: String) {
        CoroutineScope(Dispatchers.IO).launch {
            listener(SeleniumState.Loading)
            try {
                driver.get(url)
                val pageSource = driver.pageSource

                pageSource?.let {
                    withContext(Dispatchers.Main) {
                        listener(SeleniumState.Success(pageSource))
                    }
                } ?: throw Exception("Source empty")

            } catch (e: Exception) {
                withContext(Dispatchers.Main) {
                    listener(SeleniumState.Error(e.message ?: "Unknown error"))
                }
            }
        }
    }

    fun onStateChange(listener: StateListener) {
        this.listener = listener
    }

    fun quit() {
        driver.quit()
    }
}
```

**Comment by bonigarcia** [comment]
I have just released WebDriverManager 6.0.0. In this new major version, WebDriverManages uses PowerShell instead of WMIC for browser version discovery in Windows.
