### ISSUE TITLE
Can we specify chrome driver version while getting instance !

### ISSUE THREAD

**Issue by RajAsapu** [bonigarcia/webdrivermanager#141]
I am looking for some way to get the latest Chromedriver 2.29. My tests are failing now if i use  ChromeDriverManager.getInstance().setup() with chrome version 58.0. I had to use System.setProperty and set the latest chrome driver path for it to work.

**Comment by tharakadesilva** [comment]
ChromeDriverManager().getInstance().version("2.29").setup();

**Comment by tharakadesilva** [comment]
`ChromeDriverManager().getInstance().version("2.26").setup();` should work.

**Comment by tharakadesilva** [comment]
You shouldn't have to do anything specific. Are you using the cache feature?

I have the following code and it fetches the latest driver without any problems.
This is my code:
```
ChromeDriverManager.getInstance().setup();
WebDriver driver = new ChromeDriver();
```


These are my logs:
`[2017-06-03 04:13:36:051] [main] INFO BrowserManager - Reading https://chromedriver.storage.googleapis.com/ to seek [chromedriver]
[2017-06-03 04:13:36:457] [main] INFO BrowserManager - Latest version of [chromedriver] is 2.29
[2017-06-03 04:13:36:458] [main] INFO Downloader - Downloading https://chromedriver.storage.googleapis.com/2.29/chromedriver_win32.zip to C:\Users\Tharaka\.m2\repository\webdriver\chromedriver\win32\2.29\chromedriver_win32.zip
[2017-06-03 04:13:37:167] [main] INFO BrowserManager - Exporting webdriver.chrome.driver as C:\Users\Tharaka\.m2\repository\webdriver\chromedriver\win32\2.29\chromedriver.exe`

**Comment by tharakadesilva** [comment]
I added version 2.29 to the ChromeVersionTest in https://github.com/bonigarcia/webdrivermanager/pull/142 and according to line 1439 in the [continuous integration test](https://travis-ci.org/bonigarcia/webdrivermanager/builds/239037346#L1439), the webdrivermanager identified Chrome driver 2.29 to be the latest version.

**Comment by RajAsapu** [comment]
@bonigarcia @tharakadesilva : I get java.lang.RuntimeException: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
on using `ChromeDriverManager.getInstance().setup();`
while its working fine when i use System.setProperty with chrome driver 2.29.

**Comment by RajAsapu** [comment]
Stack trace:
`java.lang.RuntimeException: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
at io.github.bonigarcia.wdm.BrowserManager.manage(BrowserManager.java:317)
  at io.github.bonigarcia.wdm.BrowserManager.setup(BrowserManager.java:112)
  at io.github.bonigarcia.wdm.BrowserManager.setup(BrowserManager.java:91)
  at setup.OpenBrowser.getDriver(OpenBrowser.java:70)
  at setup.OpenBrowser.initBrowser(OpenBrowser.java:38)
  at stepdef.PageCommonSteps.openApplication(PageCommonSteps.java:45)
  at stepdef.PageCommonSteps.the_user_has_logged_into_the_mapper_application(PageCommonSteps.java:57)
  at ✽.Given the user has logged into the mapper application(/home/rasapu/Desktop/mapper-e2e-tests/src/test/resources/features/pageobjects/PageSourceCreatePage.feature:5)
Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
  at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
  at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1949)
  at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:302)
  at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296)
  at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1514)
  at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)
  at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1026)
  at sun.security.ssl.Handshaker.process_record(Handshaker.java:961)
  at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1062)
  at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
  at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
  at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
  at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
  at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
  at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1546)
  at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
  at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
  at io.github.bonigarcia.wdm.BrowserManager.getDriversFromXml(BrowserManager.java:571)
  at io.github.bonigarcia.wdm.ChromeDriverManager.getDrivers(ChromeDriverManager.java:44)
  at io.github.bonigarcia.wdm.BrowserManager.manage(BrowserManager.java:247)
  at io.github.bonigarcia.wdm.BrowserManager.setup(BrowserManager.java:112)
  at io.github.bonigarcia.wdm.BrowserManager.setup(BrowserManager.java:91)
  at setup.OpenBrowser.getDriver(OpenBrowser.java:70)
  at setup.OpenBrowser.initBrowser(OpenBrowser.java:38)
  at stepdef.PageCommonSteps.openApplication(PageCommonSteps.java:45)
  at stepdef.PageCommonSteps.the_user_has_logged_into_the_mapper_application(PageCommonSteps.java:57)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at cucumber.runtime.Utils$1.call(Utils.java:40)
  at cucumber.runtime.Timeout.timeout(Timeout.java:16)
  at cucumber.runtime.Utils.invoke(Utils.java:34)
  at cucumber.runtime.java.JavaStepDefinition.execute(JavaStepDefinition.java:38)
  at cucumber.runtime.StepDefinitionMatch.runStep(StepDefinitionMatch.java:37)
  at cucumber.runtime.Runtime.runStep(Runtime.java:300)
  at cucumber.runtime.model.StepContainer.runStep(StepContainer.java:44)
  at cucumber.runtime.model.StepContainer.runSteps(StepContainer.java:39)
  at cucumber.runtime.model.CucumberScenario.runBackground(CucumberScenario.java:59)
  at cucumber.runtime.model.CucumberScenario.run(CucumberScenario.java:42)
  at cucumber.runtime.model.CucumberScenarioOutline.run(CucumberScenarioOutline.java:46)
  at cucumber.runtime.model.CucumberFeature.run(CucumberFeature.java:165)
  at cucumber.runtime.Runtime.run(Runtime.java:122)
  at cucumber.api.cli.Main.run(Main.java:36)
  at cucumber.api.cli.Main.main(Main.java:18)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
  at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:387)
  at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:292)
  at sun.security.validator.Validator.validate(Validator.java:260)
  at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
  at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)
  at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
  at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1496)
  ... 45 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
  at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
  at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
  at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
  at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:382)
  ... 51 more`

**Comment by tharakadesilva** [comment]
@RajAsapu I feel that this is more to do with your environment. What's the version of your JDK/JRE and what JDK are you using (OpenJDK, Oracle, etc.)?

**Comment by RajAsapu** [comment]
@tharakadesilva : Oracle 8 jdk

**Comment by tharakadesilva** [comment]
@RajAsapu The issue appears to be because you don't have the cert for google in your trust store. This ought to fix your problem: https://stackoverflow.com/a/36427118. Remember, you are going to have to add it to the correct JRE (if you have multiple installations).

@bonigarcia an option on the webdrivermanager's end would be to modify the code to ignore SSL errors which is probably a really bad idea because of man in the middle attacks. What do you think? If not, this information, if works, should be added to the README.md file.

**Comment by RajAsapu** [comment]
@tharakadesilva : Okay desilva , in that case why is it working with System.setProperty with chrome driver 2.29!

**Comment by tharakadesilva** [comment]
@RajAsapu By using System.setProperty() method, you are setting the path to a local file which is already existing (chromedriver.exe executable file).

The webdrivermanager is failing is when it is trying to fetch that executable file from a google repository. For this webdrivermanager tries to make a SSL connection with the google repository but since the certificate is not in your trust store, it prevents that connection from establishing throwing the javax.net.ssl.SSLHandshakeException.

**Comment by RajAsapu** [comment]
Ok thank you @tharakadesilva

**Comment by tharakadesilva** [comment]
@RajAsapu could you let us know in this thread if that fix helped please?

**Comment by RajAsapu** [comment]
Sure I will give a try tomorrow and will let you know
