### ISSUE TITLE
Not able to connect and download, the Latest version Chromedriver from the download URL-https://chromedriver.storage.googleapis.com/index.html

### ISSUE THREAD

**Issue by KarthigaMuthusamy** [bonigarcia/webdrivermanager#144]
This is the exception which i am getting while trying to download the latest version of chromedriver from chromedriver.storage.googleapis.com.

Exception:
java.lang.RuntimeException: org.apache.http.conn.HttpHostConnectException: Connect to chromedriver.storage.googleapis.com:443 [chromedriver.storage.googleapis.com/216.58.206.16] failed: Connection timed out: connect
	at io.github.bonigarcia.wdm.BrowserManager.manage(BrowserManager.java:262)
	at io.github.bonigarcia.wdm.BrowserManager.setup(BrowserManager.java:765)
	at io.github.bonigarcia.wdm.BrowserManager.setup(BrowserManager.java:725)
	at atos.mae.auto.plugins.requirement.WebDriverProvider.setWebDriver(WebDriverProvider.java:195)
	at atos.mae.auto.action.Action.openBrowser(Action.java:223)
	at atos.mae.auto.factory.GlobalWebElement.openBrowser(GlobalWebElement.java:18)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at atos.mae.auto.excel.TestStepService.CallMethod(TestStepService.java:226)
	at atos.mae.auto.excel.TestStepService.executeStep(TestStepService.java:197)
	at atos.mae.auto.excel.TestStepService.execute(TestStepService.java:132)
	at atos.mae.auto.Main.launchTest(Main.java:350)
	at atos.mae.auto.Main.start(Main.java:247)
	at atos.mae.auto.Main.main(Main.java:175)
Caused by: org.apache.http.conn.HttpHostConnectException: Connect to chromedriver.storage.googleapis.com:443 [chromedriver.storage.googleapis.com/216.58.206.16] failed: Connection timed out: connect
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:159)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:359)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at io.github.bonigarcia.wdm.WdmHttpClient.execute(WdmHttpClient.java:81)
	at io.github.bonigarcia.wdm.BrowserManager.getDriversFromXml(BrowserManager.java:630)
	at io.github.bonigarcia.wdm.ChromeDriverManager.getDrivers(ChromeDriverManager.java:46)
	at io.github.bonigarcia.wdm.BrowserManager.manage(BrowserManager.java:193)
	... 15 more
Caused by: java.net.ConnectException: Connection timed out: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:339)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	... 28 more
atos.mae.auto.utils.Exceptions.NoDriverDefineException: No defined driver
	at atos.mae.auto.plugins.requirement.WebDriverProvider.getWebDriver(WebDriverProvider.java:259)
	at atos.mae.auto.action.Action.navigate(Action.java:249)
	at atos.mae.auto.factory.GlobalWebElement.navigate(GlobalWebElement.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at atos.mae.auto.excel.TestStepService.CallMethod(TestStepService.java:226)
	at atos.mae.auto.excel.TestStepService.executeStep(TestStepService.java:197)
	at atos.mae.auto.excel.TestStepService.execute(TestStepService.java:132)
	at atos.mae.auto.Main.launchTest(Main.java:350)
	at atos.mae.auto.Main.start(Main.java:247)
	at atos.mae.auto.Main.main(Main.java:175)

Can you please give me the solution how to solve this exception ...
Thanks in Advance

**Comment by bonigarcia** [comment]
Everything seems to work correctly in my latest tests. Maybe this is caused to a temporal problem with the chromedriver repository. Is this problem persistent for you?

**Comment by tharakadesilva** [comment]
Long shot here, but there should be a log which looks similar to:
`Reading https://chromedriver.storage.googleapis.com/ to seek [chromedriver]`

Could you link that log and your setup code please?

**Comment by KarthigaMuthusamy** [comment]
After using proxy("server:port") i am able to connect to https://chromedriver.storage.googleapis.com/ and download the webdriver.

**Comment by sayanece2** [comment]
Getting error when using v3.0.0. Its working fine when using version: 2.2.5.
POM:
 <dependency>
    <groupId>io.github.bonigarcia</groupId>
    <artifactId>webdrivermanager</artifactId>
    <version>3.0.0</version>
    <scope>test</scope>
</dependency>

Error:
[ERROR] Tests run: 4, Failures: 1, Errors: 0, Skipped: 3, Time elapsed: 4.816 s <<< FAILURE! - in TestSuite
[ERROR] beforeTest(DriverPackage.MainDriver)  Time elapsed: 4.468 s  <<< FAILURE!
io.github.bonigarcia.wdm.WebDriverManagerException: java.lang.NullPointerException
	at DriverPackage.MainDriver.beforeTest(MainDriver.java:27)
Caused by: java.lang.NullPointerException
	at DriverPackage.MainDriver.beforeTest(MainDriver.java:27)

Why its throwing null pointer exception for 3.0.0?

Thanks in advance.

**Comment by RabiaShaik** [comment]
> After using proxy("server:port") i am able to connect to https://chromedriver.storage.googleapis.com/ and download the webdriver.

May I know where u set this? in you IDE? and can u tell me the values u set please

**Comment by vishalbiradar** [comment]
> After using proxy("server:port") i am able to connect to https://chromedriver.storage.googleapis.com/ and download the webdriver.

How and where you set it?
