### ISSUE TITLE
PhantomJS SSL certificate is bad

### ISSUE THREAD

**Issue by lbenda** [bonigarcia/webdrivermanager#161]
io.github.bonigarcia.wdm.WebDriverManagerException: Exception managing driver for [phantomjs]

	at io.github.bonigarcia.wdm.BrowserManager.manage(BrowserManager.java:288)
	at io.github.bonigarcia.wdm.BrowserManager.manage(BrowserManager.java:279)
	at io.github.bonigarcia.wdm.BrowserManager.setup(BrowserManager.java:839)
	at io.github.bonigarcia.wdm.BrowserManager.setup(BrowserManager.java:787)
Caused by: javax.net.ssl.SSLPeerUnverifiedException: Host name 'bbuseruploads.s3.amazonaws.com' does not match the certificate subject provided by the peer (CN=*.s3.amazonaws.com, O=Amazon.com Inc., L=Seattle, ST=Washington, C=US)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.verifyHostname(SSLConnectionSocketFactory.java:466)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:396)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:354)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:134)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at io.github.bonigarcia.wdm.WdmHttpClient.execute(WdmHttpClient.java:90)
	at io.github.bonigarcia.wdm.Downloader.download(Downloader.java:109)
	at io.github.bonigarcia.wdm.BrowserManager.manage(BrowserManager.java:266)
	... 39 more

**Comment by adamcohenrose** [comment]
This is a bitbucket download failing -- the original links are at https://bitbucket.org/ariya/phantomjs/downloads/ but each zip redirects to a `bbuseruploads.s3.amazonaws.com` URL.

Oddly, downloading these files works fine from Chrome, so there's likely some odd SSL certificate issue going on with java accessing the bitbucket file from Amazon S3.

A temporary workaround would be to manually download the relevant zip and extract the executable to `<local-maven-repo>/webdriver/phantomjs/<os>/<version>/phantomjs` (e.g. `~/.m2/repository/webdriver/phantomjs/macosx/2.1.1/phantomjs`)

Alternatively, try adding `useTaobaoMirror()` to your `PhantomJsDriverManager.getInstance()` call

**Comment by bonigarcia** [comment]
Thanks @adamcohenrose for your comment. @lbenda is your problem solved?
