### ISSUE TITLE
Error when use taobao mirror 

### ISSUE THREAD

**Issue by sanlengjingvv** [bonigarcia/webdrivermanager#170]
with selenide 4.8
```java
Configuration.browser="chrome";
ChromeDriverManager.getInstance().useTaobaoMirror().setup();
```
> com.typesafe.config.ConfigException$BadPath: path parameter: Invalid path 'http://npm.taobao.org/mirrors/chromedriver': Token not allowed in path expression: ':' (you can double-quote this token if you really want it here)

> 	at com.typesafe.config.impl.Parser.parsePathExpression(Parser.java:1095)
	at com.typesafe.config.impl.Parser.parsePath(Parser.java:1135)
	at com.typesafe.config.impl.Path.newPath(Path.java:224)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:163)
	at com.typesafe.config.impl.SimpleConfig.getString(SimpleConfig.java:206)
	at io.github.bonigarcia.wdm.WdmConfig.getString(WdmConfig.java:52)
	at io.github.bonigarcia.wdm.ChromeDriverManager.useTaobaoMirror(ChromeDriverManager.java:87)
	at e2etest.lib.Utils.setConfiguration(Utils.java:229)
	at e2etest.manager.MngAuth.BeforeMethod(MngAuth.java:18)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:523)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:224)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:599)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)

**Comment by bonigarcia** [comment]
Thank for reporting, it seems the Taobao mirror feature is broken at this moment. I'll try to fix it asap.

**Comment by bonigarcia** [comment]
Solved. To be available on next version.
