### ISSUE TITLE
401 Unathorized when trying to download FF driver

### ISSUE THREAD

**Issue by JMVM** [bonigarcia/webdrivermanager#180]
**io.github.bonigarcia.wdm.WebDriverManagerException: io.github.bonigarcia.wdm.WebDriverManagerException: A response error is detected: HTTP/1.1 401 Unauthorized
	at io.github.bonigarcia.wdm.BrowserManager.handleException(BrowserManager.java:233)
	at io.github.bonigarcia.wdm.BrowserManager.manage(BrowserManager.java:198)
	at io.github.bonigarcia.wdm.BrowserManager.handleException(BrowserManager.java:231)
	at io.github.bonigarcia.wdm.BrowserManager.manage(BrowserManager.java:198)
	at io.github.bonigarcia.wdm.BrowserManager.setup(BrowserManager.java:726)
	at ....
Caused by: io.github.bonigarcia.wdm.WebDriverManagerException: A response error is detected: HTTP/1.1 401 Unauthorized
	at io.github.bonigarcia.wdm.WdmHttpClient.execute(WdmHttpClient.java:143)
	at io.github.bonigarcia.wdm.BrowserManager.openGitHubConnection(BrowserManager.java:623)
	at io.github.bonigarcia.wdm.BrowserManager.getDriversFromGitHub(BrowserManager.java:648)
	at io.github.bonigarcia.wdm.FirefoxDriverManager.getDrivers(FirefoxDriverManager.java:52)
	at io.github.bonigarcia.wdm.BrowserManager.filterCandidateUrls(BrowserManager.java:249)
	at io.github.bonigarcia.wdm.BrowserManager.manage(BrowserManager.java:181)
	... 35 more**

**Comment by Saurikun** [comment]
I'm experiencing same issue for Firefox driver

**Comment by bonigarcia** [comment]
I am not able to reproduce this issue. What version of WedDriverManager are you using? Is this problem persistent or intermittent?

**Comment by JMVM** [comment]
Using this one:

<dependency>
			<groupId>io.github.bonigarcia</groupId>
			<artifactId>webdrivermanager</artifactId>
			<version>2.0.1</version>
</dependency>

Thanks

**Comment by bonigarcia** [comment]
Again: Is this problem persistent or intermittent?

Are you using any proxy setup?
How do you call WebDriverManager?

**Comment by JMVM** [comment]
Investigating, the problem was a token hardcoded and probably outdated to fix https://github.com/bonigarcia/webdrivermanager#known-issues

So please close since it's not an issue.

Thanks
