### ISSUE TITLE
webdrivermanager run time issues

### ISSUE THREAD

**Issue by anwar129** [bonigarcia/webdrivermanager#185]
**Hi, 
i have been  using  mvn for webdriver manager 1.6.1 for while, now it throws error and i updated to newst version, but still get some error ,so i would like to share if you guys had similar issue or know solution. 

Thanks 
[TestNG] Running:
  C:\Users\anwar\AppData\Local\Temp\testng-eclipse--249442669\testng-customsuite.xml

java.lang.RuntimeException
	at org.testng.internal.TestResult.toString(TestResult.java:231)
	at org.testng.internal.TestResult.toString(TestResult.java:215)
	at org.testng.reporters.TestHTMLReporter.generateTable(TestHTMLReporter.java:113)
	at org.testng.reporters.TestHTMLReporter.generateLog(TestHTMLReporter.java:298)
	at org.testng.reporters.TestHTMLReporter.onFinish(TestHTMLReporter.java:40)
	at org.testng.TestRunner.fireEvent(TestRunner.java:1453)
	at org.testng.TestRunner.afterRun(TestRunner.java:1199)
	at org.testng.TestRunner.run(TestRunner.java:612)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1158)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1083)
	at org.testng.TestNG.run(TestNG.java:999)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)

		<dependency>
			<groupId>io.github.bonigarcia</groupId>
			<artifactId>webdrivermanager</artifactId>
			<version>2.1.0</version>
		</dependency>

**Comment by bonigarcia** [comment]
I don't see anything related to WebDriverManager in those traces.
