### ISSUE TITLE
Firefox 59 not launching with WebDriverManager 2.1.0

### ISSUE THREAD

**Issue by shavang** [bonigarcia/webdrivermanager#194]
I am unable to launch firefox 59 with WebDriverManager 2.1.0, but same script is working fine for chrome browser.
Not getting any exception also. Can you please help to resolve this issue.

Sample Code :
---------------------
    <dependency>
        <groupId>io.github.bonigarcia</groupId>
        <artifactId>webdrivermanager</artifactId>
        <version>2.1.0</version>
    </dependency>

  <dependency>
	<groupId>org.seleniumhq.selenium</groupId>
	<artifactId>selenium-java</artifactId>
	<version>3.4.0</version>
 </dependency>

FirefoxDriverManager.getInstance().setup();
driver = new FirefoxDriver();

Can you please guide me how to launch Firefox browser?

**Comment by bonigarcia** [comment]
It seems to be related with #193.

Could you please try to repeat your test using the current SNAPSHOT version?

You simply need to change the version of webdrivermanager to `2.1.1-SNAPSHOT`. Then, you need to include the sonatype repository in your pom.xml:

```
    <repositories>
        <repository>
            <id>sonatype-snapshots</id>
            <url>http://oss.sonatype.org/content/repositories/snapshots</url>
            <layout>default</layout>
            <releases>
                <enabled>false</enabled>
            </releases>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
    </repositories>
```

Please let me know if the error is still there using the new version.

**Comment by shavang** [comment]
Still not launching firefox 59 with WebDriverManager 2.1.1-SNAPSHOT

Updated WDM and repository.
		<dependency>
			<groupId>io.github.bonigarcia</groupId>
			<artifactId>webdrivermanager</artifactId>
			<version>2.1.1-SNAPSHOT</version>
		</dependency>

		FirefoxDriverManager.getInstance().setup();
		System.out.println(System.getProperty("webdriver.gecko.driver"));
                driver = new FirefoxDriver();
                driver.get(url); //Getting java.lang.NullPointerException

I am using

Firefox 59.0
Windows 8.1 pro

The same setup works for Chrome.

I checked and webdriver\geckodriver\win64\0.20.0\geckodriver.exe is downloaded properly. 

Please help to resolve this issue

**Comment by bonigarcia** [comment]
I would need to see the traces to find out what's going on there. Specifically, the `TRACE` level of the traces gives a lot of details.

Could you please set the logging of webdrivermanager to `TRACE` and share the logs? For example, if using logback it would be as follows:

`<logger name="io.github.bonigarcia" level="TRACE" />`

**Comment by bonigarcia** [comment]
Also, please use the latest version of Selenium, maybe that's the problem:

```
<dependency>
    <groupId>org.seleniumhq.selenium</groupId>
    <artifactId>selenium-java</artifactId>
    <version>3.11.0</version>
</dependency>
```

**Comment by rgehy84** [comment]
I'm having a similar issue. I have FF 59. I set the version to 2.1.1-SNAPSHOT and added the repo to the POM file. Chrome driver works as expected. The error that I get now with Firefox is this below:

`
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.rauschig.jarchivelib.FileModeMapper$FileSystemPreferencesReflectionChmodCommand (file:/Users/rgehy/.m2/repository/org/rauschig/jarchivelib/0.7.1/jarchivelib-0.7.1.jar) to method java.util.prefs.FileSystemPreferences.chmod(java.lang.String,int)
WARNING: Please consider reporting this to the maintainers of org.rauschig.jarchivelib.FileModeMapper$FileSystemPreferencesReflectionChmodCommand
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Mar 21, 2018 9:53:20 PM org.rauschig.jarchivelib.FileModeMapper$UnixPermissionMapper chmod
WARNING: Could not set file permissions of /var/folders/p1/pbvkfvhn47v0qjzpm4fpz415x406gv/T/3779175757905957580/geckodriver. Exception was: null
Mar 21, 2018 9:53:34 PM org.rauschig.jarchivelib.FileModeMapper$UnixPermissionMapper chmod
WARNING: Could not set file permissions of /var/folders/p1/pbvkfvhn47v0qjzpm4fpz415x406gv/T/15169863438789858449/geckodriver. Exception was: null

io.github.bonigarcia.wdm.WebDriverManagerException: java.io.FileNotFoundException: Source '/var/folders/p1/pbvkfvhn47v0qjzpm4fpz415x406gv/T/15169863438789858449/geckodriver-v0.20.0-macos.tar.gz' does not exist

	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:465)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:448)
	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:462)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:448)
	at io.github.bonigarcia.wdm.WebDriverManager.setup(WebDriverManager.java:216)
`

**Comment by bonigarcia** [comment]
@rgehy84 I have updated the SNAPSHOT version trying to solve this problem. Could you please repeat your test now and let me know the result?

**Comment by rgehy84** [comment]
@bonigarcia - I was successfully able to open firefox after the update. Thanks!

**Comment by bonigarcia** [comment]
Version 2.2.0 has been released, solving this issue. Thanks @shavang for reporting and @rgehy84 for helping in the debug process.

**Comment by aut2020** [comment]
Hi I am using selenium 4.0.0-alpha-5 and WebDriverManager 4.0.0 but unable to launch FF or any other browser. It works for Chrome without any issues but when I tried to run any other browser, it fails and following error: 
org.openqa.selenium.WebDriverException: Cannot find firefox binary in PATH. Make sure firefox is installed. OS appears to be: WIN10
Build info: version: '4.0.0-alpha-5', revision: 'b3a0d621cc'
System info: host: 'DESKTOP-OERTIH4', ip: '192.168.0.10', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '14.0.1'
Driver info: driver.version: FirefoxDriver
	at org.openqa.selenium.firefox.FirefoxBinary.<init>(FirefoxBinary.java:97)
	at java.base/java.util.Optional.orElseGet(Optional.java:362)
	at org.openqa.selenium.firefox.FirefoxOptions.getBinary(FirefoxOptions.java:198)
	at org.openqa.selenium.firefox.GeckoDriverService$Builder.withOptions(GeckoDriverService.java:177)
	at org.openqa.selenium.firefox.FirefoxDriver.toExecutor(FirefoxDriver.java:186)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:156)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:134)
	at com.qa.cvs.test.BaseTest.setUp(BaseTest.java:50)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:63)
	at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:348)
	at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:302)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:176)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
	at org.testng.TestRunner.privateRun(TestRunner.java:766)
	at org.testng.TestRunner.run(TestRunner.java:587)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
	at org.testng.TestNG.runSuites(TestNG.java:1039)
	at org.testng.TestNG.run(TestNG.java:1007)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Can anybody help in this regards please.

**Comment by AshishRawat123** [comment]
On my console I get "Cannot find firefox binary in Path"
