### ISSUE TITLE
Unzipping Issue with Chrome

### ISSUE THREAD

**Issue by jossjacobo** [bonigarcia/webdrivermanager#201]
Hello,

I seem to be running into this issue every once in a while with no seemingly consistent pattern to reproduce, `webdrivermanager` seems to not be able to find the zip file and it throws an exception. I wonder if it has to do with me running the test in parallel in CI because it seems to work just fine on my local machine. 

Logs
```
[13:19:46][Step 4/5] ERROR BrowserManager Exception managing driver for [chromedriver] java.io.FileNotFoundException: /Users/pepper_admin/.m2/repository/webdriver/chromedriver/mac64/2.38/chromedriver_mac64.zip (No such file or directory)
[13:19:46][Step 4/5] 	at java.util.zip.ZipFile.open(Native Method)
[13:19:46][Step 4/5] 	at java.util.zip.ZipFile.<init>(ZipFile.java:219)
[13:19:46][Step 4/5] 	at java.util.zip.ZipFile.<init>(ZipFile.java:149)
[13:19:46][Step 4/5] 	at java.util.zip.ZipFile.<init>(ZipFile.java:163)
[13:19:46][Step 4/5] 	at io.github.bonigarcia.wdm.Downloader.unZip(Downloader.java:153)
[13:19:46][Step 4/5] 	at io.github.bonigarcia.wdm.Downloader.extract(Downloader.java:138)
[13:19:46][Step 4/5] 	at io.github.bonigarcia.wdm.Downloader.download(Downloader.java:112)
[13:19:46][Step 4/5] 	at io.github.bonigarcia.wdm.BrowserManager.manage(BrowserManager.java:266)
[13:19:46][Step 4/5] 	at io.github.bonigarcia.wdm.BrowserManager.setup(BrowserManager.java:839)
[13:19:46][Step 4/5] 	at io.github.bonigarcia.wdm.BrowserManager.setup(BrowserManager.java:787)
[13:19:46][Step 4/5] 	at io.ddavison.conductor.util.DriverUtil.getDriver(DriverUtil.java:39)
[13:19:46][Step 4/5] 	at io.ddavison.conductor.Locomotive.init(Locomotive.java:53)
[13:19:46][Step 4/5] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[13:19:46][Step 4/5] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[13:19:46][Step 4/5] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[13:19:46][Step 4/5] 	at java.lang.reflect.Method.invoke(Method.java:498)
[13:19:46][Step 4/5] 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
[13:19:46][Step 4/5] 	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:523)
[13:19:46][Step 4/5] 	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:224)
[13:19:46][Step 4/5] 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:599)
[13:19:46][Step 4/5] 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
[13:19:46][Step 4/5] 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
[13:19:46][Step 4/5] 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
[13:19:46][Step 4/5] 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
[13:19:46][Step 4/5] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[13:19:46][Step 4/5] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[13:19:46][Step 4/5] 	at java.lang.Thread.run(Thread.java:745)
```

**Comment by bonigarcia** [comment]
Please use the latest version of WebDriverManager, i.e. 2.2.1. In theory this kind of problems are solved in the latest versions.

**Comment by jossjacobo** [comment]
A bit more info:
- Issue only happens when running builds in parallel (Using TestNG)
- Updating to the latest wdm version didn't help
- Reverting to an older version of the ChromeDriver "fixed" it
