### ISSUE TITLE
downloadAndExtract method do NOT check ability to write to folder

### ISSUE THREAD

**Issue by AlexanderPoleschuk** [bonigarcia/webdrivermanager#210]
Method **_private Optional<File> downloadAndExtract(URL url, File targetFile_**) do not check the ability to write to targetFolder, therefore when CustomTarget path is used and downloader is not able to extract file to folder -> it fails to use the driver from cache.

Steps to reproduce: CustomTargetTest.java.
On windows 10 x64 when creating a temp folder the following path is used:
Using temporal folder C:\Users\ALEXAN~1\AppData\Local\Temp\1725078330761741131

Later then when **_downloadAndExtract_** method is called, it fails to write to folder and fails with smth like:

_2018-05-18 14:43:39 [main] ERROR i.g.bonigarcia.wdm.WebDriverManager -- There was an error managing chromedriver  (Parameter 'directory' is not a directory: C:\Users\ALEXANC:\Users\AlexanderPoleschuk1\AppData\Local\Temp\1725078330761741131)
java.lang.IllegalArgumentException: Parameter 'directory' is not a directory: C:\Users\ALEXANC:\Users\AlexanderPoleschuk1\AppData\Local\Temp\1725078330761741131
	at org.apache.commons.io.FileUtils.validateListFilesParameters(FileUtils.java:541)
	at org.apache.commons.io.FileUtils.listFiles(FileUtils.java:517)
	at org.apache.commons.io.FileUtils.listFiles(FileUtils.java:689)
	at io.github.bonigarcia.wdm.WebDriverManager.getFilesInCache(WebDriverManager.java:607)
	at io.github.bonigarcia.wdm.WebDriverManager.forceCache(WebDriverManager.java:565)
	at io.github.bonigarcia.wdm.WebDriverManager.handleCache(WebDriverManager.java:552)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:439)
	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:480)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:466)
	at io.github.bonigarcia.wdm.WebDriverManager.setup(WebDriverManager.java:203)_

```
private Optional<File> downloadAndExtract(URL url, File targetFile)
            throws IOException, InterruptedException {
        log.info("Downloading {}", url);
        File targetFolder = targetFile.getParentFile();
        File tempDir = createTempDirectory("").toFile();
        File temporaryFile = new File(tempDir, targetFile.getName());

        log.trace("Target folder {} ... using temporal file {}", targetFolder,
                temporaryFile);
        copyInputStreamToFile(httpClient.execute(httpClient.createHttpGet(url))
                .getEntity().getContent(), temporaryFile);

        File extractedFile = extract(temporaryFile);
        File resultingBinary = new File(targetFolder, extractedFile.getName());
        boolean binaryExists = resultingBinary.exists();

        if (!binaryExists || config().isOverride()) {
            if (binaryExists) {
                log.info("Overriding former binary {}", resultingBinary);
                deleteFile(resultingBinary);
            }
            moveFileToDirectory(extractedFile, targetFolder, true);
        }
        if (!config().isExecutable(resultingBinary)) {
            setFileExecutable(resultingBinary);
        }
        deleteFolder(tempDir);
        log.trace("Binary driver after extraction {}", resultingBinary);

        return of(resultingBinary);
    }

```

The solution is to add smth like 
```
if (!targetFolder.canWrite()) {
   //throw exception here;
}
```
or more appropriate handling before moveFileToDirectory(extractedFile, targetFolder, true); is called.

**Comment by AlexanderPoleschuk** [comment]
Created  https://github.com/bonigarcia/webdrivermanager/pull/212 for it

**Comment by AlexanderPoleschuk** [comment]
The reason was in incorrect method getTargetPath() in Config.java for windows platforms
