### ISSUE TITLE
Throws error attempting to use in AWS Lambda

### ISSUE THREAD

**Issue by BanjoFromCurlwaa** [bonigarcia/webdrivermanager#237]
Hi,
I am getting an error as per:
https://stackoverflow.com/questions/50602673/provide-chromedriver-exe-in-aws-lambda#

I am new to AWS Lambda, so using the webdriver manager might be something that is not really an option for this product but might be something fixable.

I am using eclipse to push the lambda function to AWS and invoke it. Error reads:

java.lang.IllegalArgumentException: Parameter 'directory' is not a directory: /home/sbx_user1062/.m2/repository/webdriver: io.github.bonigarcia.wdm.WebDriverManagerException
io.github.bonigarcia.wdm.WebDriverManagerException: java.lang.IllegalArgumentException: Parameter 'directory' is not a directory: /home/sbx_user1062/.m2/repository/webdriver
	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:471)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:454)
	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:468)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:454)
	at io.github.bonigarcia.wdm.WebDriverManager.setup(WebDriverManager.java:215)
	at au.com.nexiaem.webdrivertest.LambdaFunctionHandler.handleRequest(LambdaFunctionHandler.java:24)
	at au.com.nexiaem.webdrivertest.LambdaFunctionHandler.handleRequest(LambdaFunctionHandler.java:1)
Caused by: java.lang.IllegalArgumentException: Parameter 'directory' is not a directory: /home/sbx_user1062/.m2/repository/webdriver
	at org.apache.commons.io.FileUtils.validateListFilesParameters(FileUtils.java:541)
	at org.apache.commons.io.FileUtils.listFiles(FileUtils.java:517)
	at org.apache.commons.io.FileUtils.listFiles(FileUtils.java:689)
	at io.github.bonigarcia.wdm.WebDriverManager.getFilesInCache(WebDriverManager.java:613)
	at io.github.bonigarcia.wdm.WebDriverManager.getDriverFromCache(WebDriverManager.java:566)
	at io.github.bonigarcia.wdm.WebDriverManager.handleCache(WebDriverManager.java:554)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:428)
	... 5 more

END RequestId: 782c1167-9a13-11e8-aa52-5f7d06c81e1d
REPORT RequestId: 782c1167-9a13-11e8-aa52-5f7d06c81e1d	Duration: 1973.37 ms	Billed Duration: 2000 ms 	Memory Size: 3008 MB	Max Memory Used: 103 MB	

Code for the lambda request handler is as per below - I am creating the directory prior to the error being thrown so it it not the directoy not being there that is creating the issue as far as I can tell:

package au.com.nexiaem.webdrivertest;

import java.io.File;

import org.json.JSONObject;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;

import com.amazonaws.services.lambda.runtime.Context;
import com.amazonaws.services.lambda.runtime.RequestHandler;

import io.github.bonigarcia.wdm.WebDriverManager;
public class LambdaFunctionHandler implements RequestHandler<JSONObject, String> {

    @Override
    public String handleRequest(JSONObject input, Context context) {
        context.getLogger().log("Input: " + input.toString());    
        String username = System.getProperty("user.name");
        String directoryToMake ="/home/" + username + "/.m2/repository/webdriver";
        System.out.println(directoryToMake);
        File f = new File(directoryToMake);
        if(!f.exists()) f.mkdirs();
        WebDriverManager.chromedriver().setup();     
        ChromeOptions options = new ChromeOptions();
        String[] arguments = new String[1];
        arguments[0] = "--start-maximized";
        options.addArguments(arguments);
        WebDriver driver = new ChromeDriver();                      
        // TODO: implement your handler
        return "Hello from Lambda!";
    }

}

**Comment by bonigarcia** [comment]
It seems for some reason WebDriverManager is not able to store chromedriver in the default target path (`~/.m2/repository/webdriver`) in AWS Lambda. In any case, you can try to change the value of that path with the `targetPath` method, for instance using of the following alternatives:

```
WebDriverManager.chromedriver().targetPath("/tmp").setup();
WebDriverManager.chromedriver().targetPath(".").setup();
WebDriverManager.chromedriver().targetPath("target").setup();
```

**Comment by kbosesfly** [comment]
targetPath() is not available anymore. How do we run this in aws lambda ?

**Comment by redealrutvik** [comment]
@kbosesfly yo can use cachePath() method instead of targetPath() method. Hope this will helps you.

**Comment by aziz-lendsmart** [comment]
@bonigarcia could you please provide the equivalent of `WebDriverManager.chromedriver().targetPath("/tmp").setup();` but in python
