### ISSUE TITLE
Error finding chromedriver after download

### ISSUE THREAD

**Issue by lazycodeninja** [bonigarcia/webdrivermanager#243]
Previously successful tests failed today with the following error:
```
ERROR io.github.bonigarcia.wdm.WebDriverManager - There was an error managing chromedriver 70.0.3538.16 (Driver chromedriver not found (using temporal folder /var/folders/90/5_ghb4753sj738jzqtw67hl140n9y1/T/686579030133781197))
io.github.bonigarcia.wdm.WebDriverManagerException: Driver chromedriver not found (using temporal folder /var/folders/90/5_ghb4753sj738jzqtw67hl140n9y1/T/686579030133781197)
	at io.github.bonigarcia.wdm.WebDriverManager.postDownload(WebDriverManager.java:402)
	at io.github.bonigarcia.wdm.Downloader.extract(Downloader.java:194)
	at io.github.bonigarcia.wdm.Downloader.downloadAndExtract(Downloader.java:135)
	at io.github.bonigarcia.wdm.Downloader.download(Downloader.java:78)
```
The problem went away while I was investigating, but from what I could see the error was because the zip file was being extracted into a folder with the same name as the zip, i.e. the path was `/var/folders/.../chromedriver_mac64/chromedriver` instead of `/var/folders/.../chromedriver`.  The problem seemed to go away by itself after a couple of hours, so my guess is that Google updated the zip file and the dir is no longer in the zip (though I don't see a version number change, it's still 70.0.3538.16).

Would it be possible to make the logic in `WebDriverManager.postDownload()` more robust to handle this situation?  Otherwise we could see random failures that come and go (or we could lock the chromedriver version)

**Comment by lazycodeninja** [comment]
> Which version of WebDriverManager are you using? I check it in Windows, Mac, and Linux and I am not able to reproduce the problem.

Version 3.0.0.  I haven't been able to reproduce the error either since that time.

**Comment by jsolomonraja42** [comment]
I believe this is due to the versioning pattern google following now. Earlier the version of Chromedriver in the url (https://chromedriver.storage.googleapis.com/) was 2.9 and suddenly it gone to near 70 which I believe is the version of Chrome Browser and not a Chromedriver.

![image](https://user-images.githubusercontent.com/17875055/48755352-fac3ac80-ecba-11e8-9105-218d830efc1a.png)
