### ISSUE TITLE
WDM should not connect to github too often

### ISSUE THREAD

**Issue by asolntsev** [bonigarcia/webdrivermanager#249]
When file `versions.properties` does **not** contain record for a current browser version (like for latest `firefox62`), WebDriverManager connects to github **every time** I run tests. 

### Problem:
1. it's slow
2. sometimes github returns 403 error, causing my tests to fail (see stack trace below).

### Proposed solution:
WDM could understand that it recently checked for webdriver version. It already has the latest version in `~/.m2/repository`. No need to check it again.

P.S. stack trace with 403 error:

```java
io.github.bonigarcia.wdm.WebDriverManagerException: io.github.bonigarcia.wdm.WebDriverManagerException: A response error is detected: HTTP/1.1 403 Forbidden
	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:523)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:471)
	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:520)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:471)
	at io.github.bonigarcia.wdm.WebDriverManager.setup(WebDriverManager.java:229)
  ...
Caused by: io.github.bonigarcia.wdm.WebDriverManagerException: A response error is detected: HTTP/1.1 403 Forbidden
	at io.github.bonigarcia.wdm.HttpClient.execute(HttpClient.java:167)
	at io.github.bonigarcia.wdm.WebDriverManager.openGitHubConnection(WebDriverManager.java:881)
	at io.github.bonigarcia.wdm.WebDriverManager.getDriversFromGitHub(WebDriverManager.java:896)
	at io.github.bonigarcia.wdm.FirefoxDriverManager.getDrivers(FirefoxDriverManager.java:45)
	at io.github.bonigarcia.wdm.WebDriverManager.filterCandidateUrls(WebDriverManager.java:539)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:456)
	... 81 more
```

**Comment by bonigarcia** [comment]
Thanks for your ideas @asolntsev. I'm going to improve the performance of WebDriverManager in next version.

**Comment by bonigarcia** [comment]
WebDriverManager 3.1.0 is out. A relevant new feature of this new version is related with this issue. Now, resolved driver versions (e.g. chromedriver 2.44 for Chrome 71) as stored persistently as Java preferences. This resolution is valid during a given period of time in seconds called Time To Live (TTL) (something similar to DNS resolution). By default this value is 3600 (i.e. 1 hour). As usual, this value is configurable.
