### ISSUE TITLE
WebDriverManagerException: A response error is detected: HTTP/1.1 403 Forbidden

### ISSUE THREAD

**Issue by Alphyra** [bonigarcia/webdrivermanager#263]
Hello,

I faced with error when run test:

io.github.bonigarcia.wdm.WebDriverManagerException: io.github.bonigarcia.wdm.WebDriverManagerException: A response error is detected: HTTP/1.1 403 Forbidden

Driver was not run. Can the reason be in my IP?

Thank you.

**Comment by gdiegel** [comment]
I'm currently having the same problem:

```
...
Caused by: io.github.bonigarcia.wdm.WebDriverManagerException: io.github.bonigarcia.wdm.WebDriverManagerException: A response error is detected: HTTP/1.1 403 Forbidden
	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:523)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:471)
	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:520)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:471)
	at io.github.bonigarcia.wdm.WebDriverManager.setup(WebDriverManager.java:229)
	at script1539864441533641382241.run_closure1(script1539864441533641382241.groovy:10)
	at script1539864441533641382241.run_closure1(script1539864441533641382241.groovy)
	at geb.driver.CallbackDriverFactory.getDriver(CallbackDriverFactory.groovy:29)
	... 17 more
Caused by: io.github.bonigarcia.wdm.WebDriverManagerException: A response error is detected: HTTP/1.1 403 Forbidden
	at io.github.bonigarcia.wdm.HttpClient.execute(HttpClient.java:167)
	at io.github.bonigarcia.wdm.WebDriverManager.getDriversFromXml(WebDriverManager.java:828)
	at io.github.bonigarcia.wdm.ChromeDriverManager.getDrivers(ChromeDriverManager.java:50)
	at io.github.bonigarcia.wdm.WebDriverManager.filterCandidateUrls(WebDriverManager.java:539)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:456)
	... 23 more

```

**Comment by szorlowski** [comment]
Same for me on OperaDriver. Works well on chrome

**Comment by sandeepnegi1996** [comment]
Hi @Alphyra 

Are you inside the **corporate environment** in that case you have to configure the webdrivermanager with the proper configuration,


```
WebDriverManager.chromedriver().arch32().browserVersion("81.0.4044.138").proxy(proxyUrl)
						.proxyUser(userId).proxyPass(userPass).setup();
```

proxyUrl--> is the url for proxy for your company
userid--> in my case is my windows id for the company
password --> in my case is the password I use to login to windows

Hope this can give you some idea :)

**Comment by kriegaex** [comment]
> See [Known Issues -> HTTP response code 403](https://github.com/bonigarcia/webdrivermanager#http-response-code-403).

The old link is stale. The current one is:
https://github.com/bonigarcia/webdrivermanager/blob/master/src/doc/asciidoc/index.adoc#http-response-code-403

**Comment by adrian-herscu** [comment]
Any suggestion about how configure the GITHUB_TOKEN environment variable?
Tried to add it to mine as a secret but GitHub refuses to accept variables beginning with GITHUB_.
