### ISSUE TITLE
Arch Linux Chrome version is not detected

### ISSUE THREAD

**Issue by dstoianov** [bonigarcia/webdrivermanager#269]
### Description

For detecting on `Arch Linux` version of Chrome Browser we need to use other command like this
```sh
$ google-chrome-stable --version
Google Chrome 70.0.3538.77 
```

Currently we have an error on `Arch Linux`
### Stack Trace:

```Java
[Test worker] WARN io.github.bonigarcia.wdm.Shell - There was an error executin commannd [google-chrome, --version] on the shell
    java.io.IOException: Cannot run program "google-chrome": error=2, No such file or directory
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at io.github.bonigarcia.wdm.Shell.runAndWaitNoLog(Shell.java:59)
        at io.github.bonigarcia.wdm.Shell.runAndWaitArray(Shell.java:50)
        at io.github.bonigarcia.wdm.Shell.runAndWait(Shell.java:44)
        at io.github.bonigarcia.wdm.WebDriverManager.getDefaultBrowserVersion(WebDriverManager.java:969)
        at io.github.bonigarcia.wdm.ChromeDriverManager.getBrowserVersion(ChromeDriverManager.java:68)
        at io.github.bonigarcia.wdm.WebDriverManager.getVersionForInstalledBrowser(WebDriverManager.java:477)
        at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:430)
        at io.github.bonigarcia.wdm.WebDriverManager.setup(WebDriverManager.java:229)
        at com.codeborne.selenide.webdriver.WebDriverBinaryManager.lambda$setupChrome$0(WebDriverBinaryManager.java:30)
        at com.codeborne.selenide.webdriver.WebDriverBinaryManager.cacheMeIfYouCan(WebDriverBinaryManager.java:84)
        at com.codeborne.selenide.webdriver.WebDriverBinaryManager.setupChrome(WebDriverBinaryManager.java:29)
        at com.codeborne.selenide.webdriver.WebDriverBinaryManager.setupBinaryPath(WebDriverBinaryManager.java:20)
        at com.codeborne.selenide.webdriver.WebDriverFactory.createWebDriver(WebDriverFactory.java:49)
        at com.codeborne.selenide.drivercommands.CreateDriverCommand.createDriver(CreateDriverCommand.java:38)
        at com.codeborne.selenide.drivercommands.LazyDriver.createDriver(LazyDriver.java:93)
        at com.codeborne.selenide.drivercommands.LazyDriver.getAndCheckWebDriver(LazyDriver.java:87)
        at com.codeborne.selenide.SelenideDriver.getAndCheckWebDriver(SelenideDriver.java:143)
        at com.codeborne.selenide.drivercommands.Navigator.navigateTo(Navigator.java:61)
        at com.codeborne.selenide.drivercommands.Navigator.open(Navigator.java:24)
        at com.codeborne.selenide.SelenideDriver.open(SelenideDriver.java:59)
        at SelenideTests.openTest(SelenideTests.java:35)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:515)
        at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:115)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:171)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:167)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:114)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:59)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:105)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:95)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:71)
        at java.util.ArrayList.forEach(ArrayList.java:1249)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:110)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:95)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:71)
        at java.util.ArrayList.forEach(ArrayList.java:1249)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:110)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:95)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:71)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
        at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
        at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:170)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:154)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:90)
        at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:92)
        at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$100(JUnitPlatformTestClassProcessor.java:77)
        at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:73)
        at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
        at com.sun.proxy.$Proxy2.stop(Unknown Source)
        at org.gradle.api.internal.tasks.testing.worker.TestWorker.stop(TestWorker.java:131)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:155)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:137)
        at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
        at java.lang.Thread.run(Thread.java:748)
    Caused by: java.io.IOException: error=2, No such file or directory
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
        at java.lang.ProcessImpl.start(ProcessImpl.java:134)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 83 more
    [Test worker] INFO io.github.bonigarcia.wdm.WebDriverManager - Reading https://chromedriver.storage.googleapis.com/ to seek chromedriver
    [Test worker] INFO io.github.bonigarcia.wdm.WebDriverManager - Latest version of chromedriver is 71.0.3578.33
    [Test worker] INFO io.github.bonigarcia.wdm.Downloader - Using binary driver previously downloaded
    [Test worker] INFO io.github.bonigarcia.wdm.WebDriverManager - Exporting webdriver.chrome.driver as /home/mama/.m2/repository/webdriver/chromedriver/linux64/71.0.3578.33/chromedriver
    Starting ChromeDriver 71.0.3578.33 (269aa0e3f0db08097f0fe231c7e6be200b6939f7) on port 22157
    Only local connections are allowed.
```

**Comment by bonigarcia** [comment]
Is it possible to find out if Arch Linux is used? I mean, from Java code. If so, I will be happy to support it in the next version of WebDriverManager (i.e. try to run `google-chrome-stable` instead of `google-chrome` in Arch Linux machines).

**Comment by patryksandomierski** [comment]
Maybe some kind of solution would be add another parameter to WebDriverManager API like `browserBinaryPath(String)`

**Comment by bonigarcia** [comment]
Thanks for the ideas @patryksandomierski. The API method `browserPath` will be available on next version.

**Comment by blacelle** [comment]
Where is gone browserPath in 4.4.0?

**Comment by bonigarcia** [comment]
@blacelle The commands used to detect browser versions has been moved to a separate file ([commands.properties](https://github.com/bonigarcia/webdrivermanager/blob/master/src/main/resources/commands.properties)) in version 4.4.0. Due to this, the method `browserPath()` has been replaced by `browserVersionDetectionCommand()` (see [changelog](https://github.com/bonigarcia/webdrivermanager/blob/master/CHANGELOG.md)). You can find an example of the usage of the new method in this [test](https://github.com/bonigarcia/webdrivermanager/blob/master/src/test/java/io/github/bonigarcia/wdm/test/chrome/ChromeBetaTest.java).
