### ISSUE TITLE
Firefox and ie not opening with webdrivermanger 3.0      io.github.bonigarcia.wdm.WebDriverManagerException: java.net.UnknownHostException

### ISSUE THREAD

**Issue by unnikg27** [bonigarcia/webdrivermanager#272]
Getting below exception while trying to open firefox and ie

FAILED CONFIGURATION: @BeforeClass beforeClass(org.testng.TestRunner@5170bcf4)
io.github.bonigarcia.wdm.WebDriverManagerException: java.net.UnknownHostException: csc-chd-mdn-1-cgen-pri
	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:523)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:471)
	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:520)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:471)
	at io.github.bonigarcia.wdm.WebDriverManager.setup(WebDriverManager.java:229)

**Comment by unnikg27** [comment]
@bonigarcia . Kindly look into this .

**Comment by unnikg27** [comment]
Sorry for the trouble. Looks like a maven issue. Firefoax and ie drivers were not getting downloaded.
Issue is not valid.
