### ISSUE TITLE
405 when trying to setup a chromeDriver

### ISSUE THREAD

**Issue by Alexandr-Calcifer** [bonigarcia/webdrivermanager#273]
Error:

io.github.bonigarcia.wdm.WebDriverManagerException: io.github.bonigarcia.wdm.WebDriverManagerException: A response error is detected: HTTP/1.1 405 Method Not Allowed

	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:471)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:454)
	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:468)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:454)
	at io.github.bonigarcia.wdm.WebDriverManager.setup(WebDriverManager.java:215)

The code itself looks like this:

WebDriverManager.
    .chromedriver()
    .proxy(proxyHost)
    .proxyUser(proxyUserName)
    .proxyPass(.proxyPassword)
    .setup();

**Comment by bonigarcia** [comment]
I'm going to change a bit the behavior of the connectivity of WebDriverManager in the next version. Please stay tuned.

**Comment by bonigarcia** [comment]
WebDriverManager 3.1.0 has been released. Please try the new version and confirm if the issue is solved.

**Comment by bonigarcia** [comment]
Please use WebDriverManager 3.1.1 instead (version 3.1.0 had a bug).
