### ISSUE TITLE
Warning for Firefox 63

### ISSUE THREAD

**Issue by jmaister** [bonigarcia/webdrivermanager#277]
[WARNING] The driver version for Mozilla Firefox 63 is unknown ... trying with latest
[INFO] Reading https://api.github.com/repos/mozilla/geckodriver/releases to seek geckodriver
[INFO] Latest version of geckodriver is 0.23.0
[INFO] Using binary driver previously downloaded
[INFO] Exporting webdriver.gecko.driver as /home/jordi/.m2/repository/webdriver/geckodriver/linux64/0.23.0/geckodriver

**Comment by arunaousula9421** [comment]
Saw similar issue. Unable to instantiate Firefox v63.0.3
```
[pool-1-thread-1] WARN io.github.bonigarcia.wdm.WebDriverManager - The driver version for Mozilla Firefox 45 is unknown ... trying with latest
[pool-1-thread-1] INFO io.github.bonigarcia.wdm.WebDriverManager - Reading https://api.github.com/repos/mozilla/geckodriver/releases to seek geckodriver
[pool-1-thread-1] INFO io.github.bonigarcia.wdm.WebDriverManager - Latest version of geckodriver is 0.23.0
[pool-1-thread-1] INFO io.github.bonigarcia.wdm.Downloader - Using binary driver previously downloaded
[pool-1-thread-1] INFO io.github.bonigarcia.wdm.WebDriverManager - Exporting webdriver.gecko.driver as C:\Users\arunaousula\.m2\repository\webdriver\geckodriver\win64\0.23.0\geckodriver.exe
[pool-1-thread-1] ERROR net.thucydides.core.webdriver.WebDriverFacade - FAILED TO CREATE NEW WEBDRIVER_DRIVER INSTANCE class net.thucydides.core.webdriver.ProvidedDriver: Could not instantiate new WebDriver instance of type class net.thucydides.core.webdriver.ProvidedDriver (Could not instantiate the custom webdriver provider of type mydriver
net.thucydides.core.webdriver.UnsupportedDriverException: Could not instantiate new WebDriver instance of type class net.thucydides.core.webdriver.ProvidedDriver (Could not instantiate the custom webdriver provider of type mydriver
	at net.thucydides.core.webdriver.WebDriverFactory.newWebdriverInstance(WebDriverFactory.java:136)
	at net.thucydides.core.webdriver.WebDriverFacade.newDriverInstance(WebDriverFacade.java:149)
	at net.thucydides.core.webdriver.WebDriverFacade.newProxyDriver(WebDriverFacade.java:140)
	at net.thucydides.core.webdriver.WebDriverFacade.getProxiedDriver(WebDriverFacade.java:110)
	at net.thucydides.core.webdriver.WebDriverFacade.manage(WebDriverFacade.java:370)
	at com.rxp.realcontrol.serenity.RegressionBase.getDriver(RegressionBase.java:90)
	at com.rxp.realcontrol.serenity.pages.LoginPage.openingLoginPage(LoginPage.java:77)
	at com.rxp.realcontrol.serenity.steps.LoginSteps.goingToRC21LoginPage(LoginSteps.java:31)
	at com.rxp.realcontrol.serenity.steps.LoginSteps$$EnhancerByCGLIB$$220b195e.CGLIB$goingToRC21LoginPage$0(<generated>)
	at com.rxp.realcontrol.serenity.steps.LoginSteps$$EnhancerByCGLIB$$220b195e$$FastClassByCGLIB$$60869882.invoke(<generated>)
	at net.sf.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228
)```

**Comment by bonigarcia** [comment]
This was simply a warning. In any case it has been solved.
