### ISSUE TITLE
Unable to determine Firefox version when running in headless mode

### ISSUE THREAD

**Issue by andreasf** [bonigarcia/webdrivermanager#282]
WDM fails to determine Firefox version if headless mode is enabled.

Steps to reproduce:
1. Set the environment variable `MOZ_HEADLESS` to enable headless mode. I prefer using this environment variable to trigger headless mode: it allows enabling or disabling headless depending on the runtime environment, e.g. developer workstation vs. CI system.
2. Call `WebDriverManager.firefoxdriver().setup()` in a test

Expected outcome:
WDM sets up geckodriver

Actual outcome:
WDM is unable to determine Firefox's version and crashes with the following exception:

```
$ MOZ_HEADLESS=1 ./gradlew test
    Version output according to WDM helper: *** You are running in headless mode.
    Mozilla Firefox 63.0.3

com.snoutify.snoutify.acceptance.LoginTest > classMethod FAILED
    io.github.bonigarcia.wdm.WebDriverManagerException: java.lang.StringIndexOutOfBoundsException: String index out of range: -17
        at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:523)
        at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:471)
        at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:520)
        at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:471)
        at io.github.bonigarcia.wdm.WebDriverManager.setup(WebDriverManager.java:229)
        at com.snoutify.snoutify.acceptance.LoginTest$Companion.setup(LoginTest.kt:38)
        at com.snoutify.snoutify.acceptance.LoginTest.setup(LoginTest.kt)
        Caused by:
        java.lang.StringIndexOutOfBoundsException: String index out of range: -17
            at java.lang.String.substring(String.java:1967)
            at io.github.bonigarcia.wdm.Shell.getVersionFromPosixOutput(Shell.java:80)
            at io.github.bonigarcia.wdm.WebDriverManager.getDefaultBrowserVersion(WebDriverManager.java:971)
            at io.github.bonigarcia.wdm.FirefoxDriverManager.getBrowserVersion(FirefoxDriverManager.java:80)
            at io.github.bonigarcia.wdm.WebDriverManager.getVersionForInstalledBrowser(WebDriverManager.java:477)
            at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:430)
            ... 5 more
```

**Comment by bonigarcia** [comment]
@andreasf Thank you for reporting and contributing. I am going to include the following lines of your PR in the master:

```
            Process process = new ProcessBuilder(command)
                    .redirectErrorStream(false).start();
```

I'm not merging the PR since I have made another changes in the Shell class and not it has conflicts, sorry.

**Comment by andreasf** [comment]
Thanks
