### ISSUE TITLE
POM dependency included but unable to use/access in IntelliJ IDEA

### ISSUE THREAD

**Issue by SagarBobade** [bonigarcia/webdrivermanager#284]
@bonigarcia 
In IntelliJ IDEA

![webdrivermanager issue](https://user-images.githubusercontent.com/24943038/49694448-33ff8600-fbb0-11e8-8fc8-85783c9ce661.png)

POM entry of version 3.1.0 is included but facing problem as per attached screenshot.

**Comment by SagarBobade** [comment]
@bonigarcia 
In Eclipse IDE,  following exception is getting -

**Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
	at io.github.bonigarcia.wdm.WebDriverManager.<clinit>(WebDriverManager.java:92)
	at Test.main(Test.java:11)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 2 more**

`import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;

import io.github.bonigarcia.wdm.WebDriverManager;

public class Test {
	public static void main(String[] args) {

		WebDriverManager.firefoxdriver().setup();
		WebDriver driver = new FirefoxDriver();
		driver.get("https://github.com/SagarBobade");			
	}
}`

**Comment by SagarBobade** [comment]
Problem was with my maven, please do provide jar file also for WebDriverManager library.

Thanks.
