### ISSUE TITLE
StringIndexOutOfBoundsException caused by geckodriver

### ISSUE THREAD

**Issue by allaambrozhaktest** [bonigarcia/webdrivermanager#286]
```
2018-12-10T17:29:30,373 [main] io.github.bonigarcia.wdm.WebDriverManager                                         WARN  -  There was an error managing geckodriver  (String index out of range: -17) ... trying again forcing to use cache
java.lang.StringIndexOutOfBoundsException: String index out of range: -17
	at java.lang.String.substring(String.java:1967) ~[?:1.8.0_144]
	at io.github.bonigarcia.wdm.Shell.getVersionFromPosixOutput(Shell.java:80) ~[webdrivermanager-3.0.0.jar:?]
	at io.github.bonigarcia.wdm.WebDriverManager.getDefaultBrowserVersion(WebDriverManager.java:971) ~[webdrivermanager-3.0.0.jar:?]
	at io.github.bonigarcia.wdm.FirefoxDriverManager.getBrowserVersion(FirefoxDriverManager.java:80) ~[webdrivermanager-3.0.0.jar:?]
	at io.github.bonigarcia.wdm.WebDriverManager.getVersionForInstalledBrowser(WebDriverManager.java:477) [webdrivermanager-3.0.0.jar:?]
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:430) [webdrivermanager-3.0.0.jar:?]
	at io.github.bonigarcia.wdm.WebDriverManager.setup(WebDriverManager.java:229) [webdrivermanager-3.0.0.jar:?]
	
```

**Comment by allaambrozhaktest** [comment]
@bonigarcia Could you please check what the problem could be? Seems that it was smth similar https://github.com/bonigarcia/webdrivermanager/issues/43

**Comment by pierrepinon** [comment]
@allaambrozhaktest can you provide your code to help you ?

**Comment by allaambrozhaktest** [comment]
Actually after update to newest version it wasn't reproduced. Thanks for response. I'll close it
