### ISSUE TITLE
A response error is detected: HTTP/1.1 403 Forbidden : Getting 403 error

### ISSUE THREAD

**Issue by pavankumarmt** [bonigarcia/webdrivermanager#295]
Below is the stack trace getting logged on the console on initiating the RemoteWebDriver.

14:34:21.955 [main] ERROR io.github.bonigarcia.wdm.HttpClient - A response error is detected: HTTP/1.1 403 Forbidden
14:34:21.972 [main] WARN  i.g.bonigarcia.wdm.WebDriverManager - There was an error managing wires, geckodriver  (A response error is detected: HTTP/1.1 403 Forbidden) ... trying again forcing to use cache
io.github.bonigarcia.wdm.WebDriverManagerException: A response error is detected: HTTP/1.1 403 Forbidden
	at io.github.bonigarcia.wdm.HttpClient.execute(HttpClient.java:171) ~[webdrivermanager-2.2.1.jar:na]
	at io.github.bonigarcia.wdm.WebDriverManager.openGitHubConnection(WebDriverManager.java:835) [webdrivermanager-2.2.1.jar:na]
	at io.github.bonigarcia.wdm.WebDriverManager.getDriversFromGitHub(WebDriverManager.java:851) [webdrivermanager-2.2.1.jar:na]
	at io.github.bonigarcia.wdm.FirefoxDriverManager.getDrivers(FirefoxDriverManager.java:50) ~[webdrivermanager-2.2.1.jar:na]
	at io.github.bonigarcia.wdm.WebDriverManager.filterCandidateUrls(WebDriverManager.java:492) [webdrivermanager-2.2.1.jar:na]
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:442) [webdrivermanager-2.2.1.jar:na]
	at io.github.bonigarcia.wdm.WebDriverManager.setup(WebDriverManager.java:219) [webdrivermanager-2.2.1.jar:na]
	at com.prosperworks.selenium.support.WebDriverServiceManager.setupDrivers(WebDriverServiceManager.java:83) [test-classes/:na]
	at com.prosperworks.selenium.tests.web.abstracts.AbstractTests.setupSuite(AbstractTests.java:99) [test-classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_151]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_151]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124) [testng-6.14.2.jar:na]
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59) [testng-6.14.2.jar:na]
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455) [testng-6.14.2.jar:na]
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222) [testng-6.14.2.jar:na]
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142) [testng-6.14.2.jar:na]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401) [testng-6.14.2.jar:na]
	at org.testng.SuiteRunner.run(SuiteRunner.java:364) [testng-6.14.2.jar:na]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52) [testng-6.14.2.jar:na]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84) [testng-6.14.2.jar:na]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208) [testng-6.14.2.jar:na]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137) [testng-6.14.2.jar:na]
	at org.testng.TestNG.runSuites(TestNG.java:1049) [testng-6.14.2.jar:na]
	at org.testng.TestNG.run(TestNG.java:1017) [testng-6.14.2.jar:na]
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72) [testng-plugin.jar:na]
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123) [testng-plugin.jar:na]

**Comment by bonigarcia** [comment]
See [known issues](value).
