### ISSUE TITLE
There was an error managing chromedriver 

### ISSUE THREAD

**Issue by tugcebaskan** [bonigarcia/webdrivermanager#303]
```
[main] INFO io.github.bonigarcia.wdm.WebDriverManager - Reading https://chromedriver.storage.googleapis.com/ to seek chromedriver
[main] ERROR io.github.bonigarcia.wdm.WebDriverManager - chromedriver 2.45 for LINUX64 not found in https://chromedriver.storage.googleapis.com/
[main] WARN io.github.bonigarcia.wdm.WebDriverManager - There was an error managing chromedriver 2.45 (chromedriver 2.45 for LINUX64 not found in https://chromedriver.storage.googleapis.com/) ... trying again forcing to use cache
io.github.bonigarcia.wdm.WebDriverManagerException: chromedriver 2.45 for LINUX64 not found in https://chromedriver.storage.googleapis.com/
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:514)
	at io.github.bonigarcia.wdm.WebDriverManager.setup(WebDriverManager.java:251)
	at com.trendyol.uat.models.browsertypes.Chrome.initInLocal(Chrome.java:46)
```

**Comment by bonigarcia** [comment]
I've just tried and it seems to continue working properly.

Which version of WebDriverManager are you using? In general, latest version is always recommended (3.2.0 at the time of this writing).
