### ISSUE TITLE
how to set proxy properly?

### ISSUE THREAD

**Issue by Basha1535** [bonigarcia/webdrivermanager#305]
Hi Bonigarcia ,

 I've created HTTP environmental variables and configured proxy details as below in my code:

WebDriverManager.chromedriver().proxyUser(System.getenv("HTTPS_PROXY_USER"));
WebDriverManager.chromedriver().proxyPass(System.getenv("HTTPS_PROXY_PASS"));
WebDriverManager.chromedriver().proxy(System.getenv("HTTPS_PROXY")).setup();

Please find the exception details and help me to resolve the issue. Thanks in advance!!! :)

Exception:
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Feb 05, 2019 6:47:05 PM java.util.prefs.WindowsPreferences <init>
WARNING: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5.
Feb 05, 2019 6:47:06 PM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request to {s}->https://chromedriver.storage.googleapis.com:443: Connection reset
Feb 05, 2019 6:47:06 PM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {s}->https://chromedriver.storage.googleapis.com:443
Feb 05, 2019 6:47:06 PM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request to {s}->https://chromedriver.storage.googleapis.com:443: Connection reset
Feb 05, 2019 6:47:06 PM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {s}->https://chromedriver.storage.googleapis.com:443
Feb 05, 2019 6:47:06 PM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request to {s}->https://chromedriver.storage.googleapis.com:443: Connection reset
Feb 05, 2019 6:47:06 PM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {s}->https://chromedriver.storage.googleapis.com:443
Feb 05, 2019 6:47:06 PM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request to {s}->https://chromedriver.storage.googleapis.com:443: Connection reset
Feb 05, 2019 6:47:06 PM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {s}->https://chromedriver.storage.googleapis.com:443
Feb 05, 2019 6:47:06 PM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request to {s}->https://chromedriver.storage.googleapis.com:443: Connection reset
Feb 05, 2019 6:47:06 PM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {s}->https://chromedriver.storage.googleapis.com:443
Feb 05, 2019 6:47:06 PM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request to {s}->https://chromedriver.storage.googleapis.com:443: Connection reset
Feb 05, 2019 6:47:06 PM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {s}->https://chromedriver.storage.googleapis.com:443
Exception in thread "main" io.github.bonigarcia.wdm.WebDriverManagerException: java.net.SocketException: Connection reset
	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:684)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:521)
	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:681)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:521)
	at io.github.bonigarcia.wdm.WebDriverManager.setup(WebDriverManager.java:251)
	at test.wdm.sample.TestScript1.main(TestScript1.java:16)
Caused by: java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:210)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:983)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:396)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:355)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:373)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:394)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at io.github.bonigarcia.wdm.HttpClient.execute(HttpClient.java:159)
	at io.github.bonigarcia.wdm.WebDriverManager.getDriversFromXml(WebDriverManager.java:996)
	at io.github.bonigarcia.wdm.ChromeDriverManager.getDrivers(ChromeDriverManager.java:81)
	at io.github.bonigarcia.wdm.WebDriverManager.filterCandidateUrls(WebDriverManager.java:700)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:506)
	... 4 more

**Comment by bonigarcia** [comment]
These lines are redundant:

```
WebDriverManager.chromedriver().proxyUser(System.getenv("HTTPS_PROXY_USER"));
WebDriverManager.chromedriver().proxyPass(System.getenv("HTTPS_PROXY_PASS"));
WebDriverManager.chromedriver().proxy(System.getenv("HTTPS_PROXY")).setup();
```

Since, if the envs `HTTPS_PROXY_USER`, `HTTPS_PROXY_PASS`, and `HTTPS_PROXY` exist, they are read by WebDriverManager out of the box. The question is: What is the value of that envs in your host? Is they are empty, you should find out your proxy setup and configure it as follows:

```
WebDriverManager.chromedriver().proxyUser("username").proxyPass("password").proxy("my.http.proxy:1234").setup();
```
... or:

```
WebDriverManager.chromedriver().proxy("username:password@my.http.proxy:1234").setup();
```

**Comment by sandeepnegi1996** [comment]
Hi @Basha1535  

Can you check your eclipse setting for the proxy --> Windows --> preference --> network --> here you need to configure the proxy.

I am inside the corporate network, I have to configure proxy host , port number ,user id and password. **Password with special character** needs to be converted using UTF 8 encoding 

like in my password "@" is changed to %40, Let me know if you require the complete settings.

**Comment by matheusm1789** [comment]
@bonigarcia could you help me, please?
The connection timeout error is returned when I try to run the following test:

@Test
public void run_testing(){
    WebDriverManager.chromedriver().setup();
    WebDriver driver = new ChromeDriver();
    driver.get("http://www.google.com.br");
}

**io.github.bonigarcia.wdm.WebDriverManagerException: org.apache.http.conn.HttpHostConnectException: Connect to chromedriver.storage.googleapis.com:443**

My machine is mac and my proxy is set using the **Proxy Auto-Configuration (PAC)**
