### ISSUE TITLE
ConnectException thrown while creating firefox driver instance

### ISSUE THREAD

**Issue by sandeep-singh-79** [bonigarcia/webdrivermanager#306]
I am currently getting the below error log while creating a firefox instance:
org.openqa.selenium.WebDriverException: java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:15379
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'xxxxxxxxxxxxx', ip: 'xxx.xxx.xxx.xxx', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_181'
Driver info: driver.version: LocalDriver
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:92)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:147)
	at com.mckinsey.driver.LocalDriver.createDriver(LocalDriver.java:50)
	at com.mckinsey.driver.WebDriverFactory.getLocalDriverInstance(WebDriverFactory.java:69)
	at com.mckinsey.driver.WebDriverFactory.lambda$getDriver$0(WebDriverFactory.java:45)
	at java.lang.ThreadLocal$SuppliedThreadLocal.initialValue(ThreadLocal.java:284)
	at java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:180)
	at java.lang.ThreadLocal.get(ThreadLocal.java:170)
	at com.mckinsey.driver.WebDriverFactory.getDriver(WebDriverFactory.java:62)
	at com.mckinsey.cucumber.base.RunCukesTest.launch_browser(RunCukesTest.java:69)
	at com.mckinsey.cucumber.base.RunCukesTest.setup(RunCukesTest.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:168)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:105)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
Caused by: java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:15379
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:247)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:165)
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:257)
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
	at okhttp3.RealCall.execute(RealCall.java:77)
	at org.openqa.selenium.remote.internal.OkHttpClient.execute(OkHttpClient.java:103)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:105)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:74)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	... 38 more
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at okhttp3.internal.platform.Platform.connectSocket(Platform.java:129)
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:245)
	... 60 more

As can be seen from the log statements below, the driver file is downloaded and then exported to the appropriate folder:
18:05:00.700 [main] INFO  c.m.cucumber.base.RunCukesTest - Driver LOCAL created for browser FIREFOX
18:05:01.980 [main] INFO  i.g.bonigarcia.wdm.WebDriverManager - Reading https://api.github.com/repos/mozilla/geckodriver/releases to seek geckodriver
18:05:06.039 [main] INFO  i.g.bonigarcia.wdm.WebDriverManager - Latest version of geckodriver is 0.24.0
18:05:06.078 [main] INFO  io.github.bonigarcia.wdm.Downloader - Using binary driver previously downloaded
18:05:06.079 [main] INFO  i.g.bonigarcia.wdm.WebDriverManager - Exporting webdriver.gecko.driver as C:\Users\Sandeep Singh-GGN\.m2\repository\webdriver\geckodriver\win64\0.24.0\geckodriver.exe

I see the same happening during the unit test run of webdrivermanger in FirefoxTest class.

My code for geckodriver instantiation is:
else if(browser.contains("firefox") || browser.contains("ff")) {
                WebDriverManager.firefoxdriver().setup();
                FirefoxOptions options = new FirefoxOptions();
                options.addArguments("private");
                options.setLogLevel(FirefoxDriverLogLevel.TRACE);
                if (System.getProperty("headless", config.getProperty("headless")).equalsIgnoreCase("true")) {
                    options.addArguments("--headless");
                }
                //options.merge(sslError);
                driver = new FirefoxDriver(options);
}

I also tried to set the 'webdriver.gecko.driver' System property to the geckodriver.exe downloaded separately. And, that works fine. PFB the log of the geckodriver to back that up:
1549954603770	mozrunner::runner	INFO	Running command: "C:\\Program Files\\Mozilla Firefox\\firefox.exe" "-marionette" "private" "width 1920" "height 1080" "headless" "-foreground" "-no-remote" "-profile" "C:\\Users\\SANDEE~1\\AppData\\Local\\Temp\\rust_mozprofile.AEKzRSx9Om42"
1549954603909	geckodriver::marionette	DEBUG	Waiting 60s to connect to browser on 127.0.0.1:60465
1549954606887	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid host permission: resource://pdf.js/
1549954606887	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid host permission: about:reader*
1549954607124	Marionette	TRACE	Received observer notification profile-after-change
1549954607263	Marionette	TRACE	Received observer notification toplevel-window-ready
1549954607334	Marionette	TRACE	Received observer notification command-line-startup
1549954607335	Marionette	TRACE	Received observer notification nsPref:changed
1549954607336	Marionette	DEBUG	Init aborted (running=false, enabled=true, finalUIStartup=false)
1549954607642	Marionette	TRACE	Received observer notification toplevel-window-ready
1549954612201	Marionette	TRACE	Received observer notification sessionstore-windows-restored
1549954612202	Marionette	TRACE	GFX sanity window detected, waiting until it has been closed...
1549954615031	Marionette	TRACE	Received observer notification domwindowclosed
1549954615031	Marionette	TRACE	Waiting until startup recorder finished recording startup scripts...
1549954615040	Marionette	TRACE	All scripts recorded.
1549954615041	Marionette	DEBUG	Setting recommended pref apz.content_response_timeout to 60000
1549954615041	Marionette	DEBUG	Setting recommended pref browser.contentblocking.introCount to 99
1549954615041	Marionette	DEBUG	Setting recommended pref browser.download.panel.shown to true
1549954615042	Marionette	DEBUG	Setting recommended pref browser.newtabpage.enabled to false
1549954615043	Marionette	DEBUG	Setting recommended pref browser.pagethumbnails.capturing_disabled to true
1549954615044	Marionette	DEBUG	Setting recommended pref browser.search.update to false
1549954615045	Marionette	DEBUG	Setting recommended pref browser.tabs.disableBackgroundZombification to false
1549954615045	Marionette	DEBUG	Setting recommended pref browser.tabs.warnOnCloseOtherTabs to false
1549954615045	Marionette	DEBUG	Setting recommended pref browser.tabs.warnOnOpen to false
1549954615046	Marionette	DEBUG	Setting recommended pref browser.usedOnWindows10.introURL to 
1549954615046	Marionette	DEBUG	Setting recommended pref browser.urlbar.suggest.searches to false
1549954615047	Marionette	DEBUG	Setting recommended pref datareporting.policy.dataSubmissionPolicyAccepted to false
1549954615048	Marionette	DEBUG	Setting recommended pref dom.disable_beforeunload to true
1549954615048	Marionette	DEBUG	Setting recommended pref dom.disable_open_during_load to false
1549954615048	Marionette	DEBUG	Setting recommended pref dom.file.createInChild to true
1549954615048	Marionette	DEBUG	Setting recommended pref dom.max_chrome_script_run_time to 0
1549954615048	Marionette	DEBUG	Setting recommended pref dom.max_script_run_time to 0
1549954615050	Marionette	DEBUG	Setting recommended pref extensions.getAddons.cache.enabled to false
1549954615050	Marionette	DEBUG	Setting recommended pref extensions.webservice.discoverURL to http://%(server)s/dummy/discoveryURL
1549954615050	Marionette	DEBUG	Setting recommended pref network.http.prompt-temp-redirect to false
1549954615050	Marionette	DEBUG	Setting recommended pref network.http.speculative-parallel-limit to 0
1549954615050	Marionette	DEBUG	Setting recommended pref security.fileuri.strict_origin_policy to false
1549954615051	Marionette	DEBUG	Setting recommended pref security.notification_enable_delay to 0
1549954615051	Marionette	DEBUG	Setting recommended pref signon.autofillForms to false
1549954615051	Marionette	DEBUG	Setting recommended pref signon.rememberSignons to false
1549954615052	Marionette	DEBUG	Setting recommended pref toolkit.cosmeticAnimations.enabled to false
1549954615163	Marionette	INFO	Listening on port 60465
1549954615164	Marionette	DEBUG	Remote service is active
1549954615720	geckodriver::marionette	DEBUG	Connection established on 127.0.0.1:60465. Waiting for Marionette handshake
1549954615724	Marionette	DEBUG	Accepted connection 0 from 127.0.0.1:60533
1549954615725	geckodriver::marionette	DEBUG	Connected to Marionette
1549954615727	Marionette	DEBUG	0 -> [0,1,"WebDriver:NewSession",{"acceptInsecureCerts":true,"browserName":"firefox"}]
1549954615728	Marionette	WARN	TLS certificate errors will be ignored for this session
1549954615795	Marionette	TRACE	[2147483651] Frame script loaded
1549954615798	Marionette	TRACE	[2147483651] Frame script registered
1549954615832	Marionette	TRACE	[6442450945] Frame script loaded
1549954615837	Marionette	TRACE	[6442450945] Frame script registered
1549954615853	Marionette	DEBUG	0 <- [1,1,null,{"sessionId":"4624d2b8-3555-4fc5-8a26-651969be3979","capabilities":{"browserName":"firefox","browserVersion":"65.0" ... ozprofile.AEKzRSx9Om42","moz:shutdownTimeout":60000,"moz:useNonSpecCompliantPointerOrigin":false,"moz:webdriverClick":true}}]
1549954615907	webdriver::server	DEBUG	<- 200 OK {"value":{"sessionId":"4624d2b8-3555-4fc5-8a26-651969be3979","capabilities":{"acceptInsecureCerts":true,"browserName":"firefox","browserVersion":"65.0","moz:accessibilityChecks":false,"moz:geckodriverVersion":"0.23.0","moz:headless":false,"moz:processID":30128,"moz:profile":"C:\\Users\\Sandeep Singh-GGN\\AppData\\Local\\Temp\\rust_mozprofile.AEKzRSx9Om42","moz:shutdownTimeout":60000,"moz:useNonSpecCompliantPointerOrigin":false,"moz:webdriverClick":true,"pageLoadStrategy":"normal","platformName":"windows","platformVersion":"10.0","rotatable":false,"setWindowRect":true,"strictFileInteractability":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"unhandledPromptBehavior":"dismiss and notify"}}}
Feb 12, 2019 12:26:56 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
1549954616148	Marionette	TRACE	[8589934593] Frame script loaded
1549954616168	Marionette	TRACE	[8589934593] Frame script registered
1549954616170	Marionette	TRACE	[8589934594] Frame script loaded
1549954616172	Marionette	TRACE	[8589934594] Frame script registered
1549954616365	Marionette	TRACE	[10737418241] Frame script loaded

Tried creating an instance of geckodriver by setting the 'webdriver.gecko.driver' System property. The path was set to another exe of geckodriver on the system. That seemed to work fine.

Seems like the issue is with the geckodriver.exe being downloaded by wdm. Could you look in to this at the earliest please?

**Comment by sandeep-singh-79** [comment]
Any update on this issue?

**Comment by bonigarcia** [comment]
Which version of WebDriverManager are you using?
Which is the version of your Firefox browser?

**Comment by sandeep-singh-79** [comment]
Hi Boni! sorry for the late reply. The WDM version is 3.3.0 and firefox version is 65.0.1.

**Comment by bonigarcia** [comment]
It seems a connectivity issue. Is still happening?
