### ISSUE TITLE
NTLM authentication for downloading webdriver dependencies

### ISSUE THREAD

**Issue by Yobikap** [bonigarcia/webdrivermanager#311]
Hi all,

I am using the library as a dependency on one of the project.
On running time of the application I want to download the webdriver (without using Junit tests) automatically. But I get the following error when calling `WebDriverManager.firefoxdriver().setup()`

`2019-03-08 15:01:49,438 
Exception in thread "Thread-3" java.lang.NoClassDefFoundError: org/apache/commons/logging/LogFactory
        at org.apache.http.conn.ssl.AbstractVerifier.<init>(AbstractVerifier.java:61)
        at org.apache.http.conn.ssl.AllowAllHostnameVerifier.<init>(AllowAllHostnameVerifier.java:44)
        at org.apache.http.conn.ssl.AllowAllHostnameVerifier.<clinit>(AllowAllHostnameVerifier.java:46)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.<clinit>(SSLConnectionSocketFactory.java:149)
        at io.github.bonigarcia.wdm.HttpClient.<init>(HttpClient.java:115)
        at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:466)
        at io.github.bonigarcia.wdm.WebDriverManager.setup(WebDriverManager.java:251)
        at nl..........................................startWebDriver(WebDriverStarter.java:107)
        at nl..........................................WebDriverStarter.run(WebDriverStarter.java:59)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.logging.LogFactory
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 10 more`

**Comment by bonigarcia** [comment]
It seems some dependencies are missing in your classpath.
