### ISSUE TITLE
Issues on FreeBSD

### ISSUE THREAD

**Issue by akruijff** [bonigarcia/webdrivermanager#321]
Given FreeBSD, with chrome installed
When running 'WebDriverManager.chromedriver().setup();'
Then the following null pointer exception will be thrown:

```
io.github.bonigarcia.wdm.WebDriverManagerException: java.lang.NullPointerException
	at io.github.bonigarcia.wdm.WebDriverManager.storeVersionToDownload(WebDriverManager.java:1254)
	at io.github.bonigarcia.wdm.WebDriverManager.checkLatest(WebDriverManager.java:882)
	at io.github.bonigarcia.wdm.WebDriverManager.filterCandidateUrls(WebDriverManager.java:712)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:506)
	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:686)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:521)
	at io.github.bonigarcia.wdm.WebDriverManager.setup(WebDriverManager.java:251)
```

The variable versionToDownload is null, because it is set to null at:

```
            if (continueSearchingVersion) {
                log.info(
                        "No binary found for {} {} ... seeking another version",
                        getDriverName(), versionToDownload);
                urls = removeFromList(urls, versionToDownload);
                versionToDownload = null;
            }
```

**Comment by bonigarcia** [comment]
Which version of WebDriverManager are you using?

**Comment by akruijff** [comment]
<dependency>
                <groupId>io.github.bonigarcia</groupId>
                <artifactId>webdrivermanager</artifactId>
                <version>3.3.0</version>
            </dependency>

**Comment by bonigarcia** [comment]
Thanks for reporting. I have just committed a patch solving this.
