### ISSUE TITLE
 Error while  executing the basic website launch using web driver manager

### ISSUE THREAD

**Issue by Priya0134** [bonigarcia/webdrivermanager#323]
this is my pom.xml file

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>SeleniumFramework</groupId>
	<artifactId>SeleniumFramework</artifactId>
	<version>0.0.1-SNAPSHOT</version>
<dependencies>
		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-java</artifactId>
			<version>3.141.59</version>
		</dependency>

		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.13-beta-2</version>
			<scope>test</scope>
		</dependency>
		
		<dependency>
			<groupId>io.github.bonigarcia</groupId>
			<artifactId>webdrivermanager</artifactId>
			<version>3.4.0</version>
			<scope>compile</scope>
			
		</dependency>
		
	
	<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-simple</artifactId>
			<version>1.6.2</version>
			<scope>test</scope>
		</dependency>
</dependencies>
</project>

this is how my console looks

Mar 30, 2019 6:41:58 PM java.util.prefs.WindowsPreferences <init>
WARNING: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5.
858 [main] INFO io.github.bonigarcia.wdm.WebDriverManager - Using chromedriver 2.45 (since Google Chrome 70 is installed in your machine)
870 [main] INFO io.github.bonigarcia.wdm.WebDriverManager - Reading https://chromedriver.storage.googleapis.com/ to seek chromedriver
Mar 30, 2019 6:42:03 PM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (org.apache.http.NoHttpResponseException) caught when processing request to {tls}->http://proxy.cognizant.com:80->https://chromedriver.storage.googleapis.com:443: The target server failed to respond
Mar 30, 2019 6:42:03 PM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {tls}->http://proxy.cognizant.com:80->https://chromedriver.storage.googleapis.com:443
Mar 30, 2019 6:42:07 PM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (org.apache.http.NoHttpResponseException) caught when processing request to {tls}->http://proxy.cognizant.com:80->https://chromedriver.storage.googleapis.com:443: The target server failed to respond
Mar 30, 2019 6:42:07 PM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {tls}->http://proxy.cognizant.com:80->https://chromedriver.storage.googleapis.com:443
Mar 30, 2019 6:42:11 PM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (org.apache.http.NoHttpResponseException) caught when processing request to {tls}->http://proxy.cognizant.com:80->https://chromedriver.storage.googleapis.com:443: The target server failed to respond
Mar 30, 2019 6:42:11 PM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {tls}->http://proxy.cognizant.com:80->https://chromedriver.storage.googleapis.com:443
16958 [main] WARN io.github.bonigarcia.wdm.WebDriverManager - There was an error managing chromedriver 2.45 (chromedriver.storage.googleapis.com:443 failed to respond) ... trying again using cache and mirror
Mar 30, 2019 6:42:19 PM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (org.apache.http.NoHttpResponseException) caught when processing request to {}->http://proxy.cognizant.com:80->http://npm.taobao.org:80: The target server failed to respond
Mar 30, 2019 6:42:19 PM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://proxy.cognizant.com:80->http://npm.taobao.org:80
Mar 30, 2019 6:42:23 PM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (org.apache.http.NoHttpResponseException) caught when processing request to {}->http://proxy.cognizant.com:80->http://npm.taobao.org:80: The target server failed to respond
Mar 30, 2019 6:42:23 PM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://proxy.cognizant.com:80->http://npm.taobao.org:80
Mar 30, 2019 6:42:27 PM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (org.apache.http.NoHttpResponseException) caught when processing request to {}->http://proxy.cognizant.com:80->http://npm.taobao.org:80: The target server failed to respond
Mar 30, 2019 6:42:27 PM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://proxy.cognizant.com:80->http://npm.taobao.org:80
33041 [main] ERROR io.github.bonigarcia.wdm.WebDriverManager - There was an error managing chromedriver 2.45 (npm.taobao.org:80 failed to respond)
org.apache.http.NoHttpResponseException: npm.taobao.org:80 failed to respond
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:141)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:165)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at io.github.bonigarcia.wdm.HttpClient.execute(HttpClient.java:159)
	at io.github.bonigarcia.wdm.WebDriverManager.getDriversFromMirror(WebDriverManager.java:983)
	at io.github.bonigarcia.wdm.ChromeDriverManager.getDrivers(ChromeDriverManager.java:79)
	at io.github.bonigarcia.wdm.WebDriverManager.filterCandidateUrls(WebDriverManager.java:731)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:525)
	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:712)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:540)
	at io.github.bonigarcia.wdm.WebDriverManager.setup(WebDriverManager.java:260)
	at BrowserTest.main(BrowserTest.java:10)
Exception in thread "main" io.github.bonigarcia.wdm.WebDriverManagerException: org.apache.http.NoHttpResponseException: npm.taobao.org:80 failed to respond
	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:715)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:540)
	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:712)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:540)
	at io.github.bonigarcia.wdm.WebDriverManager.setup(WebDriverManager.java:260)
	at BrowserTest.main(BrowserTest.java:10)
Caused by: org.apache.http.NoHttpResponseException: npm.taobao.org:80 failed to respond
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:141)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:165)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at io.github.bonigarcia.wdm.HttpClient.execute(HttpClient.java:159)
	at io.github.bonigarcia.wdm.WebDriverManager.getDriversFromMirror(WebDriverManager.java:983)
	at io.github.bonigarcia.wdm.ChromeDriverManager.getDrivers(ChromeDriverManager.java:79)
	at io.github.bonigarcia.wdm.WebDriverManager.filterCandidateUrls(WebDriverManager.java:731)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:525)
	... 4 more

**Comment by bonigarcia** [comment]
It seems a connectivity issue, perhaps your proxy is not configured properly.
