### ISSUE TITLE
Error when using firefox driver on MacOS

### ISSUE THREAD

**Issue by mpapikyan-bb** [bonigarcia/webdrivermanager#324]
The following exception is thrown while trying to use firefox driver:

```
java.lang.NoSuchMethodError: org.apache.commons.io.FileUtils.copyInputStreamToFile(Ljava/io/InputStream;Ljava/io/File;)V
	at io.github.bonigarcia.wdm.Downloader.downloadAndExtract(Downloader.java:135)
	at io.github.bonigarcia.wdm.Downloader.download(Downloader.java:81)
	at io.github.bonigarcia.wdm.WebDriverManager.downloadCandidateUrls(WebDriverManager.java:723)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:536)
	at io.github.bonigarcia.wdm.WebDriverManager.setup(WebDriverManager.java:260)
...
```
The code to create a firefox driver is the following:
```
    private void initDriver() throws IncorrectEnvironmentSetup {
        if (getDriverVersion() != null) {
            WebDriverManager.firefoxdriver().version(getDriverVersion()).setup();
        } else {
            WebDriverManager.firefoxdriver().setup();
        }
    }
```

Environment: **MacOS 10.13.2 (17C88)**
Maven dependency for WebDriverManager:
```
        <dependency>
            <groupId>io.github.bonigarcia</groupId>
            <artifactId>webdrivermanager</artifactId>
            <version>3.4.0</version>
        </dependency>
```

Works correctly for ChromeDriver

**Comment by mpapikyan-bb** [comment]
@bonigarcia have you had a chance to take a look at the issue above?

**Comment by bonigarcia** [comment]
It seems you have an incompatible version of apache-commons-io in your classpath.
