### ISSUE TITLE
Doesn't work with Edge Browser (Microsoft EdgeHTML 17.17134/ Microsoft Edge 42.17134.1.0)

### ISSUE THREAD

**Issue by deeppatel2** [bonigarcia/webdrivermanager#335]
I am trying to use this with Edge browser but it fails.

Current Edge Version on my pc:- Microsoft EdgeHTML 17.17134/ Microsoft Edge 42.17134.1.0

Log:-
Using MicrosoftWebDriver 6.17134 (since Microsoft Edge 42 is installed in your machine)
Exporting webdriver.edge.driver as C:\Users\depatel\Documents\capabilitydeck\webdrivers\MicrosoftWebDriver\6.17134\MicrosoftWebDriver.exe
org.apache.commons.exec.ExecuteException: Process exited with an error: -1073741512 (Exit value: -1073741512)
org.openqa.selenium.WebDriverException: Timed out waiting for driver server to start.
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'hostname', ip: 'x.x.x.x', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_211'
Driver info: driver.version: Driver
	at org.openqa.selenium.remote.service.DriverService.waitUntilAvailable(DriverService.java:202)
	at org.openqa.selenium.remote.service.DriverService.start(DriverService.java:188)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:79)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at org.openqa.selenium.edge.EdgeDriver.<init>(EdgeDriver.java:141)
	at org.openqa.selenium.edge.EdgeDriver.<init>(EdgeDriver.java:130)
	at com.gartner.utilities.testng.driver.Driver.initialize(Driver.java:271)
	at DemoTest.demo(DemoTest.java:16)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: org.openqa.selenium.net.UrlChecker$TimeoutException: Timed out waiting for [http://localhost:12927/status] to be available after 20001 ms
	at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:100)
	at org.openqa.selenium.remote.service.DriverService.waitUntilAvailable(DriverService.java:197)
	... 34 more
Caused by: java.util.concurrent.TimeoutException
	at java.util.concurrent.FutureTask.get(FutureTask.java:205)
	at com.google.common.util.concurrent.SimpleTimeLimiter.callWithTimeout(SimpleTimeLimiter.java:156)
	at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:75)
	... 35 more

When I downloaded same driver version from Microsoft site and ran my test, it worked. I noticed that exe size from Microsoft site for this version is 146 KB whereas downloaded file size by this project was 126 KB.

**Comment by bonigarcia** [comment]
There were problems with Edge in former version of WebDriverManager. I have recently released version 3.5.0, which in theory solved these issues. Please update to that version.

**Comment by deeppatel2** [comment]
I tried updating to 3.5.0 and issue still exists.

**Comment by bonigarcia** [comment]
You can try to force to download again the Edge driver, maybe it is corrupted for some reason:

```
WebDriverManager.edgedriver().forceDownload().setup();
````

**Comment by sumanverma** [comment]
Hi @bonigarcia 
I am using 3.5.0 version but still I am also facing issue with edge driver download.
Exception in thread "main" io.github.bonigarcia.wdm.WebDriverManagerException: io.github.bonigarcia.wdm.WebDriverManagerException: msedgedriver 6.17134 for WIN64 not found in https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/
	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:715)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:540)
	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:712)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:540)
	at io.github.bonigarcia.wdm.WebDriverManager.setup(WebDriverManager.java:260)
	at testProject.StartNode.main(StartNode.java:57)
Caused by: io.github.bonigarcia.wdm.WebDriverManagerException: msedgedriver 6.17134 for WIN64 not found in https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:533)
	... 4 more
