### ISSUE TITLE
WebDriverManager newest ChromeDriver crashes with error driver is for Chrome 76

### ISSUE THREAD

**Issue by greghicks01** [bonigarcia/webdrivermanager#349]
**Description of the problem**: 
Expected behaviour: successful launch of the current version of chrome on the MAC
Actual Behaviour: browser closes and test stops with this error message:
`org.openqa.selenium.SessionNotCreatedException: session not created: This version of ChromeDriver only supports Chrome version 76
Build info: version: '3.5.3', revision: 'a88d25fe6b', time: '2017-08-29T12:42:44.417Z'`

**WebDriverManager version**: 3.3.0 and 3.6.1

**Operating System**: Mac OS Majove 10.14.5 (18F132)

**WebDriverManager use**: 
`      WebDriverManager.chromedriver().setup();
        return new ChromeDriver();`

**Error trace**: 
`org.openqa.selenium.SessionNotCreatedException: session not created: This version of ChromeDriver only supports Chrome version 76
Build info: version: '3.5.3', revision: 'a88d25fe6b', time: '2017-08-29T12:42:44.417Z'
System info: host: 'AU10347', ip: 'fe80:0:0:0:1c23:4e9:3e1b:53e3%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14.5', java.version: '1.8.0_171'
Driver info: driver.version: FluentDriver
remote stacktrace: 0   chromedriver                        0x0000000106f11349 chromedriver + 3650377
1   chromedriver                        0x0000000106ea1373 chromedriver + 3191667
2   chromedriver                        0x0000000106c41f0f chromedriver + 704271
3   chromedriver                        0x0000000106bae17b chromedriver + 98683
4   chromedriver                        0x0000000106baa228 chromedriver + 82472
5   chromedriver                        0x0000000106bd640b chromedriver + 263179
6   chromedriver                        0x0000000106bd3a43 chromedriver + 252483
7   chromedriver                        0x0000000106bb01da chromedriver + 106970
8   chromedriver                        0x0000000106bb1225 chromedriver + 111141
9   chromedriver                        0x0000000106ecee5f chromedriver + 3378783
10  chromedriver                        0x0000000106edab80 chromedriver + 3427200
11  chromedriver                        0x0000000106eda918 chromedriver + 3426584
12  chromedriver                        0x0000000106eaf2a9 chromedriver + 3248809
13  chromedriver                        0x0000000106edb3f8 chromedriver + 3429368
14  chromedriver                        0x0000000106ec3147 chromedriver + 3330375
15  chromedriver                        0x0000000106ef8234 chromedriver + 3547700
16  chromedriver                        0x0000000106f17087 chromedriver + 3674247
17  libsystem_pthread.dylib             0x00007fff678242eb _pthread_body + 126
18  libsystem_pthread.dylib             0x00007fff67827249 _pthread_start + 66
19  libsystem_pthread.dylib             0x00007fff6782340d thread_start + 13

	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$new$0(W3CHandshakeResponse.java:57)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$getResponseFunction$2(W3CHandshakeResponse.java:104)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$24(ProtocolHandshake.java:359)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:362)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:136)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:142)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:646)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:255)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:237)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:138)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:178)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:167)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:124)
	at utilities.FluentDriver.start(FluentDriver.java:77)`

**Comment by bonigarcia** [comment]
Check the version of your Chrome browser. If it is 75, try this:

```
WebDriverManager.chromedriver().version("75.0.3770.8").setup();
```

**Comment by materia2021** [comment]
setting the version to 2.46 still works

**Comment by greghicks01** [comment]
hi

Further information on this. Found out my internet connection got interrupted. Side effect if the net can't be contacted. Let me have a dig :)

**Comment by greghicks01** [comment]
i think we can close this - thanks for all the feedback.

**Comment by greghicks01** [comment]
broken connection during the use of WDM.
