### ISSUE TITLE
Crash when using Chromedriver 75 in Windows

### ISSUE THREAD

**Issue by sriram04144** [bonigarcia/webdrivermanager#350]
**Description of the problem**: WebDriverManager.chromedriver().version("75").setup();   doesn't work, crashes out. 

**Browser and version**: Chrome 75, trying to download Chromedriver 75. 

**Operating system**: Windows 7

**WebDriverManager version**: 3.6.1

**WebDriverManager use**: 
```
if(property.equalsIgnoreCase("latest")) {
        	System.out.println("Starting the execution with the latest version of ChromeDriver");
        	WebDriverManager.chromedriver().setup();
    	}
    	else {        	
    		System.out.println("Downloading Chromedriver version '"+property+"' from Internet and initiating a Chromedriver");    		
    		WebDriverManager.chromedriver().version(property).setup();    
```

**WebDriverManager traces**:

**Error trace**: 
```
019-06-17 15:49:33:06S +0200 [WARNING] java.util.prefs.WindowsPreferences <init>:Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5.
[pool-2-thread-1] INFO io.github.bonigarcia.wdm.WebDriverManager - Reading https://chromedriver.storage.googleapis.com/ to seek chromedriver
[pool-2-thread-1] INFO io.github.bonigarcia.wdm.Downloader - Downloading https://chromedriver.storage.googleapis.com/75.0.3770.8/chromedriver_win32.zip
[pool-2-thread-1] INFO io.github.bonigarcia.wdm.Downloader - Extracting binary from compressed file chromedriver_win32.zip
[pool-2-thread-1] INFO io.github.bonigarcia.wdm.WebDriverManager - Exporting webdriver.chrome.driver as C:\Users\deb735k\.m2\repository\webdriver\chromedriver\win32\75\chromedriver.exe
Starting ChromeDriver 75.0.3770.8 (681f24ea911fe754973dda2fdc6d2a2e159dd300-refs/branch-heads/3770@{#40}) on port 7823
Only local connections are allowed.
Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.
2019-06-17 15:49:52:06S +0200 [SEVERE] com.cognizant.cognizantits.engine.core.Task onError:invalid argument: 'firstMatch' must contain at least one entry
Build info: version: '3.5.3', revision: 'a88d25fe6b', time: '2017-08-29T12:42:44.417Z'
System info: host: 'NDEA72207989', ip: '10.212.31.18', os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.8.0_74'
Driver info: driver.version: SeleniumDriver
remote stacktrace: Backtrace:
	Ordinal0 [0x01397DF3+1474035]
	Ordinal0 [0x013107D1+919505]
	Ordinal0 [0x012ACB43+510787]
	Ordinal0 [0x01260541+197953]
	Ordinal0 [0x012608A0+198816]
	Ordinal0 [0x0126069D+198301]
	Ordinal0 [0x0125EECB+192203]
	Ordinal0 [0x01245FF6+90102]
	Ordinal0 [0x0124765A+95834]
	Ordinal0 [0x01247554+95572]
	GetHandleVerifier [0x014F231C+1249612]
	GetHandleVerifier [0x01441575+525221]
	GetHandleVerifier [0x01441310+524608]
	Ordinal0 [0x013A5D28+1531176]
	GetHandleVerifier [0x01441D4A+527226]
	Ordinal0 [0x013275F6+1013238]
	Ordinal0 [0x0132746F+1012847]
	Ordinal0 [0x0133365B+1062491]
	Ordinal0 [0x0133379F+1062815]
	Ordinal0 [0x01332745+1058629]
	BaseThreadInitThunk [0x768D343D+18]
	RtlInitializeExceptionChain [0x775F9802+99]
	RtlInitializeExceptionChain [0x775F97D5+54]

org.openqa.selenium.InvalidArgumentException: invalid argument: 'firstMatch' must contain at least one entry
Build info: version: '3.5.3', revision: 'a88d25fe6b', time: '2017-08-29T12:42:44.417Z'
System info: host: 'NDEA72207989', ip: '10.212.31.18', os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.8.0_74'
Driver info: driver.version: SeleniumDriver
remote stacktrace: Backtrace:
	Ordinal0 [0x01397DF3+1474035]
	Ordinal0 [0x013107D1+919505]
	Ordinal0 [0x012ACB43+510787]
	Ordinal0 [0x01260541+197953]
	Ordinal0 [0x012608A0+198816]
	Ordinal0 [0x0126069D+198301]
	Ordinal0 [0x0125EECB+192203]
	Ordinal0 [0x01245FF6+90102]
	Ordinal0 [0x0124765A+95834]
	Ordinal0 [0x01247554+95572]
	GetHandleVerifier [0x014F231C+1249612]
	GetHandleVerifier [0x01441575+525221]
	GetHandleVerifier [0x01441310+524608]
	Ordinal0 [0x013A5D28+1531176]
	GetHandleVerifier [0x01441D4A+527226]
	Ordinal0 [0x013275F6+1013238]
	Ordinal0 [0x0132746F+1012847]
	Ordinal0 [0x0133365B+1062491]
	Ordinal0 [0x0133379F+1062815]
	Ordinal0 [0x01332745+1058629]
	BaseThreadInitThunk [0x768D343D+18]
	RtlInitializeExceptionChain [0x775F9802+99]
	RtlInitializeExceptionChain [0x775F97D5+54]

	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$new$0(W3CHandshakeResponse.java:57)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$getResponseFunction$2(W3CHandshakeResponse.java:104)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$24(ProtocolHandshake.java:359)
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Unknown Source)
	at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.findFirst(Unknown Source)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:362)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:136)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:142)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:646)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:255)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:237)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:138)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:178)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:146)
	at com.cognizant.cognizantits.engine.drivers.WebDriverFactory.create(WebDriverFactory.java:219)
	at com.cognizant.cognizantits.engine.drivers.WebDriverFactory.create(WebDriverFactory.java:182)
	at com.cognizant.cognizantits.engine.drivers.WebDriverFactory.create(WebDriverFactory.java:172)
	at com.cognizant.cognizantits.engine.drivers.SeleniumDriver.launchDriver(SeleniumDriver.java:66)
	at com.cognizant.cognizantits.engine.core.Task.launchBrowser(Task.java:151)
	at com.cognizant.cognizantits.engine.core.Task.runIteration(Task.java:121)
	at com.cognizant.cognizantits.engine.core.Task.run(Task.java:81)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

[DEBUG]   | invalid argument: 'firstMatch' must contain at least one entry
Build info: version: '3.5.3', revision: 'a88d25fe6b', time: '2017-08-29T12:42:44.417Z'
System info: host: 'NDEA72207989', ip: '10.212.31.18', os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.8.0_74'
Driver info: driver.version: SeleniumDriver
remote stacktrace: Backtrace:
	Ordinal0 [0x01397DF3+1474035]
	Ordinal0 [0x013107D1+919505]
	Ordinal0 [0x012ACB43+510787]
	Ordinal0 [0x01260541+197953]
	Ordinal0 [0x012608A0+198816]
	Ordinal0 [0x0126069D+198301]
	Ordinal0 [0x0125EECB+192203]
	Ordinal0 [0x01245FF6+90102]
	Ordinal0 [0x0124765A+95834]
	Ordinal0 [0x01247554+95572]
	GetHandleVerifier [0x014F231C+1249612]
	GetHandleVerifier [0x01441575+525221]
	GetHandleVerifier [0x01441310+524608]
	Ordinal0 [0x013A5D28+1531176]
	GetHandleVerifier [0x01441D4A+527226]
	Ordinal0 [0x013275F6+1013238]
	Ordinal0 [0x0132746F+1012847]
	Ordinal0 [0x0133365B+1062491]
	Ordinal0 [0x0133379F+1062815]
	Ordinal0 [0x01332745+1058629]
	BaseThreadInitThunk [0x768D343D+18]
	RtlInitializeExceptionChain [0x775F9802+99]
	RtlInitializeExceptionChain [0x775F97D5+54]

```

**Comment by inmaj** [comment]
I had same problem on win7. Resolution in: https://github.com/bonigarcia/webdrivermanager/issues/348
Try with version 3.6.1, the error should not happen with this new version.

<dependency>
    <groupId>io.github.bonigarcia</groupId>
    <artifactId>webdrivermanager</artifactId>
    <version>3.6.1</version>
</dependency>

**Comment by bonigarcia** [comment]
@sriram04144 You can try to force the specific chromedriver version for Chrome 75 as follows:

```
WebDriverManager.chromedriver().version("75.0.3770.90").setup();
```

Also, it might be interesting to use the latest stable version of Selenium, which is 3.141.59 at the moment of this writing (you are using 3.5.3).

**Comment by sriram04144** [comment]
Hi @bonigarcia  - I tried with the latest Selenium, still '74' works, but when I pass '75.0.3770.90', I get the following error message, which is weird because it says a 503 exception. 

I am using 3.6.1 WebDriverManager. 

```
2019-06-28 11:26:53:06S +0200 [WARNING] java.util.prefs.WindowsPreferences <init>:Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5.
[pool-2-thread-1] INFO io.github.bonigarcia.wdm.WebDriverManager - Reading https://chromedriver.storage.googleapis.com/ to seek chromedriver
[pool-2-thread-1] WARN io.github.bonigarcia.wdm.WebDriverManager - There was an error managing chromedriver 75.0.3770.90 (Remote host closed connection during handshake) ... trying again using cache and mirror
[pool-2-thread-1] ERROR io.github.bonigarcia.wdm.HttpClient - Error HTTP 503 executing GET http://npm.taobao.org/mirrors/chromedriver HTTP/1.1
[pool-2-thread-1] ERROR io.github.bonigarcia.wdm.WebDriverManager - There was an error managing chromedriver 75.0.3770.90 (Error HTTP 503 executing GET http://npm.taobao.org/mirrors/chromedriver HTTP/1.1)
io.github.bonigarcia.wdm.WebDriverManagerException: Error HTTP 503 executing GET http://npm.taobao.org/mirrors/chromedriver HTTP/1.1
	at io.github.bonigarcia.wdm.HttpClient.execute(HttpClient.java:165)
	at io.github.bonigarcia.wdm.WebDriverManager.getDriversFromMirror(WebDriverManager.java:991)
	at io.github.bonigarcia.wdm.ChromeDriverManager.getDrivers(ChromeDriverManager.java:83)
	at io.github.bonigarcia.wdm.WebDriverManager.filterCandidateUrls(WebDriverManager.java:739)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:534)
	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:720)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:548)
	at io.github.bonigarcia.wdm.WebDriverManager.setup(WebDriverManager.java:260)
	at com.cognizant.cognizantits.engine.drivers.WebDriverFactory.setChromeDriver(WebDriverFactory.java:293)
	at com.cognizant.cognizantits.engine.drivers.WebDriverFactory.create(WebDriverFactory.java:218)
	at com.cognizant.cognizantits.engine.drivers.WebDriverFactory.create(WebDriverFactory.java:182)
	at com.cognizant.cognizantits.engine.drivers.WebDriverFactory.create(WebDriverFactory.java:172)
	at com.cognizant.cognizantits.engine.drivers.SeleniumDriver.launchDriver(SeleniumDriver.java:66)
	at com.cognizant.cognizantits.engine.core.Task.launchBrowser(Task.java:151)
	at com.cognizant.cognizantits.engine.core.Task.runIteration(Task.java:121)
	at com.cognizant.cognizantits.engine.core.Task.run(Task.java:81)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
2019-06-28 11:27:50:06S +0200 [SEVERE] com.cognizant.cognizantits.engine.core.Task onError:io.github.bonigarcia.wdm.WebDriverManagerException: Error HTTP 503 executing GET http://npm.taobao.org/mirrors/chromedriver HTTP/1.1
io.github.bonigarcia.wdm.WebDriverManagerException: io.github.bonigarcia.wdm.WebDriverManagerException: Error HTTP 503 executing GET http://npm.taobao.org/mirrors/chromedriver HTTP/1.1
	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:723)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:548)
	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:720)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:548)
	at io.github.bonigarcia.wdm.WebDriverManager.setup(WebDriverManager.java:260)
	at com.cognizant.cognizantits.engine.drivers.WebDriverFactory.setChromeDriver(WebDriverFactory.java:293)
	at com.cognizant.cognizantits.engine.drivers.WebDriverFactory.create(WebDriverFactory.java:218)
	at com.cognizant.cognizantits.engine.drivers.WebDriverFactory.create(WebDriverFactory.java:182)
	at com.cognizant.cognizantits.engine.drivers.WebDriverFactory.create(WebDriverFactory.java:172)
	at com.cognizant.cognizantits.engine.drivers.SeleniumDriver.launchDriver(SeleniumDriver.java:66)
	at com.cognizant.cognizantits.engine.core.Task.launchBrowser(Task.java:151)
	at com.cognizant.cognizantits.engine.core.Task.runIteration(Task.java:121)
	at com.cognizant.cognizantits.engine.core.Task.run(Task.java:81)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: io.github.bonigarcia.wdm.WebDriverManagerException: Error HTTP 503 executing GET http://npm.taobao.org/mirrors/chromedriver HTTP/1.1
	at io.github.bonigarcia.wdm.HttpClient.execute(HttpClient.java:165)
	at io.github.bonigarcia.wdm.WebDriverManager.getDriversFromMirror(WebDriverManager.java:991)
	at io.github.bonigarcia.wdm.ChromeDriverManager.getDrivers(ChromeDriverManager.java:83)
	at io.github.bonigarcia.wdm.WebDriverManager.filterCandidateUrls(WebDriverManager.java:739)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:534)
	... 14 more

[DEBUG]   | io.github.bonigarcia.wdm.WebDriverManagerException: Error HTTP 503 executing GET http://npm.taobao.org/mirrors/chromedriver HTTP/1.1

```

**Comment by bonigarcia** [comment]
@sriram04144 It seems a connectivity problem in your side.

**Comment by GetteAlan** [comment]
Hi, apply the suggested changes here but I continue with the error:

org.openqa.selenium.InvalidArgumentException: invalid argument: 'firstMatch' must contain at least one entry

**Comment by BalurQA** [comment]
@bonigarcia  : I am also facing this issue now and then

 os.name: 'Windows Server 2016', 
os.arch: 'amd64', os.version: '10.0', 
java.version: '1.8.0_211'
Driver info: driver.version: ChromeDriver
webdrivermanager = '3.8.1'


```
Driver info: driver.version: ChromeDriver
remote stacktrace: Backtrace:
	Ordinal0 [0x010C5F73+2449267]
	Ordinal0 [0x00FF8361+1606497]
	Ordinal0 [0x00EEF969+522601]
	Ordinal0 [0x00EE76CF+489167]
	Ordinal0 [0x00EE6C8C+486540]
	Ordinal0 [0x00EE6EC5+487109]
	Ordinal0 [0x00EE6905+485637]
	Ordinal0 [0x00EEE6C5+517829]
	Ordinal0 [0x00EE68C2+485570]
	Ordinal0 [0x00EE7329+488233]
	Ordinal0 [0x00EE6C8C+486540]
	Ordinal0 [0x00EE6EC5+487109]
	Ordinal0 [0x00EE6905+485637]
	Ordinal0 [0x00EECEAE+511662]
	Ordinal0 [0x00EE68C2+485570]
	Ordinal0 [0x00EE7329+488233]
	Ordinal0 [0x00EE6C8C+486540]
	Ordinal0 [0x00EE6EC5+487109]
	Ordinal0 [0x00EE6905+485637]
	Ordinal0 [0x00EEB71C+505628]
	Ordinal0 [0x00EE68C2+485570]
	Ordinal0 [0x00EE7329+488233]
	Ordinal0 [0x00EE6C8C+486540]
	Ordinal0 [0x00EE6EC5+487109]
	Ordinal0 [0x00EE6905+485637]
	Ordinal0 [0x00EEADB7+503223]
	Ordinal0 [0x00EE68C2+485570]
	Ordinal0 [0x00EE7329+488233]
	Ordinal0 [0x00EE6C8C+486540]
	Ordinal0 [0x00EE6EC5+487109]
	Ordinal0 [0x00EE6905+485637]
	Ordinal0 [0x00EE31AC+471468]
	Ordinal0 [0x00EE68C2+485570]
	Ordinal0 [0x00EE6817+485399]
	Ordinal0 [0x00EF0600+525824]
	Ordinal0 [0x00E9CBB9+183225]
	Ordinal0 [0x00E9BF2D+180013]
	Ordinal0 [0x00E99E5B+171611]
	Ordinal0 [0x00E81DD8+73176]
	Ordinal0 [0x00E82E50+77392]
	Ordinal0 [0x00E82DE9+77289]
	Ordinal0 [0x0100D8D7+1693911]
	GetHandleVerifier [0x01164036+522726]
	GetHandleVerifier [0x01163D74+522020]
	GetHandleVerifier [0x01179187+609079]
	GetHandleVerifier [0x011648A6+524886]
	Ordinal0 [0x01005CBC+1662140]
	Ordinal0 [0x0100F23B+1700411]
	Ordinal0 [0x0100F3A3+1700771]
	Ordinal0 [0x01025215+1790485]
	BaseThreadInitThunk [0x760C62C4+36]
	RtlSubscribeWnfStateChangeNotification [0x77D81E39+1081]
	RtlSubscribeWnfStateChangeNotification [0x77D81E04+1028]
```
