### ISSUE TITLE
WebDriverManager downloads the webdriver version 76.0.3809.25 instead of 75.0.3770.90

### ISSUE THREAD

**Issue by materia2021** [bonigarcia/webdrivermanager#353]
**Description of the problem**: WebDriverManager downloads the webdriver version 76.0.3809.25 instead of 75.0.3770.90

**Browser and version**:  Chrome 75.0.3770.100

**Operating system**:  Windows 10 x64

**WebDriverManager version**:  3.6.1

```
		<dependency>
			<groupId>io.github.bonigarcia</groupId>
			<artifactId>webdrivermanager</artifactId>
			<version>3.6.1</version>
		</dependency>
```

**WebDriverManager use**:  
```
WebDriverManager.chromedriver().targetPath("./").setup();

2019-06-28 23:40:59.491  INFO 11268 --- [           main] i.g.bonigarcia.wdm.WebDriverManager      : Using chromedriver 76.0.3809.25 (since Google Chrome 75 is installed in your machine)
2019-06-28 23:40:59.814  INFO 11268 --- [           main] i.g.bonigarcia.wdm.WebDriverManager      : Reading https://chromedriver.storage.googleapis.com/ to seek chromedriver
2019-06-28 23:41:00.655  INFO 11268 --- [           main] io.github.bonigarcia.wdm.Downloader      : Downloading https://chromedriver.storage.googleapis.com/76.0.3809.25/chromedriver_win32.zip
2019-06-28 23:41:01.253  INFO 11268 --- [           main] io.github.bonigarcia.wdm.Downloader      : Extracting binary from compressed file chromedriver_win32.zip
2019-06-28 23:41:01.373  INFO 11268 --- [           main] i.g.bonigarcia.wdm.WebDriverManager      : Exporting webdriver.chrome.driver as .\chromedriver\win32\76.0.3809.25\chromedriver.exe

```

**WebDriverManager traces**: 

**Error trace**: 
```
org.openqa.selenium.SessionNotCreatedException: session not created: This version of ChromeDriver only supports Chrome version 76
Build info: version: '3.9.1', revision: '63f7b50', time: '2018-02-07T22:25:02.294Z'
System info: host: '18-10370', ip: '169.254.5.14', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_201'
Driver info: driver.version: ChromeDriver
remote stacktrace: Backtrace:
	Ordinal0 [0x00BA7B13+1473299]
	Ordinal0 [0x00B2AC61+961633]
	Ordinal0 [0x00AB41A3+475555]
	Ordinal0 [0x00A4F365+62309]
	Ordinal0 [0x00A4BC77+48247]
	Ordinal0 [0x00A68FD9+167897]
	Ordinal0 [0x00A68BAD+166829]
	Ordinal0 [0x00A672BB+160443]
	Ordinal0 [0x00A50AE6+68326]
	Ordinal0 [0x00A51A80+72320]
	Ordinal0 [0x00A51A19+72217]
	Ordinal0 [0x00B44A27+1067559]
	GetHandleVerifier [0x00C466F5+506677]
	GetHandleVerifier [0x00C46490+506064]
	GetHandleVerifier [0x00C4D038+533624]
	GetHandleVerifier [0x00C46ECA+508682]
	Ordinal0 [0x00B3C116+1032470]
	Ordinal0 [0x00B3BF8F+1032079]
	Ordinal0 [0x00B4693B+1075515]
	Ordinal0 [0x00B46AA3+1075875]
	Ordinal0 [0x00B45A55+1071701]
	BaseThreadInitThunk [0x748D8484+36]
	RtlAreBitsSet [0x770E41C8+136]
	RtlAreBitsSet [0x770E4198+88]

	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$new$0(W3CHandshakeResponse.java:57)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$getResponseFunction$2(W3CHandshakeResponse.java:104)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:123)
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Unknown Source)
	at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.findFirst(Unknown Source)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:126)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:73)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:138)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:219)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:142)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:181)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:168)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:157)
	at com.sss.product.scraper.ScraperTests.shouldThrowErrorBecauseOfInvalidWebDriverVersion(ScraperTests.java:186)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.springframework.test.context.junit4.statements.RunBeforeTestExecutionCallbacks.evaluate(RunBeforeTestExecutionCallbacks.java:73)
	at org.springframework.test.context.junit4.statements.RunAfterTestExecutionCallbacks.evaluate(RunAfterTestExecutionCallbacks.java:83)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:251)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:97)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)
```

**Comment by janis91** [comment]
Same problem over here.

**Comment by kathyrollo** [comment]
You can indicate the exact version number you want by invoking `version()`.

**Comment by janis91** [comment]
Well, without changing anything my tests seem to work again since 2 hours. I'm not sure what happened, but the log output changed again to:

```
14:41:54.341 [main] INFO io.github.bonigarcia.wdm.WebDriverManager - Using chromedriver 75.0.3770.8 (since Google Chrome 75 is installed in your machine)
```

@materia2021 Can you confirm this? And do you have a clue why this happened?

**Comment by materia2021** [comment]
> Well, without changing anything my tests seem to work again since 2 hours. I'm not sure what happened, but the log output changed again to:
> 
> ```
> 14:41:54.341 [main] INFO io.github.bonigarcia.wdm.WebDriverManager - Using chromedriver 75.0.3770.8 (since Google Chrome 75 is installed in your machine)
> ```
> 
> @materia2021 Can you confirm this? And do you have a clue why this happened?

It seems to work on my side also. Dunno what happened. 
Closing this ticket.

```
2019-07-03 23:17:22.470  INFO 7432 --- [           main] i.g.bonigarcia.wdm.WebDriverManager      : Using chromedriver 75.0.3770.8 (since Google Chrome 75 is installed in your machine)
```
