### ISSUE TITLE
Webdrivermanager throws java.lang.NoClassDefFoundError: org/apache/http/ssl/TrustStrategy exception

### ISSUE THREAD

**Issue by rajesha2016** [bonigarcia/webdrivermanager#359]
**Description of the problem**: Hi @bonigarcia 

Just to inform you that I got **java.lang.NoClassDefFoundError: org/apache/http/ssl/TrustStrategy** while using webdrivermanager and this is because webdrivermanager manager is looking for **httpclient** and **httpcore** library. But these two(httpclient and httcore) libraries are internally used by the selenium-java library. This is weird because I was thinking it should use that since they are in the same class path. 

**How did I resolve this?** 
I included these two(httpclient and httcore) libraries in my POM.XML explicitly and it works. 

**My question is**: do we need to include these two libraries in our pom.xml explicitly? if yes, then I think you need to update the webdrivermanager documentation.

**Browser and version**: Chrome 75

**Operating system**: Mac Mojave 10.14.5 64 bits

**WebDriverManager version**: 3.2.0

**WebDriverManager use**: 
        <dependency>
            <groupId>io.github.bonigarcia</groupId>
            <artifactId>webdrivermanager</artifactId>
            <version>3.2.0</version>
        </dependency>
also 
<dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-java</artifactId>
            <version>3.13.0</version>
        </dependency>

**Error trace**: **java.lang.NoClassDefFoundError: org/apache/http/ssl/TrustStrategy** 

Looking forward to your inputs and others as well :)

**Comment by bonigarcia** [comment]
Have you tried to update your dependencies to the latest stable versions? At the moment of this writing, these versions are:

* WebDriverManager 3.6.2
* Selenium-Jupiter: 3.141.59

**Comment by rajesha2016** [comment]
Hi @bonigarcia 

I had updated my WebDriverManager dependancy to 3.6.1 and Now I tried with 3.6.2 but it failed because of the above exception. It is trying to get the below dependency: 

       <dependency>
            <groupId>org.apache.httpcomponents</groupId>
            <artifactId>httpclient</artifactId>
            <version>4.5.6</version>
        </dependency>
        <dependency>
            <groupId>org.apache.httpcomponents</groupId>
            <artifactId>httpcore</artifactId>
            <version>4.4.8</version>
        </dependency>
To my surprise these dependancies are internally called by selenium-java which should work fine. If I remove these two from my POM it failed else it works fine.

I am using TestNG, do I need selenium-Jupiter library ? 

Looking forward to your solution or suggestion.

**Comment by bonigarcia** [comment]
It seems an incompatibility in the version of httpclient. WebDriverManager uses 4.5.6.

**Comment by pinakinc** [comment]
Hi Boni,

I have the following JARs
WebDriverManager 3.6.2
Selenium WebDriver 3.141.59
I get this error

Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/http/HttpRequest
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at rough.TestRun.main(TestRun.java:11)
Caused by: java.lang.ClassNotFoundException: org.apache.http.HttpRequest
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 25 more
