### ISSUE TITLE
Nexus Authentication

### ISSUE THREAD

**Issue by artsok** [bonigarcia/webdrivermanager#363]
**Description of the problem**: ChromeDriver and other Drivers located in the Inner Nexus. When I set wdm.chromeDriverUrl, wdm.ChromeDriverMirrorUrl and etc, I got HTTP 401 Unauthorized 

**Version Browsers**: Any

**Operating system**:  Windows 7 and architecture (32 bits)

**WebDriverManager version**: 3.4.0

**WebDriverManager use**: I tried to use vanilla HTTP apache client like described in this article https://www.baeldung.com/httpclient-4-basic-authentication - all fine.

**WebDriverManager traces**: 

WARN WebDriverManager:handleException:710 - There was an error managing chromedriver 2.38 (Error HTTP 401 executing GET http://nexus:8081/nexus/content/repositories/x/ru/x/qa/chromedriver/ HTTP/1.1) ... trying again using cache and mirror
19:12:10,833 @178 ERROR HttpClient:execute:164 - Error HTTP 401 executing GET http://nexus:8081/nexus/content/repositories/x/ru/x/qa/chromedriver/ HTTP/1.1
19:12:10,834 @178 ERROR WebDriverManager:handleException:714 - There was an error managing chromedriver 2.38 (Error HTTP 401 executing GET http://nexus:8081/nexus/content/repositories/x/ru/x/qa/chromedriver/ HTTP/1.1)
io.github.bonigarcia.wdm.WebDriverManagerException: Error HTTP 401 executing GET http://nexus:8081/nexus/content/repositories/x/ru/x/qa/chromedriver/ HTTP/1.1
                at io.github.bonigarcia.wdm.HttpClient.execute(HttpClient.java:165)
                at io.github.bonigarcia.wdm.WebDriverManager.getDriversFromXml(WebDriverManager.java:1009)
                at io.github.bonigarcia.wdm.ChromeDriverManager.getDrivers(ChromeDriverManager.java:81)
                at io.github.bonigarcia.wdm.WebDriverManager.filterCandidateUrls(WebDriverManager.java:731)
                at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:525)
                at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:712)
                at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:540)
                at io.github.bonigarcia.wdm.WebDriverManager.setup(WebDriverManager.java:260)

**Question**: How I can set basic authorization for Nexus? Or I need to make PR.

**Comment by bonigarcia** [comment]
Thanks for the PR. Merged.
