### ISSUE TITLE
ChromeDriver 76.0.3809.68 - Fatal error: Uncaught Facebook\WebDriver\Exception\UnknownServerException: Cannot define class using reflection

### ISSUE THREAD

**Issue by awakash** [bonigarcia/webdrivermanager#367]
Getting the following fatal error when running php test.php:
```
Fatal error: Uncaught Facebook\WebDriver\Exception\UnknownServerException: Cannot define class using reflection in /test/selenium/vendor/facebook/webdriver/lib/Exception/WebDriverException.php:114
Stack trace:
#0 /test/selenium/vendor/facebook/webdriver/lib/Remote/HttpCommandExecutor.php(331): Facebook\WebDriver\Exception\WebDriverException::throwException(13, 'Cannot define c...', Array)
#1 /test/selenium/vendor/facebook/webdriver/lib/Remote/RemoteWebDriver.php(144): Facebook\WebDriver\Remote\HttpCommandExecutor->execute(Object(Facebook\WebDriver\Remote\WebDriverCommand))
#2 /test/selenium/test.php(19): Facebook\WebDriver\Remote\RemoteWebDriver::create('http://localhos...', Object(Facebook\WebDriver\Remote\DesiredCapabilities), 5000)
#3 {main}
  thrown in /test/selenium/vendor/facebook/webdriver/lib/Exception/WebDriverException.php on line 114
```

**Description of the problem**: 

**Browser and version**: 
Chrome 76
ChromeDriver 76.0.3809.68
java -jar selenium-server-standalone-3.9.0.jar

**Operating system**: 
MacOS Mojave 10.14.6

**WebDriverManager version**: 

**WebDriverManager use**: 
```
<?php
// An example of using php-webdriver.

namespace Facebook\WebDriver;

use Facebook\WebDriver\Remote\DesiredCapabilities;
use Facebook\WebDriver\Remote\RemoteWebDriver;
use Facebook\WebDriver\Chrome\ChromeOptions;

require_once('vendor/autoload.php');

// start Chrome with 5 second timeout
$host = 'http://localhost:4444/wd/hub'; // this is the default
$capabilities = DesiredCapabilities::chrome();
$options = new ChromeOptions();
$options->addArguments(array("--headless","--disable-gpu", "--no-sandbox"));
$capabilities->setCapability(ChromeOptions::CAPABILITY, $options);

$driver = RemoteWebDriver::create($host, $capabilities, 5000);

// navigate to login screen
$driver->get('https://www.google.com');
$driver->quit();
```

**WebDriverManager traces**: 

java -jar selenium-server-standalone-3.9.0.jar
```
16:16:50.759 INFO - Selenium build info: version: '3.9.0', revision: '698b3178f0'
16:16:50.759 INFO - Launching a standalone Selenium Server on port 4444
2019-07-30 16:16:50.897:INFO::main: Logging initialized @379ms to org.seleniumhq.jetty9.util.log.StdErrLog
2019-07-30 16:16:50.989:INFO:osjs.Server:main: jetty-9.4.7.v20170914, build timestamp: 2017-11-21T16:27:37-05:00, git hash: 82b...
2019-07-30 16:16:51.011:WARN:osjs.SecurityHandler:main: ServletContext@o.s.j.s.ServletContextHandler@7e5afaa6{/,null,STARTING} has uncovered http methods for path: /
2019-07-30 16:16:51.015:INFO:osjsh.ContextHandler:main: Started o.s.j.s.ServletContextHandler@7e5afaa6{/,null,AVAILABLE}
2019-07-30 16:16:51.042:INFO:osjs.AbstractConnector:main: Started ServerConnector@576d5deb{HTTP/1.1,[http/1.1]}{0.0.0.0:4444}
2019-07-30 16:16:51.042:INFO:osjs.Server:main: Started @525ms
16:16:51.042 INFO - Selenium Server is up and running on port 4444
2019-07-30 16:16:58.777:INFO:osjshC.ROOT:qtp1594199808-18: org.openqa.selenium.remote.server.WebDriverServlet-65b3f4a4: Initialising WebDriverServlet
16:16:58.830 INFO - Found handler: org.openqa.selenium.remote.server.commandhandler.BeginSession@6f3b071e
16:16:58.834 INFO - /session: Executing POST on /session (handler: BeginSession)
16:16:58.885 INFO - Capabilities are: Capabilities {browserName: chrome, chromeOptions: {args: [--headless, --disable-gpu, --no-sandbox], binary: , w3c: false}}
16:16:58.887 INFO - Capabilities {browserName: chrome, chromeOptions: {args: [--headless, --disable-gpu, --no-sandbox], binary: , w3c: false}} matched class org.openqa.selenium.remote.server.ServicedSession$Factory (provider: org.openqa.selenium.chrome.ChromeDriverService)
Starting ChromeDriver 76.0.3809.68 (420c9498db8ce8fcd190a954d51297672c1515d5-refs/branch-heads/3809@{#864}) on port 40902
Only local connections are allowed.
Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.
16:16:59.378 INFO - Detected dialect: OSS
```

**Error trace**:

**Comment by awakash** [comment]
Incorrect repo, do ignore.
