### ISSUE TITLE
Web driver manager is not working with chrome version 76.0.3809.132

### ISSUE THREAD

**Issue by manishsewlikar** [bonigarcia/webdrivermanager#380]
MAVEN

<dependency>
    <groupId>io.github.bonigarcia</groupId>
    <artifactId>webdrivermanager</artifactId>
    <version>3.6.0</version>
</dependency>

code 
WebDriverManager.chromedriver().setup();
		WebDriverManager.chromedriver().version(" 76.0.3809.132").setup();
		WebDriver driver1=new ChromeDriver();
		driver1.get("https://www.google.com/");

==========================================================
ERROR
11:22:03.286 [main] DEBUG io.github.bonigarcia.wdm.Shell - There was a problem executing command <wmic datafile where name='C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe' get Version /value> on the shell: Cannot run program "wmic" (in directory "C:\Windows\System32"): CreateProcess error=2, The system cannot find the file specified
11:22:03.301 [main] DEBUG io.github.bonigarcia.wdm.WebDriverManager - The proper chromedriver version for your Google Chrome is unknown ... trying with the latest
11:22:03.707 [main] DEBUG io.github.bonigarcia.wdm.WebDriverManager - Latest version of chromedriver according to https://chromedriver.storage.googleapis.com/LATEST_RELEASE is 76.0.3809.126
11:22:03.708 [main] DEBUG io.github.bonigarcia.wdm.WebDriverManager - Driver chromedriver 76.0.3809.126 found in cache
11:22:03.708 [main] INFO io.github.bonigarcia.wdm.WebDriverManager - Exporting webdriver.chrome.driver as C:\Users\MS0038522\.m2\repository\webdriver\chromedriver\win32\76.0.3809.126\chromedriver.exe
11:22:03.739 [main] INFO io.github.bonigarcia.wdm.WebDriverManager - Reading https://chromedriver.storage.googleapis.com/ to seek chromedriver
11:22:04.753 [main] ERROR io.github.bonigarcia.wdm.WebDriverManager - chromedriver  76.0.3809.132 for WIN64 not found in https://chromedriver.storage.googleapis.com/
11:22:04.753 [main] WARN io.github.bonigarcia.wdm.WebDriverManager - There was an error managing chromedriver  76.0.3809.132 (chromedriver  76.0.3809.132 for WIN64 not found in https://chromedriver.storage.googleapis.com/) ... trying again using cache and mirror
11:22:25.791 [main] ERROR io.github.bonigarcia.wdm.WebDriverManager - There was an error managing chromedriver  76.0.3809.132 (Connect to npm.taobao.org:80 [npm.taobao.org/114.55.80.225] failed: Connection timed out: connect)
org.apache.http.conn.HttpHostConnectException: Connect to npm.taobao.org:80 [npm.taobao.org/114.55.80.225] failed: Connection timed out: connect
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:158)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at io.github.bonigarcia.wdm.HttpClient.execute(HttpClient.java:159)
	at io.github.bonigarcia.wdm.WebDriverManager.getDriversFromMirror(WebDriverManager.java:991)
	at io.github.bonigarcia.wdm.ChromeDriverManager.getDrivers(ChromeDriverManager.java:83)
	at io.github.bonigarcia.wdm.WebDriverManager.filterCandidateUrls(WebDriverManager.java:739)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:534)
	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:720)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:548)
	at io.github.bonigarcia.wdm.WebDriverManager.setup(WebDriverManager.java:260)
	at com.colt.test.Chrometest.main(Chrometest.java:30)
Caused by: java.net.ConnectException: Connection timed out: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:74)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141)
	... 18 common frames omitted
Exception in thread "main" io.github.bonigarcia.wdm.WebDriverManagerException: org.apache.http.conn.HttpHostConnectException: Connect to npm.taobao.org:80 [npm.taobao.org/114.55.80.225] failed: Connection timed out: connect
	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:723)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:548)
	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:720)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:548)
	at io.github.bonigarcia.wdm.WebDriverManager.setup(WebDriverManager.java:260)
	at com.colt.test.Chrometest.main(Chrometest.java:30)
Caused by: org.apache.http.conn.HttpHostConnectException: Connect to npm.taobao.org:80 [npm.taobao.org/114.55.80.225] failed: Connection timed out: connect
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:158)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at io.github.bonigarcia.wdm.HttpClient.execute(HttpClient.java:159)
	at io.github.bonigarcia.wdm.WebDriverManager.getDriversFromMirror(WebDriverManager.java:991)
	at io.github.bonigarcia.wdm.ChromeDriverManager.getDrivers(ChromeDriverManager.java:83)
	at io.github.bonigarcia.wdm.WebDriverManager.filterCandidateUrls(WebDriverManager.java:739)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:534)
	... 4 more
Caused by: java.net.ConnectException: Connection timed out: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:74)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141)
	... 18 more

**Comment by bonigarcia** [comment]
That version does not exist. Try with 76.0.3809.126. And call WebDriverManager just once:

```
WebDriverManager.chromedriver().version("76.0.3809.126").setup();
```

**Comment by BobIT37** [comment]
Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: session not created: This version of ChromeDriver only supports Chrome version 79

browser version is working but driver version is not working in latest webdrivermanager version

WebDriverManager.chromedriver().driverVersion("79.0").setup();

**Comment by gamedevshirious** [comment]
I found a workaround to download latest version of ChromeDriver via WebDriverManager
You could try something like,
```
WebDriver driver = null ;
boolean oldVersion = true;
String chromeVersion = "";
try {
    try{
		FileReader reader = new FileReader("chromeVersion.txt") ;
		BufferedReader br = new BufferedReader(reader) ;
		
		String line;
		
		while ((line = br.readLine()) != null){
			chromeVersion = line.trim();
		}
		reader.close();
	} catch (IOException e ) {}
	
	WebDriverManager.chromedriver().version(chromeVersion).setup();
	driver = new ChromeDriver() ;
} catch (Exception e) {
	oldVersion = false;
	String err = e.getMessage() ;
	chromeVersion = err.split("version is")[1].split("with binary path")[0].trim();
	try{
		FileWriter writer = new FileWriter("chromeVersion.txt", true) ;
		writer.write(chromeVersion) ;
		writer.close();
	} catch (IOException er ) {}
}

if (!oldVersion){
	WebDriverManager.chromedriver().version(chromeVersion).setup();
	driver = new ChromeDriver() ;
}

driver.get("https://www.google.com") ;
```
Hope it helps :)

**Comment by senthilhere2019** [comment]
Hi Boni,
Thanks for the wonderful work .It helps me a lot

I am facing the  issue with launching the chrome browser in jenkins

ERROR io.github.bonigarcia.wdm.WebDriverManager - There was an error managing chromedriver (latest version) 
(org.apache.hc.client5.http.HttpHostConnectException: Connect to https://chromedriver.storage.googleapis.com:443 [chromedriver.storage.googleapis.com/172.217.2.240, chromedriver.storage.googleapis.com/2607:f8b0:4000:811:0:0:0:2010] failed: Network is unreachable (connect failed))
