### ISSUE TITLE
Error launching tests with latest chrome version

### ISSUE THREAD

**Issue by ramsesdm** [bonigarcia/webdrivermanager#386]
**Description of the problem**: 
Launching test using latest stable Chrome version and exception appears and the test fails

**Browser and version**: 
Chrome 77.0.3865.90 (Official Build) (64-bit)

**Operating system**: 
MacOS Mojave

**WebDriverManager version**: 
3.7.1

**WebDriverManager use**: 

**WebDriverManager traces**: 

Here some logs:
`2019-09-24 21:13:31,054 [main] INFO  i.g.bonigarcia.wdm.WebDriverManager - Using chromedriver 77.0.3865.40 (since Google Chrome 77 is installed in your machine)
2019-09-24 21:13:31,070 [main] INFO  i.g.bonigarcia.wdm.WebDriverManager - Exporting webdriver.chrome.driver as /Users/myuser/.m2/repository/webdriver/chromedriver/mac64/77.0.3865.40/chromedriver`

`Driver info: driver.version: ChromeDriver
remote stacktrace: 0   chromedriver                        0x0000000100be3f09 chromedriver + 3694345
1   chromedriver                        0x0000000100b70fd3 chromedriver + 3223507
2   chromedriver                        0x000000010091058f chromedriver + 730511
3   chromedriver                        0x000000010089efe5 chromedriver + 266213
4   chromedriver                        0x000000010089f618 chromedriver + 267800
5   chromedriver                        0x000000010089ce83 chromedriver + 257667
6   chromedriver                        0x000000010087823d chromedriver + 107069
7   chromedriver                        0x00000001008791d5 chromedriver + 111061
8   chromedriver                        0x0000000100b9f07f chromedriver + 3412095
9   chromedriver                        0x0000000100babced chromedriver + 3464429
10  chromedriver                        0x0000000100baba78 chromedriver + 3463800
11  chromedriver                        0x0000000100b7e959 chromedriver + 3279193
12  chromedriver                        0x0000000100bac548 chromedriver + 3466568
13  chromedriver                        0x0000000100b931b7 chromedriver + 3363255
14  chromedriver                        0x0000000100bca474 chromedriver + 3589236
15  chromedriver                        0x0000000100be9ce7 chromedriver + 3718375
16  libsystem_pthread.dylib             0x00007fff5a2c92eb _pthread_body + 126
17  libsystem_pthread.dylib             0x00007fff5a2cc249 _pthread_start + 66
18  libsystem_pthread.dylib             0x00007fff5a2c840d thread_start + 13

	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_211]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_211]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_211]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_211]
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$errorHandler$0(W3CHandshakeResponse.java:62) ~[selenium-remote-driver-3.141.59.jar:na]
	at org.openqa.selenium.remote.HandshakeResponse.lambda$getResponseFunction$0(HandshakeResponse.java:30) ~[selenium-remote-driver-3.141.59.jar:na]
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:126) ~[selenium-remote-driver-3.141.59.jar:na]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[na:1.8.0_211]
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958) ~[na:1.8.0_211]
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126) ~[na:1.8.0_211]
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498) ~[na:1.8.0_211]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485) ~[na:1.8.0_211]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[na:1.8.0_211]
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152) ~[na:1.8.0_211]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_211]
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464) ~[na:1.8.0_211]
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:128) ~[selenium-remote-driver-3.141.59.jar:na]
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:74) ~[selenium-remote-driver-3.141.59.jar:na]
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136) ~[selenium-remote-driver-3.141.59.jar:na]
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83) ~[selenium-remote-driver-3.141.59.jar:na]
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552) ~[selenium-remote-driver-3.141.59.jar:na]
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213) ~[selenium-remote-driver-3.141.59.jar:na]
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131) ~[selenium-remote-driver-3.141.59.jar:na]
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:181) ~[selenium-chrome-driver-3.141.59.jar:na]
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:147) ~[selenium-chrome-driver-3.141.59.jar:na]`

**Error trace**:

**Comment by rmoralesuscs** [comment]
Any luck with this issue? I have the same setup and im running into the same error.

**Comment by ramsesdm** [comment]
> Any luck with this issue? I have the same setup and im running into the same error.

So far, no.

**Comment by rmoralesuscs** [comment]
> > Any luck with this issue? I have the same setup and im running into the same error.
> 
> So far, no.
Bummer, btw hard coding the path with the driver already downloaded works but thats not a solution. Ill post back if I find a legit solution. thanks

**Comment by bonigarcia** [comment]
This is quite strange. Is it still happening?

**Comment by ramsesdm** [comment]
Seems that after the latest chrome update (78) evething is working
