### ISSUE TITLE
Selenium Grid :Not able to Start Hub

### ISSUE THREAD

**Issue by aruvimal** [bonigarcia/webdrivermanager#387]
When i try to run your script StartHub.java for starting the hub, i was getting below error. Please advise do we need any thing have to be done for running this script. 

Exception in thread "main" java.lang.NoSuchMethodError: com.beust.jcommander.JCommander.newBuilder()Lcom/beust/jcommander/JCommander$Builder;
	at org.openqa.grid.selenium.GridLauncherV3.parse(GridLauncherV3.java:217)
	at org.openqa.grid.selenium.GridLauncherV3.lambda$buildLaunchers$5(GridLauncherV3.java:255)
	at org.openqa.grid.selenium.GridLauncherV3.lambda$launch$0(GridLauncherV3.java:86)
	at java.util.Optional.map(Optional.java:215)
	at org.openqa.grid.selenium.GridLauncherV3.launch(GridLauncherV3.java:86)
	at org.openqa.grid.selenium.GridLauncherV3.main(GridLauncherV3.java:70)
	at com.ally.storefront.aem.tests.StartHub.main(StartHub.java:7)

**webdrivermanager.version - 3.6.2**

**Comment by bonigarcia** [comment]
This question does not belong to this repository but webdrivermanager-examples.
