### ISSUE TITLE
I am not able to open driver in GitLab pipeline getting below exception

### ISSUE THREAD

**Issue by thotakurianil** [bonigarcia/webdrivermanager#397]
I am not able to open driver in GitLab pipeline getting below exception

Webdrivermanager version : 2.2.3

Stacktrace:
com.usaa.ecm.authoring.automation.authui.testpages.LoginPageTest.setup FAILED
    io.github.bonigarcia.wdm.WebDriverManagerException: io.github.bonigarcia.wdm.WebDriverManagerException: A response error is detected: HTTP/1.1 403 Forbidden
        at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:471)
        at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:454)
        at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:468)
        at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:454)
        at io.github.bonigarcia.wdm.WebDriverManager.setup(WebDriverManager.java:215)
        at com.usaa.ecm.authoring.automation.authui.base.TestBase.intialization(TestBase.java:93)
        at com.usaa.ecm.authoring.automation.authui.testpages.LoginPageTest.setup(LoginPageTest.java:25)

        Caused by:
        io.github.bonigarcia.wdm.WebDriverManagerException: A response error is detected: HTTP/1.1 403 Forbidden
            at io.github.bonigarcia.wdm.HttpClient.execute(HttpClient.java:171)
            at io.github.bonigarcia.wdm.WebDriverManager.getDriversFromXml(WebDriverManager.java:780)
            at io.github.bonigarcia.wdm.ChromeDriverManager.getDrivers(ChromeDriverManager.java:54)
            at io.github.bonigarcia.wdm.WebDriverManager.filterCandidateUrls(WebDriverManager.java:487)
            at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:439)
            ... 5 more

**Comment by bonigarcia** [comment]
Use the latest version of WebDriverManager.
