### ISSUE TITLE
session not created: This version of ChromeDriver only supports Chrome version 79

### ISSUE THREAD

**Issue by kanthi84** [bonigarcia/webdrivermanager#402]
I am using Chrome Version 78.0.3904.87 (Official Build) (64-bit) in my MacBook.

I started getting this error. I tried to update my Chrome browser with version 79, but it seems like a beta version. The latest version for mac seems to be 78.0.3904.97.

Could you please help me with how to fix it and launch my browser??

-----------------------------------------------

[2019-11-13 20:36:14:891] [main] INFO ConfigLoader - SpockReports config loaded: {com.athaydes.spockframework.report.showCodeBlocks=false, com.athaydes.spockframework.report.template.TemplateReportCreator.reportFileExtension=md, com.athaydes.spockframework.report.testSourceRoots=src/test/groovy, com.athaydes.spockframework.report.IReportCreator=com.athaydes.spockframework.report.internal.HtmlReportCreator, com.athaydes.spockframework.report.outputDir=build/spock-reports, com.athaydes.spockframework.report.internal.HtmlReportCreator.inlineCss=true, com.athaydes.spockframework.report.internal.HtmlReportCreator.featureReportCss=spock-feature-report.css, com.athaydes.spockframework.report.hideEmptyBlocks=false, com.athaydes.spockframework.report.internal.HtmlReportCreator.summaryReportCss=spock-summary-report.css, com.athaydes.spockframework.report.projectVersion=Unknown, com.athaydes.spockframework.report.template.TemplateReportCreator.specTemplateFile=/templateReportCreator/spec-template.md, com.athaydes.spockframework.report.template.TemplateReportCreator.summaryTemplateFile=/templateReportCreator/summary-template.md, com.athaydes.spockframework.report.internal.HtmlReportCreator.excludeToc=false, com.athaydes.spockframework.report.template.TemplateReportCreator.enabled=true, com.athaydes.spockframework.report.projectName=, com.athaydes.spockframework.report.template.TemplateReportCreator.summaryFileName=summary.md, com.athaydes.spockframework.report.internal.HtmlReportCreator.printThrowableStackTrace=false, com.athaydes.spockframework.report.internal.HtmlReportCreator.enabled=true}[2019-11-13 20:36:17:705] [main] INFO BrowserManager - Reading https://chromedriver.storage.googleapis.com/ to seek [chromedriver]
[2019-11-13 20:36:18:792] [main] INFO BrowserManager - Latest version of [chromedriver] is 79.0.3945.16
[2019-11-13 20:36:18:805] [main] INFO BrowserManager - Exporting webdriver.chrome.driver as /Users/kanthi/.m2/repository/webdriver/chromedriver/mac64/79.0.3945.16/chromedriver
Starting ChromeDriver 79.0.3945.16 (93fcc21110c10dbbd49bbff8f472335360e31d05-refs/branch-heads/3945@{#262}) on port 26146
Only local connections are allowed.
Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.
[2019-11-13 20:36:20:877] [main] INFO BrowserManager - Reading https://chromedriver.storage.googleapis.com/ to seek [chromedriver]
[2019-11-13 20:36:21:697] [main] INFO BrowserManager - Latest version of [chromedriver] is 79.0.3945.16
[2019-11-13 20:36:21:697] [main] INFO BrowserManager - Exporting webdriver.chrome.driver as /Users/kanthi/.m2/repository/webdriver/chromedriver/mac64/79.0.3945.16/chromedriver
Starting ChromeDriver 79.0.3945.16 (93fcc21110c10dbbd49bbff8f472335360e31d05-refs/branch-heads/3945@{#262}) on port 40235
Only local connections are allowed.
Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.
[2019-11-13 20:36:22:931] [main] INFO BrowserManager - Reading https://chromedriver.storage.googleapis.com/ to seek [chromedriver]
[2019-11-13 20:36:23:688] [main] INFO BrowserManager - Latest version of [chromedriver] is 79.0.3945.16
[2019-11-13 20:36:23:689] [main] INFO BrowserManager - Exporting webdriver.chrome.driver as /Users/kanthi/.m2/repository/webdriver/chromedriver/mac64/79.0.3945.16/chromedriver
Starting ChromeDriver 79.0.3945.16 (93fcc21110c10dbbd49bbff8f472335360e31d05-refs/branch-heads/3945@{#262}) on port 33794
Only local connections are allowed.
Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.
[2019-11-13 20:36:24:943] [main] INFO BrowserManager - Reading https://chromedriver.storage.googleapis.com/ to seek [chromedriver]
[2019-11-13 20:36:25:650] [main] INFO BrowserManager - Latest version of [chromedriver] is 79.0.3945.16
[2019-11-13 20:36:25:650] [main] INFO BrowserManager - Exporting webdriver.chrome.driver as /Users/kanthi/.m2/repository/webdriver/chromedriver/mac64/79.0.3945.16/chromedriver
Starting ChromeDriver 79.0.3945.16 (93fcc21110c10dbbd49bbff8f472335360e31d05-refs/branch-heads/3945@{#262}) on port 10369
Only local connections are allowed.
Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.

geb.driver.DriverCreationException: failed to create driver from callback 'script1573657575342727031110$_run_closure1@5f80fa43'

	at geb.driver.CallbackDriverFactory.getDriver(CallbackDriverFactory.groovy:35)
	at geb.driver.CachingDriverFactory.getDriver_closure3(CachingDriverFactory.groovy:85)
	at geb.driver.CachingDriverFactory.getDriver_closure3(CachingDriverFactory.groovy)
	at geb.driver.CachingDriverFactory$SimpleCache.get(CachingDriverFactory.groovy:32)
	at geb.driver.CachingDriverFactory.getDriver(CachingDriverFactory.groovy:84)
	at geb.Configuration.createDriver(Configuration.groovy:382)
	at geb.Configuration.getDriver(Configuration.groovy:371)
	at geb.Browser.getDriver(Browser.groovy:108)
	at geb.navigator.factory.BrowserBackedNavigatorFactory.<init>(BrowserBackedNavigatorFactory.groovy:35)
	at geb.Configuration.createNavigatorFactory(Configuration.groovy:417)
	at geb.Browser.createNavigatorFactory(Browser.groovy:130)
	at geb.Browser.getNavigatorFactory(Browser.groovy:118)
	at geb.Page.init(Page.groovy:131)
	at geb.Browser.createPage(Browser.groovy:875)
	at geb.Browser.at(Browser.groovy:336)
	at geb.spock.GebSpec.methodMissing(GebSpec.groovy:56)
	at specs.GoogleTestSpec.As a user I can Search for Digital Reasoning home page in Google(GoogleTestSpec.groovy:10)
Caused by: org.openqa.selenium.SessionNotCreatedException: session not created: This version of ChromeDriver only supports Chrome version 79
  (Driver info: chromedriver=79.0.3945.16 (93fcc21110c10dbbd49bbff8f472335360e31d05-refs/branch-heads/3945@{#262}),platform=Mac OS X 10.14.6 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 1.65 seconds
Build info: version: '2.52.0', revision: '4c2593cfc3689a7fcd7be52549167e5ccc93ad28', time: '2016-02-11 11:22:43'
System info: host: '192.168.1.10', ip: '192.168.1.10', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14.6', java.version: '1.8.0_121'
Driver info: org.openqa.selenium.chrome.ChromeDriver
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:249)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:144)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:170)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:138)
	at script1573657575342727031110.run_closure1(script1573657575342727031110.groovy:16)
	at script1573657575342727031110.run_closure1(script1573657575342727031110.groovy)
	at geb.driver.CallbackDriverFactory.getDriver(CallbackDriverFactory.groovy:29)
	... 16 more

**Comment by bonigarcia** [comment]
Use the latest version of WebDriverManager.
