### ISSUE TITLE
chromedriver().setup() results in `java.lang.NoSuchMethodError: org.apache.commons.io.IOUtils.toString(Ljava/io/InputStream;Ljava/nio/charset/Charset;)Ljava/lang/String;`

### ISSUE THREAD

**Issue by SlavikCA** [bonigarcia/webdrivermanager#404]
The code:
```Java
WebDriverManager.chromedriver().setup();
```
Results in this exception:
```
java.lang.NoSuchMethodError: org.apache.commons.io.IOUtils.toString(Ljava/io/InputStream;Ljava/nio/charset/Charset;)Ljava/lang/String;

	at io.github.bonigarcia.wdm.Shell.runAndWaitNoLog(Shell.java:66)
	at io.github.bonigarcia.wdm.Shell.runAndWaitArray(Shell.java:56)
	at io.github.bonigarcia.wdm.Shell.runAndWait(Shell.java:50)
	at io.github.bonigarcia.wdm.WebDriverManager.getBrowserVersionInWindows(WebDriverManager.java:1210)
	at io.github.bonigarcia.wdm.WebDriverManager.getDefaultBrowserVersion(WebDriverManager.java:1175)
	at io.github.bonigarcia.wdm.ChromeDriverManager.getBrowserVersion(ChromeDriverManager.java:103)
	at io.github.bonigarcia.wdm.WebDriverManager.detectDriverVersionFromBrowser(WebDriverManager.java:581)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:509)
	at io.github.bonigarcia.wdm.WebDriverManager.setup(WebDriverManager.java:260)
	at io.github.bonigarcia.wdm.WebDriverManager$setup$0.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:119)
```

So, failing on this code:
https://github.com/bonigarcia/webdrivermanager/blob/8b0e927bc79420de98e93849173672386bed81f1/src/main/java/io/github/bonigarcia/wdm/Shell.java#L66

Env:
- running tests on Windows 10 x64
- Java 8, Groovy 2.5.5
- webdrivermanager 3.7.1

**Comment by SlavikCA** [comment]
Issue reproduced on `Oracle Linux Server 7.7` 4.14.35-1902.6.6.el7uek.x86_64

**Comment by SlavikCA** [comment]
I found, that this issue was caused by adding `com.browserstack:browserstack-local-java:1.0.3` dependency to the project.

`webdrivermanager` uses `commons-io:2.6`
```
+--- io.github.bonigarcia:webdrivermanager:3.7.1
|    +--- commons-io:commons-io:2.6
```

and `browserstack-local-java` uses apparently incompatible `commons-io:1.3.2`
```
+--- com.browserstack:browserstack-local-java:1.0.3
|    +--- org.apache.commons:commons-io:1.3.2
```

Now, I need to figure out how to resolve these dependencies
