### ISSUE TITLE
Caused by: io.github.bonigarcia.wdm.WebDriverManagerException: geckodriver 0.25.0 for WIN64 not found in http://npm.taobao.org/mirrors/geckodriver

### ISSUE THREAD

**Issue by xxammuxx** [bonigarcia/webdrivermanager#410]
**Description of the problem**:
Getting below error when running mvn clean test
"Caused by: io.github.bonigarcia.wdm.WebDriverManagerException: geckodriver 0.25.0 for WIN64 not found in http://npm.taobao.org/mirrors/geckodriver"

**Operating system**: Windows 10 64 bit

**Error trace**:
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
2019-11-28 16:26:05 [main] DEBUG io.github.bonigarcia.wdm.Preferences - Preference firefox=68 (valid until 2019-11-29 16:05:33)
2019-11-28 16:26:05 [main] DEBUG io.github.bonigarcia.wdm.Preferences - Preference firefox68=0.25.0 (valid until 2019-11-29 16:05:33)
2019-11-28 16:26:05 [main] INFO  i.g.bonigarcia.wdm.WebDriverManager - Using geckodriver 0.25.0 (since Mozilla Firefox 68 is installed in your machine)
2019-11-28 16:26:05 [main] INFO  i.g.bonigarcia.wdm.WebDriverManager - Reading https://api.github.com/repos/mozilla/geckodriver/releases to seek geckodriver
2019-11-28 16:26:27 [main] WARN  i.g.bonigarcia.wdm.WebDriverManager - There was an error managing geckodriver 0.25.0 (Connect to api.github.com:443 [api.github.com/140.82.113.6] failed: Connection timed out: connect) ... trying again using cache and mirror
2019-11-28 16:26:27 [main] INFO  i.g.bonigarcia.wdm.WebDriverManager - Reading http://npm.taobao.org/mirrors/geckodriver to seek geckodriver
2019-11-28 16:26:28 [main] ERROR i.g.bonigarcia.wdm.WebDriverManager - geckodriver 0.25.0 for WIN64 not found in http://npm.taobao.org/mirrors/geckodriver
2019-11-28 16:26:28 [main] ERROR i.g.bonigarcia.wdm.WebDriverManager - There was an error managing geckodriver 0.25.0 (geckodriver 0.25.0 for WIN64 not found in http://npm.taobao.org/mirrors/geckodriver)
io.github.bonigarcia.wdm.WebDriverManagerException: geckodriver 0.25.0 for WIN64 not found in http://npm.taobao.org/mirrors/geckodriver
        at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:556)
        at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:751)
        at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:563)
        at io.github.bonigarcia.wdm.WebDriverManager.setup(WebDriverManager.java:260)
        at io.github.bonigarcia.wdm.test.FirefoxTest.setupClass(FirefoxTest.java:47)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.junit.runners.Suite.runChild(Suite.java:128)
        at org.junit.runners.Suite.runChild(Suite.java:27)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)
        at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)
        at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:107)
        at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:83)
        at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
        at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:161)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
Running io.github.bonigarcia.wdm.test.FirefoxTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.002 sec <<< FAILURE! - in io.github.bonigarcia.wdm.test.FirefoxTest
io.github.bonigarcia.wdm.test.FirefoxTest  Time elapsed: 0.001 sec  <<< ERROR!
io.github.bonigarcia.wdm.WebDriverManagerException: io.github.bonigarcia.wdm.WebDriverManagerException: geckodriver 0.25.0 for WIN64 not found in http://npm.taobao.org/mirrors/geckodriver
        at io.github.bonigarcia.wdm.test.FirefoxTest.setupClass(FirefoxTest.java:47)
Caused by: io.github.bonigarcia.wdm.WebDriverManagerException: geckodriver 0.25.0 for WIN64 not found in http://npm.taobao.org/mirrors/geckodriver
        at io.github.bonigarcia.wdm.test.FirefoxTest.setupClass(FirefoxTest.java:47)

**Comment by bonigarcia** [comment]
Please follow the issue template (e.g. it is missing WebDiverManager version you are using).
