### ISSUE TITLE
I am not able to start Chrome with my test framework, it gives following error:

### ISSUE THREAD

**Issue by gulhankarali** [bonigarcia/webdrivermanager#422]
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

io.github.bonigarcia.wdm.WebDriverManagerException: io.github.bonigarcia.wdm.WebDriverManagerException: chromedriver <!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>chromedriverLATEST_RELEASE Mirror</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <link href="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" media="screen">
    <style>
      #fork{position:fixed;top:0;right:0;_position:absolute;z-index: 10000;}
      .bottom{margin: 20px auto; width: 100%; text-align: center;}
      .container{width: 1080px; margin: 50px auto;}
    </style>
  <head>
  <body>
    <a href="https://github.com/cnpm/cnpmjs.org" id="fork" target="_blank">
        <img alt="Fork me on GitHub" src="//s3.amazonaws.com/github/ribbons/forkme_right_darkblue_121621.png">
    </a>
    <div class="container">
      <h1>Mirror index of <a target="_blank" href=""></a></h1>
<hr>
<pre><a href="../">../</a>
</pre>
<hr>
    </div>
      <hr/>
      <div class="bottom">
        Copyright &copy; <a href="https://github.com/cnpm" target="_blank">cnpm</a>
        |
        <a href="/">Home</a>
    </div>
  </body>
</html>
 for MAC64 not found in http://npm.taobao.org/mirrors/chromedriver
    at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:754)
    at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:563)
    at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:751)
    at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:563)
    at io.github.bonigarcia.wdm.WebDriverManager.setup(WebDriverManager.java:260)
    at com.cybertek.utilities.Driver.get(Driver.java:25)
    at com.cybertek.tests.TestBase.setUpMethod(TestBase.java:55)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
    at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:63)
    at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:348)
    at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:302)
    at org.testng.internal.TestInvoker.runConfigMethods(TestInvoker.java:695)
    at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:523)
    at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
    at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
    at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
    at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
    at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
    at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
    at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
    at org.testng.TestRunner.privateRun(TestRunner.java:766)
    at org.testng.TestRunner.run(TestRunner.java:587)
    at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
    at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
    at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
    at org.testng.SuiteRunner.run(SuiteRunner.java:286)
    at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
    at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
    at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
    at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
    at org.testng.TestNG.runSuites(TestNG.java:1039)
    at org.testng.TestNG.run(TestNG.java:1007)
    at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73)
    at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
Caused by: io.github.bonigarcia.wdm.WebDriverManagerException: chromedriver <!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>chromedriverLATEST_RELEASE Mirror</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <link href="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" media="screen">
    <style>
      #fork{position:fixed;top:0;right:0;_position:absolute;z-index: 10000;}
      .bottom{margin: 20px auto; width: 100%; text-align: center;}
      .container{width: 1080px; margin: 50px auto;}
    </style>
  <head>
  <body>
    <a href="https://github.com/cnpm/cnpmjs.org" id="fork" target="_blank">
        <img alt="Fork me on GitHub" src="//s3.amazonaws.com/github/ribbons/forkme_right_darkblue_121621.png">
    </a>
    <div class="container">
      <h1>Mirror index of <a target="_blank" href=""></a></h1>
<hr>
<pre><a href="../">../</a>
</pre>
<hr>
    </div>
      <hr/>
      <div class="bottom">
        Copyright &copy; <a href="https://github.com/cnpm" target="_blank">cnpm</a>
        |
        <a href="/">Home</a>
    </div>
  </body>
</html>

 or MAC64 not found in http://npm.taobao.org/mirrors/chromedriver
    at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:556)
    ... 36 more
Test ignored.

===============================================
Default Suite
Total tests run: 1, Passes: 0, Failures: 0, Skips: 1
Configuration Failures: 1, Skips: 1
===============================================
Process finished with exit code 0

**Comment by bonigarcia** [comment]
Please follow the issue template to report a problem.
