### ISSUE TITLE
ChromeDriver has been crash when running

### ISSUE THREAD

**Issue by phuoctrung-ppt** [bonigarcia/webdrivermanager#434]
Console log: `org.openqa.selenium.SessionNotCreatedException: session not created: This version of ChromeDriver only supports Chrome version 80
Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:19:58.91Z'
System info: host: 'XXXXX', ip: '172.20.8.17', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_131'
Driver info: driver.version: ChromeDriver
remote stacktrace: Backtrace:
	Ordinal0 [0x01240AE3+1706723]
	Ordinal0 [0x011A68C1+1075393]
	Ordinal0 [0x0111DFA9+516009]
	Ordinal0 [0x010B0554+66900]
	Ordinal0 [0x010ACCE2+52450]
	Ordinal0 [0x010CBFD7+180183]
	Ordinal0 [0x010CBDDD+179677]
	Ordinal0 [0x010C9D4B+171339]
	Ordinal0 [0x010B1D4A+73034]
	Ordinal0 [0x010B2DC0+77248]
	Ordinal0 [0x010B2D59+77145]
	Ordinal0 [0x011BBB37+1162039]
	GetHandleVerifier [0x012DA7C6+508998]
	GetHandleVerifier [0x012DA504+508292]
	GetHandleVerifier [0x012EF617+594583]
	GetHandleVerifier [0x012DB036+511158]
	Ordinal0 [0x011B3FFC+1130492]
	Ordinal0 [0x011BD49B+1168539]
	Ordinal0 [0x011BD603+1168899]
	Ordinal0 [0x011D5B05+1268485]
	BaseThreadInitThunk [0x76860419+25]
	RtlGetAppContainerNamedObjectPath [0x7763662D+237]
	RtlGetAppContainerNamedObjectPath [0x776365FD+189]

	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$new$0(W3CHandshakeResponse.java:57)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$getResponseFunction$2(W3CHandshakeResponse.java:104)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:122)
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Unknown Source)
	at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.findFirst(Unknown Source)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:125)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:73)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:548)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:212)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:130)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:181)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:168)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:123)
	at rsqa.common.utils.DriverProvider.getDriver(DriverProvider.java:50)
	at rsqa.testsuites.rapidresults.adminsettings.procedurecode.TestUpdateProcedureCode.environmentSetup(TestUpdateProcedureCode.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:514)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:215)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.TestRunner.beforeRun(TestRunner.java:656)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
`

**Browser and version**: ChromeDriver version 80

**Operating system**: Windows x64
I have issue , ChromeDriver has been crash when running source. At pom, i used <dependency>
	    <groupId>org.seleniumhq.selenium</groupId>
	    <artifactId>selenium-firefox-driver</artifactId>
	    <version>3.14.0</version>
	</dependency>
   <dependency>
	    <groupId>io.github.bonigarcia</groupId>
	    <artifactId>webdrivermanager</artifactId>
	    <version>3.0.0</version>
	</dependency>	
	<dependency>
		<groupId>autoitx4java</groupId>
		<artifactId>autoitx4java</artifactId>
		<version>1.0.0</version>
	</dependency>

Hi Bonigarcia, please help me fixed it! Thanks and have nice day

**Comment by phuoctrung-ppt** [comment]
i have resolved ticket, issue will closed. Thanks

**Comment by rciddagoni** [comment]
Hi Phuoctrung, can you please share ,how did the issue resolved. thank in advance.
