### ISSUE TITLE
Automatic PhantomJS driver download doesn't work anymore

### ISSUE THREAD

**Issue by ndtreviv** [bonigarcia/webdrivermanager#44]
As of this morning we're getting this:

```
java.lang.RuntimeException: org.openqa.selenium.NoSuchElementException: Unable to locate element with ID: available-downloads
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'
System info: host: 'Nathans-MacBook-Pro.local', ip: '10.0.50.166', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.6', java.version: '1.7.0_79'
Driver info: driver.version: HtmlUnitDriver
	at io.github.bonigarcia.wdm.BrowserManager.manage(BrowserManager.java:224)
	at io.github.bonigarcia.wdm.BrowserManager.setup(BrowserManager.java:96)
	at io.github.bonigarcia.wdm.BrowserManager.setup(BrowserManager.java:75)
	at com.cameraforensics.ui.DriverFactory.createNewDriver(DriverFactory.java:40)
	at com.cameraforensics.ui.DriverFactory.access$000(DriverFactory.java:14)
	at com.cameraforensics.ui.DriverFactory$1.initialValue(DriverFactory.java:22)
	at com.cameraforensics.ui.DriverFactory$1.initialValue(DriverFactory.java:19)
	at java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:160)
	at java.lang.ThreadLocal.get(ThreadLocal.java:150)
	at com.cameraforensics.ui.DriverFactory.get(DriverFactory.java:27)
	at com.cameraforensics.ui.UserInterfaceTest.setup(UserInterfaceTest.java:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:326)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:88)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:58)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:291)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:72)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:289)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:59)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:269)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:365)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:105)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:56)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:64)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.messaging.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.messaging.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:360)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.openqa.selenium.NoSuchElementException: Unable to locate element with ID: available-downloads
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'
System info: host: 'Nathans-MacBook-Pro.local', ip: '10.0.50.166', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.6', java.version: '1.7.0_79'
Driver info: driver.version: HtmlUnitDriver
	at org.openqa.selenium.htmlunit.HtmlUnitDriver.findElementById(HtmlUnitDriver.java:1008)
	at org.openqa.selenium.By$ById.findElement(By.java:218)
	at org.openqa.selenium.htmlunit.HtmlUnitDriver$5.call(HtmlUnitDriver.java:1707)
	at org.openqa.selenium.htmlunit.HtmlUnitDriver$5.call(HtmlUnitDriver.java:1703)
	at org.openqa.selenium.htmlunit.HtmlUnitDriver.implicitlyWaitFor(HtmlUnitDriver.java:1357)
	at org.openqa.selenium.htmlunit.HtmlUnitDriver.findElement(HtmlUnitDriver.java:1703)
	at org.openqa.selenium.htmlunit.HtmlUnitDriver.findElement(HtmlUnitDriver.java:595)
	at io.github.bonigarcia.wdm.PhantomJsDriverManager.getDrivers(PhantomJsDriverManager.java:72)
```

If I go to the driver downloads URL, I can't see an `available-downloads` identified table. Could it be that they've changed their page somehow?

**Comment by ndtreviv** [comment]
Just noticed that we're still on 1.4.3. Trying 1.4.6 to see if the same thing happens.

**Comment by ndtreviv** [comment]
Nope. It's still the same :( Looks like maybe they've moved it from a table to a tab.

**Comment by hsirk** [comment]
just found the issue and yes page got changed and id is 'downloads' not 'available-downloads' 
https://bitbucket.org/ariya/phantomjs/downloads/
could you please release a fix 
WebElement downloadsTable = driver
				.findElement(By.id("available-downloads"));

**Comment by ndtreviv** [comment]
It's actually called `uploaded-files` now.

So changing this:
`WebElement downloadsTable = driver.findElement(By.id("available-downloads"));`
to this:
`WebElement downloadsTable = driver.findElement(By.id("uploaded-files"));`
should work.

**Comment by bonigarcia** [comment]
I have just released version 1.4.7 with the buf-fix provided in #45. It will be available on Maven Central in a few minutes.

Thanks for reporting and contributing.

**Comment by hsirk** [comment]
java.lang.RuntimeException: java.lang.RuntimeException: [phantomjs] 2.1.2 for win64 not found in https://bitbucket.org/ariya/phantomjs/downloads/

doesnt support all OS ?

**Comment by ndtreviv** [comment]
:( Dang. I didn't actually check Windows. Sorry dude.

**Comment by hsirk** [comment]
could you please update on fix to handle win64 or other OS ?

**Comment by ndtreviv** [comment]
@hsirk There is no version 2.1.2 on that downloads list. It would work, if that version were there. Sorry.

**Comment by ndtreviv** [comment]
PS: 2.1.1 should be just fine.

**Comment by hsirk** [comment]
thank it works now
quick help how to suppress the warnings / info / errors printing on console ? but no errors from selenium scripts and all goes fine

[INFO  - 2016-08-05T04:51:07.420Z] GhostDriver - Main - running on port 43981
phantomjs://platform/console++.js:263 in error
[ERROR - 2016-08-05T04:51:14.776Z] RouterReqHand - _handle.error - {"name":"Invalid Command Method","message":"{\"headers\":{\"Accept-Encoding\":\"gzip,deflate\",\"Cache-Control\":\"no-cache\",\"Connection\":\"Keep-Alive\",\"Host\":\"localhost:43981\",\"User-Agent\":\"Apache-HttpClient/4.3 (java 1.5)\"},\"httpVersion\":\"1.1\",\"method\":\"GET\",\"url\":\"/alert_text\",\"urlParsed\":{\"anchor\":\"\",\"query\":\"\",\"file\":\"alert_text\",\"directory\":\"/\",\"path\":\"/alert_text\",\"relative\":\"/alert_text\",\"port\":\"\",\"host\":\"\",\"password\":\"\",\"user\":\"\",\"userInfo\":\"\",\"authority\":\"\",\"protocol\":\"\",\"source\":\"/alert_text\",\"queryKey\":{},\"chunks\":[\"alert_text\"]},\"urlOriginal\":\"/session/38e09460-5ac8-11e6-a865-6bc8bb075cd4/alert_text\"}","line":202,"sourceURL":"phantomjs://code/session_request_handler.js","stack":"_handle@phantomjs://code/session_request_handler.js:202:66\n_reroute@phantomjs://code/request_handler.js:61:20\n_handle@phantomjs://code/router_request_handler.js:78:46"}

  phantomjs://platform/console++.js:263 in error

**Comment by ndtreviv** [comment]
This thread may help: https://github.com/detro/ghostdriver/issues/338

**Comment by hsirk** [comment]
yes, worked thanks !
