### ISSUE TITLE
Resolving of '~' in targetPath fails on windows using 8.3 naming format

### ISSUE THREAD

**Issue by xlemmingx** [bonigarcia/webdrivermanager#440]
**Description of the problem**: Resolving of **~** in targetPath leads to problems on windows systems using 8.3 format (see https://docs.microsoft.com/de-de/windows/win32/fileio/naming-a-file?redirectedfrom=MSDN). Current behaviour only works for UNIX-systems and there also the current way of replacing **~** anywhere in the path with System.getProperty("user.home") is not correct. This could be done if the path begins with **~** and is followed by a separator. Otherwise you can't use (valid) file paths containing **~** or the (also valid) UNIX descriptor ~anotheruser/path.

Example of failing resolve of a valid windows path:
_C:\user\abcdef~1\path_
p.e. valid resolve to _C:\user\abcdefghi\path_

**Browser and version**:  Chrome 80 but reproducible with all browsers

**Operating system**: Windows Server 2012 R2 Standard

**WebDriverManager version**: 3.8.1

**WebDriverManager use**: Maven dependency:
```
<dependency>
	<groupId>io.github.bonigarcia</groupId>
	<artifactId>webdrivermanager</artifactId>
	<version>3.8.1</version>
</dependency>
```

**WebDriverManager traces**: N.A.

**Error trace**: 
Caused by: java.lang.IllegalArgumentException: Parameter 'directory' is not a directory
	at org.apache.commons.io.FileUtils.validateListFilesParameters(FileUtils.java:545)
	at org.apache.commons.io.FileUtils.listFiles(FileUtils.java:521)
	at org.apache.commons.io.FileUtils.listFiles(FileUtils.java:691)
	at io.github.bonigarcia.wdm.WebDriverManager.getFilesInCache(WebDriverManager.java:926)
	at io.github.bonigarcia.wdm.WebDriverManager.getDriverFromCache(WebDriverManager.java:869)
	at io.github.bonigarcia.wdm.WebDriverManager.handleCache(WebDriverManager.java:860)
	at io.github.bonigarcia.wdm.WebDriverManager.downloadAndExport(WebDriverManager.java:557)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:547)
	... 23 more

**Comment by bonigarcia** [comment]
Thanks for reporting. I will improve this behavior for the next version of WebDriverManager.
