### ISSUE TITLE
Compatability  issue with Chrome V 79

### ISSUE THREAD

**Issue by Lakssh** [bonigarcia/webdrivermanager#453]
Hi,

I use Webdrivermanager version "3.7.1"  ,it was working fine till i upgrade chrome version to Version 79.0.3945.130 (Official Build) (64-bit) . Post upgrade , i get below error while running my scripts. Could you please help to resolve this issue. Tried to upgrade driver manager to 3.8.1 But no luck!!!

Driver info: driver.version: ChromeDriver
remote stacktrace: Backtrace:
        Ordinal0 [0x002D1B43+1448771]
        Ordinal0 [0x00255A31+940593]
        Ordinal0 [0x001E2293+467603]
        Ordinal0 [0x0017F27E+62078]
        Ordinal0 [0x0017BBBD+48061]
        Ordinal0 [0x00198D09+167177]
        Ordinal0 [0x001988DD+166109]
        Ordinal0 [0x00196FEB+159723]
        Ordinal0 [0x001809F6+68086]
        Ordinal0 [0x00181990+72080]
        Ordinal0 [0x00181929+71977]
        GetHandleVerifier [0x00412E8C+1172172]
        GetHandleVerifier [0x0036FE55+504469]
        GetHandleVerifier [0x0036FBF0+503856]
        Ordinal0 [0x002DC9C8+1493448]
        GetHandleVerifier [0x0037062A+506474]
        Ordinal0 [0x00267156+1012054]
        Ordinal0 [0x00266FCF+1011663]
        Ordinal0 [0x0027135B+1053531]
        Ordinal0 [0x002714C3+1053891]
        Ordinal0 [0x002704F5+1049845]
        BaseThreadInitThunk [0x77628674+36]
        RtlGetAppContainerNamedObjectPath [0x77925E17+311]
        RtlGetAppContainerNamedObjectPath [0x77925DE7+263]

        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$new$0(W3CHandshakeResponse.java:57)
        at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$getResponseFunction$2(W3CHandshakeResponse.java:104)
        at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:123)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
        at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
        at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:126)
        at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:73)
        at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)
        at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
        at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:207)
        at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:130)
        at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:181)
        at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:168)
        at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:157)
        at com.cognizant.framework.WebDriverFactory.getWebDriver(WebDriverFactory.java:122)
        at com.cognizant.framework.DriverFactory.createWebDriverInstance(DriverFactory.java:33)
        at com.cognizant.framework.TestHarness.invokeDriver(TestHarness.java:40)
        at com.cognizant.steps.CukeHooks.setUp(CukeHooks.java:44)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at cucumber.runtime.Utils$1.call(Utils.java:26)
        at cucumber.runtime.Timeout.timeout(Timeout.java:16)
        at cucumber.runtime.Utils.invoke(Utils.java:20)
        at cucumber.runtime.java.JavaHookDefinition.execute(JavaHookDefinition.java:65)
        at cucumber.runner.HookDefinitionMatch.runStep(HookDefinitionMatch.java:16)
        at cucumber.runner.TestStep.executeStep(TestStep.java:65)
        at cucumber.runner.TestStep.run(TestStep.java:50)
        at cucumber.runner.TestCase.run(TestCase.java:42)
        at cucumber.runner.Runner.runPickle(Runner.java:50)
        at io.cucumber.testng.TestNGCucumberRunner.runScenario(TestNGCucumberRunner.java:79)
        at io.cucumber.testng.AbstractTestNGCucumberTests.runScenario(AbstractTestNGCucumberTests.java:24)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
        at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
        at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
        at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)
        at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

Thanks,
Lakshmanan C

**Comment by ricksbrown** [comment]
Looks similar to: https://github.com/bonigarcia/webdrivermanager/issues/318#issuecomment-566649653

**Comment by bonigarcia** [comment]
Please follow the issue template to report any problem. Remember to include the WebDriverManager traces (`io.github.bonigarcia.wdm.*`) at `DEBUG` level. Otherwise, it is impossible to know what is happening.
