### ISSUE TITLE
java.lang.NoSuchMethodError: org.apache.commons.io.IOUtils.toString(Ljava/io/InputStream;Ljava/nio/charset/Charset;)Ljava/lang/String;

### ISSUE THREAD

**Issue by saikrishnameda248** [bonigarcia/webdrivermanager#459]
Unable to start / open chrome browser through webDriverManager(3.4.1) version. getting below error 
java.lang.NoSuchMethodError: org.apache.commons.io.IOUtils.toString(Ljava/io/InputStream;Ljava/nio/charset/Charset;)Ljava/lang/String;
OS : Windows 10
Architecture : 64 bit

![image](https://user-images.githubusercontent.com/57066046/78871273-1886e280-7a65-11ea-8d29-139573dbbced.png)

**Comment by engzizo79** [comment]
Same Problem. webDriverManager v3.8.1 and Chrome Version 81.0.4044.92 on Windows 10
`     java.lang.NoSuchMethodError: 'java.lang.String org.apache.commons.io.IOUtils.toString(java.io.InputStream, java.nio.charset.Charset)'
	at io.github.bonigarcia.wdm.Shell.runAndWaitNoLog(Shell.java:66)
	at io.github.bonigarcia.wdm.Shell.runAndWaitArray(Shell.java:56)
	at io.github.bonigarcia.wdm.Shell.runAndWait(Shell.java:50)
	at io.github.bonigarcia.wdm.WebDriverManager.getBrowserVersionInWindows(WebDriverManager.java:1180)
	at io.github.bonigarcia.wdm.WebDriverManager.getDefaultBrowserVersion(WebDriverManager.java:1146)
	at io.github.bonigarcia.wdm.ChromeDriverManager.getBrowserVersion(ChromeDriverManager.java:103)
	at io.github.bonigarcia.wdm.WebDriverManager.detectDriverVersionFromBrowser(WebDriverManager.java:558)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:494)
	at io.github.bonigarcia.wdm.WebDriverManager.setup(WebDriverManager.java:260)`

**Comment by bonigarcia** [comment]
Please follow the issue template to report any problem.

**Comment by Praveen-jr21** [comment]
> Please follow the issue template to report any problem.

Getting below error
Failure in before hook:Hooks.beforeScenario(Scenario)
Message: java.lang.NoSuchMethodError: org.apache.commons.io.IOUtils.toString(L

**Comment by asolntsev** [comment]
This is a typical dependency conflict.
This post describes how to resolve such conflicts: 
https://www.google.com/url?sa=t&source=web&rct=j&url=https://www.javaadvent.com/2020/12/how-to-debug-dependency-conflicts-in-maven-and-gradle.html/amp&ved=2ahUKEwigzZ7s_d7tAhWCtYsKHZ9LBMkQFjACegQIDBAB&usg=AOvVaw0Q4YeiFCeaP4W6MeCduScJ&ampcf=1
