### ISSUE TITLE
webdriver: session not created: This version of ChromeDriver only supports Chrome version 81

### ISSUE THREAD

**Issue by sriramkukkadapu** [bonigarcia/webdrivermanager#462]
When i run my tests with command npm run test i am facing above error

Version of webdriver-manager:  12.1.0

2020-04-12T11:11:20.395Z INFO webdriver: [POST] http://localhost:9515/session
2020-04-12T11:11:20.395Z INFO webdriver: DATA {
  capabilities: { alwaysMatch: { browserName: 'chrome' }, firstMatch: [ {} ] },
  desiredCapabilities: { browserName: 'chrome' }
}
[0-0] 2020-04-12T11:11:21.498Z ERROR webdriver: Request failed with status 500 due to session not created: session not created: This version of ChromeDriver only supports Chrome version 81
[0-0] 2020-04-12T11:11:21.498Z ERROR webdriver: session not created: session not created: This version of ChromeDriver only supports Chrome version 81
    at getErrorFromResponseBody (/Users/sriramku/Documents/webdriver-io-practice/node_modules/webdriver/build/utils.js:124:10)
    at WebDriverRequest._request (/Users/sriramku/Documents/webdriver-io-practice/node_modules/webdriver/build/request.js:118:56)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async startWebDriverSession (/Users/sriramku/Documents/webdriver-io-practice/node_modules/webdriver/build/utils.js:41:16)
    at async Function.newSession (/Users/sriramku/Documents/webdriver-io-practice/node_modules/webdriver/build/index.js:46:23)
    at async remote (/Users/sriramku/Documents/webdriver-io-practice/node_modules/webdriverio/build/index.js:66:20)
    at async Runner._startSession (/Users/sriramku/Documents/webdriver-io-practice/node_modules/@wdio/runner/build/index.js:212:50)
    at async Runner._initSession (/Users/sriramku/Documents/webdriver-io-practice/node_modules/@wdio/runner/build/index.js:181:21)
    at async Runner.run (/Users/sriramku/Documents/webdriver-io-practice/node_modules/@wdio/runner/build/index.js:99:15)
2020-04-12T11:11:21.499Z ERROR @wdio/runner: Error: Failed to create session.
session not created: This version of ChromeDriver only supports Chrome version 81
    at startWebDriverSession (/Users/sriramku/Documents/webdriver-io-practice/node_modules/webdriver/build/utils.js:45:11)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[0-0]  Error:  Failed to create session.
session not created: This version of ChromeDriver only supports Chrome version 81
[0-0] FAILED in chrome - /test/element.js
2020-04-12T11:11:21.610Z INFO @wdio/cli:launcher: Run onComplete hook

Spec Files:      0 passed, 1 failed, 1 total (100% completed) in 00:00:07

2020-04-12T11:11:21.632Z INFO @wdio/local-runner: Shutting down spawned worker
2020-04-12T11:11:21.886Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully
2020-04-12T11:11:21.886Z INFO @wdio/local-runner: shutting down

**Comment by Suban5** [comment]
I am having a same issue. The same code was working fine earlier. When i try to run same code, i am getting following error in my ubuntu system:

```
[main] INFO io.github.bonigarcia.wdm.WebDriverManager - Exporting webdriver.chrome.driver as /home/suban/.m2/repository/webdriver/chromedriver/linux64/81.0.4044.69/chromedriver
Starting ChromeDriver 81.0.4044.69 (6813546031a4bc83f717a2ef7cd4ac6ec1199132-refs/branch-heads/4044@{#776}) on port 5899
Only local connections are allowed.
Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.
FAILED CONFIGURATION: @BeforeClass setup("chrome")
org.openqa.selenium.SessionNotCreatedException: session not created: This version of ChromeDriver only supports Chrome version 81
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'suban', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '5.3.0-46-generic', java.version: '11.0.6'
Driver info: driver.version: ChromeDriver
remote stacktrace: #0 0x5653cb4b65b9 <unknown>

        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$errorHandler$0(W3CHandshakeResponse.java:62)
        at org.openqa.selenium.remote.HandshakeResponse.lambda$getResponseFunction$0(HandshakeResponse.java:30)
        at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:126)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
        at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
        at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543)
        at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:128)
        at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:74)
        at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)
        at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
        at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
        at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
        at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:181)
        at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:168)
        at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:123)
        at com.nobilis.utility.BrowserFactory.startApplication(BrowserFactory.java:21)
        at com.nobilis.page.BaseClass.setup(BaseClass.java:46)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)

```

Chromium Version 80.0.3987.163 (Official Build) Built on Ubuntu , running on Ubuntu 18.04 (64-bit)

**Comment by sriramkukkadapu** [comment]
@bonigarcia  Any updates on this issue ? Any fix available ?

**Comment by khrissh** [comment]
Currently 81 Chrome version is available, so after I've updated mu Chrome issue was fixed. My webdriver-manager  is 12.1.7

**Comment by Suban5** [comment]
if I don't want to update my chromium version, WebDriverManager must be able to run the code in my browser. I don't want to manually update my chromium each time new version of browser is available

**Comment by MatheusVp2** [comment]
My webdriver when I try to access GMAIL, says that this app or browser is not safe!
What can it be ?

**Comment by sriramkukkadapu** [comment]
@khrissh  Yes update google chrome to 81 version(which is latest) fixed this issue.

**Comment by rohanraviyadav** [comment]
Added WebDriverManager.chromedriver().clearCache(); before WebDriverManager.chromedriver().setup();

It solved following issue >>

2020-05-26 22:10:53 [INFO]  Browser session not created: This version of ChromeDriver only supports Chrome version 81
Build info: version: '3.11.0', revision: 'e59cfb3', time: '2018-03-11T20:26:55.152Z'
System info: host: 'RENTEST004641', ip: '10.32.193.217', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_171'
Driver info: driver.version: Driver
remote stacktrace: Backtrace:
	Ordinal0 [0x005D5E93+2449043]
	Ordinal0 [0x00508281+1606273]
	Ordinal0 [0x003FF889+522377]
	Ordinal0 [0x003905F3+67059]
