### ISSUE TITLE
WebDriverManager is unable to download the msedge driver

### ISSUE THREAD

**Issue by fshaik123** [bonigarcia/webdrivermanager#463]
The following error is thrown when tried to run my test using EDGE Chromium Browser:
[main] ERROR io.github.bonigarcia.wdm.WebDriverManager - There was an error managing msedgedriver (latest version) (Connect to developer.microsoft.com:443 [developer.microsoft.com/23.65.246.239] failed: Connection refused: connect)
org.apache.http.conn.HttpHostConnectException: Connect to developer.microsoft.com:443 [developer.microsoft.com/23.65.246.239] failed: Connection refused: connect
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:159) ~[httpclient-4.5.6.jar:4.5.6]
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:373) ~[httpclient-4.5.6.jar:4.5.6]
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:394) ~[httpclient-4.5.6.jar:4.5.6]
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237) ~[httpclient-4.5.6.jar:4.5.6]
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185) ~[httpclient-4.5.6.jar:4.5.6]
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) ~[httpclient-4.5.6.jar:4.5.6]
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[httpclient-4.5.6.jar:4.5.6]
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[httpclient-4.5.6.jar:4.5.6]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[httpclient-4.5.6.jar:4.5.6]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108) ~[httpclient-4.5.6.jar:4.5.6]
	at io.github.bonigarcia.wdm.HttpClient.execute(HttpClient.java:169) ~[webdrivermanager-3.8.1.jar:?]
	at io.github.bonigarcia.wdm.EdgeDriverManager.getDrivers(EdgeDriverManager.java:103) ~[webdrivermanager-3.8.1.jar:?]
	at io.github.bonigarcia.wdm.WebDriverManager.filterCandidateUrls(WebDriverManager.java:792) ~[webdrivermanager-3.8.1.jar:?]
	at io.github.bonigarcia.wdm.WebDriverManager.downloadAndExport(WebDriverManager.java:568) [webdrivermanager-3.8.1.jar:?]
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:547) [webdrivermanager-3.8.1.jar:?]
	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:773) [webdrivermanager-3.8.1.jar:?]
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:550) [webdrivermanager-3.8.1.jar:?]
	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:766) [webdrivermanager-3.8.1.jar:?]
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:550) [webdrivermanager-3.8.1.jar:?]
	at io.github.bonigarcia.wdm.WebDriverManager.setup(WebDriverManager.java:260) [webdrivermanager-3.8.1.jar:?]
	at com.wheels.automation.driver.edge.AutomationEdgeDriver.getWebDriver(AutomationEdgeDriver.java:21) [automation-core-1.29.jar:?]
	at com.wheels.automation.factory.WebDriverFactory.getEdgeDriver(WebDriverFactory.java:119) [automation-core-1.29.jar:?]
	at com.wheels.automation.factory.WebDriverFactory.getStandaloneDriver(WebDriverFactory.java:75) [automation-core-1.29.jar:?]
	at com.wheels.automation.factory.WebDriverFactory.getWebDriver(WebDriverFactory.java:30) [automation-core-1.29.jar:?]
	at com.wheels.automation.base.Base.beforeMethod(Base.java:164) [automation-core-1.29.jar:?]
	at com.wheels.automation.tests.SmokeTestTillStep09.beforeMethod(SmokeTestTillStep09.java:76) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_162]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_162]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_162]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_162]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85) [selenium-server-standalone-2.53.0.jar:?]
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510) [selenium-server-standalone-2.53.0.jar:?]
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211) [selenium-server-standalone-2.53.0.jar:?]
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:585) [selenium-server-standalone-2.53.0.jar:?]
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816) [selenium-server-standalone-2.53.0.jar:?]
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124) [selenium-server-standalone-2.53.0.jar:?]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125) [selenium-server-standalone-2.53.0.jar:?]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108) [selenium-server-standalone-2.53.0.jar:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:774) [selenium-server-standalone-2.53.0.jar:?]
	at org.testng.TestRunner.run(TestRunner.java:624) [selenium-server-standalone-2.53.0.jar:?]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359) [selenium-server-standalone-2.53.0.jar:?]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354) [selenium-server-standalone-2.53.0.jar:?]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312) [selenium-server-standalone-2.53.0.jar:?]
	at org.testng.SuiteRunner.run(SuiteRunner.java:261) [selenium-server-standalone-2.53.0.jar:?]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52) [selenium-server-standalone-2.53.0.jar:?]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86) [selenium-server-standalone-2.53.0.jar:?]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215) [selenium-server-standalone-2.53.0.jar:?]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140) [selenium-server-standalone-2.53.0.jar:?]
	at org.testng.TestNG.run(TestNG.java:1048) [selenium-server-standalone-2.53.0.jar:?]
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66) [testng-rt.jar:?]
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:110) [testng-rt.jar:?]
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method) ~[?:1.8.0_162]
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79) ~[?:1.8.0_162]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[?:1.8.0_162]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[?:1.8.0_162]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[?:1.8.0_162]
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172) ~[?:1.8.0_162]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_162]
	at java.net.Socket.connect(Socket.java:589) ~[?:1.8.0_162]
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:339) ~[httpclient-4.5.6.jar:4.5.6]
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142) ~[httpclient-4.5.6.jar:4.5.6]
	... 50 more

**Comment by bonigarcia** [comment]
I think this is related to #464. In any case, please follow the issue template, otherwise it is impossible to know the root of the problem.
