### ISSUE TITLE
WebDriverManager not able to fetch the windows edge (chromium) 64bit driver

### ISSUE THREAD

**Issue by markloughery** [bonigarcia/webdrivermanager#464]
**Description of the problem**: 
I am using Edge Chromium on Windows 10 (64 bit) and WebDriverManager is unable to pull the edgedriver_win64.zip from the repository. 

**Browser and version**: 
Edge Chromium 81.0.416.45 WIN64

**Operating system**: 
Windows 10

**WebDriverManager version**:
3.8.1

**WebDriverManager use**: 
WebDriverManager.edgedriver().operatingSystem(OperatingSystem.WIN).setup();
WebDriver driver = new EdgeDriver();

**WebDriverManager traces**: 
```
0 [main] DEBUG io.github.bonigarcia.wdm.Shell  - Running command on the shell: [wmic, datafile, where, name='C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe', get, Version, /value]
372 [main] DEBUG io.github.bonigarcia.wdm.Shell  - Result: Version=81.0.416.53
372 [main] DEBUG io.github.bonigarcia.wdm.WebDriverManager  - Edge (based on Chromium) version 81 found
376 [main] DEBUG io.github.bonigarcia.wdm.WebDriverManager  - Getting driver version for edge81 from online versions.properties
400 [main] DEBUG org.apache.http.client.protocol.RequestAddCookies  - CookieSpec selected: standard
408 [main] DEBUG org.apache.http.client.protocol.RequestAuthCache  - Auth cache not set in the context
410 [main] DEBUG org.apache.http.impl.conn.PoolingHttpClientConnectionManager  - Connection request: [route: {s}->https://raw.githubusercontent.com:443][total kept alive: 0; route allocated: 0 of 2; total allocated: 0 of 20]
432 [main] DEBUG org.apache.http.impl.conn.PoolingHttpClientConnectionManager  - Connection leased: [id: 0][route: {s}->https://raw.githubusercontent.com:443][total kept alive: 0; route allocated: 1 of 2; total allocated: 1 of 20]
434 [main] DEBUG org.apache.http.impl.execchain.MainClientExec  - Opening connection {s}->https://raw.githubusercontent.com:443
496 [main] DEBUG org.apache.http.impl.conn.DefaultHttpClientConnectionOperator  - Connecting to raw.githubusercontent.com/151.101.192.133:443
497 [main] DEBUG org.apache.http.conn.ssl.SSLConnectionSocketFactory  - Connecting socket to raw.githubusercontent.com/151.101.192.133:443 with timeout 0
620 [main] DEBUG org.apache.http.conn.ssl.SSLConnectionSocketFactory  - Enabled protocols: [TLSv1.3, TLSv1.2, TLSv1.1, TLSv1]

2117 [main] DEBUG org.apache.http.headers  - http-outgoing-2 << Expires: -1
2117 [main] DEBUG org.apache.http.headers  - http-outgoing-2 << Vary: Accept-Encoding
2117 [main] DEBUG org.apache.http.headers  - http-outgoing-2 << Server: Microsoft-IIS/10.0
2117 [main] DEBUG org.apache.http.headers  - http-outgoing-2 << X-Frame-Options: SAMEORIGIN
2117 [main] DEBUG org.apache.http.headers  - http-outgoing-2 << X-ResponseUrl: https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/
2117 [main] DEBUG org.apache.http.headers  - http-outgoing-2 << request-context: appId=cid-v1:60a8fa6b-cb7f-40c9-8b6a-597315715d14
2117 [main] DEBUG org.apache.http.headers  - http-outgoing-2 << X-XSS-Protection: 1; mode=block
2117 [main] DEBUG org.apache.http.headers  - http-outgoing-2 << X-Download-Options: noopen
2117 [main] DEBUG org.apache.http.headers  - http-outgoing-2 << X-Content-Type-Options: nosniff,nosniff
2117 [main] DEBUG org.apache.http.headers  - http-outgoing-2 << x-dns-prefetch-control: on
2117 [main] DEBUG org.apache.http.headers  - http-outgoing-2 << X-AspNet-Version: 4.0.30319
2117 [main] DEBUG org.apache.http.headers  - http-outgoing-2 << MS-CorrelationId: cf5bdeb9-570d-402f-acbb-27cdfb8d8fcb
2118 [main] DEBUG org.apache.http.headers  - http-outgoing-2 << X-Powered-By: ASP.NET
2118 [main] DEBUG org.apache.http.headers  - http-outgoing-2 << X-UA-Compatible: IE=edge
2118 [main] DEBUG org.apache.http.headers  - http-outgoing-2 << Content-Encoding: gzip
2118 [main] DEBUG org.apache.http.headers  - http-outgoing-2 << Date: Fri, 17 Apr 2020 10:09:01 GMT
2118 [main] DEBUG org.apache.http.headers  - http-outgoing-2 << Content-Length: 4039
2118 [main] DEBUG org.apache.http.headers  - http-outgoing-2 << Connection: keep-alive
2118 [main] DEBUG org.apache.http.headers  - http-outgoing-2 << Set-Cookie: Session-Id=d42171f1-41e7-485e-afcd-991b36a1415e; path=/;SameSite=Lax; secure; HttpOnly
2118 [main] DEBUG org.apache.http.headers  - http-outgoing-2 << Set-Cookie: MarketplaceSelectedLocale=en-us; expires=Sat, 17-Apr-2021 10:09:00 GMT; path=/;SameSite=None; secure; HttpOnly
2118 [main] DEBUG org.apache.http.headers  - http-outgoing-2 << Strict-Transport-Security: max-age=31536000; includeSubDomains
2118 [main] DEBUG org.apache.http.impl.execchain.MainClientExec  - Connection can be kept alive indefinitely
2118 [main] DEBUG org.apache.http.client.protocol.ResponseProcessCookies  - Cookie accepted [Session-Id="d42171f1-41e7-485e-afcd-991b36a1415e", version:0, domain:developer.microsoft.com, path:/, expiry:null]
2119 [main] DEBUG org.apache.http.client.protocol.ResponseProcessCookies  - Cookie accepted [MarketplaceSelectedLocale="en-us", version:0, domain:developer.microsoft.com, path:/, expiry:Sat Apr 17 11:09:00 BST 2021]
2136 [main] DEBUG org.apache.http.impl.conn.PoolingHttpClientConnectionManager  - Connection [id: 2][route: {s}->https://developer.microsoft.com:443] can be kept alive indefinitely
2136 [main] DEBUG org.apache.http.impl.conn.DefaultManagedHttpClientConnection  - http-outgoing-2: set socket timeout to 0
2136 [main] DEBUG org.apache.http.impl.conn.PoolingHttpClientConnectionManager  - Connection released: [id: 2][route: {s}->https://developer.microsoft.com:443][total kept alive: 1; route allocated: 1 of 2; total allocated: 1 of 20]
2137 [main] ERROR io.github.bonigarcia.wdm.WebDriverManager  - msedgedriver 81.0.416.45 for WIN64 not found in https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/
2137 [main] WARN io.github.bonigarcia.wdm.WebDriverManager  - There was an error managing msedgedriver 81.0.416.45 (msedgedriver 81.0.416.45 for WIN64 not found in https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/) ... trying again using latest from cache
2166 [main] DEBUG io.github.bonigarcia.wdm.WebDriverManager  - Driver msedgedriver (latest version) found in cache
2167 [main] INFO io.github.bonigarcia.wdm.WebDriverManager  - Exporting webdriver.edge.driver as ~\.m2\repository\webdriver\edgedriver\mac64\x64\81.0.410.0\msedgedriver
```

**Error trace**: 
```
org.openqa.selenium.WebDriverException: Timed out waiting for driver server to start.
Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:19:58.91Z'
System info: host: 'OPUS2-4788', ip: '192.168.1.57', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '13.0.1'
Driver info: driver.version: Driver
	at org.openqa.selenium.remote.service.DriverService.waitUntilAvailable(DriverService.java:193)
	at org.openqa.selenium.remote.service.DriverService.start(DriverService.java:179)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:79)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:548)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:212)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:130)
	at org.openqa.selenium.edge.EdgeDriver.<init>(EdgeDriver.java:141)
	at org.openqa.selenium.edge.EdgeDriver.<init>(EdgeDriver.java:130)
	at implementation.Driver.getDriver(Driver.java:110)
	at stepdefinitions.Hooks.testStartup(Hooks.java:93)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at cucumber.runtime.Utils$1.call(Utils.java:40)
	at cucumber.runtime.Timeout.timeout(Timeout.java:16)
	at cucumber.runtime.Utils.invoke(Utils.java:34)
	at cucumber.runtime.java.JavaHookDefinition.execute(JavaHookDefinition.java:60)
	at cucumber.runtime.Runtime.runHookIfTagsMatch(Runtime.java:224)
	at cucumber.runtime.Runtime.runHooks(Runtime.java:212)
	at cucumber.runtime.Runtime.runBeforeHooks(Runtime.java:202)
	at cucumber.runtime.model.CucumberScenario.run(CucumberScenario.java:40)
	at cucumber.runtime.model.CucumberFeature.run(CucumberFeature.java:165)
	at cucumber.runtime.Runtime.run(Runtime.java:122)
	at cucumber.api.cli.Main.run(Main.java:36)
	at cucumber.api.cli.Main.main(Main.java:18)
Caused by: org.openqa.selenium.net.UrlChecker$TimeoutException: Timed out waiting for [http://localhost:7877/status] to be available after 20002 ms
	at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:100)
	at org.openqa.selenium.remote.service.DriverService.waitUntilAvailable(DriverService.java:188)
	... 25 more
Caused by: java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
	at com.google.common.util.concurrent.SimpleTimeLimiter.callWithTimeout(SimpleTimeLimiter.java:156)
	at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:75)
	... 26 more

java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:222)
	at org.openqa.selenium.support.ui.FluentWait.<init>(FluentWait.java:115)
	at org.openqa.selenium.support.ui.WebDriverWait.<init>(WebDriverWait.java:102)
	at org.openqa.selenium.support.ui.WebDriverWait.<init>(WebDriverWait.java:45)
	at implementation.Base.waitForPageLoad(Base.java:3313)
	at implementation.Driver.getCurrentUrlWait(Driver.java:598)
	at implementation.Driver.takeScreenshot(Driver.java:370)
	at stepdefinitions.Hooks.testTearDown(Hooks.java:124)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at cucumber.runtime.Utils$1.call(Utils.java:40)
	at cucumber.runtime.Timeout.timeout(Timeout.java:16)
	at cucumber.runtime.Utils.invoke(Utils.java:34)
	at cucumber.runtime.java.JavaHookDefinition.execute(JavaHookDefinition.java:60)
	at cucumber.runtime.Runtime.runHookIfTagsMatch(Runtime.java:224)
	at cucumber.runtime.Runtime.runHooks(Runtime.java:212)
	at cucumber.runtime.Runtime.runAfterHooks(Runtime.java:206)
	at cucumber.runtime.model.CucumberScenario.run(CucumberScenario.java:46)
	at cucumber.runtime.model.CucumberFeature.run(CucumberFeature.java:165)
	at cucumber.runtime.Runtime.run(Runtime.java:122)
	at cucumber.api.cli.Main.run(Main.java:36)
	at cucumber.api.cli.Main.main(Main.java:18)
```

**Comment by Aman-RateHub** [comment]
I am facing the same issue.

**Comment by bonigarcia** [comment]
Indeed it seems the support for Edge is currently broken. I am going to try to fix it and release a new version ASAP.

**Comment by Aman-RateHub** [comment]
its working now. Thanks!

**Comment by bonigarcia** [comment]
Please upgrade to WebDriverManager 4.0.0. If the problem persists, open a new issue and include the WebDriverManager traces at `DEBUG` level.

**Comment by MUTAIRMAN** [comment]
Getting below traces when tried for Edge of version 83.0.478.50 with WebDriver Manager 4.0.0



io.github.bonigarcia.wdm.config.WebDriverManagerException: io.github.bonigarcia.wdm.config.WebDriverManagerException: msedgedriver 83.0.478.54 for WIN 64 not found in https://msedgedriver.azureedge.net/
	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:725)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:531)
	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:722)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:531)
	at io.github.bonigarcia.wdm.WebDriverManager.setup(WebDriverManager.java:277)
	at muthu.com.AppliToolsApp.TraditionalV1.TaskOnetabs_mobiles_V1.beforeTest(TaskOnetabs_mobiles_V1.java:337)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:523)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:224)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:146)
	at org.testng.TestRunner.beforeRun(TestRunner.java:626)
	at org.testng.TestRunner.run(TestRunner.java:594)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.github.bonigarcia.wdm.config.WebDriverManagerException: msedgedriver 83.0.478.54 for WIN 64 not found in https://msedgedriver.azureedge.net/
	at io.github.bonigarcia.wdm.WebDriverManager.noCandidateUrlFound(WebDriverManager.java:607)
	at io.github.bonigarcia.wdm.WebDriverManager.createUrlHandler(WebDriverManager.java:756)
	at io.github.bonigarcia.wdm.WebDriverManager.download(WebDriverManager.java:593)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:525)
	... 22 more

**Comment by alisahrustic** [comment]
I am facing the same issue.

**Comment by mayankverma24** [comment]
I am also facing the same issue

io.github.bonigarcia.wdm.config.WebDriverManagerException: io.github.bonigarcia.wdm.config.WebDriverManagerException: msedgedriver 83.0.478.61 for WIN 64 not found in https://msedgedriver.azureedge.net/
	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:725)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:531)
	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:722)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:531)
	at io.github.bonigarcia.wdm.WebDriverManager.setup(WebDriverManager.java:277)
	at com.org.managers.DriverManager.createLocalDriver(DriverManager.java:56)
	at com.org.managers.DriverManager.createDriver(DriverManager.java:40)
	at com.org.managers.DriverManager.getDriver(DriverManager.java:33)
	at com.org.cucumber.TestContext.<init>(TestContext.java:14)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at org.picocontainer.injectors.AbstractInjector.newInstance(AbstractInjector.java:145)
	at org.picocontainer.injectors.ConstructorInjector$1.run(ConstructorInjector.java:342)
	at org.picocontainer.injectors.AbstractInjector$ThreadLocalCyclicDependencyGuard.observe(AbstractInjector.java:270)
	at org.picocontainer.injectors.ConstructorInjector.getComponentInstance(ConstructorInjector.java:364)
	at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.getComponentInstance(AbstractInjectionFactory.java:56)
	at org.picocontainer.behaviors.AbstractBehavior.getComponentInstance(AbstractBehavior.java:64)
	at org.picocontainer.behaviors.Stored.getComponentInstance(Stored.java:91)
	at org.picocontainer.DefaultPicoContainer.getInstance(DefaultPicoContainer.java:699)
	at org.picocontainer.DefaultPicoContainer.getComponent(DefaultPicoContainer.java:647)
	at org.picocontainer.DefaultPicoContainer.getComponent(DefaultPicoContainer.java:632)
	at org.picocontainer.parameters.BasicComponentParameter$1.resolveInstance(BasicComponentParameter.java:118)
	at org.picocontainer.parameters.ComponentParameter$1.resolveInstance(ComponentParameter.java:136)
	at org.picocontainer.injectors.SingleMemberInjector.getParameter(SingleMemberInjector.java:78)
	at org.picocontainer.injectors.ConstructorInjector$CtorAndAdapters.getParameterArguments(ConstructorInjector.java:309)
	at org.picocontainer.injectors.ConstructorInjector$1.run(ConstructorInjector.java:335)
	at org.picocontainer.injectors.AbstractInjector$ThreadLocalCyclicDependencyGuard.observe(AbstractInjector.java:270)
	at org.picocontainer.injectors.ConstructorInjector.getComponentInstance(ConstructorInjector.java:364)
	at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.getComponentInstance(AbstractInjectionFactory.java:56)
	at org.picocontainer.behaviors.AbstractBehavior.getComponentInstance(AbstractBehavior.java:64)
	at org.picocontainer.behaviors.Stored.getComponentInstance(Stored.java:91)
	at org.picocontainer.DefaultPicoContainer.getInstance(DefaultPicoContainer.java:699)
	at org.picocontainer.DefaultPicoContainer.getComponent(DefaultPicoContainer.java:647)
	at org.picocontainer.DefaultPicoContainer.getComponent(DefaultPicoContainer.java:678)
	at io.cucumber.picocontainer.PicoFactory.getInstance(PicoFactory.java:49)
	at io.cucumber.java.AbstractGlueDefinition.invokeMethod(AbstractGlueDefinition.java:44)
	at io.cucumber.java.JavaHookDefinition.execute(JavaHookDefinition.java:59)
	at io.cucumber.core.runner.CoreHookDefinition.execute(CoreHookDefinition.java:44)
	at io.cucumber.core.runner.HookDefinitionMatch.runStep(HookDefinitionMatch.java:21)
	at io.cucumber.core.runner.TestStep.executeStep(TestStep.java:92)
	at io.cucumber.core.runner.TestStep.run(TestStep.java:63)
	at io.cucumber.core.runner.TestCase.run(TestCase.java:95)
	at io.cucumber.core.runner.Runner.runPickle(Runner.java:71)
	at io.cucumber.testng.TestNGCucumberRunner.lambda$runScenario$0(TestNGCucumberRunner.java:115)
	at io.cucumber.core.runtime.CucumberExecutionContext.runTestCase(CucumberExecutionContext.java:131)
	at io.cucumber.testng.TestNGCucumberRunner.runScenario(TestNGCucumberRunner.java:112)
	at io.cucumber.testng.AbstractTestNGCucumberTests.runScenario(AbstractTestNGCucumberTests.java:31)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: io.github.bonigarcia.wdm.config.WebDriverManagerException: msedgedriver 83.0.478.61 for WIN 64 not found in https://msedgedriver.azureedge.net/
	at io.github.bonigarcia.wdm.WebDriverManager.noCandidateUrlFound(WebDriverManager.java:607)
	at io.github.bonigarcia.wdm.WebDriverManager.createUrlHandler(WebDriverManager.java:756)
	at io.github.bonigarcia.wdm.WebDriverManager.download(WebDriverManager.java:593)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:525)
	... 73 more

**Comment by harshchokshi** [comment]
> Please upgrade to WebDriverManager 4.0.0. If the problem persists, open a new issue and include the WebDriverManager traces at `DEBUG` level.

Yes sir, updating WebDriverManager with latest version fix the issue.... Loved it.
Also,
