### ISSUE TITLE
Unable to setup phantomJS (v1.4.7)

### ISSUE THREAD

**Issue by xtwmx** [bonigarcia/webdrivermanager#47]
Hello,

I received this error when trying to set up phantomjs:
JDK: 1.7

```
DEBUG com.gargoylesoftware.htmlunit.WebClient  - Get page for window named '', using WebRequest[<url="https://bitbucket.org/ariya/phantomjs/downloads/", GET, EncodingType[name=application/x-www-form-urlencoded], [], {Accept-Encoding=gzip, deflate, Accept=text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8}, null>]
DEBUG com.gargoylesoftware.htmlunit.WebClient  - Load response for GET https://bitbucket.org/ariya/phantomjs/downloads/

java.lang.NoClassDefFoundError: org/apache/http/conn/ssl/NoopHostnameVerifier
	at com.gargoylesoftware.htmlunit.httpclient.HtmlUnitSSLConnectionSocketFactory.buildSSLSocketFactory(HtmlUnitSSLConnectionSocketFactory.java:111)
	at com.gargoylesoftware.htmlunit.HttpWebConnection.configureHttpsScheme(HttpWebConnection.java:601)
	at com.gargoylesoftware.htmlunit.HttpWebConnection.createHttpClient(HttpWebConnection.java:536)
	at com.gargoylesoftware.htmlunit.HttpWebConnection.getHttpClientBuilder(HttpWebConnection.java:498)
	at com.gargoylesoftware.htmlunit.HttpWebConnection.getResponse(HttpWebConnection.java:156)
	at com.gargoylesoftware.htmlunit.WebClient.loadWebResponseFromWebConnection(WebClient.java:1323)
	at com.gargoylesoftware.htmlunit.WebClient.loadWebResponse(WebClient.java:1240)
	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:347)
	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:416)
	at org.openqa.selenium.htmlunit.HtmlUnitDriver.get(HtmlUnitDriver.java:519)
	at org.openqa.selenium.htmlunit.HtmlUnitDriver.get(HtmlUnitDriver.java:508)
	at io.github.bonigarcia.wdm.PhantomJsDriverManager.getDrivers(PhantomJsDriverManager.java:71)
	at io.github.bonigarcia.wdm.BrowserManager.manage(BrowserManager.java:209)
	at io.github.bonigarcia.wdm.BrowserManager.setup(BrowserManager.java:103)
	at io.github.bonigarcia.wdm.BrowserManager.setup(BrowserManager.java:82)
```

**Comment by bonigarcia** [comment]
I am not able to reproduce this problem. Could you provide more info?

**Comment by xtwmx** [comment]
Found the problem:
I had to add https://mvnrepository.com/artifact/org.apache.httpcomponents/httpclient to my dependencies.
