### ISSUE TITLE
About Error in selenium

### ISSUE THREAD

**Issue by sachdhum** [bonigarcia/webdrivermanager#475]
My code,

package samplePrograms;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

public class SamplePrograms {

	public static void main(String[] args) 
	{
		System.setProperty("webDriver.chrome.driver","E:\\Selenium Material\\seleniumDriver\\chromedriver.exe");
	WebDriver driver=new ChromeDriver();
      driver.get("https://www.google.co.in");
	}
}

The following error is coming,
Exception in thread "main" java.lang.IllegalStateException: The path to the driver executable must be set by the webdriver.chrome.driver system property; for more information, see https://github.com/SeleniumHQ/selenium/wiki/ChromeDriver. The latest version can be downloaded from http://chromedriver.storage.googleapis.com/index.html
	at com.google.common.base.Preconditions.checkState(Preconditions.java:847)
	at org.openqa.selenium.remote.service.DriverService.findExecutable(DriverService.java:125)
	at org.openqa.selenium.chrome.ChromeDriverService.access$000(ChromeDriverService.java:35)
	at org.openqa.selenium.chrome.ChromeDriverService$Builder.findDefaultExecutable(ChromeDriverService.java:156)
	at org.openqa.selenium.remote.service.DriverService$Builder.build(DriverService.java:346)
	at org.openqa.selenium.chrome.ChromeDriverService.createDefaultService(ChromeDriverService.java:91)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:123)
	at samplePrograms.SamplePrograms.main(SamplePrograms.java:11)

**Comment by bonigarcia** [comment]
Use `webdriver.chrome.driver` for the property name (all in lower case).

**Comment by sachdhum** [comment]
Thanks.

I will try & let you know the result.


Sachin Dhumale
Nanded, Maharashtra, India.
