### ISSUE TITLE
java.lang.ClassNotFoundException: org.apache.http.client.HttpClient when running REST API call in 4.0.0

### ISSUE THREAD

**Issue by kmacf** [bonigarcia/webdrivermanager#490]
When running REST API calls within automation framework, using 4.0.0, receive a java.lang.ClassNotFoundException pointing to the HttpClient. If I downgrade to 3.8.1, it works fine, and if I run without WebDriverManager it also works.

Caused by: java.lang.NoClassDefFoundError: org/apache/http/client/HttpClient
	at io.restassured.config.HttpClientConfig.defaultHttpClientFactory(HttpClientConfig.java:264)
	at io.restassured.config.HttpClientConfig.<init>(HttpClientConfig.java:76)
	at io.restassured.config.RestAssuredConfig.<init>(RestAssuredConfig.java:41)
	at io.restassured.RestAssured.<clinit>(RestAssured.java:420)
	at api.com.ibm.ApiFrameworkCore.Request.configSpecification(Request.java:41)
	---internal code---
	... 50 more
Caused by: java.lang.ClassNotFoundException: org.apache.http.client.HttpClient
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 57 more

Reproduced on Chrome 83 and Edge 83 on both Mac and Windows

WebDriverManager version: 4.0.0 
If I downgrade to WebDriverManager version 3.8.1, it works fine. It also works successfully if I launch the browser without using WebDriverManager.

**WebDriverManager traces**: 
[DEBUG] Resolution chrome=83 in cache (valid until 08:35:22 29/05/2020 EDT)
[INFO] Using chromedriver 83.0.4103.39 (since Chrome 83 is installed in your machine)
[DEBUG] Driver chromedriver 83.0.4103.39 found in cache
[INFO] Exporting webdriver.chrome.driver as /..../.m2/repository/webdriver/chromedriver/mac64/83.0.4103.39/chromedriver

**Comment by bonigarcia** [comment]
WebDriverManager 4.x uses HttpClient version 5.0. I suppose you have a dependency problem with this version and the previous one in your project.
