### ISSUE TITLE
WebDriverManagerException : java.security.KeyStoreException

### ISSUE THREAD

**Issue by tulsi26ram** [bonigarcia/webdrivermanager#500]
Hi Team,

I am using the following line of code to instantiate Chrome Browser

WebDriverManager.chromedriver().setup();

Exception:

io.github.bonigarcia.wdm.config.WebDriverManagerException: java.security.KeyStoreException: problem accessing trust storejava.io.IOException: Invalid keystore format 	at io.github.bonigarcia.wdm.online.HttpClient.<init>(HttpClient.java:117) 	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:490) 	at io.github.bonigarcia.wdm.WebDriverManager.setup(WebDriverManager.java:277)
--
 Caused by 

Caused by: java.security.KeyStoreException: problem accessing trust storejava.io.IOException: Invalid keystore format 	at sun.security.ssl.TrustManagerFactoryImpl.engineInit(TrustManagerFactoryImpl.java:74) 	at javax.net.ssl.TrustManagerFactory.init(TrustManagerFactory.java:250) 	at org.apache.hc.core5.ssl.SSLContextBuilder.loadTrustMaterial(SSLContextBuilder.java:201) 	at io.github.bonigarcia.wdm.online.HttpClient.<init>(HttpClient.java:99) 	... 20 more
--

**Comment by bonigarcia** [comment]
Please follow the template to report issues.
