### ISSUE TITLE
Web driver manager is not working with IE version 11.0.185

### ISSUE THREAD

**Issue by Nihar1991** [bonigarcia/webdrivermanager#504]
Hi team,

i am getting below issue in console while trying to launch IE 11 browser (Ver 11.0.185) using webdrivermanager. can you please help me on this. 

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
2020-06-23 13:08:55 INFO  RetryExec:97 - I/O exception (java.net.SocketException) caught when processing request to {s}->https://selenium-release.storage.googleapis.com:443: Connection reset
2020-06-23 13:08:55 INFO  RetryExec:113 - Retrying request to {s}->https://selenium-release.storage.googleapis.com:443
2020-06-23 13:08:56 INFO  RetryExec:97 - I/O exception (java.net.SocketException) caught when processing request to {s}->https://selenium-release.storage.googleapis.com:443: Connection reset
2020-06-23 13:08:56 INFO  RetryExec:113 - Retrying request to {s}->https://selenium-release.storage.googleapis.com:443
2020-06-23 13:08:56 INFO  RetryExec:97 - I/O exception (java.net.SocketException) caught when processing request to {s}->https://selenium-release.storage.googleapis.com:443: Connection reset
2020-06-23 13:08:56 INFO  RetryExec:113 - Retrying request to {s}->https://selenium-release.storage.googleapis.com:443
2020-06-23 13:08:57 INFO  RetryExec:97 - I/O exception (java.net.SocketException) caught when processing request to {s}->https://selenium-release.storage.googleapis.com:443: Connection reset
2020-06-23 13:08:57 INFO  RetryExec:113 - Retrying request to {s}->https://selenium-release.storage.googleapis.com:443
2020-06-23 13:08:58 INFO  RetryExec:97 - I/O exception (java.net.SocketException) caught when processing request to {s}->https://selenium-release.storage.googleapis.com:443: Connection reset
2020-06-23 13:08:58 INFO  RetryExec:113 - Retrying request to {s}->https://selenium-release.storage.googleapis.com:443
2020-06-23 13:08:59 INFO  RetryExec:97 - I/O exception (java.net.SocketException) caught when processing request to {s}->https://selenium-release.storage.googleapis.com:443: Connection reset
2020-06-23 13:08:59 INFO  RetryExec:113 - Retrying request to {s}->https://selenium-release.storage.googleapis.com:443
2020-06-23 13:09:00 INFO  RetryExec:97 - I/O exception (java.net.SocketException) caught when processing request to {s}->https://selenium-release.storage.googleapis.com:443: Connection reset
2020-06-23 13:09:00 INFO  RetryExec:113 - Retrying request to {s}->https://selenium-release.storage.googleapis.com:443
2020-06-23 13:09:00 INFO  RetryExec:97 - I/O exception (java.net.SocketException) caught when processing request to {s}->https://selenium-release.storage.googleapis.com:443: Connection reset
2020-06-23 13:09:00 INFO  RetryExec:113 - Retrying request to {s}->https://selenium-release.storage.googleapis.com:443
2020-06-23 13:09:01 INFO  RetryExec:97 - I/O exception (java.net.SocketException) caught when processing request to {s}->https://selenium-release.storage.googleapis.com:443: Connection reset
2020-06-23 13:09:01 INFO  RetryExec:113 - Retrying request to {s}->https://selenium-release.storage.googleapis.com:443
io.github.bonigarcia.wdm.WebDriverManagerException: java.net.SocketException: Connection reset
	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:776)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:550)
	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:773)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:550)
	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:766)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:550)
	at io.github.bonigarcia.wdm.WebDriverManager.setup(WebDriverManager.java:260)
	at com.im.wrapper.api.ConfiguredBrowserInstance.getIEDriver(ConfiguredBrowserInstance.java:87)
	at com.im.wrapper.api.ConfiguredBrowserInstance.getDriver(ConfiguredBrowserInstance.java:40)
	at com.im.imonline.pom.business.AppUtil.preparePrequisites(AppUtil.java:75)
	at com.im.imonline.pom.tests.smoke.SmokeSuite.SmokeTestWithExistingCartClean(SmokeSuite.java:119)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at sun.security.ssl.InputRecord.readFully(Unknown Source)
	at sun.security.ssl.InputRecord.read(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:396)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:355)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:373)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:394)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at io.github.bonigarcia.wdm.HttpClient.execute(HttpClient.java:169)
	at io.github.bonigarcia.wdm.WebDriverManager.getDriversFromXml(WebDriverManager.java:1080)
	at io.github.bonigarcia.wdm.InternetExplorerDriverManager.getDrivers(InternetExplorerDriverManager.java:77)
	at io.github.bonigarcia.wdm.WebDriverManager.filterCandidateUrls(WebDriverManager.java:792)
	at io.github.bonigarcia.wdm.WebDriverManager.downloadAndExport(WebDriverManager.java:568)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:547)
	... 22 more
inside TEstNGListener onTestFailure sMethod=SmokeTestWithExistingCartClean]
2020-06-23 13:09:03 ERROR TestngListener:124 - The complete Exception for the Debugging: [null]
Exception in thread "TestNG-test=Test-2" java.lang.NullPointerException
	at com.im.utility.listener.TestngListener.onTestFailure(TestngListener.java:130)
	at org.testng.internal.TestListenerHelper.runTestListeners(TestListenerHelper.java:67)
	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1388)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1041)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
inside TEstNGListener onFinish
the submitted order number is as follows:

===============================================
Suite
Total tests run: 2, Failures: 0, Skips: 0
===============================================

Thanks
Nihar

**Comment by bonigarcia** [comment]
Please follow the template to report issues.
