### ISSUE TITLE
ignoreDriverVersions not working for latest geckodriver version (0.27.0)

### ISSUE THREAD

**Issue by nlacombe42** [bonigarcia/webdrivermanager#529]
**Description of the problem**
Webdrivermanager fails to dowload/use second to last version of geckodriver when ignoring latest version of geckodriver.
Currently the latest version of geckodriver is 0.27.0.

It looks like webdrivermanager is filtering by a specific default version (the latest geckodriver version 0.27.0) before ignoring the version that the user wants to ignore; therefore this makes it so that if the user ignored version is the same as the default version, the resulting list of driver version URLs is empty.

To me it look likes it should do the following:
1. get all URL for driver versions for the specific driver type (ex: geckodriver)
2. filter  the list by OS
3. filter the list by arch
4. filter the list by user ignored versions
5. filter out beta versions, if the list is now empty, pick the latest version compatible with the browser from setp 4
6. pick the latest version compatible with the browser version

**Browser and version**
```
2020-08-15 19:51:36,551 DEBUG [http-nio-8004-exec-2  ] [Shell               ] - Running command on the shell: [firefox, -v]                                 @io.github.bonigarcia.wdm.versions.Shell 
2020-08-15 19:51:36,595 DEBUG [http-nio-8004-exec-2  ] [Shell               ] - Result: Mozilla Firefox 79.0                                                @io.github.bonigarcia.wdm.versions.Shell 
```

**Operating system**
Manjaro Linux, x86_64, linux kernel version: 5.7.9-1-MANJARO

**WebDriverManager version**
4.1.0

**WebDriverManager use**
```java
    public static WebDriver getWebDriver(boolean headless)
    {
        var webDriverManager = WebDriverManager.firefoxdriver();
        webDriverManager.clearResolutionCache();
        webDriverManager.ignoreDriverVersions("0.27.0").setup();

        logger.info(">>> getDownloadedVersion: " + webDriverManager.getDownloadedVersion());
        logger.info(">>> getBinaryPath: " + webDriverManager.getBinaryPath());
        logger.info(">>> getDriverManagerType: " + webDriverManager.getDriverManagerType());
        logger.info(">>> getDriverVersions: " + webDriverManager.getDriverVersions());

        var options = new FirefoxOptions();
        options.setHeadless(headless);

        return new FirefoxDriver(options);
    }
```

**WebDriverManager traces**
```
2020-08-15 19:51:36,993 INFO  [http-nio-8004-exec-2  ] [WebDriverManager    ] - Reading https://api.github.com/repos/mozilla/geckodriver/releases to seek geckodriver @io.github.bonigarcia.wdm.WebDriverManager 
2020-08-15 19:51:38,445 TRACE [http-nio-8004-exec-2  ] [WebDriverManager    ] - All driver URLs: [https://github.com/mozilla/geckodriver/releases/download/v0.27.0/geckodriver-v0.27.0-linux32.tar.gz, https://github.com/mozilla/geckodriver/releases/download/v0.27.0/geckodriver-v0.27.0-linux32.tar.gz.asc, https://github.com/mozilla/geckodriver/releases/download/v0.27.0/geckodriver-v0.27.0-linux64.tar.gz, https://github.com/mozilla/geckodriver/releases/download/v0.27.0/geckodriver-v0.27.0-linux64.tar.gz.asc, https://github.com/mozilla/geckodriver/releases/download/v0.27.0/geckodriver-v0.27.0-macos.tar.gz, https://github.com/mozilla/geckodriver/releases/download/v0.27.0/geckodriver-v0.27.0-win32.zip, https://github.com/mozilla/geckodriver/releases/download/v0.27.0/geckodriver-v0.27.0-win64.zip, https://github.com/mozilla/geckodriver/releases/download/v0.26.0/geckodriver-v0.26.0-linux32.tar.gz, https://github.com/mozilla/geckodriver/releases/download/v0.26.0/geckodriver-v0.26.0-linux64.tar.gz, https://github.com/mozilla/geckodriver/releases/download/v0.26.0/geckodriver-v0.26.0-macos.tar.gz, https://github.com/mozilla/geckodriver/releases/download/v0.26.0/geckodriver-v0.26.0-win32.zip, https://github.com/mozilla/geckodriver/releases/download/v0.26.0/geckodriver-v0.26.0-win64.zip, https://github.com/mozilla/geckodriver/releases/download/v0.25.0/geckodriver-v0.25.0-linux32.tar.gz, https://github.com/mozilla/geckodriver/releases/download/v0.25.0/geckodriver-v0.25.0-linux64.tar.gz, https://github.com/mozilla/geckodriver/releases/download/v0.25.0/geckodriver-v0.25.0-macos.tar.gz, https://github.com/mozilla/geckodriver/releases/download/v0.25.0/geckodriver-v0.25.0-win32.zip, https://github.com/mozilla/geckodriver/releases/download/v0.25.0/geckodriver-v0.25.0-win64.zip, https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-linux32.tar.gz, https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-linux64.tar.gz, https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-macos.tar.gz, https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-win32.zip, https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-win64.zip, https://github.com/mozilla/geckodriver/releases/download/v0.23.0/geckodriver-v0.23.0-arm7hf.tar.gz, https://github.com/mozilla/geckodriver/releases/download/v0.23.0/geckodriver-v0.23.0-linux32.tar.gz, https://github.com/mozilla/geckodriver/releases/download/v0.23.0/geckodriver-v0.23.0-linux64.tar.gz, https://github.com/mozilla/geckodriver/releases/download/v0.23.0/geckodriver-v0.23.0-macos.tar.gz, https://github.com/mozilla/geckodriver/releases/download/v0.23.0/geckodriver-v0.23.0-win32.zip, https://github.com/mozilla/geckodriver/releases/download/v0.23.0/geckodriver-v0.23.0-win64.zip, https://github.com/mozilla/geckodriver/releases/download/v0.22.0/geckodriver-v0.22.0-arm7hf.tar.gz, https://github.com/mozilla/geckodriver/releases/download/v0.22.0/geckodriver-v0.22.0-linux32.tar.gz, https://github.com/mozilla/geckodriver/releases/download/v0.22.0/geckodriver-v0.22.0-linux64.tar.gz, https://github.com/mozilla/geckodriver/releases/download/v0.22.0/geckodriver-v0.22.0-macos.tar.gz, https://github.com/mozilla/geckodriver/releases/download/v0.22.0/geckodriver-v0.22.0-win32.zip, https://github.com/mozilla/geckodriver/releases/download/v0.22.0/geckodriver-v0.22.0-win64.zip, https://github.com/mozilla/geckodriver/releases/download/v0.21.0/geckodriver-v0.21.0-arm7hf.tar.gz, https://github.com/mozilla/geckodriver/releases/download/v0.21.0/geckodriver-v0.21.0-linux32.tar.gz, https://github.com/mozilla/geckodriver/releases/download/v0.21.0/geckodriver-v0.21.0-linux64.tar.gz, https://github.com/mozilla/geckodriver/releases/download/v0.21.0/geckodriver-v0.21.0-macos.tar.gz, https://github.com/mozilla/geckodriver/releases/download/v0.21.0/geckodriver-v0.21.0-win32.zip, https://github.com/mozilla/geckodriver/releases/download/v0.21.0/geckodriver-v0.21.0-win64.zip, https://github.com/mozilla/geckodriver/releases/download/v0.20.1/geckodriver-v0.20.1-arm7hf.tar.gz, https://github.com/mozilla/geckodriver/releases/download/v0.20.1/geckodriver-v0.20.1-linux32.tar.gz, https://github.com/mozilla/geckodriver/releases/download/v0.20.1/geckodriver-v0.20.1-linux64.tar.gz, https://github.com/mozilla/geckodriver/releases/download/v0.20.1/geckodriver-v0.20.1-macos.tar.gz, https://github.com/mozilla/geckodriver/releases/download/v0.20.1/geckodriver-v0.20.1-win32.zip, https://github.com/mozilla/geckodriver/releases/download/v0.20.1/geckodriver-v0.20.1-win64.zip, https://github.com/mozilla/geckodriver/releases/download/v0.20.0/geckodriver-v0.20.0-arm7hf.tar.gz, https://github.com/mozilla/geckodriver/releases/download/v0.20.0/geckodriver-v0.20.0-linux32.tar.gz, https://github.com/mozilla/geckodriver/releases/download/v0.20.0/geckodriver-v0.20.0-linux64.tar.gz, https://github.com/mozilla/geckodriver/releases/download/v0.20.0/geckodriver-v0.20.0-macos.tar.gz, https://github.com/mozilla/geckodriver/releases/download/v0.20.0/geckodriver-v0.20.0-win32.zip, https://github.com/mozilla/geckodriver/releases/download/v0.20.0/geckodriver-v0.20.0-win64.zip, https://github.com/mozilla/geckodriver/releases/download/v0.19.1/geckodriver-v0.19.1-arm7hf.tar.gz, https://github.com/mozilla/geckodriver/releases/download/v0.19.1/geckodriver-v0.19.1-linux32.tar.gz, https://github.com/mozilla/geckodriver/releases/download/v0.19.1/geckodriver-v0.19.1-linux64.tar.gz, https://github.com/mozilla/geckodriver/releases/download/v0.19.1/geckodriver-v0.19.1-macos.tar.gz, https://github.com/mozilla/geckodriver/releases/download/v0.19.1/geckodriver-v0.19.1-win32.zip, https://github.com/mozilla/geckodriver/releases/download/v0.19.1/geckodriver-v0.19.1-win64.zip, https://github.com/mozilla/geckodriver/releases/download/v0.19.0/geckodriver-v0.19.0-arm7hf.tar.gz, https://github.com/mozilla/geckodriver/releases/download/v0.19.0/geckodriver-v0.19.0-linux32.tar.gz, https://github.com/mozilla/geckodriver/releases/download/v0.19.0/geckodriver-v0.19.0-linux64.tar.gz, https://github.com/mozilla/geckodriver/releases/download/v0.19.0/geckodriver-v0.19.0-macos.tar.gz, https://github.com/mozilla/geckodriver/releases/download/v0.19.0/geckodriver-v0.19.0-win32.zip, https://github.com/mozilla/geckodriver/releases/download/v0.19.0/geckodriver-v0.19.0-win64.zip, https://github.com/mozilla/geckodriver/releases/download/v0.18.0/geckodriver-v0.18.0-arm7hf.tar.gz, https://github.com/mozilla/geckodriver/releases/download/v0.18.0/geckodriver-v0.18.0-linux32.tar.gz, https://github.com/mozilla/geckodriver/releases/download/v0.18.0/geckodriver-v0.18.0-linux64.tar.gz, https://github.com/mozilla/geckodriver/releases/download/v0.18.0/geckodriver-v0.18.0-macos.tar.gz, https://github.com/mozilla/geckodriver/releases/download/v0.18.0/geckodriver-v0.18.0-win32.zip, https://github.com/mozilla/geckodriver/releases/download/v0.18.0/geckodriver-v0.18.0-win64.zip, https://github.com/mozilla/geckodriver/releases/download/v0.17.0/geckodriver-v0.17.0-arm7hf.tar.gz, https://github.com/mozilla/geckodriver/releases/download/v0.17.0/geckodriver-v0.17.0-linux32.tar.gz, https://github.com/mozilla/geckodriver/releases/download/v0.17.0/geckodriver-v0.17.0-linux64.tar.gz, https://github.com/mozilla/geckodriver/releases/download/v0.17.0/geckodriver-v0.17.0-macos.tar.gz, https://github.com/mozilla/geckodriver/releases/download/v0.17.0/geckodriver-v0.17.0-win32.zip, https://github.com/mozilla/geckodriver/releases/download/v0.17.0/geckodriver-v0.17.0-win64.zip, https://github.com/mozilla/geckodriver/releases/download/v0.16.1/geckodriver-v0.16.1-arm7hf.tar.gz, https://github.com/mozilla/geckodriver/releases/download/v0.16.1/geckodriver-v0.16.1-linux64.tar.gz, https://github.com/mozilla/geckodriver/releases/download/v0.16.1/geckodriver-v0.16.1-macos.tar.gz, https://github.com/mozilla/geckodriver/releases/download/v0.16.1/geckodriver-v0.16.1-win32.zip, https://github.com/mozilla/geckodriver/releases/download/v0.16.1/geckodriver-v0.16.1-win64.zip, https://github.com/mozilla/geckodriver/releases/download/v0.16.0/geckodriver-v0.16.0-arm7hf.tar.gz, https://github.com/mozilla/geckodriver/releases/download/v0.16.0/geckodriver-v0.16.0-linux64.tar.gz, https://github.com/mozilla/geckodriver/releases/download/v0.16.0/geckodriver-v0.16.0-macos.tar.gz, https://github.com/mozilla/geckodriver/releases/download/v0.16.0/geckodriver-v0.16.0-win32.zip, https://github.com/mozilla/geckodriver/releases/download/v0.16.0/geckodriver-v0.16.0-win64.zip, https://github.com/mozilla/geckodriver/releases/download/v0.15.0/geckodriver-v0.15.0-arm7hf.tar.gz, https://github.com/mozilla/geckodriver/releases/download/v0.15.0/geckodriver-v0.15.0-linux64.tar.gz, https://github.com/mozilla/geckodriver/releases/download/v0.15.0/geckodriver-v0.15.0-macos.tar.gz, https://github.com/mozilla/geckodriver/releases/download/v0.15.0/geckodriver-v0.15.0-win32.zip, https://github.com/mozilla/geckodriver/releases/download/v0.15.0/geckodriver-v0.15.0-win64.zip, https://github.com/mozilla/geckodriver/releases/download/v0.14.0/geckodriver-v0.14.0-arm7hf.tar.gz, https://github.com/mozilla/geckodriver/releases/download/v0.14.0/geckodriver-v0.14.0-linux32.tar.gz, https://github.com/mozilla/geckodriver/releases/download/v0.14.0/geckodriver-v0.14.0-linux64.tar.gz, https://github.com/mozilla/geckodriver/releases/download/v0.14.0/geckodriver-v0.14.0-macos.tar.gz, https://github.com/mozilla/geckodriver/releases/download/v0.14.0/geckodriver-v0.14.0-win32.zip, https://github.com/mozilla/geckodriver/releases/download/v0.14.0/geckodriver-v0.14.0-win64.zip, https://github.com/mozilla/geckodriver/releases/download/v0.13.0/geckodriver-v0.13.0-arm7hf.tar.gz, https://github.com/mozilla/geckodriver/releases/download/v0.13.0/geckodriver-v0.13.0-linux32.tar.gz, https://github.com/mozilla/geckodriver/releases/download/v0.13.0/geckodriver-v0.13.0-linux64.tar.gz, https://github.com/mozilla/geckodriver/releases/download/v0.13.0/geckodriver-v0.13.0-macos.tar.gz, https://github.com/mozilla/geckodriver/releases/download/v0.13.0/geckodriver-v0.13.0-win32.zip, https://github.com/mozilla/geckodriver/releases/download/v0.13.0/geckodriver-v0.13.0-win64.zip, https://github.com/mozilla/geckodriver/releases/download/v0.12.0/geckodriver-v0.12.0-arm7hf.tar.gz, https://github.com/mozilla/geckodriver/releases/download/v0.12.0/geckodriver-v0.12.0-linux32.tar.gz, https://github.com/mozilla/geckodriver/releases/download/v0.12.0/geckodriver-v0.12.0-linux64.tar.gz, https://github.com/mozilla/geckodriver/releases/download/v0.12.0/geckodriver-v0.12.0-macos.tar.gz, https://github.com/mozilla/geckodriver/releases/download/v0.12.0/geckodriver-v0.12.0-win32.zip, https://github.com/mozilla/geckodriver/releases/download/v0.12.0/geckodriver-v0.12.0-win64.zip, https://github.com/mozilla/geckodriver/releases/download/v0.11.1/geckodriver-v0.11.1-arm7hf.tar.gz, https://github.com/mozilla/geckodriver/releases/download/v0.11.1/geckodriver-v0.11.1-linux32.tar.gz, https://github.com/mozilla/geckodriver/releases/download/v0.11.1/geckodriver-v0.11.1-linux64.tar.gz, https://github.com/mozilla/geckodriver/releases/download/v0.11.1/geckodriver-v0.11.1-macos.tar.gz, https://github.com/mozilla/geckodriver/releases/download/v0.11.1/geckodriver-v0.11.1-win32.zip, https://github.com/mozilla/geckodriver/releases/download/v0.11.1/geckodriver-v0.11.1-win64.zip, https://github.com/mozilla/geckodriver/releases/download/v0.11.0/geckodriver-v0.11.0-arm7hf.tar.gz, https://github.com/mozilla/geckodriver/releases/download/v0.11.0/geckodriver-v0.11.0-linux32.tar.gz, https://github.com/mozilla/geckodriver/releases/download/v0.11.0/geckodriver-v0.11.0-linux64.tar.gz, https://github.com/mozilla/geckodriver/releases/download/v0.11.0/geckodriver-v0.11.0-macos.tar.gz, https://github.com/mozilla/geckodriver/releases/download/v0.11.0/geckodriver-v0.11.0-win32.zip, https://github.com/mozilla/geckodriver/releases/download/v0.11.0/geckodriver-v0.11.0-win64.zip, https://github.com/mozilla/geckodriver/releases/download/v0.10.0/geckodriver-v0.10.0-arm7hf.tar.gz, https://github.com/mozilla/geckodriver/releases/download/v0.10.0/geckodriver-v0.10.0-linux64.tar.gz, https://github.com/mozilla/geckodriver/releases/download/v0.10.0/geckodriver-v0.10.0-macos.tar.gz, https://github.com/mozilla/geckodriver/releases/download/v0.10.0/geckodriver-v0.10.0-win64.zip, https://github.com/mozilla/geckodriver/releases/download/v0.9.0/geckodriver-v0.9.0-arm7hf.tar.gz, https://github.com/mozilla/geckodriver/releases/download/v0.9.0/geckodriver-v0.9.0-linux64.tar.gz, https://github.com/mozilla/geckodriver/releases/download/v0.9.0/geckodriver-v0.9.0-mac.tar.gz, https://github.com/mozilla/geckodriver/releases/download/v0.9.0/geckodriver-v0.9.0-win64.zip, https://github.com/mozilla/geckodriver/releases/download/v0.8.0/geckodriver-0.8.0-linux64.gz, https://github.com/mozilla/geckodriver/releases/download/v0.8.0/geckodriver-0.8.0-OSX.gz, https://github.com/mozilla/geckodriver/releases/download/v0.8.0/geckodriver-v0.8.0-win32.zip, https://github.com/mozilla/geckodriver/releases/download/v0.7.1/wires-0.7.1-linux64.gz, https://github.com/mozilla/geckodriver/releases/download/v0.7.1/wires-0.7.1-OSX.gz, https://github.com/mozilla/geckodriver/releases/download/v0.7.1/wires-v0.7.1-win32.zip, https://github.com/mozilla/geckodriver/releases/download/v0.6.2/wires-0.6.2-linux64.gz, https://github.com/mozilla/geckodriver/releases/download/v0.6.2/wires-0.6.2-OSX.gz, https://github.com/mozilla/geckodriver/releases/download/v0.6.2/wires-0.6.2-win.zip, https://github.com/mozilla/geckodriver/releases/download/v0.6.0/wires-0.6.0-linux.gz, https://github.com/mozilla/geckodriver/releases/download/v0.6.0/wires-0.6.0-osx.gz, https://github.com/mozilla/geckodriver/releases/download/v0.6.0/wires-0.6.0-win.zip, https://github.com/mozilla/geckodriver/releases/download/v0.5.0/wires-0.5.0-linux64.gz, https://github.com/mozilla/geckodriver/releases/download/v0.5.0/wires-0.5.0-osx.gz, https://github.com/mozilla/geckodriver/releases/download/v0.5.0/wires-v0.5.0-win.zip, https://github.com/mozilla/geckodriver/releases/download/v0.4.2/wires-0.4.2-linux64.gz, https://github.com/mozilla/geckodriver/releases/download/v0.4.2/wires-0.4.2-osx.gz, https://github.com/mozilla/geckodriver/releases/download/v0.4.2/wires-0.4.2-win.zip, https://github.com/mozilla/geckodriver/releases/download/v0.4.1/wires-0.4.1-osx.gz] @io.github.bonigarcia.wdm.WebDriverManager 
2020-08-15 19:51:38,446 DEBUG [http-nio-8004-exec-2  ] [WebDriverManager    ] - Driver to be downloaded geckodriver 0.27.0                                  @io.github.bonigarcia.wdm.WebDriverManager 
2020-08-15 19:51:38,447 TRACE [http-nio-8004-exec-2  ] [WebDriverManager    ] - Driver URLs after filtering for version: [https://github.com/mozilla/geckodriver/releases/download/v0.27.0/geckodriver-v0.27.0-linux32.tar.gz, https://github.com/mozilla/geckodriver/releases/download/v0.27.0/geckodriver-v0.27.0-linux32.tar.gz.asc, https://github.com/mozilla/geckodriver/releases/download/v0.27.0/geckodriver-v0.27.0-linux64.tar.gz, https://github.com/mozilla/geckodriver/releases/download/v0.27.0/geckodriver-v0.27.0-linux64.tar.gz.asc, https://github.com/mozilla/geckodriver/releases/download/v0.27.0/geckodriver-v0.27.0-macos.tar.gz, https://github.com/mozilla/geckodriver/releases/download/v0.27.0/geckodriver-v0.27.0-win32.zip, https://github.com/mozilla/geckodriver/releases/download/v0.27.0/geckodriver-v0.27.0-win64.zip] @io.github.bonigarcia.wdm.WebDriverManager 
2020-08-15 19:51:38,447 TRACE [http-nio-8004-exec-2  ] [UrlHandler          ] - URLs before filtering by OS (LINUX): [https://github.com/mozilla/geckodriver/releases/download/v0.27.0/geckodriver-v0.27.0-linux32.tar.gz, https://github.com/mozilla/geckodriver/releases/download/v0.27.0/geckodriver-v0.27.0-linux32.tar.gz.asc, https://github.com/mozilla/geckodriver/releases/download/v0.27.0/geckodriver-v0.27.0-linux64.tar.gz, https://github.com/mozilla/geckodriver/releases/download/v0.27.0/geckodriver-v0.27.0-linux64.tar.gz.asc, https://github.com/mozilla/geckodriver/releases/download/v0.27.0/geckodriver-v0.27.0-macos.tar.gz, https://github.com/mozilla/geckodriver/releases/download/v0.27.0/geckodriver-v0.27.0-win32.zip, https://github.com/mozilla/geckodriver/releases/download/v0.27.0/geckodriver-v0.27.0-win64.zip] @io.github.bonigarcia.wdm.online.UrlHandler 
2020-08-15 19:51:38,448 TRACE [http-nio-8004-exec-2  ] [UrlHandler          ] - URLs after filtering by OS (LINUX): [https://github.com/mozilla/geckodriver/releases/download/v0.27.0/geckodriver-v0.27.0-linux32.tar.gz, https://github.com/mozilla/geckodriver/releases/download/v0.27.0/geckodriver-v0.27.0-linux32.tar.gz.asc, https://github.com/mozilla/geckodriver/releases/download/v0.27.0/geckodriver-v0.27.0-linux64.tar.gz, https://github.com/mozilla/geckodriver/releases/download/v0.27.0/geckodriver-v0.27.0-linux64.tar.gz.asc] @io.github.bonigarcia.wdm.online.UrlHandler 
2020-08-15 19:51:38,448 TRACE [http-nio-8004-exec-2  ] [UrlHandler          ] - URLs before filtering by architecture (64): [https://github.com/mozilla/geckodriver/releases/download/v0.27.0/geckodriver-v0.27.0-linux32.tar.gz, https://github.com/mozilla/geckodriver/releases/download/v0.27.0/geckodriver-v0.27.0-linux32.tar.gz.asc, https://github.com/mozilla/geckodriver/releases/download/v0.27.0/geckodriver-v0.27.0-linux64.tar.gz, https://github.com/mozilla/geckodriver/releases/download/v0.27.0/geckodriver-v0.27.0-linux64.tar.gz.asc] @io.github.bonigarcia.wdm.online.UrlHandler 
2020-08-15 19:51:38,449 TRACE [http-nio-8004-exec-2  ] [UrlHandler          ] - URLs after filtering by architecture (64): [https://github.com/mozilla/geckodriver/releases/download/v0.27.0/geckodriver-v0.27.0-linux64.tar.gz, https://github.com/mozilla/geckodriver/releases/download/v0.27.0/geckodriver-v0.27.0-linux64.tar.gz.asc] @io.github.bonigarcia.wdm.online.UrlHandler 
2020-08-15 19:51:43,306 TRACE [http-nio-8004-exec-2  ] [UrlHandler          ] - URLs before filtering by ignored versions ([0.27.0]): [https://github.com/mozilla/geckodriver/releases/download/v0.27.0/geckodriver-v0.27.0-linux64.tar.gz, https://github.com/mozilla/geckodriver/releases/download/v0.27.0/geckodriver-v0.27.0-linux64.tar.gz.asc] @io.github.bonigarcia.wdm.online.UrlHandler 
2020-08-15 19:51:43,307 TRACE [http-nio-8004-exec-2  ] [UrlHandler          ] - URLs after filtering by ignored versions ([0.27.0]): []                     @io.github.bonigarcia.wdm.online.UrlHandler 
2020-08-15 19:51:43,307 TRACE [http-nio-8004-exec-2  ] [UrlHandler          ] - URLs before filtering by beta versions: []                                  @io.github.bonigarcia.wdm.online.UrlHandler 
2020-08-15 19:51:43,308 TRACE [http-nio-8004-exec-2  ] [UrlHandler          ] - URLs after filtering by beta versions: []                                   @io.github.bonigarcia.wdm.online.UrlHandler 
2020-08-15 19:51:43,310 WARN  [http-nio-8004-exec-2  ] [WebDriverManager    ] - There was an error managing geckodriver 0.27.0 (No proper candidate URL to download geckodriver 0.27.0) ... trying again using latest driver stored in cache @io.github.bonigarcia.wdm.WebDriverManager 
2020-08-15 19:51:43,313 TRACE [http-nio-8004-exec-2  ] [WebDriverManager    ] - Error trace:                                                                @io.github.bonigarcia.wdm.WebDriverManager 
io.github.bonigarcia.wdm.config.WebDriverManagerException: No proper candidate URL to download geckodriver 0.27.0
```

**Error trace**
```
io.github.bonigarcia.wdm.config.WebDriverManagerException: No proper candidate URL to download geckodriver 0.27.0
	at io.github.bonigarcia.wdm.online.UrlHandler.getCandidateUrl(UrlHandler.java:284)
	at io.github.bonigarcia.wdm.WebDriverManager.download(WebDriverManager.java:603)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:535)
	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:744)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:541)
	at io.github.bonigarcia.wdm.WebDriverManager.setup(WebDriverManager.java:277)
	at net.nlacombe.vault.importws.util.WebDriverUtil.getWebDriver(WebDriverUtil.java:36)
```
The last line and the rest of the stacktrace is my own code.

**Comment by bonigarcia** [comment]
I have just committed a patch implementing this. I plan to release a new version of WebDriverManager this week.

**Comment by nlacombe42** [comment]
I confirm it works :)
