### ISSUE TITLE
Cannot find MSEdge binary

### ISSUE THREAD

**Issue by batuhan-evam** [bonigarcia/webdrivermanager#544]
**Description of the problem**: I can't run my tests on Windows Edge.

**Browser and version**:  Microsoft Edge 44.18362.449.0

**Operating system**: Windows 10 Turkish Language

**WebDriverManager version**: 4.2.0

**WebDriverManager use**: 

```
public WebDriver createDriver() {
        DesiredCapabilities cap = setCapabilities();

        if (prop.runsOnGrid())
            return remoteDriver(cap);

        switch (prop.getBrowser().toLowerCase()) {
            case "firefox":
                return firefoxDriver(cap);
            case "edge":
                return edgeDriver(cap);
            default:
                return chromeDriver(cap);
        }
    }

private WebDriver edgeDriver(DesiredCapabilities cap) {
        WebDriverManager.edgedriver().setup();
        EdgeOptions edgeOptions = new EdgeOptions();

        edgeOptions.setCapability("headless", prop.isHeadless());
        edgeOptions.setCapability("window-size", "1536,722");
        edgeOptions.setCapability("profile.default_content_settings.popups", 0);
        edgeOptions.setCapability("download.default_directory", prop.getDownloadPath());
        edgeOptions.setCapability("browser.setDownloadBehavior", "allow");
        edgeOptions.merge(cap);

        return new EdgeDriver(edgeOptions);
    }
```

**WebDriverManager traces**: 

```
11:21:04.770 [main] DEBUG i.g.bonigarcia.wdm.versions.Shell - Running command on the shell: [wmic.exe, datafile, where, name='C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe', get, Version, /value]
11:21:04.896 [main] DEBUG i.g.bonigarcia.wdm.versions.Shell - Result: 
11:21:04.897 [main] DEBUG i.g.bonigarcia.wdm.versions.Shell - Running command on the shell: [wmic.exe, datafile, where, name='C:\\Program Files\\Microsoft\\Edge\\Application\\msedge.exe', get, Version, /value]
11:21:04.993 [main] DEBUG i.g.bonigarcia.wdm.versions.Shell - Result: 
11:21:04.994 [main] DEBUG i.g.bonigarcia.wdm.versions.Shell - Running command on the shell: [wmic.exe, datafile, where, name='C:\\Program Files (x86)\\Microsoft\\Edge Beta\\Application\\msedge.exe', get, Version, /value]
11:21:05.100 [main] DEBUG i.g.bonigarcia.wdm.versions.Shell - Result: 
11:21:05.101 [main] DEBUG i.g.bonigarcia.wdm.versions.Shell - Running command on the shell: [wmic.exe, datafile, where, name='C:\\Program Files\\Microsoft\\Edge Beta\\Application\\msedge.exe', get, Version, /value]
11:21:05.198 [main] DEBUG i.g.bonigarcia.wdm.versions.Shell - Result: 
11:21:05.199 [main] DEBUG i.g.bonigarcia.wdm.versions.Shell - Running command on the shell: [wmic.exe, datafile, where, name='C:\\Program Files (x86)\\Microsoft\\Edge Dev\\Application\\msedge.exe', get, Version, /value]
11:21:05.292 [main] DEBUG i.g.bonigarcia.wdm.versions.Shell - Result: 
11:21:05.335 [main] DEBUG i.g.bonigarcia.wdm.versions.Shell - Running command on the shell: [wmic.exe, datafile, where, name='C:\\Program Files\\Microsoft\\Edge Dev\\Application\\msedge.exe', get, Version, /value]
11:21:05.424 [main] DEBUG i.g.bonigarcia.wdm.versions.Shell - Result: 
11:21:05.425 [main] DEBUG i.g.bonigarcia.wdm.WebDriverManager - The driver version for Edge is unknown ... trying with latest
11:21:05.442 [main] DEBUG o.a.h.c.h.i.c.InternalHttpClient - ex-00000001: preparing request execution
11:21:05.448 [main] DEBUG o.a.h.c.h.protocol.RequestAddCookies - Cookie spec selected: strict
11:21:05.455 [main] DEBUG o.a.h.c.h.protocol.RequestAuthCache - Auth cache not set in the context
11:21:05.456 [main] DEBUG o.a.h.c.h.impl.classic.ProtocolExec - ex-00000001: target auth state: UNCHALLENGED
11:21:05.457 [main] DEBUG o.a.h.c.h.impl.classic.ProtocolExec - ex-00000001: proxy auth state: UNCHALLENGED
11:21:05.458 [main] DEBUG o.a.h.c.h.impl.classic.ConnectExec - ex-00000001: acquiring connection with route {s}->https://msedgedriver.azureedge.net:443
11:21:05.458 [main] DEBUG o.a.h.c.h.i.c.InternalHttpClient - ex-00000001: acquiring endpoint (3 MINUTES)
11:21:05.460 [main] DEBUG o.a.h.c.h.i.i.PoolingHttpClientConnectionManager - ex-00000001: endpoint lease request (3 MINUTES) [route: {s}->https://msedgedriver.azureedge.net:443][total available: 0; route allocated: 0 of 5; total allocated: 0 of 25]
11:21:05.467 [main] DEBUG o.a.h.c.h.i.i.PoolingHttpClientConnectionManager - ex-00000001: endpoint leased [route: {s}->https://msedgedriver.azureedge.net:443][total available: 0; route allocated: 1 of 5; total allocated: 1 of 25]
11:21:05.483 [main] DEBUG o.a.h.c.h.i.i.PoolingHttpClientConnectionManager - ex-00000001: acquired ep-00000000
11:21:05.483 [main] DEBUG o.a.h.c.h.i.c.InternalHttpClient - ex-00000001: acquired endpoint ep-00000000
11:21:05.483 [main] DEBUG o.a.h.c.h.impl.classic.ConnectExec - ex-00000001: opening connection {s}->https://msedgedriver.azureedge.net:443
11:21:05.484 [main] DEBUG o.a.h.c.h.i.c.InternalHttpClient - ep-00000000: connecting endpoint (30 SECONDS)
11:21:05.484 [main] DEBUG o.a.h.c.h.i.i.PoolingHttpClientConnectionManager - ep-00000000: connecting endpoint to https://msedgedriver.azureedge.net:443 (30 SECONDS)
11:21:05.604 [main] DEBUG o.a.h.c.h.i.i.DefaultHttpClientConnectionOperator - http-outgoing-0: connecting to msedgedriver.azureedge.net/13.107.246.10:443
11:21:05.605 [main] DEBUG o.a.h.c.h.s.SSLConnectionSocketFactory - Connecting socket to msedgedriver.azureedge.net/13.107.246.10:443 with timeout 30 SECONDS
11:21:05.674 [main] DEBUG o.a.h.c.h.s.SSLConnectionSocketFactory - Enabled protocols: [TLSv1.2]
11:21:05.674 [main] DEBUG o.a.h.c.h.s.SSLConnectionSocketFactory - Enabled cipher suites:[TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384, TLS_RSA_WITH_AES_256_GCM_SHA384, TLS_ECDH_ECDSA_WITH_AES_256_GCM_SHA384, TLS_ECDH_RSA_WITH_AES_256_GCM_SHA384, TLS_DHE_RSA_WITH_AES_256_GCM_SHA384, TLS_DHE_DSS_WITH_AES_256_GCM_SHA384, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, TLS_RSA_WITH_AES_128_GCM_SHA256, TLS_ECDH_ECDSA_WITH_AES_128_GCM_SHA256, TLS_ECDH_RSA_WITH_AES_128_GCM_SHA256, TLS_DHE_RSA_WITH_AES_128_GCM_SHA256, TLS_DHE_DSS_WITH_AES_128_GCM_SHA256, TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384, TLS_RSA_WITH_AES_256_CBC_SHA256, TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA384, TLS_ECDH_RSA_WITH_AES_256_CBC_SHA384, TLS_DHE_RSA_WITH_AES_256_CBC_SHA256, TLS_DHE_DSS_WITH_AES_256_CBC_SHA256, TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA, TLS_RSA_WITH_AES_256_CBC_SHA, TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA, TLS_ECDH_RSA_WITH_AES_256_CBC_SHA, TLS_DHE_RSA_WITH_AES_256_CBC_SHA, TLS_DHE_DSS_WITH_AES_256_CBC_SHA, TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256, TLS_RSA_WITH_AES_128_CBC_SHA256, TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA256, TLS_ECDH_RSA_WITH_AES_128_CBC_SHA256, TLS_DHE_RSA_WITH_AES_128_CBC_SHA256, TLS_DHE_DSS_WITH_AES_128_CBC_SHA256, TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA, TLS_RSA_WITH_AES_128_CBC_SHA, TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA, TLS_ECDH_RSA_WITH_AES_128_CBC_SHA, TLS_DHE_RSA_WITH_AES_128_CBC_SHA, TLS_DHE_DSS_WITH_AES_128_CBC_SHA, TLS_EMPTY_RENEGOTIATION_INFO_SCSV]
11:21:05.674 [main] DEBUG o.a.h.c.h.s.SSLConnectionSocketFactory - Starting handshake
11:21:05.924 [main] DEBUG o.a.h.c.h.s.SSLConnectionSocketFactory - Secure session established
11:21:05.925 [main] DEBUG o.a.h.c.h.s.SSLConnectionSocketFactory -  negotiated protocol: TLSv1.2
11:21:05.925 [main] DEBUG o.a.h.c.h.s.SSLConnectionSocketFactory -  negotiated cipher suite: TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
11:21:05.925 [main] DEBUG o.a.h.c.h.s.SSLConnectionSocketFactory -  peer principal: CN=*.azureedge.net
11:21:05.925 [main] DEBUG o.a.h.c.h.s.SSLConnectionSocketFactory -  peer alternative names: [*.azureedge.net, *.media.microsoftstream.com, *.origin.mediaservices.windows.net, *.streaming.mediaservices.windows.net]
11:21:05.926 [main] DEBUG o.a.h.c.h.s.SSLConnectionSocketFactory -  issuer principal: CN=Microsoft IT TLS CA 4, OU=Microsoft IT, O=Microsoft Corporation, L=Redmond, ST=Washington, C=US
11:21:05.928 [main] DEBUG o.a.h.c.h.i.i.DefaultHttpClientConnectionOperator - http-outgoing-0: connection established 192.168.2.115:50753<->13.107.246.10:443
11:21:05.928 [main] DEBUG o.a.h.c.h.i.i.PoolingHttpClientConnectionManager - ep-00000000: connected http-outgoing-0
11:21:05.928 [main] DEBUG o.a.h.c.h.i.c.InternalHttpClient - ep-00000000: endpoint connected
11:21:05.928 [main] DEBUG o.a.h.c.h.i.classic.MainClientExec - ex-00000001: executing GET /LATEST_STABLE HTTP/1.1
11:21:05.929 [main] DEBUG o.a.h.c.h.i.c.InternalHttpClient - ep-00000000: start execution ex-00000001
11:21:05.929 [main] DEBUG o.a.h.c.h.i.i.PoolingHttpClientConnectionManager - ep-00000000: executing exchange ex-00000001 over http-outgoing-0
11:21:05.930 [main] DEBUG org.apache.hc.client5.http.headers - http-outgoing-0 >> GET /LATEST_STABLE HTTP/1.1
11:21:05.930 [main] DEBUG org.apache.hc.client5.http.headers - http-outgoing-0 >> user-agent: Apache-HttpClient/5.0
11:21:05.930 [main] DEBUG org.apache.hc.client5.http.headers - http-outgoing-0 >> accept-encoding: gzip, deflate, br
11:21:05.930 [main] DEBUG org.apache.hc.client5.http.headers - http-outgoing-0 >> cache-control: max-age=0
11:21:05.930 [main] DEBUG org.apache.hc.client5.http.headers - http-outgoing-0 >> Host: msedgedriver.azureedge.net
11:21:05.930 [main] DEBUG org.apache.hc.client5.http.headers - http-outgoing-0 >> Connection: keep-alive
11:21:05.931 [main] DEBUG org.apache.hc.client5.http.wire - http-outgoing-0 >> "GET /LATEST_STABLE HTTP/1.1[\r][\n]"
11:21:05.931 [main] DEBUG org.apache.hc.client5.http.wire - http-outgoing-0 >> "user-agent: Apache-HttpClient/5.0[\r][\n]"
11:21:05.931 [main] DEBUG org.apache.hc.client5.http.wire - http-outgoing-0 >> "accept-encoding: gzip, deflate, br[\r][\n]"
11:21:05.931 [main] DEBUG org.apache.hc.client5.http.wire - http-outgoing-0 >> "cache-control: max-age=0[\r][\n]"
11:21:05.931 [main] DEBUG org.apache.hc.client5.http.wire - http-outgoing-0 >> "Host: msedgedriver.azureedge.net[\r][\n]"
11:21:05.931 [main] DEBUG org.apache.hc.client5.http.wire - http-outgoing-0 >> "Connection: keep-alive[\r][\n]"
11:21:05.931 [main] DEBUG org.apache.hc.client5.http.wire - http-outgoing-0 >> "[\r][\n]"
11:21:05.985 [main] DEBUG org.apache.hc.client5.http.wire - http-outgoing-0 << "HTTP/1.1 200 OK[\r][\n]"
11:21:05.985 [main] DEBUG org.apache.hc.client5.http.wire - http-outgoing-0 << "Content-Length: 28[\r][\n]"
11:21:05.985 [main] DEBUG org.apache.hc.client5.http.wire - http-outgoing-0 << "Content-Type: application/octet-stream[\r][\n]"
11:21:05.985 [main] DEBUG org.apache.hc.client5.http.wire - http-outgoing-0 << "Content-MD5: uHmNjNU2zHoqGM0urJmx3Q==[\r][\n]"
11:21:05.985 [main] DEBUG org.apache.hc.client5.http.wire - http-outgoing-0 << "Last-Modified: Mon, 31 Aug 2020 21:54:35 GMT[\r][\n]"
11:21:05.985 [main] DEBUG org.apache.hc.client5.http.wire - http-outgoing-0 << "ETag: 0x8D84DF8736BC103[\r][\n]"
11:21:05.985 [main] DEBUG org.apache.hc.client5.http.wire - http-outgoing-0 << "Vary: Origin[\r][\n]"
11:21:05.985 [main] DEBUG org.apache.hc.client5.http.wire - http-outgoing-0 << "X-Cache: TCP_HIT[\r][\n]"
11:21:05.985 [main] DEBUG org.apache.hc.client5.http.wire - http-outgoing-0 << "Server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0[\r][\n]"
11:21:05.985 [main] DEBUG org.apache.hc.client5.http.wire - http-outgoing-0 << "x-ms-request-id: bc877315-801e-003b-3dff-80af5c000000[\r][\n]"
11:21:05.985 [main] DEBUG org.apache.hc.client5.http.wire - http-outgoing-0 << "x-ms-version: 2009-09-19[\r][\n]"
11:21:05.985 [main] DEBUG org.apache.hc.client5.http.wire - http-outgoing-0 << "x-ms-lease-status: unlocked[\r][\n]"
11:21:05.985 [main] DEBUG org.apache.hc.client5.http.wire - http-outgoing-0 << "x-ms-blob-type: BlockBlob[\r][\n]"
11:21:05.985 [main] DEBUG org.apache.hc.client5.http.wire - http-outgoing-0 << "X-Azure-Ref: 08FVPXwAAAAAgkKU/kn1zTJMfgGcvhSciQU1TRURHRTA1MTMAYmZmZGRiZWYtMjA4NS00Mzk5LTk3MDMtYjQxYWI1YzI4YTYz[\r][\n]"
11:21:05.986 [main] DEBUG org.apache.hc.client5.http.wire - http-outgoing-0 << "Date: Wed, 02 Sep 2020 08:21:03 GMT[\r][\n]"
11:21:05.986 [main] DEBUG org.apache.hc.client5.http.wire - http-outgoing-0 << "[\r][\n]"
11:21:05.986 [main] DEBUG org.apache.hc.client5.http.wire - http-outgoing-0 << "[0xffffffff][0xfffffffe]8[0x0]5[0x0].[0x0]0[0x0].[0x0]5[0x0]6[0x0]4[0x0].[0x0]4[0x0]4[0x0][\r][0x0][\n]"
11:21:05.986 [main] DEBUG org.apache.hc.client5.http.wire - http-outgoing-0 << "[0x0]"
11:21:05.989 [main] DEBUG org.apache.hc.client5.http.headers - http-outgoing-0 << HTTP/1.1 200 OK
11:21:05.989 [main] DEBUG org.apache.hc.client5.http.headers - http-outgoing-0 << Content-Length: 28
11:21:05.989 [main] DEBUG org.apache.hc.client5.http.headers - http-outgoing-0 << Content-Type: application/octet-stream
11:21:05.989 [main] DEBUG org.apache.hc.client5.http.headers - http-outgoing-0 << Content-MD5: uHmNjNU2zHoqGM0urJmx3Q==
11:21:05.989 [main] DEBUG org.apache.hc.client5.http.headers - http-outgoing-0 << Last-Modified: Mon, 31 Aug 2020 21:54:35 GMT
11:21:05.989 [main] DEBUG org.apache.hc.client5.http.headers - http-outgoing-0 << ETag: 0x8D84DF8736BC103
11:21:05.989 [main] DEBUG org.apache.hc.client5.http.headers - http-outgoing-0 << Vary: Origin
11:21:05.989 [main] DEBUG org.apache.hc.client5.http.headers - http-outgoing-0 << X-Cache: TCP_HIT
11:21:05.989 [main] DEBUG org.apache.hc.client5.http.headers - http-outgoing-0 << Server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
11:21:05.989 [main] DEBUG org.apache.hc.client5.http.headers - http-outgoing-0 << x-ms-request-id: bc877315-801e-003b-3dff-80af5c000000
11:21:05.989 [main] DEBUG org.apache.hc.client5.http.headers - http-outgoing-0 << x-ms-version: 2009-09-19
11:21:05.989 [main] DEBUG org.apache.hc.client5.http.headers - http-outgoing-0 << x-ms-lease-status: unlocked
11:21:05.989 [main] DEBUG org.apache.hc.client5.http.headers - http-outgoing-0 << x-ms-blob-type: BlockBlob
11:21:05.989 [main] DEBUG org.apache.hc.client5.http.headers - http-outgoing-0 << X-Azure-Ref: 08FVPXwAAAAAgkKU/kn1zTJMfgGcvhSciQU1TRURHRTA1MTMAYmZmZGRiZWYtMjA4NS00Mzk5LTk3MDMtYjQxYWI1YzI4YTYz
11:21:05.990 [main] DEBUG org.apache.hc.client5.http.headers - http-outgoing-0 << Date: Wed, 02 Sep 2020 08:21:03 GMT
11:21:05.994 [main] DEBUG o.a.h.c.h.i.classic.MainClientExec - ex-00000001: connection can be kept alive for 3 MINUTES
11:21:05.999 [main] DEBUG o.a.h.c.h.i.c.InternalHttpClient - ep-00000000: releasing valid endpoint
11:21:05.999 [main] DEBUG o.a.h.c.h.i.i.PoolingHttpClientConnectionManager - ep-00000000: releasing endpoint
11:21:05.999 [main] DEBUG o.a.h.c.h.i.i.PoolingHttpClientConnectionManager - ep-00000000: connection http-outgoing-0 can be kept alive for 3 MINUTES
11:21:06.000 [main] DEBUG o.a.h.c.h.i.i.PoolingHttpClientConnectionManager - ep-00000000: connection released [route: {s}->https://msedgedriver.azureedge.net:443][total available: 1; route allocated: 1 of 5; total allocated: 1 of 25]
11:21:06.000 [main] DEBUG i.g.b.wdm.versions.VersionDetector - Latest version of msedgedriver according to https://msedgedriver.azureedge.net/LATEST_STABLE is 85.0.564.44
11:21:06.001 [main] TRACE i.g.b.wdm.cache.CacheHandler - Checking if msedgedriver exists in cache
11:21:06.023 [main] TRACE i.g.b.wdm.cache.CacheHandler - Filter cache by msedgedriver -- input list [C:\Users\90539\.cache\selenium\chromedriver\win32\84.0.4147.30\chromedriver.exe, C:\Users\90539\.cache\selenium\chromedriver\win32\85.0.4183.87\chromedriver.exe, C:\Users\90539\.cache\selenium\geckodriver\win64\0.27.0\geckodriver.exe, C:\Users\90539\.cache\selenium\msedgedriver\win64\85.0.564.44\msedgedriver.exe, C:\Users\90539\.cache\selenium\resolution.properties] -- output list [C:\Users\90539\.cache\selenium\msedgedriver\win64\85.0.564.44\msedgedriver.exe] 
11:21:06.024 [main] TRACE i.g.b.wdm.cache.CacheHandler - Filter cache by 85.0.564.44 -- input list [C:\Users\90539\.cache\selenium\msedgedriver\win64\85.0.564.44\msedgedriver.exe] -- output list [C:\Users\90539\.cache\selenium\msedgedriver\win64\85.0.564.44\msedgedriver.exe] 
11:21:06.024 [main] TRACE i.g.b.wdm.cache.CacheHandler - Filter cache by WIN -- input list [C:\Users\90539\.cache\selenium\msedgedriver\win64\85.0.564.44\msedgedriver.exe] -- output list [C:\Users\90539\.cache\selenium\msedgedriver\win64\85.0.564.44\msedgedriver.exe] 
11:21:06.025 [main] DEBUG i.g.bonigarcia.wdm.WebDriverManager - Driver msedgedriver 85.0.564.44 found in cache
11:21:06.026 [main] INFO  i.g.bonigarcia.wdm.WebDriverManager - Exporting webdriver.edge.driver as C:\Users\90539\.cache\selenium\msedgedriver\win64\85.0.564.44\msedgedriver.exe
Starting MSEdgeDriver 85.0.564.44 (3b106b45f8e7cd4c3e2aac5a6ba411645c16df60) on port 26913
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping MSEdgeDriver safe.
MSEdgeDriver was started successfully.



org.openqa.selenium.WebDriverException: unknown error: cannot find MSEdge binary
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'BATUARSLAN', ip: '192.168.2.115', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_261'
Driver info: driver.version: EdgeDriver
remote stacktrace: Backtrace:
	Ordinal0 [0x0082BFA3+3194787]
	Ordinal0 [0x0060770C+947980]
	Ordinal0 [0x0058DBDC+449500]
	Ordinal0 [0x0058BC1E+441374]
	Ordinal0 [0x005AEE5B+585307]
	Ordinal0 [0x005AE8FD+583933]
	Ordinal0 [0x005ACD5B+576859]
	Ordinal0 [0x00593302+471810]
	Ordinal0 [0x0059406A+475242]
	Ordinal0 [0x00594007+475143]
	Ordinal0 [0x007504AB+2294955]
	GetHandleVerifier [0x00929FDD+940269]
	GetHandleVerifier [0x0093AAB7+1008583]
	GetHandleVerifier [0x0092A906+942614]
	Ordinal0 [0x00748EF8+2264824]
	Ordinal0 [0x00751A4B+2300491]
	Ordinal0 [0x00751BC1+2300865]
	Ordinal0 [0x0075FB70+2358128]
	BaseThreadInitThunk [0x75A06359+25]
	RtlGetAppContainerNamedObjectPath [0x77A17C24+228]
	RtlGetAppContainerNamedObjectPath [0x77A17BF4+180]


	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$errorHandler$0(W3CHandshakeResponse.java:62)
	at org.openqa.selenium.remote.HandshakeResponse.lambda$getResponseFunction$0(HandshakeResponse.java:30)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:126)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:128)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:74)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at org.openqa.selenium.edge.EdgeDriver.<init>(EdgeDriver.java:141)
	at org.openqa.selenium.edge.EdgeDriver.<init>(EdgeDriver.java:130)
	at utils.driver.DriverFactory.edgeDriver(DriverFactory.java:124)
	at utils.driver.DriverFactory.createDriver(DriverFactory.java:49)
	at base.TestCase.beforeClass(TestCase.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:63)
	at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:348)
	at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:302)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:176)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.testng.TestRunner.privateRun(TestRunner.java:766)
	at org.testng.TestRunner.run(TestRunner.java:587)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
	at org.testng.TestNG.runSuites(TestNG.java:1039)
	at org.testng.TestNG.run(TestNG.java:1007)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
```

**Comment by eliasnogueira** [comment]
Hi @batuhan-evam 
Based on the following message I would say that the Edge browser wasn't found in your machine
```
org.openqa.selenium.WebDriverException: unknown error: cannot find MSEdge binary
```

WebDriverManager uses the Edge driver based on the MSEdge with the Chromium engine (browser version => 75.0.139.20)
As I'm not a Windows user I would like to know if `44.18362.449.0` is the latest version for MSEdge on Windows machines.

**Comment by batuhan-evam** [comment]
I do have Edge browser though

**Comment by eliasnogueira** [comment]
@batuhan-evam I think I found the issue...
The default MSEdge provided on Windows 10 is not the one with the Chromium engine, so it won't work with the WebDriverManager.

If you download the latest Edge version from the link below you will get the "correct" one.
https://www.microsoft.com/en-us/edge

Can you please try to download, install it, and run your code again?

@bonigarcia I think it's worth mentioning that the Edge provided by the default Windows 10 installation won't work.
I will send a PR.

**Comment by batuhan-evam** [comment]
It worked @eliasnogueira thank you !

**Comment by xlemmingx** [comment]
Currently Edge Chromium is rolled out via windows update, so if you already installed Update KB4559309 it should work out of the box. But it comes gradually, so maybe you didn't even receive it yet.
At least in a few month this shouldn't be an issue anymore if you didn't opt out from windows updates in general or this specific update.

**Comment by bonigarcia** [comment]
Indeed, as of WebDriverManager 4.x, the Edge support is only for the Chromium-based version (Edge 75+). For Edge 44, you should install the driver as follows (doc [here](https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/)):

```
DISM.exe /Online /Add-Capability /CapabilityName:Microsoft.WebDriver~~~~0.0.1.0
```
