### ISSUE TITLE
Suddenly i am facing NoSuchMethodError, 

### ISSUE THREAD

**Issue by jayanthktn** [bonigarcia/webdrivermanager#545]
**Description of the problem**: 
I am facing java.lang.NoSuchMethodError today suddenly, i didn't done anything in my code. 

**Browser and version**:Chrome 85.

**Operating system**: Windows 10, 64 bits

**WebDriverManager version**: 4.2.0
**WebDriverManager use**: 
/*
     * Set chrome property, delete cookies and load the logger
     */
    protected void InitialiZe_driver(String driverPath){
        log.info("Initializing the driver in the base class!");
        /*System.setProperty("webdriver.chrome.driver",  driverPath);*/
        WebDriverManager.chromedriver().setup();
        driver = new ChromeDriver();
        driver.manage().window().maximize();
        driver.manage().deleteAllCookies();
        PropertyConfigurator.configure("Inputs/Log.Properties");
    }

**WebDriverManager traces**: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

	at io.github.bonigarcia.wdm.versions.Shell.runAndWaitNoLog(Shell.java:66)
	at io.github.bonigarcia.wdm.versions.Shell.runAndWaitArray(Shell.java:55)
	at io.github.bonigarcia.wdm.versions.Shell.runAndWait(Shell.java:49)

java.lang.NoSuchMethodError: org.apache.commons.io.IOUtils.toString(Ljava/io/InputStream;Ljava/nio/charset/Charset;)Ljava/lang/String;

	at io.github.bonigarcia.wdm.versions.Shell.runAndWaitNoLog(Shell.java:66)
	at io.github.bonigarcia.wdm.versions.Shell.runAndWaitArray(Shell.java:55)
	at io.github.bonigarcia.wdm.versions.Shell.runAndWait(Shell.java:49)
	at io.github.bonigarcia.wdm.versions.VersionDetector.getBrowserVersionInWindows(VersionDetector.java:220)
	at io.github.bonigarcia.wdm.versions.VersionDetector.getDefaultBrowserVersion(VersionDetector.java:180)
	at io.github.bonigarcia.wdm.managers.ChromeDriverManager.getBrowserVersionFromTheShell(ChromeDriverManager.java:124)
	at io.github.bonigarcia.wdm.WebDriverManager.detectBrowserVersion(WebDriverManager.java:696)
	at io.github.bonigarcia.wdm.WebDriverManager.resolveDriverVersion(WebDriverManager.java:569)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:521)
	at io.github.bonigarcia.wdm.WebDriverManager.setup(WebDriverManager.java:285)
	at CommonFunctions.DriverHelper.InitialiZe_driver(DriverHelper.java:142)
	at StepDefinitions.LoginSteps.initializeTheDriversAndProperties(LoginSteps.java:197)
	at ✽.Given initialize the drivers and properties(Jenkins/QA/DailyRun.feature:8)

java.lang.NoSuchMethodError: org.apache.commons.io.IOUtils.toString(Ljava/io/InputStream;Ljava/nio/charset/Charset;)Ljava/lang/String;

	at io.github.bonigarcia.wdm.versions.Shell.runAndWaitNoLog(Shell.java:66)
	at io.github.bonigarcia.wdm.versions.Shell.runAndWaitArray(Shell.java:55)
	at io.github.bonigarcia.wdm.versions.Shell.runAndWait(Shell.java:49)
	at io.github.bonigarcia.wdm.versions.VersionDetector.getBrowserVersionInWindows(VersionDetector.java:220)
	at io.github.bonigarcia.wdm.versions.VersionDetector.getDefaultBrowserVersion(VersionDetector.java:180)
	at io.github.bonigarcia.wdm.managers.ChromeDriverManager.getBrowserVersionFromTheShell(ChromeDriverManager.java:124)
	at io.github.bonigarcia.wdm.WebDriverManager.detectBrowserVersion(WebDriverManager.java:696)
	at io.github.bonigarcia.wdm.WebDriverManager.resolveDriverVersion(WebDriverManager.java:569)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:521)
	at io.github.bonigarcia.wdm.WebDriverManager.setup(WebDriverManager.java:285)
	at CommonFunctions.DriverHelper.InitialiZe_driver(DriverHelper.java:142)
	at StepDefinitions.LoginSteps.initializeTheDriversAndProperties(LoginSteps.java:197)
	at ✽.Given initialize the drivers and properties(Jenkins/QA/DailyRun.feature:8)

![image](https://user-images.githubusercontent.com/27004220/92071545-a1b00480-edcc-11ea-9bdd-8a32d31b11ae.png)

**Comment by anilreddy** [comment]
@jayanthktn Just add commons.io to your pom.xml and run again.

```java
<dependency>
    <groupId>commons-io</groupId>
    <artifactId>commons-io</artifactId>
    <version>2.7</version>
</dependency>
```

**Comment by jayanthktn** [comment]
Already added 2.5 version. Its working now. I thought to add comment
tomorrow. Anyway, Thanks for your help.

previously I was using common.io 1.7 version. That caused the issue.
Some one / any one please add as a note here.. like "If project using
common io lib, please make sure this should be above 2..3"



Thanks
Jayanth

**Comment by anilreddy** [comment]
Then close this defect.
