### ISSUE TITLE
msedgedriver 86.0.622.48 for WIN 64 not found in https://msedgedriver.azureedge.net/

### ISSUE THREAD

**Issue by ashishBorana007** [bonigarcia/webdrivermanager#567]
io.github.bonigarcia.wdm.config.WebDriverManagerException: io.github.bonigarcia.wdm.config.WebDriverManagerException: msedgedriver 86.0.622.48 for WIN 64 not found in https://msedgedriver.azureedge.net/
at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:725)
at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:531)
at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:722)
at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:531)
at io.github.bonigarcia.wdm.WebDriverManager.setup(WebDriverManager.java:277)

Caused by: io.github.bonigarcia.wdm.config.WebDriverManagerException: msedgedriver 86.0.622.48 for WIN 64 not found in https://msedgedriver.azureedge.net/
at io.github.bonigarcia.wdm.WebDriverManager.noCandidateUrlFound(WebDriverManager.java:607)
at io.github.bonigarcia.wdm.WebDriverManager.createUrlHandler(WebDriverManager.java:756)
at io.github.bonigarcia.wdm.WebDriverManager.download(WebDriverManager.java:593)
at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:525)
... 38 more

**Comment by bonigarcia** [comment]
Use the latest version of WebDriverManager, and please follow the issue template to report any further issue.

**Comment by ashishBorana007** [comment]
Apologies, thanks for the help.
