### ISSUE TITLE
Unable to download msedgedriver 86.0.622.48. Worked fine before the update.

### ISSUE THREAD

**Issue by ramam-v** [bonigarcia/webdrivermanager#568]
**Description of the problem**:  Unable to download msedgedriver 86.0.622.48.

**Browser and version**: Version 86.0.622.48 (Official build) (64-bit)

**Operating system**: Windows 10 64 bit

**WebDriverManager version**: 4.0.0. 

**WebDriverManager use**: WebDriverManager.edgedriver().setup();
				driver = new EdgeDriver(); 

**Error trace**: io.github.bonigarcia.wdm.config.WebDriverManagerException: io.github.bonigarcia.wdm.config.WebDriverManagerException: msedgedriver 86.0.622.48 for WIN 64 not found in https://msedgedriver.azureedge.net/
	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:725)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:531)
	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:722)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:531)
	at io.github.bonigarcia.wdm.WebDriverManager.setup(WebDriverManager.java:277)

**Comment by ramam-v** [comment]
I was able to resolve the issue by upgrading to  release 4.2.2
