### ISSUE TITLE
Getting Class Not Found Exception while using webdriver manager

### ISSUE THREAD

**Issue by Manoharch1994** [bonigarcia/webdrivermanager#588]
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

import io.github.bonigarcia.wdm.WebDriverManager;

public class AlertType2 {
	
	
	public static void main(String[] args) throws InterruptedException {
		//System.setProperty("webdriver.chrome.driver","C:\\drivers\\chromedriver.exe");
		WebDriverManager.chromedriver().setup();
		WebDriver driver= new ChromeDriver();
		driver.get("http://the-internet.herokuapp.com/javascript_alerts");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//button[contains(text(),'Click for JS Prompt')]")).click();
		String alerttext=driver.switchTo().alert().getText();
	
			Thread.sleep(2000);
		
		driver.switchTo().alert().sendKeys("Hello world");

	}

}

![wdmanagerissue](https://user-images.githubusercontent.com/39347104/102197407-1bd14880-3ee7-11eb-85b8-ec4686e5e08b.png)

**Comment by bonigarcia** [comment]
You need to resolve properly the dependencies of your project. I would use Maven or Gradle for that.

**Comment by wadhwasagar** [comment]
Hello I have used Maven for the same, I also get the same error, even though i have removed the "test" scope as my code is in src/java 

` public static void main(String[] args) throws InterruptedException {

        SeleniumTriage seleniumTriage = new SeleniumTriage();
        WebDriverManager.chromedriver().setup();
        WebDriver ldriver= new ChromeDriver();`

I have even added the http dependencies, but still the same issue


Error:
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/lang3/SystemUtils
	at io.github.bonigarcia.wdm.config.Config.defaultOsName(Config.java:282)
	at io.github.bonigarcia.wdm.config.Config.<init>(Config.java:94)
	at io.github.bonigarcia.wdm.WebDriverManager.<init>(WebDriverManager.java:164)
	at io.github.bonigarcia.wdm.managers.ChromeDriverManager.<init>(ChromeDriverManager.java:42)
	at io.github.bonigarcia.wdm.WebDriverManager.chromedriver(WebDriverManager.java:183)
	at pageObjects.SeleniumTriage2.main(SeleniumTriage2.java:41)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang3.SystemUtils
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 6 more
