### ISSUE TITLE
Getting WebDriver Manager issue on running my code in Edge Browser and Web Driver Manager version is 4.3.0

### ISSUE THREAD

**Issue by NishantJohri12** [bonigarcia/webdrivermanager#592]
Error is as below:
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" io.github.bonigarcia.wdm.config.WebDriverManagerException: io.github.bonigarcia.wdm.config.WebDriverManagerException: java.net.UnknownHostException: msedgedriver.azureedge.net
	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:776)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:573)
	at io.github.bonigarcia.wdm.WebDriverManager.fallback(WebDriverManager.java:792)
	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:773)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:573)
	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:766)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:573)
	at io.github.bonigarcia.wdm.WebDriverManager.setup(WebDriverManager.java:287)
	at com.ranosys.tims.automation.TimsAutomation.main(TimsAutomation.java:38)
Caused by: io.github.bonigarcia.wdm.config.WebDriverManagerException: java.net.UnknownHostException: msedgedriver.azureedge.net
	at io.github.bonigarcia.wdm.WebDriverManager.getDriversFromXml(WebDriverManager.java:915)
	at io.github.bonigarcia.wdm.managers.EdgeDriverManager.getDriverUrls(EdgeDriverManager.java:106)
	at io.github.bonigarcia.wdm.WebDriverManager.createUrlHandler(WebDriverManager.java:797)
	at io.github.bonigarcia.wdm.WebDriverManager.download(WebDriverManager.java:649)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:567)
	... 7 more
Caused by: java.net.UnknownHostException: msedgedriver.azureedge.net
	at java.net.InetAddress.getAllByName0(Unknown Source)
	at java.net.InetAddress.getAllByName(Unknown Source)
	at java.net.InetAddress.getAllByName(Unknown Source)
	at org.apache.hc.client5.http.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:43)
	at org.apache.hc.client5.http.impl.io.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:118)
	at org.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:409)
	at org.apache.hc.client5.http.impl.classic.InternalExecRuntime.connectEndpoint(InternalExecRuntime.java:164)
	at org.apache.hc.client5.http.impl.classic.InternalExecRuntime.connectEndpoint(InternalExecRuntime.java:174)
	at org.apache.hc.client5.http.impl.classic.ConnectExec.execute(ConnectExec.java:135)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
	at org.apache.hc.client5.http.impl.classic.ProtocolExec.execute(ProtocolExec.java:172)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
	at org.apache.hc.client5.http.impl.classic.HttpRequestRetryExec.execute(HttpRequestRetryExec.java:93)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
	at org.apache.hc.client5.http.impl.classic.ContentCompressionExec.execute(ContentCompressionExec.java:128)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
	at org.apache.hc.client5.http.impl.classic.RedirectExec.execute(RedirectExec.java:116)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.InternalHttpClient.doExecute(InternalHttpClient.java:178)
	at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:75)
	at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:89)
	at io.github.bonigarcia.wdm.online.HttpClient.execute(HttpClient.java:139)
	at io.github.bonigarcia.wdm.WebDriverManager.getDriversFromXml(WebDriverManager.java:900)
	... 11 more

**Comment by bonigarcia** [comment]
It seems a connectivity issue at your end. If you use a proxy, maybe you need to configure it using the WebDriverManager API. Take a look at the doc.
