### ISSUE TITLE
Microsoft Edge on macOS: "dyld: Library not loaded: @rpath/libc++.dylib"

### ISSUE THREAD

**Issue by jamespizzurro** [bonigarcia/webdrivermanager#593]
**Description of the problem**: On macOS, invoking `WebDriverManager.edgedriver().setup();` followed by `new EdgeDriver(new EdgeOptions());` yields the following error:
```
dyld: Library not loaded: @rpath/libc++.dylib
  Referenced from: /Users/jpizzurro/.m2/repository/webdriver/edgedriver/mac64/x64/87.0.669.0/msedgedriver
  Reason: image not found
```

**Browser and version**: Microsoft Edge Version 87.0.664.75 (Official build) (64-bit)

**Operating system**: macOS Catalina Version 10.15.7 (19H15)

**WebDriverManager version**: 4.3.0

**WebDriverManager use**:
```
WebDriverManager.edgedriver().setup();
new EdgeDriver(new EdgeOptions());
```

**WebDriverManager traces**: N/A

**Error trace**:
```
Exception in thread "main" org.openqa.selenium.WebDriverException: Timed out waiting for driver server to start.
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'C02Z90CQLVDV.fios-router.home', ip: '192.168.1.219', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.15.7', java.version: '1.8.0_231'
Driver info: driver.version: EdgeDriver
        at org.openqa.selenium.remote.service.DriverService.waitUntilAvailable(DriverService.java:202)
        at org.openqa.selenium.remote.service.DriverService.start(DriverService.java:188)
        at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:79)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
        at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
        at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
        at org.openqa.selenium.edge.EdgeDriver.<init>(EdgeDriver.java:141)
        at org.openqa.selenium.edge.EdgeDriver.<init>(EdgeDriver.java:130)
        at com.levelaccess.continuum.scriptexecutor.TestScriptExecutor.initialize(TestScriptExecutor.java:1723)
        at com.levelaccess.continuum.scriptexecutor.TestScriptExecutor.executeTests(TestScriptExecutor.java:1837)
        at com.levelaccess.continuum.scriptexecutor.TestScriptExecutor.main(TestScriptExecutor.java:68)
Caused by: org.openqa.selenium.net.UrlChecker$TimeoutException: Timed out waiting for [http://localhost:33304/status] to be available after 20006 ms
        at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:100)
        at org.openqa.selenium.remote.service.DriverService.waitUntilAvailable(DriverService.java:197)
        ... 10 more
Caused by: java.util.concurrent.TimeoutException
        at java.util.concurrent.FutureTask.get(FutureTask.java:205)
        at com.google.common.util.concurrent.SimpleTimeLimiter.callWithTimeout(SimpleTimeLimiter.java:156)
        at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:75)
        ... 11 more
```

Based on [this comment on a different issue](https://github.com/bonigarcia/webdrivermanager/issues/573#issuecomment-721994340), it seems like macOS users need to manually add `libc++.dylib` to the same directory where Microsoft WebDriver is installed. Could this be done for us to make using WebDriverManager truly automated when using Edge on a Mac?

**Comment by bonigarcia** [comment]
I've just committed a patch solving this issue. It will be available for the next version, to be released soon.

**Comment by jamespizzurro** [comment]
@bonigarcia Thank you very much!

**Comment by bonigarcia** [comment]
WebDriverManager 4.3.1 is out. This problem should be fixed in that release.

**Comment by jamespizzurro** [comment]
@bonigarcia Just retested using the same OS and browser versions after upgrading to WDM v4.3.1 and I'm no longer seeing the issue. Thank you again!
