### ISSUE TITLE
Error HTTP 403 executing https://api.github.com/repos/mozilla/geckodriver/releases

### ISSUE THREAD

**Issue by SureshGedela** [bonigarcia/webdrivermanager#614]
**Description of the problem**:  Getting 403 Error

**Browser and version**:  Firefox 86

**Operating system**: Windows 10

**WebDriverManager version**: 4.3.1

**WebDriverManager use**: 

private static FirefoxDriver getFirefoxDriver() {

		WebDriverManager.firefoxdriver().setup();

		DesiredCapabilities capabilities = DesiredCapabilities.firefox();
		capabilities.setCapability(FirefoxDriver.MARIONETTE, true);
		capabilities.setCapability(FirefoxDriver.PROFILE, fp);

		FirefoxOptions options = new FirefoxOptions();
		options.merge(capabilities);

		return new FirefoxDriver(options);
	}

**WebDriverManager traces**: 

 io.github.bonigarcia.wdm.config.WebDriverManagerException: io.github.bonigarcia.wdm.config.WebDriverManagerException: Error HTTP 403 executing https://api.github.com/repos/mozilla/geckodriver/releases
	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:776)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:573)
	at io.github.bonigarcia.wdm.WebDriverManager.fallback(WebDriverManager.java:792)
	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:769)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:573)
	at io.github.bonigarcia.wdm.WebDriverManager.setup(WebDriverManager.java:287)
	at com.carbonite.browser.BrowserUtil.getFirefoxDriver(BrowserUtil.java:136)
	at com.carbonite.browser.BrowserUtil.getWebDriver(BrowserUtil.java:344)
	at com.carbonite.browser.BrowserUtil.getWebDriver(BrowserUtil.java:229)
	at com.carbonite.hooks.Hooks.before(Hooks.java:81)
Caused by: io.github.bonigarcia.wdm.config.WebDriverManagerException: Error HTTP 403 executing https://api.github.com/repos/mozilla/geckodriver/releases
	at io.github.bonigarcia.wdm.online.HttpClient.execute(HttpClient.java:153)
	at io.github.bonigarcia.wdm.WebDriverManager.openGitHubConnection(WebDriverManager.java:947)
	at io.github.bonigarcia.wdm.WebDriverManager.getDriversFromGitHub(WebDriverManager.java:961)
	at io.github.bonigarcia.wdm.managers.FirefoxDriverManager.getDriverUrls(FirefoxDriverManager.java:90)
	at io.github.bonigarcia.wdm.WebDriverManager.createUrlHandler(WebDriverManager.java:797)
	at io.github.bonigarcia.wdm.WebDriverManager.download(WebDriverManager.java:649)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:567)
	at io.github.bonigarcia.wdm.WebDriverManager.fallback(WebDriverManager.java:792)
	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:769)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:573)
	at io.github.bonigarcia.wdm.WebDriverManager.setup(WebDriverManager.java:287)

**Comment by SureshGedela** [comment]
Known issue. Closing it.

**Comment by kriegaex** [comment]
A link for documentation about the known issue and how to solve it:
https://github.com/bonigarcia/webdrivermanager/blob/master/src/doc/asciidoc/index.adoc#http-response-code-403
