### ISSUE TITLE
getting Exception in thread "main" java.lang.IllegalStateException: The path to the driver executable The path to the driver executable must be set by the webdriver.chrome.driver system property; for more information, see https://github.com/SeleniumHQ/selenium/wiki/ChromeDriver. The latest version can be downloaded from http://chromedriver.storage.googleapis.com/index.html

### ISSUE THREAD

**Issue by biswajeetsethi** [bonigarcia/webdrivermanager#639]
HI Team,
 I am getting error while running the webdriver code. Please advise if I am doing anything wrong.

Exception in thread "main" java.lang.IllegalStateException: The path to the driver executable The path to the driver executable must be set by the webdriver.chrome.driver system property; for more information, see https://github.com/SeleniumHQ/selenium/wiki/ChromeDriver. The latest version can be downloaded from http://chromedriver.storage.googleapis.com/index.html

*Version 90.0.4430.85 (Official Build) (64-bit)
**Wn10

**"C:\Program Files\Java\jdk-16\bin\java.exe" "-javaagent:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.3.3\lib\idea_rt.jar=51817:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.3.3\bin" -Dfile.encoding=UTF-8 -classpath D:\IdeaProjects\MySelenium\out\production\MySelenium;D:\IdeaProjects\selenium-java-4.0.0-beta-3\selenium-api-4.0.0-beta-3.jar;D:\IdeaProjects\selenium-java-4.0.0-beta-3\selenium-http-4.0.0-beta-3.jar;D:\IdeaProjects\selenium-java-4.0.0-beta-3\selenium-java-4.0.0-beta-3.jar;D:\IdeaProjects\selenium-java-4.0.0-beta-3\selenium-json-4.0.0-beta-3.jar;D:\IdeaProjects\selenium-java-4.0.0-beta-3\selenium-support-4.0.0-beta-3.jar;D:\IdeaProjects\selenium-java-4.0.0-beta-3\selenium-devtools-4.0.0-beta-3.jar;D:\IdeaProjects\selenium-java-4.0.0-beta-3\selenium-ie-driver-4.0.0-beta-3.jar;D:\IdeaProjects\selenium-java-4.0.0-beta-3\selenium-api-4.0.0-beta-3-sources.jar;D:\IdeaProjects\selenium-java-4.0.0-beta-3\selenium-edge-driver-4.0.0-beta-3.jar;D:\IdeaProjects\selenium-java-4.0.0-beta-3\selenium-devtools-v85-4.0.0-beta-3.jar;D:\IdeaProjects\selenium-java-4.0.0-beta-3\selenium-devtools-v88-4.0.0-beta-3.jar;D:\IdeaProjects\selenium-java-4.0.0-beta-3\selenium-devtools-v89-4.0.0-beta-3.jar;D:\IdeaProjects\selenium-java-4.0.0-beta-3\selenium-devtools-v90-4.0.0-beta-3.jar;D:\IdeaProjects\selenium-java-4.0.0-beta-3\selenium-devtools-v91-4.0.0-beta-3.jar;D:\IdeaProjects\selenium-java-4.0.0-beta-3\selenium-http-4.0.0-beta-3-sources.jar;D:\IdeaProjects\selenium-java-4.0.0-beta-3\selenium-java-4.0.0-beta-3-sources.jar;D:\IdeaProjects\selenium-java-4.0.0-beta-3\selenium-json-4.0.0-beta-3-sources.jar;D:\IdeaProjects\selenium-java-4.0.0-beta-3\selenium-opera-driver-4.0.0-beta-3.jar;D:\IdeaProjects\selenium-java-4.0.0-beta-3\selenium-chrome-driver-4.0.0-beta-3.jar;D:\IdeaProjects\selenium-java-4.0.0-beta-3\selenium-remote-driver-4.0.0-beta-3.jar;D:\IdeaProjects\selenium-java-4.0.0-beta-3\selenium-safari-driver-4.0.0-beta-3.jar;D:\IdeaProjects\selenium-java-4.0.0-beta-3\selenium-firefox-driver-4.0.0-beta-3.jar;D:\IdeaProjects\selenium-java-4.0.0-beta-3\selenium-chromium-driver-4.0.0-beta-3.jar;D:\IdeaProjects\selenium-java-4.0.0-beta-3\selenium-support-4.0.0-beta-3-sources.jar;D:\IdeaProjects\selenium-java-4.0.0-beta-3\selenium-devtools-4.0.0-beta-3-sources.jar;D:\IdeaProjects\selenium-java-4.0.0-beta-3\selenium-ie-driver-4.0.0-beta-3-sources.jar;D:\IdeaProjects\selenium-java-4.0.0-beta-3\selenium-firefox-xpi-driver-4.0.0-beta-3.jar;D:\IdeaProjects\selenium-java-4.0.0-beta-3\selenium-edge-driver-4.0.0-beta-3-sources.jar;D:\IdeaProjects\selenium-java-4.0.0-beta-3\selenium-devtools-v85-4.0.0-beta-3-sources.jar;D:\IdeaProjects\selenium-java-4.0.0-beta-3\selenium-devtools-v88-4.0.0-beta-3-sources.jar;D:\IdeaProjects\selenium-java-4.0.0-beta-3\selenium-devtools-v89-4.0.0-beta-3-sources.jar;D:\IdeaProjects\selenium-java-4.0.0-beta-3\selenium-devtools-v90-4.0.0-beta-3-sources.jar;D:\IdeaProjects\selenium-java-4.0.0-beta-3\selenium-devtools-v91-4.0.0-beta-3-sources.jar;D:\IdeaProjects\selenium-java-4.0.0-beta-3\selenium-opera-driver-4.0.0-beta-3-sources.jar;D:\IdeaProjects\selenium-java-4.0.0-beta-3\selenium-chrome-driver-4.0.0-beta-3-sources.jar;D:\IdeaProjects\selenium-java-4.0.0-beta-3\selenium-remote-driver-4.0.0-beta-3-sources.jar;D:\IdeaProjects\selenium-java-4.0.0-beta-3\selenium-safari-driver-4.0.0-beta-3-sources.jar;D:\IdeaProjects\selenium-java-4.0.0-beta-3\selenium-firefox-driver-4.0.0-beta-3-sources.jar;D:\IdeaProjects\selenium-java-4.0.0-beta-3\selenium-chromium-driver-4.0.0-beta-3-sources.jar;D:\IdeaProjects\selenium-java-4.0.0-beta-3\selenium-firefox-xpi-driver-4.0.0-beta-3-sources.jar com.selenium.Main
Exception in thread "main" java.lang.IllegalStateException: The path to the driver executable The path to the driver executable must be set by the webdriver.chrome.driver system property; for more information, see https://github.com/SeleniumHQ/selenium/wiki/ChromeDriver. The latest version can be downloaded from http://chromedriver.storage.googleapis.com/index.html
	at org.openqa.selenium.internal.Require$StateChecker.nonNull(Require.java:280)
	at org.openqa.selenium.remote.service.DriverService.findExecutable(DriverService.java:142)
	at org.openqa.selenium.chrome.ChromeDriverService.access$000(ChromeDriverService.java:37)
	at org.openqa.selenium.chrome.ChromeDriverService$Builder.findDefaultExecutable(ChromeDriverService.java:222)
	at org.openqa.selenium.remote.service.DriverService$Builder.build(DriverService.java:419)
	at org.openqa.selenium.chrome.ChromeDriverService.createDefaultService(ChromeDriverService.java:119)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:41)
	at com.selenium.Main.main(Main.java:15)

Process finished with exit code 1

Code:
package com.selenium;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

import java.util.concurrent.TimeUnit;

public class Main {

    public  static WebDriver driver = null;

    public static void main(String[] args) throws  InterruptedException{
        System.setProperty("webDriver.chrome.driver","D:\\IdeaProjects\\selenium-java-4.0.0-beta-3\\chromedriver.exe");
        driver = new ChromeDriver();
        driver.get("http://www.google.com");
        //WebDriver.ChromeDriver().setup();
        driver.manage().timeouts().implicitlyWait(15, TimeUnit.SECONDS);
        driver.navigate().to("https://www.amazon.in");
        driver.manage().window().maximize();
        String title = driver.getTitle();

        if (title.equalsIgnoreCase("Amazon.in"))
            System.out.println("Title Matched");
        else
            System.out.println(title);

    }
}

**Comment by gregma** [comment]
I can confirm.  WebDriverManager version 4.4.1:

`
                WebDriverManager.chromedriver().setup();
                WebDriverManager.chromedriver().clearDriverCache();
                WebDriverManager.chromedriver().clearResolutionCache();
                // Initialize the driver for use
                ChromeDriverService service = new ChromeDriverService.Builder().usingAnyFreePort().build();
                wDriver = new ChromeDriver(service, options);
`

`
java.lang.IllegalStateException: The path to the driver executable must be set by the webdriver.chrome.driver system property; for more information, see https://github.com/SeleniumHQ/selenium/wiki/ChromeDriver. The latest version can be downloaded from http://chromedriver.storage.googleapis.com/index.html

	at com.google.common.base.Preconditions.checkState(Preconditions.java:847)
	at org.openqa.selenium.remote.service.DriverService.findExecutable(DriverService.java:134)
	at org.openqa.selenium.chrome.ChromeDriverService.access$000(ChromeDriverService.java:35)
	at org.openqa.selenium.chrome.ChromeDriverService$Builder.findDefaultExecutable(ChromeDriverService.java:159)
	at org.openqa.selenium.remote.service.DriverService$Builder.build(DriverService.java:355)
	at framework.DriverFactory.getDriver(DriverFactory.java:323)
	at tests.BaseTest.launchDriver(BaseTest.java:1282)
	at tests.BaseTest.beforeSuite(BaseTest.java:942)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
`

**Comment by edumco** [comment]
@biswajeetsethi Thank you for reporting the problem!

I see you're using Java 16. We still don't use 16 in the pipeline and I recommend you try with Java 11 to check if you find the same problem.

I could not find the version 90.0.4430.85 in the chrome repository https://chromedriver.storage.googleapis.com/index.html

What version of web driver manager are you using?

What maven/gradle version?

**Comment by bonigarcia** [comment]
@biswajeetsethi You are not using WebDriverManager in your code:

`
WebDriverManager.chromedriver().setup();
`
