### ISSUE TITLE
Issue while running in Chrome

### ISSUE THREAD

**Issue by Yogesh-CSE** [bonigarcia/webdrivermanager#643]
**Description of the problem**:  The following issue is seen in my Windows 7 machine 
2021-05-05 05:22:13,331 - FATAL : main(ADMIN) - io.github.bonigarcia.wdm.config.WebDriverManagerException: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 258; The reference to entity "display" must end with the ';' delimiter.

**Browser and version**: Chrome 90.0.4430.85 (64 bit)
**Operating system**: Windows 7 and 64 bit

**WebDriverManager version**: 4.3.1

**WebDriverManager use**: protected void createWebDriver() {
		//Automatic Web driver installation done 
		logWriter.info("Initializing the Web driver automatically for chrome browser");
		WebDriverManager.chromedriver().setup();		
		driver = new ChromeDriver();
		logWriter.info("Chrome driver initialized");
		try {
			driver.manage().timeouts().implicitlyWait(60, TimeUnit.SECONDS);
			driver.manage().deleteAllCookies();
			driver.manage().window().maximize();
		} catch (WebDriverException e) {
			LogWriter.getInstance().writeToLog(LogStatus.ERROR,"Exception in driver intialization");
			logWriter.info("Exception : "+e);
			throw e;
		}
		
	}

**WebDriverManager traces**: io.github.bonigarcia.wdm.config.WebDriverManagerException: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 258; The reference to entity "display" must end with the ';' delimiter.
io.github.bonigarcia.wdm.config.WebDriverManagerException: io.github.bonigarcia.wdm.config.WebDriverManagerException: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 258; The reference to entity "display" must end with the ';' delimiter.
at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:777)
at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:574)
at io.github.bonigarcia.wdm.WebDriverManager.fallback(WebDriverManager.java:793)
at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:774)
at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:574)
at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:767)
at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:574)
at io.github.bonigarcia.wdm.WebDriverManager.setup(WebDriverManager.java:288)

**Error trace**:

**Comment by Yogesh-CSE** [comment]
Any Update on this i am unable to find anything ?

**Comment by edumco** [comment]
@Yogesh-CSE Thank you for reporting a problem

I need more information to reproduce this: 
- Java version
- Java distribution (oracle, openjdk)
- Maven or gradle version
- Windows 7 is updated?

**Comment by Yogesh-CSE** [comment]
Java Version: java 1.8.0.191
Java distribution: OpenJDK 8
Maven Version: we are using Maven artifact : maven-jar-plugin Version: 2.3.1
Windows 7 Professional 6.1 Build 7601: service pack1

**Comment by Yogesh-CSE** [comment]
@edumco Please let me know if more information is needed

**Comment by edumco** [comment]
> @edumco Please let me know if more information is needed

- The `mvn --version` text

- The results running some previous or more recent version of web driver manager

**Comment by bonigarcia** [comment]
@Yogesh-CSE Use the latest version of WebDriverManager. If the problem persists, please open a new issue and include the WebDriverManager traces (see issue template for more information about that).
