### ISSUE TITLE
Failed to create Chrome process

### ISSUE THREAD

**Issue by VictorSem** [bonigarcia/webdrivermanager#650]
Hi. Some strange situation with webdrivermanager.
If I run the tests locally, there are no errors, and everything works. If I run Jenkins job, then this is the error (before that, everything was OK on Jenkins)

Google Chrome 90.0.4430.212
webdrivermanager 4.4.3

```
 WebDriverManager.chromedriver().driverVersion("90.0.4430.24").setup();
 WebDriver driver = new ChromeDriver ();
```

 But I get an error

```
Starting ChromeDriver 90.0.4430.24 (4c6d850f087da467d926e8eddb76550aed655991-refs/branch-heads/4430@{#429}) on port 18444
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
org.openqa.selenium.WebDriverException: unknown error: Failed to create Chrome process.
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'WIN10-XXXX-TEST', ip: 'XXXXXXXXXXXXXXXXXXXXXXXX', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_221'
Driver info: driver.version: ChromeDriver
remote stacktrace: Backtrace:
	Ordinal0 [0x011EC013+2474003]
	Ordinal0 [0x011829C1+2042305]
	Ordinal0 [0x01092F68+1060712]
	Ordinal0 [0x010AD9C8+1169864]
	Ordinal0 [0x010AAA83+1157763]
	Ordinal0 [0x010DA2A2+1352354]
	Ordinal0 [0x010D8FAA+1347498]
	Ordinal0 [0x010D66DB+1337051]
	Ordinal0 [0x010B3427+1192999]
	Ordinal0 [0x010B42EE+1196782]
	Ordinal0 [0x010B4279+1196665]
	GetHandleVerifier [0x013796FC+1590332]
	GetHandleVerifier [0x01428614+2306900]
	GetHandleVerifier [0x01279E93+543699]
	GetHandleVerifier [0x012792CE+540686]
	Ordinal0 [0x011886BA+2066106]
	Ordinal0 [0x0118D1C8+2085320]
	Ordinal0 [0x0118D308+2085640]
	Ordinal0 [0x011967F3+2123763]
	BaseThreadInitThunk [0x770BFA29+25]
	RtlGetAppContainerNamedObjectPath [0x77487A7E+286]
	RtlGetAppContainerNamedObjectPath [0x77487A4E+238]

	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$errorHandler$0(W3CHandshakeResponse.java:62)
	at org.openqa.selenium.remote.HandshakeResponse.lambda$getResponseFunction$0(HandshakeResponse.java:30)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:126)
```

**Comment by bonigarcia** [comment]
This problem is definitively not caused by WebDriverManager. As you can see in the trace `Starting ChromeDriver 90.0.4430.24 ...`, chromdriver is starting correctly, and so, WebDriverManager has resolved that driver correctly. For problem should be other,

**Comment by VictorSem** [comment]
I do not know what the error was, but it is working correctly now
