### ISSUE TITLE
Unable to download binary exe on client server

### ISSUE THREAD

**Issue by tarunbansak** [bonigarcia/webdrivermanager#655]
**Description of the problem**: I am using maven project and added WebDriver Manager dependency in POM file. But i am not able to download binary exe file during runtime. I am running this code on client server wherein firewall is there which is restricting it to download binary files. Can you please share the url with me using which it downloads exe files so that i can get that url whitelisted on server.

**Browser and version**: Chrome & 91.0.4472.77

**Operating system**: Windows 10

**WebDriverManager version**: 4.4.3

**WebDriverManager use**:
 WebDriverManager.chromedriver().setup();
driver = new ChromeDriver();
driver.manage().window().maximize();

**WebDriverManager traces**: 

**Error trace**: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" io.github.bonigarcia.wdm.config.WebDriverManagerException: io.github.bonigarcia.wdm.config.WebDriverManagerException: org.apache.hc.client5.http.HttpHostConnectException: Connect to https://chromedriver.storage.googleapis.com:443 [chromedriver.storage.googleapis.com/142.250.185.176] failed: Connection timed out: connect
	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:809)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:599)
	at io.github.bonigarcia.wdm.WebDriverManager.fallback(WebDriverManager.java:825)
	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:806)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:599)
	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:799)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:599)
	at io.github.bonigarcia.wdm.WebDriverManager.setup(WebDriverManager.java:287)
	at WebDriverManager.WebDriverManager.App.initializeDriver(App.java:26)
	at WebDriverManager.WebDriverManager.App.main(App.java:34)
Caused by: io.github.bonigarcia.wdm.config.WebDriverManagerException: org.apache.hc.client5.http.HttpHostConnectException: Connect to https://chromedriver.storage.googleapis.com:443 [chromedriver.storage.googleapis.com/142.250.185.176] failed: Connection timed out: connect
	at io.github.bonigarcia.wdm.WebDriverManager.getDriversFromXml(WebDriverManager.java:956)
	at io.github.bonigarcia.wdm.managers.ChromeDriverManager.getDriverUrls(ChromeDriverManager.java:100)
	at io.github.bonigarcia.wdm.WebDriverManager.createUrlHandler(WebDriverManager.java:830)
	at io.github.bonigarcia.wdm.WebDriverManager.download(WebDriverManager.java:677)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:593)
	... 8 more
Caused by: org.apache.hc.client5.http.HttpHostConnectException: Connect to https://chromedriver.storage.googleapis.com:443 [chromedriver.storage.googleapis.com/142.250.185.176] failed: Connection timed out: connect
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:81)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:476)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:218)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:200)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:162)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:394)
	at java.net.Socket.connect(Socket.java:606)
	at org.apache.hc.client5.http.ssl.SSLConnectionSocketFactory$1.run(SSLConnectionSocketFactory.java:219)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.apache.hc.client5.http.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:216)
	at org.apache.hc.client5.http.impl.io.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:148)
	at org.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:409)
	at org.apache.hc.client5.http.impl.classic.InternalExecRuntime.connectEndpoint(InternalExecRuntime.java:164)
	at org.apache.hc.client5.http.impl.classic.InternalExecRuntime.connectEndpoint(InternalExecRuntime.java:174)
	at org.apache.hc.client5.http.impl.classic.ConnectExec.execute(ConnectExec.java:135)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
	at org.apache.hc.client5.http.impl.classic.ProtocolExec.execute(ProtocolExec.java:172)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
	at org.apache.hc.client5.http.impl.classic.HttpRequestRetryExec.execute(HttpRequestRetryExec.java:93)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
	at org.apache.hc.client5.http.impl.classic.ContentCompressionExec.execute(ContentCompressionExec.java:128)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
	at org.apache.hc.client5.http.impl.classic.RedirectExec.execute(RedirectExec.java:116)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.InternalHttpClient.doExecute(InternalHttpClient.java:178)
	at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:75)
	at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:89)
	at io.github.bonigarcia.wdm.online.HttpClient.execute(HttpClient.java:139)
	at io.github.bonigarcia.wdm.WebDriverManager.getDriversFromXml(WebDriverManager.java:941)
	... 12 more

**Comment by bonigarcia** [comment]
You can see all the online repositories used by WebDriverManager in the [documentation](https://github.com/bonigarcia/webdrivermanager#configuration), for instance:

```
wdm.chromeDriverUrl=https://chromedriver.storage.googleapis.com/
wdm.geckoDriverUrl=https://api.github.com/repos/mozilla/geckodriver/releases
wdm.operaDriverUrl=https://api.github.com/repos/operasoftware/operachromiumdriver/releases
wdm.edgeDriverUrl=https://msedgedriver.azureedge.net/
wdm.internetExplorerDriverUrl=https://selenium-release.storage.googleapis.com/
wdm.phantomjsDriverUrl=https://bitbucket.org/api/2.0/repositories/ariya/phantomjs/downloads
```
