### ISSUE TITLE
chromedriver 91.0.4472.101 for MAC64 not found in http://npm.taobao.org/mirrors/chromedriver

### ISSUE THREAD

**Issue by asifraaja** [bonigarcia/webdrivermanager#661]
chromedriver 91.0.4472.101 for MAC64 not found in http://npm.taobao.org/mirrors/chromedriver. 
And hence unable to run tests with chrome version 91
 

chrome version = 91

macOs catalina 10.15.7

webdriverManager version = 4.4.3

io.github.bonigarcia.wdm.WebDriverManagerException: chromedriver 91.0.4472.101 for MAC64 not found in http://npm.taobao.org/mirrors/chromedriver
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:514)
	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:686)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:521)
	at io.github.bonigarcia.wdm.WebDriverManager.setup(WebDriverManager.java:251)

Please add the version of chrome driver.

**Comment by bonigarcia** [comment]
It sometimes happen that the Taobao mirror is not perfectly synchronized. Now that version is available, and your problem should be fixed.

**Comment by asifraaja** [comment]
Yes, it's fixed now. Thank you
