### ISSUE TITLE
WebDriverManager downloads chromedriver 93 instead of 92

### ISSUE THREAD

**Issue by danieldruga** [bonigarcia/webdrivermanager#681]
**Description of the problem**: WebDriverManager downloads chromedriver 93 instead of 92

**Browser and version**: Chrome 92

**Operating system**: Windows 10 64 bits

**WebDriverManager version**: 4.4.3

**WebDriverManager traces**: 
11:19:48.477 DEBUG [ForkJoinPool-1-worker-3] - [io.github.bonigarcia.wdm.cache.ResolutionCache] - Removing resolution chrome=91 from cache (expired on Tue Jul 27 13:58:23 EEST 2021)
11:19:48.487 DEBUG [ForkJoinPool-1-worker-3] - [io.github.bonigarcia.wdm.versions.VersionDetector] - Detecting chrome version using local commands.properties
11:19:48.488 DEBUG [ForkJoinPool-1-worker-3] - [io.github.bonigarcia.wdm.versions.Shell] - Running command on the shell: [cmd.exe, /C, wmic, datafile, where, name="%PROGRAMFILES(X86):\=\\%\\Google\\Chrome\\Application\\chrome.exe", get, Version, /value]
11:19:48.579 DEBUG [ForkJoinPool-1-worker-3] - [io.github.bonigarcia.wdm.versions.Shell] - Result: Version=92.0.4515.107
11:19:49.086 ERROR [ForkJoinPool-1-worker-3] - [io.github.bonigarcia.wdm.online.HttpClient] - Error HTTP 404 executing https://chromedriver.storage.googleapis.com/LATEST_RELEASE_Version=92
11:19:49.087 WARN  [ForkJoinPool-1-worker-3] - [io.github.bonigarcia.wdm.versions.VersionDetector] - Exception reading https://chromedriver.storage.googleapis.com/LATEST_RELEASE_Version=92 to get latest version of chromedriver (Error HTTP 404 executing https://chromedriver.storage.googleapis.com/LATEST_RELEASE_Version=92)
11:19:49.088 DEBUG [ForkJoinPool-1-worker-3] - [io.github.bonigarcia.wdm.versions.VersionDetector] - Getting driver version for chromeVersion=92 from online versions.properties
11:19:49.212 DEBUG [ForkJoinPool-1-worker-3] - [io.github.bonigarcia.wdm.versions.VersionDetector] - Driver for chromeVersion=92 not found in online properties (using local versions.properties)
11:19:49.213 DEBUG [ForkJoinPool-1-worker-3] - [io.github.bonigarcia.wdm.WebDriverManager] - The driver version for CHROME Version=92 is unknown ... trying with latest
11:19:49.302 DEBUG [ForkJoinPool-1-worker-3] - [io.github.bonigarcia.wdm.versions.VersionDetector] - Latest version of chromedriver according to https://chromedriver.storage.googleapis.com/LATEST_RELEASE is 93.0.4577.15
11:19:49.311 DEBUG [ForkJoinPool-1-worker-3] - [io.github.bonigarcia.wdm.WebDriverManager] - Driver chromedriver 93.0.4577.15 found in cache
11:19:49.312 INFO  [ForkJoinPool-1-worker-3] - [io.github.bonigarcia.wdm.WebDriverManager] - Exporting webdriver.chrome.driver as C:\Users\ep041667\.cache\selenium\chromedriver\win32\93.0.4577.15\chromedriver.exe

**Error trace**: 
org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: session not created: This version of ChromeDriver only supports Chrome version 93
Current browser version is 92.0.4515.107 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe
Build info: version: '4.0.0-beta-4', revision: '29f46d02dd'
System info: host: ******, ip: ******, os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.11'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [null, newSession {capabilities=[Capabilities {acceptInsecureCerts: true, browserName: chrome, goog:chromeOptions: {args: [start-maximized], excludeSwitches: [enable-automation], extensions: [], prefs: {credentials_enable_service: false, profile.password_manager_enabled: false}, useAutomationExtension: false}, unhandledPromptBehavior: accept}], desiredCapabilities=Capabilities {acceptInsecureCerts: true, browserName: chrome, goog:chromeOptions: {args: [start-maximized], excludeSwitches: [enable-automation], extensions: [], prefs: {credentials_enable_service: false, profile.password_manager_enabled: false}, useAutomationExtension: false}, unexpectedAlertBehaviour: accept, unhandledPromptBehavior: accept}}]
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:126)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:84)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:62)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:156)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:162)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:137)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:612)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:244)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:165)
	at org.openqa.selenium.chromium.ChromiumDriver.<init>(ChromiumDriver.java:89)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:99)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:86)
	at com.ddruga.test.selenium.config.CustomChromeDriver.createWebDriver(CustomChromeDriver.java:31)
	at com.ddruga.test.selenium.config.CustomChromeDriver.getInstance(CustomChromeDriver.java:25)
	at com.ddruga.test.selenium.context.ScenarioContext.getNewDriverInstance(ScenarioContext.java:53)
	at com.ddruga.test.selenium.context.ScenarioContext$$FastClassBySpringCGLIB$$fe1f49e8.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:779)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.aop.support.DelegatingIntroductionInterceptor.doProceed(DelegatingIntroductionInterceptor.java:137)
	at org.springframework.aop.support.DelegatingIntroductionInterceptor.invoke(DelegatingIntroductionInterceptor.java:124)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:692)
	at com.ddruga.test.selenium.context.ScenarioContext$$EnhancerBySpringCGLIB$$c380179f.getNewDriverInstance(<generated>)
	at com.ddruga.test.selenium.runner.CucumberHooks.beforeScenario(CucumberHooks.java:32)

**Comment by bonigarcia** [comment]
How are you calling to WebDriverManager (e.g. `WebDriverManager.chromedriver().setup();`)?

**Comment by swarvette** [comment]
Hi, I'm also getting the same issue.  This is how I'm calling to WebDriverManager:

new WebDriverManager.DriverManager().SetUpDriver(new ChromeConfig());
                    var chromeOptions = new ChromeOptions();
                    if (headless)
                    {
                        chromeOptions.AddArguments("window-size=1920,1080", "headless");
                    }
                    return new ChromeDriver(chromeOptions);

**Comment by bonigarcia** [comment]
@swarvette This line: `new WebDriverManager.DriverManager().SetUpDriver(new ChromeConfig());` is not standard in WebDriverManager. I don't know anything about that.

**Comment by danieldruga** [comment]
I call it how you describe it:
`WebDriverManager.getInstance(type).setup();`

**Comment by bonigarcia** [comment]
@danieldruga I am not able to reproduce this issue, it is working fine in my local tests using that call and WDM version. Please do it the following to try to find the issue:

1. Change the log level of WDM to `TRACE`
2. Clear resolution cache in the WDM call: `WebDriverManager.getInstance(type).clearResolutionCache().setup();`
3. Post the resulting traces here for further analysis

**Comment by danieldruga** [comment]
15:02:11.375 DEBUG [ForkJoinPool-1-worker-3] - [io.github.bonigarcia.wdm.cache.ResolutionCache] - Removing resolution chrome=92 from cache (expired on Tue Jul 27 14:13:44 EEST 2021)
15:02:11.384 TRACE [ForkJoinPool-1-worker-3] - [io.github.bonigarcia.wdm.versions.VersionDetector] - Reading local commands.properties to find out driver version
15:02:11.390 DEBUG [ForkJoinPool-1-worker-3] - [io.github.bonigarcia.wdm.versions.VersionDetector] - Detecting chrome version using local commands.properties
15:02:11.392 DEBUG [ForkJoinPool-1-worker-3] - [io.github.bonigarcia.wdm.versions.Shell] - Running command on the shell: [cmd.exe, /C, wmic, datafile, where, name="%PROGRAMFILES(X86):\=\\%\\Google\\Chrome\\Application\\chrome.exe", get, Version, /value]
15:02:11.511 DEBUG [ForkJoinPool-1-worker-3] - [io.github.bonigarcia.wdm.versions.Shell] - Result: 
15:02:11.511 DEBUG [ForkJoinPool-1-worker-3] - [io.github.bonigarcia.wdm.versions.Shell] - Running command on the shell: [cmd.exe, /C, wmic, datafile, where, name="%LOCALAPPDATA:\=\\%\\Google\\Chrome\\Application\\chrome.exe", get, Version, /value]
15:02:11.625 DEBUG [ForkJoinPool-1-worker-3] - [io.github.bonigarcia.wdm.versions.Shell] - Result: 
15:02:11.626 DEBUG [ForkJoinPool-1-worker-3] - [io.github.bonigarcia.wdm.versions.Shell] - Running command on the shell: [cmd.exe, /C, wmic, datafile, where, name="%PROGRAMFILES:\=\\%\\Google\\Chrome\\Application\\chrome.exe", get, Version, /value]
15:02:11.757 DEBUG [ForkJoinPool-1-worker-3] - [io.github.bonigarcia.wdm.versions.Shell] - Result: Version=92.0.4515.107
15:02:11.758 TRACE [ForkJoinPool-1-worker-3] - [io.github.bonigarcia.wdm.versions.VersionDetector] - Detected browser version is Version=92.0.4515.107
15:02:12.120 ERROR [ForkJoinPool-1-worker-3] - [io.github.bonigarcia.wdm.online.HttpClient] - Error HTTP 404 executing https://chromedriver.storage.googleapis.com/LATEST_RELEASE_Version=92
15:02:12.120 WARN  [ForkJoinPool-1-worker-3] - [io.github.bonigarcia.wdm.versions.VersionDetector] - Exception reading https://chromedriver.storage.googleapis.com/LATEST_RELEASE_Version=92 to get latest version of chromedriver (Error HTTP 404 executing https://chromedriver.storage.googleapis.com/LATEST_RELEASE_Version=92)
15:02:12.122 DEBUG [ForkJoinPool-1-worker-3] - [io.github.bonigarcia.wdm.versions.VersionDetector] - Getting driver version for chromeVersion=92 from online versions.properties
15:02:12.122 TRACE [ForkJoinPool-1-worker-3] - [io.github.bonigarcia.wdm.versions.VersionDetector] - Reading online versions.properties to find out driver version
15:02:12.257 DEBUG [ForkJoinPool-1-worker-3] - [io.github.bonigarcia.wdm.versions.VersionDetector] - Driver for chromeVersion=92 not found in online properties (using local versions.properties)
15:02:12.257 TRACE [ForkJoinPool-1-worker-3] - [io.github.bonigarcia.wdm.versions.VersionDetector] - Reading local versions.properties to find out driver version
15:02:12.258 DEBUG [ForkJoinPool-1-worker-3] - [io.github.bonigarcia.wdm.WebDriverManager] - The driver version for CHROME Version=92 is unknown ... trying with latest
15:02:12.361 DEBUG [ForkJoinPool-1-worker-3] - [io.github.bonigarcia.wdm.versions.VersionDetector] - Latest version of chromedriver according to https://chromedriver.storage.googleapis.com/LATEST_RELEASE is 93.0.4577.15
15:02:12.362 TRACE [ForkJoinPool-1-worker-3] - [io.github.bonigarcia.wdm.cache.CacheHandler] - Checking if chromedriver exists in cache
15:02:12.376 TRACE [ForkJoinPool-1-worker-3] - [io.github.bonigarcia.wdm.cache.CacheHandler] - Filter cache by chromedriver -- input list [C:\Users\DD060918\.cache\selenium\chromedriver\win32\88.0.4324.96\chromedriver.exe, C:\Users\DD060918\.cache\selenium\chromedriver\win32\89.0.4389.23\chromedriver.exe, C:\Users\DD060918\.cache\selenium\chromedriver\win32\90.0.4430.24\chromedriver.exe, C:\Users\DD060918\.cache\selenium\chromedriver\win32\91.0.4472.101\chromedriver.exe, C:\Users\DD060918\.cache\selenium\chromedriver\win32\91.0.4472.19\chromedriver.exe, C:\Users\DD060918\.cache\selenium\chromedriver\win32\92.0.4515.43\chromedriver.exe, C:\Users\DD060918\.cache\selenium\chromedriver\win32\93.0.4577.15\chromedriver.exe, C:\Users\DD060918\.cache\selenium\msedgedriver\win64\88.0.705.41\msedgedriver.exe, C:\Users\DD060918\.cache\selenium\msedgedriver\win64\88.0.705.63\msedgedriver.exe, C:\Users\DD060918\.cache\selenium\resolution.properties] -- output list [C:\Users\DD060918\.cache\selenium\chromedriver\win32\88.0.4324.96\chromedriver.exe, C:\Users\DD060918\.cache\selenium\chromedriver\win32\89.0.4389.23\chromedriver.exe, C:\Users\DD060918\.cache\selenium\chromedriver\win32\90.0.4430.24\chromedriver.exe, C:\Users\DD060918\.cache\selenium\chromedriver\win32\91.0.4472.101\chromedriver.exe, C:\Users\DD060918\.cache\selenium\chromedriver\win32\91.0.4472.19\chromedriver.exe, C:\Users\DD060918\.cache\selenium\chromedriver\win32\92.0.4515.43\chromedriver.exe, C:\Users\DD060918\.cache\selenium\chromedriver\win32\93.0.4577.15\chromedriver.exe] 
15:02:12.376 TRACE [ForkJoinPool-1-worker-3] - [io.github.bonigarcia.wdm.cache.CacheHandler] - Filter cache by 93.0.4577.15 -- input list [C:\Users\DD060918\.cache\selenium\chromedriver\win32\88.0.4324.96\chromedriver.exe, C:\Users\DD060918\.cache\selenium\chromedriver\win32\89.0.4389.23\chromedriver.exe, C:\Users\DD060918\.cache\selenium\chromedriver\win32\90.0.4430.24\chromedriver.exe, C:\Users\DD060918\.cache\selenium\chromedriver\win32\91.0.4472.101\chromedriver.exe, C:\Users\DD060918\.cache\selenium\chromedriver\win32\91.0.4472.19\chromedriver.exe, C:\Users\DD060918\.cache\selenium\chromedriver\win32\92.0.4515.43\chromedriver.exe, C:\Users\DD060918\.cache\selenium\chromedriver\win32\93.0.4577.15\chromedriver.exe] -- output list [C:\Users\DD060918\.cache\selenium\chromedriver\win32\93.0.4577.15\chromedriver.exe] 
15:02:12.376 TRACE [ForkJoinPool-1-worker-3] - [io.github.bonigarcia.wdm.cache.CacheHandler] - Filter cache by WIN -- input list [C:\Users\DD060918\.cache\selenium\chromedriver\win32\93.0.4577.15\chromedriver.exe] -- output list [C:\Users\DD060918\.cache\selenium\chromedriver\win32\93.0.4577.15\chromedriver.exe] 
15:02:12.377 DEBUG [ForkJoinPool-1-worker-3] - [io.github.bonigarcia.wdm.WebDriverManager] - Driver chromedriver 93.0.4577.15 found in cache
15:02:12.377 INFO  [ForkJoinPool-1-worker-3] - [io.github.bonigarcia.wdm.WebDriverManager] - Exporting webdriver.chrome.driver as C:\Users\DD060918\.cache\selenium\chromedriver\win32\93.0.4577.15\chromedriver.exe

**Comment by bonigarcia** [comment]
The problem seem to be in the code that extracts the version from the shell output, which is correct. Are you overriding the WebDriverManager properties? This property should be present:

```
wdm.browserVersionDetectionRegex=[^\\d^\\.]
```

The equivalent code is the following:

```
 String detectedVersion = "Version=92.0.4515.107";
String parserVersion = detectedVersion.replaceAll("[^\\d^\\.]", "");
System.out.println(parserVersion);
```

If you run the snippet before in your machine, you should see `92.0.4515.107` in the standard output. If so, the problem is that the above-mentioned configuration key is missing at your end.

**Comment by danieldruga** [comment]
Indeed it was from this wdm.browserVersionDetectionRegex property. I added a breakpoint and observed that the properties from the webdrivermanager.properties file had null values. I added 
`config.setBrowserVersionDetectionRegex("[^\\d^\\.]")` 
before the call to the WebDriverManager and it worked fine.
But then I deleted this new line to see what happends and it still works correctly, the issue seems to be fixed for me.

**Comment by mrahman2327** [comment]
Hello, I am facing the same when using the npm package version - 12.1.8. I have scripts setup that uses the command `webdriver-manager update && webdriver-manager start`. Yesterday it was fine, but since today it is now using chrome version 93. Below is what I see when using this command. Notice the Chromedriver version as 93. 
```webdriver-manager update && webdriver-manager start
webdriver-manager: using local installed version 12.1.8
[09:20:22] I/update - selenium standalone: file exists /Users/mushfiq.rahman/Showpad/frontend/node_modules/webdriver-manager/selenium/selenium-server-standalone-3.141.59.jar
[09:20:22] I/update - selenium standalone: selenium-server-standalone-3.141.59.jar up to date
[09:20:22] E/downloader - getaddrinfo ENOTFOUND github-releases.githubusercontent.com
[09:20:22] I/update - geckodriver: file exists /Users/mushfiq.rahman/Showpad/frontend/node_modules/webdriver-manager/selenium/geckodriver-v0.29.1.tar.gz
[09:20:22] I/update - geckodriver: unzipping geckodriver-v0.29.1.tar.gz
[09:20:22] I/update - geckodriver: setting permissions to 0755 for /Users/mushfiq.rahman/Showpad/frontend/node_modules/webdriver-manager/selenium/geckodriver-v0.29.1
[09:20:22] I/update - geckodriver: geckodriver-v0.29.1 up to date
[09:20:22] I/update - chromedriver: file exists /Users/mushfiq.rahman/Showpad/frontend/node_modules/webdriver-manager/selenium/chromedriver_93.0.4577.15.zip
[09:20:22] I/update - chromedriver: unzipping chromedriver_93.0.4577.15.zip
[09:20:22] I/update - chromedriver: setting permissions to 0755 for /Users/mushfiq.rahman/Showpad/frontend/node_modules/webdriver-manager/selenium/chromedriver_93.0.4577.15
[09:20:22] I/update - chromedriver: chromedriver_93.0.4577.15 up to date
webdriver-manager: using local installed version 12.1.8
[09:20:24] I/start - java -Dwebdriver.gecko.driver=/Users/mushfiq.rahman/Showpad/frontend/node_modules/webdriver-manager/selenium/geckodriver-v0.29.1 -Dwebdriver.chrome.driver=/Users/mushfiq.rahman/Showpad/frontend/node_modules/webdriver-manager/selenium/chromedriver_93.0.4577.15 -jar /Users/mushfiq.rahman/Showpad/frontend/node_modules/webdriver-manager/selenium/selenium-server-standalone-3.141.59.jar -port 4444
```

**Comment by arunahk** [comment]
I'm facing the same issue since this morning.
` session not created: This version of ChromeDriver only supports Chrome version 93
    Current browser version is 92.0.4515.107 with binary path C:\Program Files (x86)\Google\Chrome\Application\chrome.exe`

**Comment by arunahk** [comment]
[https://chromedriver.storage.googleapis.com/LATEST_RELEASE](https://chromedriver.storage.googleapis.com/LATEST_RELEASE) is returning version 93. I think this is causing the problem.

**Comment by danieldruga** [comment]
This problem reappeared to me. Yesterday after I deleted the `config.setBrowserVersionDetectionRegex("[^\\d^\\.]")` line, it worked, but now it's back to not working. I am not changing that property durring the tests and in the bellow image you can see that it has a null value. Also, it seems that all properties from webdrivermanager.properties come with null values.

![image](https://user-images.githubusercontent.com/30805787/127599161-f2a3311f-425c-47c7-9b3d-8001d4f31f14.png)

For me, it all worked fine the last days, until yesterday when I created the issue. I ran the tests multiple times yesterday morning without this issue occurring.

**Comment by mrahman2327** [comment]
@arunahk Good catch!! https://chromedriver.storage.googleapis.com/LATEST_RELEASE is now returning the right version. The command `webdriver-manager update && webdriver-manager start` is now working as expected for me. Version 92 is being used.

**Comment by keerthivenigalla** [comment]
It is still downloading 93 version chromedriver for me.
Here is the stack trace from my test run

2021-07-30 11:34:39 INFO  logger:67 - Creating New Driver
2021-07-30 11:34:39 INFO  logger:160 - Browser is set to CHROME
2021-07-30 11:34:42 INFO  WebDriverManager:575 - Using chromedriver 93.0.4577.15 (since Google Chrome 92 is installed in your machine)
2021-07-30 11:34:42 INFO  WebDriverManager:1052 - Exporting webdriver.chrome.driver as server\wdmDownloads\chromedriver\win32\93.0.4577.15\chromedriver.exe
Starting ChromeDriver 93.0.4577.15 (660fc11082ba57405eca2e8c49c3e1af756fbfae-refs/branch-heads/4577@{#203}) on port 31857
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
[1627670084.162][WARNING]: Deprecated chrome option is ignored: useAutomationExtension
[1627670084.162][WARNING]: Deprecated chrome option is ignored: useAutomationExtension
2021-07-30 11:34:45 ERROR logger:104 - Exception = sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)

org.xxx.automation.automationcoreframework.exceptions.DriverSetupException: Driver Creation Error: session not created: This version of ChromeDriver only supports Chrome version 93
Current browser version is 92.0.4515.107 with binary path C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'CAL7004108', ip: '10.101.152.146', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_291'
Driver info: driver.version: ChromeDriver
remote stacktrace: Backtrace:
	Ordinal0 [0x0123A2D3+2663123]
	Ordinal0 [0x011CA491+2204817]
	Ordinal0 [0x010B2118+1057048]
	Ordinal0 [0x010D041A+1180698]
	Ordinal0 [0x010CC335+1164085]
	Ordinal0 [0x010C9B7F+1153919]
	Ordinal0 [0x010F9D8F+1351055]
	Ordinal0 [0x010F99FA+1350138]
	Ordinal0 [0x010F589B+1333403]
	Ordinal0 [0x010D1F74+1187700]
	Ordinal0 [0x010D2DC9+1191369]
	GetHandleVerifier [0x013D30D6+1610054]
	GetHandleVerifier [0x0147B53B+2299307]
	GetHandleVerifier [0x012C8DA9+519705]
	GetHandleVerifier [0x012C7759+513993]
	Ordinal0 [0x011D112D+2232621]
	Ordinal0 [0x011D55F8+2250232]
	Ordinal0 [0x011D5732+2250546]
	Ordinal0 [0x011DE591+2286993]
	BaseThreadInitThunk [0x75690419+25]
	RtlGetAppContainerNamedObjectPath [0x770472AD+237]
	RtlGetAppContainerNamedObjectPath [0x7704727D+189]

**Comment by sardaralii** [comment]
09:27:04.288 [main] ERROR io.github.bonigarcia.wdm.online.HttpClient - Error HTTP 404 executing https://chromedriver.storage.googleapis.com/LATEST_RELEASE_115
Starting ChromeDriver 114.0.5735.90 (386bc09e8f4f2e025eddae123f36f6263096ae49-refs/branch-heads/5735@{#1052}) on port 38481
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
[1691400426.012][WARNING]: This version of ChromeDriver has not been tested with Chrome version 115.
Aug 07, 2023 9:27:06 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected upstream dialect: W3C
Aug 07, 2023 9:27:06 AM org.openqa.selenium.remote.http.WebSocket$Listener onError
WARNING: Invalid Status code=403 text=Forbidden
java.io.IOException: Invalid Status code=403 text=Forbidden
	at org.asynchttpclient.netty.handler.WebSocketHandler.abort(WebSocketHandler.java:92)
	at org.asynchttpclient.netty.handler.WebSocketHandler.handleRead(WebSocketHandler.java:118)
	at org.asynchttpclient.netty.handler.AsyncHttpClientHandler.channelRead(AsyncHttpClientHandler.java:78)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:314)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:435)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)

please Guide me to solve this issue
