### ISSUE TITLE
WebDrivermanager - gets webdriver exception saying "unknown error: cannot find Chrome binary"

### ISSUE THREAD

**Issue by BBLearnerPASM** [bonigarcia/webdrivermanager#705]
Simple testng test , tried to use the Webdrivermanager to open up the chrome browser received the error **"org.openqa.selenium.WebDriverException: unknown error: cannot find Chrome binary"**

public class seleniumtest {

    @Test
    public void openGoogleTest() {

        WebDriverManager.chromedriver().setup();
        WebDriver d = new ChromeDriver();

        d.get("http://google.com");
        d.findElement(By.name("q")).sendKeys("Spring Boot");
        d.findElement(By.name("q")).sendKeys(Keys.TAB);
        d.close();

    }
}

Lab Version details as follows
Windows 10
java.version: '11.0.8'
Chrome Browser "93.0.4577.82"
selenium.version "3.141.59"
webdrivermanager.version "4.4.2" 

Also tried with the below lines but no luck

   1 ) WebDriverManager.chromedriver().browserVersion("93.0.4577.63").setup();
   2 ) WebDriverManager.chromedriver().browserVersion("93.0.4577.15").setup();
   3 ) WebDriverManager.chromedriver().driverVersion("93.0.4577.63").setup();
   4 ) WebDriverManager.chromedriver().driverVersion("93.0.4577.15").setup();
   
   
   Error log 
   
   org.openqa.selenium.WebDriverException: unknown error: cannot find Chrome binary
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-VNCBN0B', ip: '192.168.56.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.8'
Driver info: driver.version: ChromeDriver
remote stacktrace: Backtrace:
	Ordinal0 [0x00C3A2D3+2663123]
	Ordinal0 [0x00BCA491+2204817]
	Ordinal0 [0x00AB2118+1057048]
	Ordinal0 [0x00ACB52C+1160492]
	Ordinal0 [0x00AC9B7F+1153919]
	Ordinal0 [0x00AF9D8F+1351055]
	Ordinal0 [0x00AF99FA+1350138]
	Ordinal0 [0x00AF589B+1333403]
	Ordinal0 [0x00AD1F74+1187700]
	Ordinal0 [0x00AD2DC9+1191369]
	GetHandleVerifier [0x00DD30D6+1610054]
	GetHandleVerifier [0x00E7B53B+2299307]
	GetHandleVerifier [0x00CC8DA9+519705]
	GetHandleVerifier [0x00CC7759+513993]
	Ordinal0 [0x00BD112D+2232621]
	Ordinal0 [0x00BD55F8+2250232]
	Ordinal0 [0x00BD5732+2250546]
	Ordinal0 [0x00BDE591+2286993]
	BaseThreadInitThunk [0x774AFA29+25]
	RtlGetAppContainerNamedObjectPath [0x777B7A7E+286]
	RtlGetAppContainerNamedObjectPath [0x777B7A4E+238]

	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$errorHandler$0(W3CHandshakeResponse.java:62)
	at org.openqa.selenium.remote.HandshakeResponse.lambda$getResponseFunction$0(HandshakeResponse.java:30)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:126)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:128)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:74)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:181)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:168)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:123)
	at com.XXX.XXX.XXX.XXX.openGoogleTest(seleniumtest.java:20)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.testng.TestRunner.privateRun(TestRunner.java:794)
	at org.testng.TestRunner.run(TestRunner.java:596)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
	at org.testng.SuiteRunner.run(SuiteRunner.java:276)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
	at org.testng.TestNG.runSuites(TestNG.java:1063)
	at org.testng.TestNG.run(TestNG.java:1031)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)

**Comment by bonigarcia** [comment]
That's an issue of Selenium WebDriver, not WebDriverManager. See for example [StackOverflow](https://stackoverflow.com/questions/50138615/webdriverexception-unknown-error-cannot-find-chrome-binary-error-with-selenium).
