### ISSUE TITLE
Getting io.github.bonigarcia.wdm.WebDriverManagerException: Error HTTP 401 error while running code on FF

### ISSUE THREAD

**Issue by ShivjayKolwankar** [bonigarcia/webdrivermanager#708]
Getting 401 error, while running the code on firefox.
Previously it work nicely but from last two days it giving me this error

2021-09-20 09:24:24 INFO  WebDriverManager:1056 - Reading https://api.github.com/repos/mozilla/geckodriver/releases to seek geckodriver
2021-09-20 09:24:25 ERROR HttpClient:164 - Error HTTP 401 executing GET https://api.github.com/repos/mozilla/geckodriver/releases HTTP/1.1
2021-09-20 09:24:25 ERROR WebDriverManager:683 - There was an error managing geckodriver  (Error HTTP 401 executing GET https://api.github.com/repos/mozilla/geckodriver/releases HTTP/1.1)
io.github.bonigarcia.wdm.WebDriverManagerException: Error HTTP 401 executing GET https://api.github.com/repos/mozilla/geckodriver/releases HTTP/1.1
	at io.github.bonigarcia.wdm.HttpClient.execute(HttpClient.java:165)
	at io.github.bonigarcia.wdm.WebDriverManager.openGitHubConnection(WebDriverManager.java:1050)
	at io.github.bonigarcia.wdm.WebDriverManager.getDriversFromGitHub(WebDriverManager.java:1065)
	at io.github.bonigarcia.wdm.FirefoxDriverManager.getDrivers(FirefoxDriverManager.java:76)
	at io.github.bonigarcia.wdm.WebDriverManager.filterCandidateUrls(WebDriverManager.java:700)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:506)
	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:681)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:521)
	at io.github.bonigarcia.wdm.WebDriverManager.setup(WebDriverManager.java:251)
	at com.pearson.itautomation.accuplacer.test.TestBase.getBrowser(TestBase.java:641)
	at com.pearson.itautomation.accuplacer.test.TestBase.getBrowser(TestBase.java:632)
	at com.pearson.itautomation.accuplacer.test.testsetup.TestOperationsAcademicFactorsIA.beforeClass(TestOperationsAcademicFactorsIA.java:241)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:168)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:105)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

**Comment by edumco** [comment]
@ShivjayKolwankar Could you please add more details? 

**Browser and version**: 

**Operating system**: 

**WebDriverManager version**: 

**WebDriverManager call**:

**Comment by ShivjayKolwankar** [comment]
Browser and version: Firefox version 91.0.2

Operating system:Windows

WebDriverManager version: 3.2.0

WebDriverManager call: 
public synchronized Browser getBrowser(Browser browserInstance) {
		if (browserInstance == null) {
			if (browserName.equalsIgnoreCase("Firefox")) {
				WebDriverManager.firefoxdriver().gitHubTokenName("Webdriver Token");
				WebDriverManager.firefoxdriver().gitHubTokenSecret("edbfcfc4011b8b57a1d2b0753768835c9f562489");
				WebDriverManager.firefoxdriver().setup();
				WebDriver driver = setFireFoxProfile();

				browserInstance = new AccuplacerBrowser(driver);
			}

**Comment by edumco** [comment]
@ShivjayKolwankar I will try to reproduce but I believe you are in an "too old" version.

> WebDriverManager version: 3.2.0

What is your Java version?

**Comment by ShivjayKolwankar** [comment]
@edumco 
What is your Java version:- Java 1.8

**Comment by bonigarcia** [comment]
@ShivjayKolwankar Bump to the latest version of WebDriverManager.
