### ISSUE TITLE
[Issue] Creating a Firefox Driver - throws IllegalArgumentException key can't be empty

### ISSUE THREAD

**Issue by kyleshrader** [bonigarcia/webdrivermanager#71]
As of version 1.4.9 I am receiving the following error when calling `WebDriverManager.getInstance(FirefoxDriver.class.asSubclass(WebDriver.class)).setup("x64");`

```
java.lang.RuntimeException: java.lang.IllegalArgumentException: key can't be empty
	at io.github.bonigarcia.wdm.BrowserManager.manage(BrowserManager.java:273)
	at io.github.bonigarcia.wdm.BrowserManager.setup(BrowserManager.java:103)
	at io.github.bonigarcia.wdm.BrowserManager.setup(BrowserManager.java:90)
	... 40 more
Caused by: java.lang.IllegalArgumentException: key can't be empty
	at java.lang.System.checkKey(System.java:841)
	at java.lang.System.setProperty(System.java:789)
	at io.github.bonigarcia.wdm.BrowserManager.exportDriver(BrowserManager.java:518)
	at io.github.bonigarcia.wdm.BrowserManager.manage(BrowserManager.java:205)
	... 40 more
```

**Comment by rosolko** [comment]
@kyleshrader Can you try to use command to get driver binary like this:
`MarionetteDriverManager.getInstance().setup(Architecture.x64);`

**Comment by bonigarcia** [comment]
You can also do like this:

`WebDriverManager.getInstance(MarionetteDriver.class).setup(Architecture.x64);`
