### ISSUE TITLE
Avoid reading `application.conf` file

### ISSUE THREAD

**Issue by asolntsev** [bonigarcia/webdrivermanager#72]
Hi!
I tried to use WebDriverManager in my project and got the following error.
The problem is that my project contains file `conf/application.conf`, and WebDriverManager tries to parse it automatically (and fails). But I don't want WebDriverManager to parse my `application.conf`!

```java


com.typesafe.config.ConfigException$Parse: application.conf: 1: Reserved character '@' is not allowed outside quotes (if you intended '@' (Reserved character '@' is not allowed outside quotes) to be part of a key or string value, try enclosing the key or value in double quotes)

	at com.typesafe.config.impl.Parser$ParseContext.nextToken(Parser.java:279)
	at com.typesafe.config.impl.Parser$ParseContext.nextTokenIgnoringNewline(Parser.java:302)
	at com.typesafe.config.impl.Parser$ParseContext.parse(Parser.java:976)
	at com.typesafe.config.impl.Parser.parse(Parser.java:34)
	at com.typesafe.config.impl.Parseable.rawParseValue(Parseable.java:222)
	at com.typesafe.config.impl.Parseable$ParseableResources.rawParseValue(Parseable.java:602)
	at com.typesafe.config.impl.Parseable$ParseableResources.rawParseValue(Parseable.java:554)
	at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:176)
	at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:170)
	at com.typesafe.config.impl.Parseable.parse(Parseable.java:148)
	at com.typesafe.config.impl.SimpleIncluder.fromBasename(SimpleIncluder.java:185)
	at com.typesafe.config.impl.ConfigImpl.parseResourcesAnySyntax(ConfigImpl.java:128)
	at com.typesafe.config.ConfigFactory.parseResourcesAnySyntax(ConfigFactory.java:811)
	at com.typesafe.config.ConfigFactory.load(ConfigFactory.java:113)
	at com.typesafe.config.ConfigFactory.load(ConfigFactory.java:136)
	at com.typesafe.config.ConfigFactory.loadDefaultConfig(ConfigFactory.java:228)
	at com.typesafe.config.ConfigFactory.access$000(ConfigFactory.java:38)
	at com.typesafe.config.ConfigFactory$1.call(ConfigFactory.java:378)
	at com.typesafe.config.ConfigFactory$1.call(ConfigFactory.java:375)
	at com.typesafe.config.impl.ConfigImpl$LoaderCache.getOrElseUpdate(ConfigImpl.java:58)
	at com.typesafe.config.impl.ConfigImpl.computeCachedConfig(ConfigImpl.java:86)
	at com.typesafe.config.ConfigFactory.load(ConfigFactory.java:375)
	at com.typesafe.config.ConfigFactory.load(ConfigFactory.java:299)
	at com.typesafe.config.ConfigFactory.load(ConfigFactory.java:288)
	at io.github.bonigarcia.wdm.WdmConfig.<init>(WdmConfig.java:35)
	at io.github.bonigarcia.wdm.WdmConfig.getInstance(WdmConfig.java:40)
	at io.github.bonigarcia.wdm.WdmConfig.getString(WdmConfig.java:46)
	at io.github.bonigarcia.wdm.ChromeDriverManager.getDriverVersion(ChromeDriverManager.java:54)
	at io.github.bonigarcia.wdm.BrowserManager.setup(BrowserManager.java:102)
	at io.github.bonigarcia.wdm.BrowserManager.setup(BrowserManager.java:87)
```

**Comment by bonigarcia** [comment]
Yes, it is a side-effect of using the default name for the properties file (`application.properties`) by wdm. Due to the fact that you are also using the library com.typesafe.config in your project, wdm tries to read your `application.conf` in the first place.

To solve this, first I am going to accept your PR #73, and also I am going to change the default name of the internal properties of wdm. This will be available in the next version.

Thanks for reporting and contributing.
