### ISSUE TITLE
Allow to provide docker image prefix for docker registry mirror

### ISSUE THREAD

**Issue by tyge68** [bonigarcia/webdrivermanager#740]
**Description of the problem**: 
I am using an Artifactory as mirror serveur for docker registry (with authentication) in place 

In the past it used to work (when using selenium jupiter 3.4.0 based on webdriver manager 4.4.3)

Currently it is not possible to provide the url pattern to use alternative docker registry
using the -Dwdm.dockerBrowserSelenoidImageFormat=docker-hub-remote.dr-uw2.mydomain.com/selenoid/vnc:%s_%s

**Browser and version**:  Not related

**Operating system**:  Not related

**WebDriverManager version**: latest snapshot

**WebDriverManager call**:  wdm.create()

**WebDriverManager traces**: 

 11:38:50.168 [ForkJoinPool-1-worker-1] ERROR i.g.b.w.o.HttpClient - Error HTTP 404 executing https://hub.docker.com/v2/repositories/docker-hub-remote.dr-uw2.mydomain.com/selenoid/vnc/tags?page=1&page_size=1024
 11:38:50.170 [ForkJoinPool-1-worker-1] WARN  i.g.b.w.d.DockerHubService - Exception getting browser image list from Docker Hub
 io.github.bonigarcia.wdm.config.WebDriverManagerException: Error HTTP 404 executing https://hub.docker.com/v2/repositories/docker-hub-remote.dr-uw2.mydomain.com/selenoid/vnc/tags?page=1&page_size=1024
 	at io.github.bonigarcia.wdm.online.HttpClient.execute(HttpClient.java:172)
 	at io.github.bonigarcia.wdm.docker.DockerHubService.listTags(DockerHubService.java:76)
 	at io.github.bonigarcia.wdm.docker.DockerService.getImageVersionFromDockerHub(DockerService.java:386)
 	at io.github.bonigarcia.wdm.WebDriverManager.createDockerWebDriver(WebDriverManager.java:1532)
 	at io.github.bonigarcia.wdm.WebDriverManager.instantiateDriver(WebDriverManager.java:1463)
 	at io.github.bonigarcia.wdm.WebDriverManager.create(WebDriverManager.java:370)

**Error log**: 

It would be nice to be able then to provide a -Dwdm.dockerMirrorPrefix (kind of parameter) so that once it resolved the image to use from docker hub eventually it would use the prefix to really pull and run the docker image (that would be same also for recorder and novnc images for example)

**Comment by tyge68** [comment]
currently the only alternative is to use custom image, but then we loose the feature to automatically use the latest available version as we need to hard code the image url

**Comment by tyge68** [comment]
not that in the past it used to work that we could prefix the chrome image pattern (when using via selenium jupiter), but now even if I change a bit the code in webdrivermanager (dockerservice) to use the prefix to the dockerimage, it still fails to proceed, most likely it tries to perform some action itself, not via the docker service (so for example it wouldn't have any idea about docker login for that prefixed docker image url).

**Comment by tyge68** [comment]
This issue is mainly due to registry-mirrors settings that doesn't allow authenticated registry, otherwise it would work transparently  (1), so we need a way to prefix selenoid images but still allow to resolve them (as it used to work in older release)

(1) https://github.com/moby/moby/issues/30880

**Comment by bonigarcia** [comment]
Thanks a lot for contributing. I am not sure if your PR is actually needed. There is another configuration parameter that allows to change the Docker Hub URL, called `wdm.dockerHubUrl`, which by default is `https://hub.docker.com/`.  Have you try the following?

```
-Dwdm.dockerHubUrl=https://docker-hub-remote.dr-uw2.mydomain.com
```

**Comment by tyge68** [comment]
@bonigarcia It's not working with that parameters, the reason is that the artifactory is probably not really a docker hub

7:37:20.104 [main] WARN  i.g.b.w.d.DockerHubService - Exception getting browser image list from Docker Hub
java.net.UnknownHostException: docker-hub-remote.dr-uw2.mydomainitc.comv2: nodename nor servname provided, or not known
	at java.base/java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:929)
	at java.base/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1515)
	at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:848)
	at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1505)
	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1364)
	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1298)
	at org.apache.hc.client5.http.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:43)
	at org.apache.hc.client5.http.impl.io.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:118)
	at org.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:409)
	at org.apache.hc.client5.http.impl.classic.InternalExecRuntime.connectEndpoint(InternalExecRuntime.java:164)
	at org.apache.hc.client5.http.impl.classic.InternalExecRuntime.connectEndpoint(InternalExecRuntime.java:174)
	at org.apache.hc.client5.http.impl.classic.ConnectExec.execute(ConnectExec.java:135)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
	at org.apache.hc.client5.http.impl.classic.ProtocolExec.execute(ProtocolExec.java:172)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
	at org.apache.hc.client5.http.impl.classic.HttpRequestRetryExec.execute(HttpRequestRetryExec.java:93)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
	at org.apache.hc.client5.http.impl.classic.ContentCompressionExec.execute(ContentCompressionExec.java:128)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
	at org.apache.hc.client5.http.impl.classic.RedirectExec.execute(RedirectExec.java:116)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.InternalHttpClient.doExecute(InternalHttpClient.java:178)
	at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:75)
	at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:89)
	at io.github.bonigarcia.wdm.online.HttpClient.execute(HttpClient.java:158)
	at io.github.bonigarcia.wdm.docker.DockerHubService.listTags(DockerHubService.java:76)
	at io.github.bonigarcia.wdm.docker.DockerService.getImageVersionFromDockerHub(DockerService.java:386)
	at io.github.bonigarcia.wdm.WebDriverManager.createDockerWebDriver(WebDriverManager.java:1532)
	at io.github.bonigarcia.wdm.WebDriverManager.instantiateDriver(WebDriverManager.java:1463)
	at io.github.bonigarcia.wdm.WebDriverManager.create(WebDriverManager.java:370)
	at com.mydomain.qe.selenium.junit.extensions.WebdriverSetupExtension.beforeEach(WebdriverSetupExtension.java:78)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeBeforeEachCallbacks$1(TestMethodTestDescriptor.java:161)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeBeforeMethodsOrCallbacksUntilExceptionOccurs$5(TestMethodTestDescriptor.java:197)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeBeforeMethodsOrCallbacksUntilExceptionOccurs(TestMethodTestDescriptor.java:197)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeBeforeEachCallbacks(TestMethodTestDescriptor.java:160)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:131)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:71)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:135)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:229)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:197)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:211)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:191)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:71)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)

while it works if we simply prefix as I did in that PR and as it used to work also in the previous versions of webdriver manager 4.4.3 (via selenium jupiter) with the old parameter to set the image like with
-Dsel.jup.selenoid.image=${this.dockerRemoteBaseURL}/aerokube/selenoid:1.10.1
-Dsel.jup.chrome.image.format=${this.dockerRemoteBaseURL}/selenoid/vnc:chrome_%s
-Dsel.jup.recording.image=${this.dockerRemoteBaseURL}/selenoid/video-recorder:latest

**Comment by bonigarcia** [comment]
If I am not wrong, the new image in your PR is composed by appending the "prefix" (which is specified using the configuration `key wdm.dockerPrivateEndpoint`) plus the regular docker image format:

```
newDockerImage = String.format("%s/%s", prefix, dockerImage);
```

Therefore, I do not see the difference of executing your test using this configuration:

```
 -Dwdm.dockerBrowserSelenoidImageFormat=docker-hub-remote.dr-uw2.mydomain.com/selenoid/vnc:%s_%s
```

... from this:

```
-Dwdm.dockerPrivateEndpoint= docker-hub-remote.dr-uw2.mydomain.com -Dwdm.dockerBrowserSelenoidImageFormat=selenoid/vnc:%s_%s
```

For the other Docker images (the recorder and noVNC), you also have configuration capabilities for changing the default value (Selenoid is not used anymore, so you don't need to worry about that):

```
wdm.dockerRecordingImage=selenoid/video-recorder:7.1
wdm.dockerNoVncImage=bonigarcia/novnc:1.1.0
```

What am I missing here? Could you please specify how do you run your tests using your PR?

**Comment by tyge68** [comment]
@bonigarcia  not really, if I use docker-hub-remote.dr-uw2.mydomain.com/selenoid/vnc:%s_%s , it will fail to try to resolve the possible docker images as this process doesn't use the authentication, it seems it only use the authentication stored in the .docker/config.json, when it does the pull command, but for any other command that is not happening, mainly because it uses the original docker index endpoint, which will not find then the images starting with docker-hub-remote.dr-uw2.mydomain.com/...

I simply run the my ITs with -Dwdm.dockerPrivateEndpoint=docker-hub-remote.dr-uw2.mydomain.com using my snapshot version of WebDriverManager 

If you have an artifactory / docker private registry (with authentication token) you could easily reproduce it.

**Comment by bonigarcia** [comment]
@tyge68 Thanks for the clarifications. Just one more thing before merging the PR. Could you please include an update in the [asciidoc source](https://github.com/bonigarcia/webdrivermanager/blob/master/src/doc/asciidoc/index.adoc) to explain the new configuration key and method? Thank you.

**Comment by bonigarcia** [comment]
Thanks a lot @tyge68. This will be available in next version of WebDriverManager (I'm waiting until a new version of docker-java is available).

**Comment by tyge68** [comment]
@bonigarcia  thanks a lot, indeed it would be great that docker-java get released too, currently I am using also an internal release.
