### ISSUE TITLE
Cannot initialize web driver on Mac

### ISSUE THREAD

**Issue by hoffic-cz** [bonigarcia/webdrivermanager#758]
**Description of the problem**:
I'm trying to launch ChromeDriver through WebDriverManager on my Mac, but I'm getting the following exception:
```
SEVERE: org.apache.commons.exec.ExecuteException: Execution failed (Exit value: -559038737. Caused by java.io.IOException: Cannot run program "/Users/hoffic/.cache/selenium/chromedriver/mac64/96.0.4664.45/chromedriver" (in directory "."): error=0, posix_spawn failed)
```
 This only happens on Mac, Windows and Linux work well. Executing the mentioned program directly works:
```
$ /Users/hoffic/.cache/selenium/chromedriver/mac64/96.0.4664.45/chromedriver
Starting ChromeDriver 96.0.4664.45 (76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}) on port 9515
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
```

**Browser and version**: Version 96.0.4664.110 (Official Build) (x86_64)

**Operating system**: MacOS Big Sur 11.6.1 (Intel)

**WebDriverManager version**: 4.4.3

**WebDriverManager call**:
```
new ChromeDriver();
```

**WebDriverManager traces**:
```
org.openqa.selenium.WebDriverException: Timed out waiting for driver server to start.
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: '88665a380cff.ant.amazon.com', ip: '192.168.1.126', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.16', java.version: '11.0.11'
Driver info: driver.version: ChromeDriver
        at com.app.merged.module@1.0-SNAPSHOT/org.openqa.selenium.remote.service.DriverService.waitUntilAvailable(DriverService.java:202)
        at com.app.merged.module@1.0-SNAPSHOT/org.openqa.selenium.remote.service.DriverService.start(DriverService.java:188)
        at com.app.merged.module@1.0-SNAPSHOT/org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:79)
        at com.app.merged.module@1.0-SNAPSHOT/org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
        at com.app.merged.module@1.0-SNAPSHOT/org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
        at com.app.merged.module@1.0-SNAPSHOT/org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
        at com.app.merged.module@1.0-SNAPSHOT/org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:181)
        at com.app.merged.module@1.0-SNAPSHOT/org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:168)
        at com.app.merged.module@1.0-SNAPSHOT/org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:157)
        at com.app@1.0-SNAPSHOT/com.app.crawler.CrawlerLogic.setupBrowser(CrawlerLogic.java:67)
        at com.app@1.0-SNAPSHOT/com.app.crawler.CrawlerLogic.configureWebsiteStructure(CrawlerLogic.java:35)
        at com.app@1.0-SNAPSHOT/com.app.controller.DashboardController.lambda$setup$4(DashboardController.java:86)
        at com.app.controller.DashboardController$$Lambda$595/0x0000000004e62870.run(Unknown Source)
        at java.base/java.lang.Thread.run(Thread.java:836)
Caused by: org.openqa.selenium.net.UrlChecker$TimeoutException: Timed out waiting for [http://localhost:1257/status] to be available after 20001 ms
        at com.app.merged.module@1.0-SNAPSHOT/org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:100)
        at com.app.merged.module@1.0-SNAPSHOT/org.openqa.selenium.remote.service.DriverService.waitUntilAvailable(DriverService.java:197)
        ... 13 more
Caused by: java.util.concurrent.TimeoutException
        at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
        at com.app.merged.module@1.0-SNAPSHOT/com.google.common.util.concurrent.SimpleTimeLimiter.callWithTimeout(SimpleTimeLimiter.java:155)
        at com.app.merged.module@1.0-SNAPSHOT/org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:75)
        ... 14 more
```

**Error log**: 
```
SEVERE: org.apache.commons.exec.ExecuteException: Execution failed (Exit value: -559038737. Caused by java.io.IOException: Cannot run program "/Users/hoffic/.cache/selenium/chromedriver/mac64/96.0.4664.45/chromedriver" (in directory "."): error=0, posix_spawn failed)
```

**Comment by mNarraMine** [comment]
@hoffic-cz Try to refer to [this](https://github.com/bonigarcia/webdrivermanager/issues/737).
run your driver binary via terminal and make sure that your driver fir to your Intel or M-platform.
Better get update webdrivermanager version to last one.

**Comment by hoffic-cz** [comment]
I don't believe this is the issue:

- When I run the driver binary in the terminal, it executes successfully.
- I cannot upgrade to a newer version because it [doesn't work with modular java apps](https://github.com/bonigarcia/webdrivermanager/issues/759).
