### ISSUE TITLE
Internet Explorer does not work with new 5.0.3 version

### ISSUE THREAD

**Issue by dougnoel** [bonigarcia/webdrivermanager#771]
**Description of the problem**: Steps to Reproduce:
1. Upgrade to WebDriverManager 5.0.3 from 4.4.1
2. Create an IE driver using
```            var ieOptions = new InternetExplorerOptions();
        	ieOptions.ignoreZoomSettings();
        	WebDriverManager.iedriver().setup();
        	driver = new InternetExplorerDriver(ieOptions);
```

**RESULT:** A MalformedURLException is thrown
io.github.bonigarcia.wdm.config.WebDriverManagerException: java.net.MalformedURLException: no protocol: 
	at io.github.bonigarcia.wdm.config.Config.parse(Config.java:295) ~[webdrivermanager-5.0.3.jar:?]

**EXPECTED:** The existing IEServerDriver.exe would be used OR the IEServerDriver.exe would be downloaded and used.

**NOTE:** We debugged this issue, and it appears that the new version does not retrieve a driver list, and is returning null, resulting in a URL being created using a null. We attempted the below code to pass in the URL used in 4.4.1 and got the following error:

12:32:29.148 ERROR wdm.WebDriverManager (WebDriverManager.java:1139) - There was an error managing IEDriverServer (latest version) (java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 1 column 1 path $)
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 1 column 1 path $

```
WebDriverManager wdm = WebDriverManager.iedriver();
            try {
                wdm.config().setIExplorerDriverUrl(new URL("https://selenium-release.storage.googleapis.com/"));
            } catch (MalformedURLException e) {
                throw new RuntimeException(e);
            }
            wdm.setup();
```

**Browser and version**: Internet Explorer 20H2 (Windows 10 Home OS Build 19042.1415)

**Operating system**: Windows 10 Home OS Build 19042.1415 64-bit

**WebDriverManager version**: 5.0.3

**WebDriverManager call**:
```            var ieOptions = new InternetExplorerOptions();
        	ieOptions.ignoreZoomSettings();
        	WebDriverManager.iedriver().setup();
        	driver = new InternetExplorerDriver(ieOptions);
```

**WebDriverManager traces**: 
```12:28:19.159 DEBUG wdm.WebDriverManager (WebDriverManager.java:993) - The driver version for IEXPLORER is unknown ... trying with latest
12:28:19.162 WARN  wdm.WebDriverManager (WebDriverManager.java:1150) - There was an error managing IEDriverServer (latest version) (java.net.MalformedURLException: no protocol: ) ... trying again using latest driver stored in cache
12:28:19.162 TRACE wdm.WebDriverManager (WebDriverManager.java:1153) - Error trace: 
io.github.bonigarcia.wdm.config.WebDriverManagerException: java.net.MalformedURLException: no protocol: 
	at io.github.bonigarcia.wdm.config.Config.parse(Config.java:295) ~[webdrivermanager-5.0.3.jar:?]
	at io.github.bonigarcia.wdm.config.Config.resolver(Config.java:277) ~[webdrivermanager-5.0.3.jar:?]
	at io.github.bonigarcia.wdm.config.Config.resolve(Config.java:262) ~[webdrivermanager-5.0.3.jar:?]
	at io.github.bonigarcia.wdm.config.Config.getIExplorerDriverUrl(Config.java:873) ~[webdrivermanager-5.0.3.jar:?]
	at io.github.bonigarcia.wdm.managers.InternetExplorerDriverManager.getDriverUrl(InternetExplorerDriverManager.java:78) ~[webdrivermanager-5.0.3.jar:?]
	at io.github.bonigarcia.wdm.WebDriverManager.getDriversFromGitHub(WebDriverManager.java:1321) ~[webdrivermanager-5.0.3.jar:?]
	at io.github.bonigarcia.wdm.managers.InternetExplorerDriverManager.getDriverUrls(InternetExplorerDriverManager.java:98) ~[webdrivermanager-5.0.3.jar:?]
	at io.github.bonigarcia.wdm.WebDriverManager.createUrlHandler(WebDriverManager.java:1161) [webdrivermanager-5.0.3.jar:?]
	at io.github.bonigarcia.wdm.WebDriverManager.download(WebDriverManager.java:1009) [webdrivermanager-5.0.3.jar:?]
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:927) [webdrivermanager-5.0.3.jar:?]
	at io.github.bonigarcia.wdm.WebDriverManager.setup(WebDriverManager.java:337) [webdrivermanager-5.0.3.jar:?]
	at com.dougnoel.sentinel.webdrivers.WebDriverFactory.instantiateWebDriver(WebDriverFactory.java:87) [classes/:?]
	at com.dougnoel.sentinel.webdrivers.WebdriverFactoryBadBrowserNameTest.passOSSpecificBrowser(WebdriverFactoryBadBrowserNameTest.java:51) [test-classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50) [junit-4.12.jar:4.12]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) [junit-4.12.jar:4.12]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47) [junit-4.12.jar:4.12]
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325) [junit-4.12.jar:4.12]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78) [junit-4.12.jar:4.12]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268) [junit-4.12.jar:4.12]
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363) [junit-4.12.jar:4.12]
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210) [.cp/:?]
Caused by: java.net.MalformedURLException: no protocol: 
	at java.net.URL.<init>(URL.java:674) ~[?:?]
	at java.net.URL.<init>(URL.java:569) ~[?:?]
	at java.net.URL.<init>(URL.java:516) ~[?:?]
	at io.github.bonigarcia.wdm.config.Config.parse(Config.java:293) ~[webdrivermanager-5.0.3.jar:?]
	... 36 more
12:28:19.167 DEBUG wdm.WebDriverManager (WebDriverManager.java:993) - The driver version for IEXPLORER is unknown ... trying with latest
12:28:19.168 ERROR wdm.WebDriverManager (WebDriverManager.java:1139) - There was an error managing IEDriverServer (latest version) (java.net.MalformedURLException: no protocol: )
io.github.bonigarcia.wdm.config.WebDriverManagerException: java.net.MalformedURLException: no protocol: 
	at io.github.bonigarcia.wdm.config.Config.parse(Config.java:295) ~[webdrivermanager-5.0.3.jar:?]
	at io.github.bonigarcia.wdm.config.Config.resolver(Config.java:277) ~[webdrivermanager-5.0.3.jar:?]
	at io.github.bonigarcia.wdm.config.Config.resolve(Config.java:262) ~[webdrivermanager-5.0.3.jar:?]
	at io.github.bonigarcia.wdm.config.Config.getIExplorerDriverUrl(Config.java:873) ~[webdrivermanager-5.0.3.jar:?]
	at io.github.bonigarcia.wdm.managers.InternetExplorerDriverManager.getDriverUrl(InternetExplorerDriverManager.java:78) ~[webdrivermanager-5.0.3.jar:?]
	at io.github.bonigarcia.wdm.WebDriverManager.getDriversFromGitHub(WebDriverManager.java:1321) ~[webdrivermanager-5.0.3.jar:?]
	at io.github.bonigarcia.wdm.managers.InternetExplorerDriverManager.getDriverUrls(InternetExplorerDriverManager.java:98) ~[webdrivermanager-5.0.3.jar:?]
	at io.github.bonigarcia.wdm.WebDriverManager.createUrlHandler(WebDriverManager.java:1161) ~[webdrivermanager-5.0.3.jar:?]
	at io.github.bonigarcia.wdm.WebDriverManager.download(WebDriverManager.java:1009) [webdrivermanager-5.0.3.jar:?]
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:927) [webdrivermanager-5.0.3.jar:?]
	at io.github.bonigarcia.wdm.WebDriverManager.fallback(WebDriverManager.java:1156) [webdrivermanager-5.0.3.jar:?]
	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:1133) [webdrivermanager-5.0.3.jar:?]
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:933) [webdrivermanager-5.0.3.jar:?]
	at io.github.bonigarcia.wdm.WebDriverManager.setup(WebDriverManager.java:337) [webdrivermanager-5.0.3.jar:?]
	at com.dougnoel.sentinel.webdrivers.WebDriverFactory.instantiateWebDriver(WebDriverFactory.java:87) [classes/:?]
	at com.dougnoel.sentinel.webdrivers.WebdriverFactoryBadBrowserNameTest.passOSSpecificBrowser(WebdriverFactoryBadBrowserNameTest.java:51) [test-classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50) [junit-4.12.jar:4.12]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) [junit-4.12.jar:4.12]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47) [junit-4.12.jar:4.12]
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325) [junit-4.12.jar:4.12]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78) [junit-4.12.jar:4.12]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268) [junit-4.12.jar:4.12]
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363) [junit-4.12.jar:4.12]
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210) [.cp/:?]
Caused by: java.net.MalformedURLException: no protocol: 
	at java.net.URL.<init>(URL.java:674) ~[?:?]
	at java.net.URL.<init>(URL.java:569) ~[?:?]
	at java.net.URL.<init>(URL.java:516) ~[?:?]
	at io.github.bonigarcia.wdm.config.Config.parse(Config.java:293) ~[webdrivermanager-5.0.3.jar:?]
	... 39 more ```

**Error log**: See above

**Comment by altus34** [comment]
Hi,
Can you try to use this code to create a new driver for you case?

```
WebDriverManager wdm = WebDriverManager.iedriver();

InternetExplorerOptions options = new InternetExplorerOptions();
options.ignoreZoomSettings();

wdm.capabilities(options);
WebDriver driver =  wdm.create();
```

**Comment by bonigarcia** [comment]
I have just executed this [test](https://github.com/bonigarcia/webdrivermanager/blob/master/src/test/java/io/github/bonigarcia/wdm/test/iexplorer/IExplorerTest.java) in a Windows machine with Explorer and it works nicely:

```
2022-02-01 14:58:36 [main] DEBUG i.g.bonigarcia.wdm.WebDriverManager.resolveDriverVersion(1112) -- The driver version for IEXPLORER is unknown ... trying with latest
2022-02-01 14:58:36 [main] INFO  i.g.bonigarcia.wdm.WebDriverManager.logSeekRepo(1411) -- Reading https://api.github.com/repos/SeleniumHQ/selenium/releases to seek IEDriverServer
2022-02-01 14:58:38 [main] DEBUG i.g.bonigarcia.wdm.WebDriverManager.createUrlHandler(1304) -- Driver to be downloaded IEDriverServer 4.0.0
2022-02-01 14:58:38 [main] INFO  i.g.bonigarcia.wdm.WebDriverManager.exportDriver(1140) -- Exporting webdriver.ie.driver as C:\Users\boni\.cache\selenium\IEDriverServer\win64\4.0.0\IEDriverServer.exe
Started InternetExplorerDriver server (64-bit)
4.0.0.0
Listening on port 50801
Only local connections are allowed
feb 01, 2022 2:58:49 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFORMACIÓN: Detected dialect: W3C
```

I suppose you have some kind of configuration problem at your end. The URL for IE drivers is supposed to be following:

https://api.github.com/repos/SeleniumHQ/selenium/releases

**Comment by dougnoel** [comment]
Great thanks. I will take a look at this week.
