### ISSUE TITLE
Missing explicit dependency for org.apache.httpcomponents.core5:httpcore5:5.1.x

### ISSUE THREAD

**Issue by tyge68** [bonigarcia/webdrivermanager#802]
**Description of the problem**: HttpClient class fail to load dependencies -> NoClassDefFoundError
From  our observation building our project with maven version 3.5.x was working fine, since 3.6.x and above it started to miss some dependencies. 

With 3.6.x and above we need to explicitly add the following dependency in our pom.xml
```
        <dependency>
            <groupId>org.apache.httpcomponents.core5</groupId>
            <artifactId>httpcore5</artifactId>
            <version>5.1.3</version>
        </dependency>
```

I suppose this dependency should be explicit in webdrivermanager pom.xml itself. Since the code that depend on it is the class HttpClient.

**Browser and version**: chrome 99 via docker standalone image
**Operating system**: docker container based on adoptopenjdk/openjdk11:jre

**WebDriverManager version**: 5.1.0

**WebDriverManager call**: WebDriverManager.create(..)

**WebDriverManager traces**: 

**Error log**: 
```
â”‚  â”‚  â”‚  â”‚     caught: [31mjava.lang.NoClassDefFoundError: org/apache/hc/core5/http/io/ResponseOutOfOrderStrategy[0m
â”‚  â”‚  â”‚  â”‚               [31m	at org.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManager.<init>(PoolingHttpClientConnectionManager.java:203)[0m
â”‚  â”‚  â”‚  â”‚               [31m	at org.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManager.<init>(PoolingHttpClientConnectionManager.java:168)[0m
â”‚  â”‚  â”‚  â”‚               [31m	at org.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManager.<init>(PoolingHttpClientConnectionManager.java:157)[0m
â”‚  â”‚  â”‚  â”‚               [31m	at org.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManager.<init>(PoolingHttpClientConnectionManager.java:140)[0m
â”‚  â”‚  â”‚  â”‚               [31m	at org.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManager.<init>(PoolingHttpClientConnectionManager.java:132)[0m
â”‚  â”‚  â”‚  â”‚               [31m	at org.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManager.<init>(PoolingHttpClientConnectionManager.java:126)[0m
â”‚  â”‚  â”‚  â”‚               [31m	at io.github.bonigarcia.wdm.online.HttpClient.<init>(HttpClient.java:118)[0m
â”‚  â”‚  â”‚  â”‚               [31m	at io.github.bonigarcia.wdm.WebDriverManager.setup(WebDriverManager.java:379)[0m
â”‚  â”‚  â”‚  â”‚               [31m	at io.github.bonigarcia.wdm.WebDriverManager.create(WebDriverManager.java:398)[0m
```

**Comment by tyge68** [comment]
As workaround we currently include this dependency in our module, ultimately I believe it should be defined in webdrivermanager itself.
