### ISSUE TITLE
Exception reading resolution cache as a properties file

### ISSUE THREAD

**Issue by pabloxid** [bonigarcia/webdrivermanager#814]
**Description of the problem**: expected: not crash; actual: crash

**Browser and version**: chrome

**Operating system**: android 7

**WebDriverManager version**: 5.1.0

**WebDriverManager call**: WebDriverManager.chromedriver().setup()

**Error log**: io.github.bonigarcia.wdm.config.WebDriverManagerException: Exception reading resolution cache as a properties file
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2957)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
     Caused by: io.github.bonigarcia.wdm.config.WebDriverManagerException: Exception reading resolution cache as a properties file
        at io.github.bonigarcia.wdm.cache.ResolutionCache.<init>(ResolutionCache.java:86)
        at io.github.bonigarcia.wdm.WebDriverManager.getResolutionCache(WebDriverManager.java:1490)
        at io.github.bonigarcia.wdm.WebDriverManager.clearResolutionCache(WebDriverManager.java:780)
        at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:1263)
        at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:1060)
        at io.github.bonigarcia.wdm.WebDriverManager.setup(WebDriverManager.java:393)
        at com.example.ircbot_android.MainActivity.onCreate(MainActivity.kt:66)
        at android.app.Activity.performCreate(Activity.java:7183)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2910)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6944) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374) 
     Caused by: java.io.IOException: No such file or directory
        at java.io.UnixFileSystem.createFileExclusively0(Native Method)
        at java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:281)
        at java.io.File.createNewFile(File.java:1000)
        at io.github.bonigarcia.wdm.cache.ResolutionCache.<init>(ResolutionCache.java:75)
        at io.github.bonigarcia.wdm.WebDriverManager.getResolutionCache(WebDriverManager.java:1490) 
        at io.github.bonigarcia.wdm.WebDriverManager.clearResolutionCache(WebDriverManager.java:780) 
        at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:1263) 
        at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:1060) 
        at io.github.bonigarcia.wdm.WebDriverManager.setup(WebDriverManager.java:393) 
        at com.example.ircbot_android.MainActivity.onCreate(MainActivity.kt:66) 
        at android.app.Activity.performCreate(Activity.java:7183) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2910) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6944) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

**Comment by pabloxid** [comment]
the problem arises at this line of ResolutionCache.java: 

75    boolean createNewFile = resolutionCacheFile.createNewFile();

as resolutionCacheFile has an invalid path "/.cache/selenium/resolution.properties".

That "/.cache" path does not actually exist and causes a java.io.IOException: No such file or directory
Instead, cache dir should be something like java temp dir (System.getProperty("java.io.tmpdir")). That's my though

**Comment by bonigarcia** [comment]
WebDriverManager is not indented to be executed in an Android device. It should be able to write files (e.g., the downloaded drivers) in the file system. I suppose that should your problem.

**Comment by pabloxid** [comment]
I managed to solve this by calling setup() this way:

WebDriverManager.chromedriver().cachePath(this.cacheDir.toString()).setup()

Now I get this error when try to actually use Chromedriver:

org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
