### ISSUE TITLE
 Intermittent issue:Possible causes are the invalid address of the remote server or browser start-up failure

### ISSUE THREAD

**Issue by bachhavdipak** [bonigarcia/webdrivermanager#817]
Hi,
I am trying to execute a parallel test but facing the below issue on an intermittent basis. I am using serenity with Junit 5 and trying to run 120 test cases across different territories in a parallel mode (for example Australia, Netherlands, Finland ....etc)

Error due to Could not start a new session. **Possible causes are the invalid address of the remote server or browser start-up failure.**
2022-04-12T14:14:47.3907735Z     net.thucydides.core.webdriver.DriverConfigurationError: Could not instantiate new WebDriver instance of type class net.thucydides.core.webdriver.ProvidedDriver (Could not instantiate the custom webdriver provider of type mydriver). See below for more details.

```
#####################################################
# Default Serenity Web Driver Config
#####################################################
webdriver.driver = provided
webdriver.provided.type = mydriver
webdriver.provided.mydriver = Driver.ChromeRemoteDriver
serenity.driver.capabilities = mydriver
```

```

import io.github.bonigarcia.wdm.WebDriverManager;
import io.github.bonigarcia.wdm.config.DriverManagerType;
import io.github.bonigarcia.wdm.managers.ChromeDriverManager;
import lombok.AllArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import net.thucydides.core.util.EnvironmentVariables;
import net.thucydides.core.util.SystemEnvironmentVariables;
import net.thucydides.core.webdriver.DriverSource;
import org.apache.commons.lang3.SystemUtils;
import org.jetbrains.annotations.NotNull;
import org.openqa.selenium.UnexpectedAlertBehaviour;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriverService;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.remote.CapabilityType;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.UnreachableBrowserException;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import java.net.URL;
import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.CountDownLatch;

public class ChromeRemoteDriver implements DriverSource {


        private static final Logger logger = LoggerFactory.getLogger(Framework.Drivers.ChromeDriver.class);

        @NotNull
        private static ChromeOptions getChromeOptions() {

            final ChromeOptions chromeOptions = new ChromeOptions();

            Map<String, Object> prefs = new HashMap<String, Object>();

            prefs.put("googlegeolocationaccess.enabled", false);
            prefs.put("profile.default_content_setting_values.geolocation", 2); // 1:allow 2:block
            prefs.put("profile.default_content_setting_values.notifications", 1);
            prefs.put("profile.managed_default_content_settings", 1);
            chromeOptions.setExperimentalOption("prefs", prefs);

            chromeOptions.setAcceptInsecureCerts(true);

            chromeOptions.addArguments(
                    "--ignore-certificate-errors",
                    "--disable-download-notification",
                    "--no-sandbox",
                    "--disable-site-isolation-trials",
                    "--enable-strict-powerful-feature-restrictions",
                    "--disable-geolocation",
                    "--disable-gpu");

            chromeOptions.setCapability(CapabilityType.UNEXPECTED_ALERT_BEHAVIOUR, UnexpectedAlertBehaviour.IGNORE);

            if (SystemUtils.IS_OS_LINUX) {
                chromeOptions.addArguments(
                        "--headless",
                        "--allow-running-insecure-content",
                        "--disable-web-security",
                        "--window-size=1920,1080"
                );

                DesiredCapabilities capabilities = new DesiredCapabilities();
                capabilities.acceptInsecureCerts();
            } else if (SystemUtils.IS_OS_MAC || SystemUtils.IS_OS_WINDOWS) {
                chromeOptions.addArguments(
                        "--incognito",
                        "--start-fullscreen"
                );
            }
            return chromeOptions;
        }

        @Override
        public WebDriver newDriver() {

            RemoteWebDriver driver = null;

            DesiredCapabilities dc = new DesiredCapabilities();

            EnvironmentVariables environmentVariables = SystemEnvironmentVariables.createEnvironmentVariables();
            boolean remote = Boolean.parseBoolean(environmentVariables.getProperty("remote"));


                ConcurrentHashMap<String, Object> chromePrefs = new ConcurrentHashMap<String, Object>();
                chromePrefs.put("profile.default_content_settings.popups", 0);

                logger.info("##### Running web tests on remote ####");
                String accessKey = System.getenv("key");
                String serverAddress = environmentVariables.getProperty("server");

                if (accessKey == null) {
                    accessKey = environmentVariables.getProperty("key");
                }

                ChromeDriverService service;

                try {

                    setupChromeDriverBinary();
                    service = new ChromeDriverService.Builder()
                            .usingAnyFreePort()
                            .build();
                    service.start();
                    dc.setCapability(CapabilityType.BROWSER_VERSION, "97");
                    dc.setCapability(ChromeOptions.CAPABILITY, getChromeOptions());
                    dc.setCapability("testName", "Test Name");
                    dc.setCapability("accessKey", accessKey);

                    driver = new RemoteWebDriver(new URL(serverAddress), dc);


                } catch (Exception e) {
                    logger.error("Error due to " + e.getMessage());
                    throw new UnreachableBrowserException(e.getMessage());
                }
                return driver;
            }



        private void setupChromeDriverBinary() {

            try {
                if (SystemUtils.IS_OS_MAC || SystemUtils.IS_OS_WINDOWS || SystemUtils.IS_OS_LINUX) {

                    logger.info("driver binary setup started...");
                    CountDownLatch latch = new CountDownLatch(1);
                    WebDriverManager.chromedriver().clearDriverCache();
                    ChromeDriverManager.getInstance(DriverManagerType.CHROME).driverVersion("97.0.4692.71").setup();
                    WebDriverManager.chromedriver().driverVersion("97.0.4692.71").setup();
                    latch.countDown();
                    latch.await();
                } else {
                    System.getenv();
                }

            } catch (Exception e) {
                logger.info("Driver binary not setup correctly...");
                e.printStackTrace();
            }
        }



        @Override
        public boolean takesScreenshots() {
            return true;
        }


}

```

**Comment by vishnu93tr** [comment]
even I am facing this issue while launching chrome browser

 WebDriverManager.firefoxdriver().clearDriverCache().setup();
  WebDriver driver=new FirefoxDriver();

stack trace:
USAGE:
    geckodriver --port <PORT>

For more information try --help


org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.

	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:585)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:248)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:164)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:118)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:106)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:86)
	at org.selenium.pom.factory.DriverManager.initializeDriver(DriverManager.java:12)
	at org.selenium.pom.Base.BaseTest.startDriver(BaseTest.java:13)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:65)
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:381)
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:319)
	at org.testng.internal.invokers.TestInvoker.runConfigMethods(TestInvoker.java:803)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:589)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.testng.TestRunner.privateRun(TestRunner.java:808)
	at org.testng.TestRunner.run(TestRunner.java:603)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
	at org.testng.SuiteRunner.run(SuiteRunner.java:326)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.runSuites(TestNG.java:1092)
	at org.testng.TestNG.run(TestNG.java:1060)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
Caused by: org.openqa.selenium.WebDriverException: Driver server process died prematurely.
Build info: version: '4.1.4', revision: '535d840ee2'
System info: host: 'ET-C02T91MYG8WN.local', ip: '192.168.0.106', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '11.6', java.version: '18.0.1.1'
Driver info: driver.version: FirefoxDriver
	at org.openqa.selenium.remote.service.DriverService.start(DriverService.java:226)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:98)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:567)
	... 36 more

**Comment by bonigarcia** [comment]
This is not a issue of WebDriverManager, it seems caused by Firefox or geckodriver.
