### ISSUE TITLE
Error when using Edge Driver

### ISSUE THREAD

**Issue by beniamin-kis** [bonigarcia/webdrivermanager#82]
When using EdgeDriverManager.getInstance().setup(); I get this error:

java.lang.NoSuchMethodError: org.jsoup.Connection.proxy(Ljava/net/Proxy;)Lorg/jsoup/Connection;
	at io.github.bonigarcia.wdm.EdgeDriverManager.getDrivers(EdgeDriverManager.java:59)
	at io.github.bonigarcia.wdm.BrowserManager.manage(BrowserManager.java:221)
	at io.github.bonigarcia.wdm.BrowserManager.setup(BrowserManager.java:108)
	at io.github.bonigarcia.wdm.BrowserManager.setup(BrowserManager.java:87)

It works fine for ChromeDriver, InternetExplorerDriver, OperaDriver, FirefoxDriver.

**Comment by bonigarcia** [comment]
WebDriverManager uses **jsoup** internally:

```
<jsoup.version>1.9.2</jsoup.version>

<dependency>
	<groupId>org.jsoup</groupId>
	<artifactId>jsoup</artifactId>
	<version>${jsoup.version}</version>
</dependency>
```

It seems that you are using a different version in your project and this causing that problem.
