### ISSUE TITLE
[error] Unable to install 'edge' where the rest of browsers is able

### ISSUE THREAD

**Issue by naturalDev0** [bonigarcia/webdrivermanager#835]
**Description of the problem**: 
* Unable to install 'edge' webdriver into the list.

**Browser and version**: 

* N.A

**Operating system**: 

* Windows 10 Pro | OS build 19044.1706 | Version 21H2

**WebDriverManager version**: 

* 0.10.0

**WebDriverManager call**: 

* N.A

**WebDriverManager traces**: 

* N.A

**Error log**: 

```
(virtualenv) PS C:\Users\User\Tommy Devground\Training_ROBOTFRAME> webdrivermanager.exe --os win edge 
Downloading WebDriver for browser: "edge"
Traceback (most recent call last):
  File "C:\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\User\Tommy Devground\Training_ROBOTFRAME\env4Robot\Scripts\webdrivermanager.exe\__main__.py", line 7, in <module>
  File "C:\Users\User\Tommy Devground\Training_ROBOTFRAME\env4Robot\lib\site-packages\webdrivermanager\__main__.py", line 81, in main
    extracted_binary, link = downloader.download_and_install(version)
  File "C:\Users\User\Tommy Devground\Training_ROBOTFRAME\env4Robot\lib\site-packages\webdrivermanager\base.py", line 271, in download_and_install
    filename_with_path = self.download(version, show_progress_bar=show_progress_bar)
  File "C:\Users\User\Tommy Devground\Training_ROBOTFRAME\env4Robot\lib\site-packages\webdrivermanager\base.py", line 229, in download
  File "C:\Users\User\Tommy Devground\Training_ROBOTFRAME\env4Robot\lib\site-packages\webdrivermanager\edge.py", line 24, in get_download_path
    return self.download_root / "edge" / version
TypeError: unsupported operand type(s) for /: 'WindowsPath' and 'NoneType'
```

**Comment by naturalDev0** [comment]
@bonigarcia pardon me for the mistook. Happened to observed wrongly.
