### ISSUE TITLE
Latest image of selenoid/vnc:chrome is not getting pulled when using browserInDocker()

### ISSUE THREAD

**Issue by adumitreseibogdan** [bonigarcia/webdrivermanager#853]
**Description of the problem**:  Can't pull latest version of Chrome in Docker Hub

**Browser and version**: Chrome 102

**Operating system**:  Windows 10, 64 bits

**WebDriverManager version**: 5.2.0

**WebDriverManager call**: `WebDriverManager.chromedriver().browserInDocker().create()`

**WebDriverManager traces**: 
```
[INFO] Running TestRunner
..2022-06-15 14:10:38 [main] DEBUG i.g.b.wdm.cache.ResolutionCache.<init>(77) - Created new resolution cache file at /root/.cache/selenium/resolution.properties
2022-06-15 14:10:38 [main] DEBUG i.g.b.wdm.docker.DockerHubService.listTags(60) - Getting browser image list from Docker Hub
2022-06-15 14:10:38 [main] TRACE i.g.b.wdm.docker.DockerHubService.listTags(73) - Sending request to https://hub.docker.com/v2/repositories/selenoid/vnc/tags?page=1&page_size=1024
2022-06-15 14:10:39 [main] TRACE i.g.b.wdm.docker.DockerHubService.listTags(73) - Sending request to https://hub.docker.com/v2/repositories/selenoid/vnc/tags?page=2&page_size=1024
2022-06-15 14:10:40 [main] TRACE i.g.b.wdm.docker.DockerHubService.listTags(73) - Sending request to https://hub.docker.com/v2/repositories/selenoid/vnc/tags?page=3&page_size=1024
2022-06-15 14:10:40 [main] DEBUG i.g.b.wdm.docker.DockerService.getImageVersionFromDockerHub(440) - The latest version of Chrome in Docker Hub is 102.0
2022-06-15 14:10:40 [main] TRACE i.g.b.wdm.docker.DockerService.getDockerImage(486) - Docker image: selenoid/vnc:chrome_102.0
2022-06-15 14:10:40 [main] INFO  i.g.b.wdm.docker.DockerService.pullImageIfNecessary(299) - Pulling Docker image selenoid/vnc:chrome_102.0 (this might take some time, but only the first time)
2022-06-15 14:10:40 [docker-java-stream--2081338138] ERROR c.g.d.a.async.ResultCallbackTemplate.onError(52) - Error during callback
java.lang.RuntimeException: java.io.IOException: com.sun.jna.LastErrorException: [2] No such file or directory
        at com.github.dockerjava.httpclient5.ApacheDockerHttpClientImpl.execute(ApacheDockerHttpClientImpl.java:195)
        at com.github.dockerjava.httpclient5.ApacheDockerHttpClient.execute(ApacheDockerHttpClient.java:9)
        at com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:228)
        at com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.io.IOException: com.sun.jna.LastErrorException: [2] No such file or directory
        at com.github.dockerjava.transport.DomainSocket.<init>(DomainSocket.java:63)
        at com.github.dockerjava.transport.LinuxDomainSocket.<init>(LinuxDomainSocket.java:41)
        at com.github.dockerjava.transport.DomainSocket.get(DomainSocket.java:140)
        at com.github.dockerjava.transport.UnixSocket.get(UnixSocket.java:29)
        at com.github.dockerjava.httpclient5.ApacheDockerHttpClientImpl$2.createSocket(ApacheDockerHttpClientImpl.java:153)
        at org.apache.hc.client5.http.impl.io.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:125)
        at org.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:396)
        at org.apache.hc.client5.http.impl.classic.InternalExecRuntime.connectEndpoint(InternalExecRuntime.java:158)
        at org.apache.hc.client5.http.impl.classic.InternalExecRuntime.connectEndpoint(InternalExecRuntime.java:168)
        at org.apache.hc.client5.http.impl.classic.ConnectExec.execute(ConnectExec.java:136)
        at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
        at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
        at org.apache.hc.client5.http.impl.classic.ProtocolExec.execute(ProtocolExec.java:175)
        at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
        at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
        at org.apache.hc.client5.http.impl.classic.HttpRequestRetryExec.execute(HttpRequestRetryExec.java:96)
        at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
        at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
        at org.apache.hc.client5.http.impl.classic.ContentCompressionExec.execute(ContentCompressionExec.java:133)
        at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
        at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
        at org.apache.hc.client5.http.impl.classic.RedirectExec.execute(RedirectExec.java:115)
        at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
        at org.apache.hc.client5.http.impl.classic.InternalHttpClient.doExecute(InternalHttpClient.java:170)
        at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:67)
        at com.github.dockerjava.httpclient5.ApacheDockerHttpClientImpl.execute(ApacheDockerHttpClientImpl.java:191)
        ... 4 common frames omitted
```

**Comment by adumitreseibogdan** [comment]
Randomly it started working again, no idea what was the issue.
