### ISSUE TITLE
Provide possibility to disable Selenium OpenTracing on RemoteWebDriver

### ISSUE THREAD

**Issue by ctroller** [bonigarcia/webdrivermanager#871]
**Description of the problem**
Selenium's `RemoteWebDriver` allows to specify if it should use opentelemetry's tracing capabilities. This can lead to NoSuchMethodError, if you don't include the opentelemetry lib as a dependency, or have a JAR clash (in my case)

Per default, with webdrivermanager's current implementation at https://github.com/bonigarcia/webdrivermanager/blob/5efe3447a99834a3683463b137308127491e0018/src/main/java/io/github/bonigarcia/wdm/webdriver/WebDriverCreator.java#L89, you always set this to 'enabled', as this is Selenium's default as well (questionable as to why, but i'm not judging).

A preferred solution would be to make this configurable at the driver DSL creation, with e.g. an `.tracing()` call or `.tracing(false)` to be backwards compatible.

**Browser and version**: 
Any Remote based driver

**Operating system**:
Any

**WebDriverManager version**:
5.2.1 and onwards

**WebDriverManager call**: 
`WebDriverManager.chromedriver().remoteAddress( hubAddress ).create()`

**WebDriverManager traces**: 
Irrelevant in my opinion

**Error log**: 
```
java.lang.NoSuchMethodError: 'io.opentelemetry.sdk.autoconfigure.spi.ConfigProperties io.opentelemetry.sdk.autoconfigure.DefaultConfigProperties.get()'
	at io.opentelemetry.sdk.autoconfigure.OpenTelemetrySdkAutoConfiguration.initialize(OpenTelemetrySdkAutoConfiguration.java:45)
	at io.opentelemetry.sdk.autoconfigure.OpenTelemetrySdkAutoConfiguration.initialize(OpenTelemetrySdkAutoConfiguration.java:34)
	at org.openqa.selenium.remote.tracing.opentelemetry.OpenTelemetryTracer.createTracer(OpenTelemetryTracer.java:77)
	at org.openqa.selenium.remote.tracing.opentelemetry.OpenTelemetryTracer.getInstance(OpenTelemetryTracer.java:59)
	at org.openqa.selenium.remote.RemoteWebDriver.createTracedExecutorWithTracedHttpClient(RemoteWebDriver.java:151)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:146)
	at io.github.bonigarcia.wdm.webdriver.WebDriverCreator.createRemoteWebDriver(WebDriverCreator.java:89)
	at io.github.bonigarcia.wdm.WebDriverManager.instantiateDriver(WebDriverManager.java:1742)
	at io.github.bonigarcia.wdm.WebDriverManager.create(WebDriverManager.java:422)
```

**Comment by asolntsev** [comment]
@bonigarcia I think you don't need to avoid NoSuchMethodError. Who wants telemetry - needs to add opentelemetry lib. As simple as that.

**Comment by ctroller** [comment]
NoSuchMethodError is due to a JAR Clash (I had a separate dependency on selenium, which was not compliant with the bundled one of WebDriverManager), but this has now been resolved from my side.

Thanks for the quick response, appreciate it.
