### ISSUE TITLE
Webdrivermanage edgedriver giving error with io.github.bonigarcia.wdm.config.WebDriverManagerException: java.net.SocketException: Connection reset in java

### ISSUE THREAD

**Issue by sharathhatter1** [bonigarcia/webdrivermanager#890]
When running the testcase for the edge browser on jenkins getting io.github.bonigarcia.wdm.config.WebDriverManagerException: java.net.SocketException: Connection reset

But when running locally, It executes perfectly fine

Using WDM - implementation 'io.github.bonigarcia:webdrivermanager:5.2.0'

**Operating system**:windows

**WebDriverManager version**:5.2.0
**WebDriverManager call**: 
 EdgeOptions edgeOptions = new EdgeOptions();
                //edgeOptions.addArguments("--headless");
                //edgeOptions.addArguments("--no-sandbox");
                //edgeOptions.addArguments("--disable-dev-shm-usage");
                //edgeOptions.addArguments("--remote-debugging-port=9222");
//                edgeOptions.addArguments("--width=1440");
//                edgeOptions.addArguments("--height=900");
                //edgeOptions.addArguments("--window-size=1440,900");
                WebDriverManager.edgedriver().setup();
                driver = new EdgeDriver(edgeOptions);

**WebDriverManager traces**: 
  io.github.bonigarcia.wdm.config.WebDriverManagerException: io.github.bonigarcia.wdm.config.WebDriverManagerException: java.net.SocketException: Connection reset
        at app//io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:1381)
        at app//io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:1164)
        at app//io.github.bonigarcia.wdm.WebDriverManager.fallback(WebDriverManager.java:1397)
        at app//io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:1378)
        at app//io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:1164)
        at app//io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:1371)
        at app//io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:1164)
        at app//io.github.bonigarcia.wdm.WebDriverManager.setup(WebDriverManager.java:406)
        at app//web.factory.DriverFactory.initDriver(DriverFactory.java:119)
        at app//web.factory.DriverFactory.getDriver(DriverFactory.java:39)
        at app//web.base.BaseTest.launchBrowserAndOpenUrl(BaseTest.java:71)
        at app//web.tests.smoke.NewsTests.setupBeforeMethod(NewsTests.java:39)

        Caused by:
        io.github.bonigarcia.wdm.config.WebDriverManagerException: java.net.SocketException: Connection reset
            at app//io.github.bonigarcia.wdm.WebDriverManager.getDriversFromXml(WebDriverManager.java:1528)
            at app//io.github.bonigarcia.wdm.managers.EdgeDriverManager.getDriverUrls(EdgeDriverManager.java:113)
            at app//io.github.bonigarcia.wdm.WebDriverManager.createUrlHandler(WebDriverManager.java:1402)
            at app//io.github.bonigarcia.wdm.WebDriverManager.download(WebDriverManager.java:1240)
            at app//io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:1158)
            ... 10 more

            Caused by:
            java.net.SocketException: Connection reset
                at java.base/java.net.SocketInputStream.read(SocketInputStream.java:186)
                at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
                at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:478)
                at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:472)
                at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:160)
                at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:111)
                at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1506)
                at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1416)
                at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:456)
                at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:427)
                at org.apache.hc.client5.http.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:273)
                at org.apache.hc.client5.http.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:241)
                at org.apache.hc.client5.http.impl.io.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:148)
                at org.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:396)
                at org.apache.hc.client5.http.impl.classic.InternalExecRuntime.connectEndpoint(InternalExecRuntime.java:158)
                at org.apache.hc.client5.http.impl.classic.InternalExecRuntime.connectEndpoint(InternalExecRuntime.java:168)
                at org.apache.hc.client5.http.impl.classic.ConnectExec.execute(ConnectExec.java:136)
                at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
                at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
                at org.apache.hc.client5.http.impl.classic.ProtocolExec.execute(ProtocolExec.java:175)
                at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
                at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
                at org.apache.hc.client5.http.impl.classic.HttpRequestRetryExec.execute(HttpRequestRetryExec.java:96)
                at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
                at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
                at org.apache.hc.client5.http.impl.classic.ContentCompressionExec.execute(ContentCompressionExec.java:133)
                at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
                at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
                at org.apache.hc.client5.http.impl.classic.RedirectExec.execute(RedirectExec.java:115)
                at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
                at org.apache.hc.client5.http.impl.classic.InternalHttpClient.doExecute(InternalHttpClient.java:170)
                at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:75)
                at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:89)
                at io.github.bonigarcia.wdm.online.HttpClient.execute(HttpClient.java:158)
                at io.github.bonigarcia.wdm.WebDriverManager.getDriversFromXml(WebDriverManager.java:1513)
                ... 14 more

**Comment by bonigarcia** [comment]
It seems it is a connectivity issue in your CI server. Is it behind a proxy? If so, maybe you need to set it up correctly (see `proxy()` method in the [doc](https://bonigarcia.dev/webdrivermanager/)).
