### ISSUE TITLE
io.github.bonigarcia.wdm.config.WebDriverManagerException: io.github.bonigarcia.wdm.config.WebDriverManagerException: No proper candidate URL to download geckodriver 0.31.0

### ISSUE THREAD

**Issue by pduyet** [bonigarcia/webdrivermanager#893]
**Description of the problem**: io.github.bonigarcia.wdm.config.WebDriverManagerException: No proper candidate URL to download geckodriver 0.31.0

**Browser and version**: _**Firefox 104.0 (64-bit)**_

**Operating system**: **ubuntu 18.04 arm**

**WebDriverManager version**: 5.2.2

**WebDriverManager call**: WebDriverManager.firefoxdriver().setup();

**WebDriverManager traces**: io.github.bonigarcia.wdm.config.WebDriverManagerException: io.github.bonigarcia.wdm.config.WebDriverManagerException: No proper candidate URL to download geckodriver 0.31.0
	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:1412)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:1195)
	at io.github.bonigarcia.wdm.WebDriverManager.fallback(WebDriverManager.java:1428)
	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:1405)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:1195)
	at io.github.bonigarcia.wdm.WebDriverManager.setup(WebDriverManager.java:416)
	at base.BaseTest.setUp(BaseTest.java:43)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:361)
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:296)
	at org.testng.internal.invokers.TestInvoker.runConfigMethods(TestInvoker.java:816)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:590)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.testng.TestRunner.privateRun(TestRunner.java:806)
	at org.testng.TestRunner.run(TestRunner.java:601)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
	at org.testng.SuiteRunner.run(SuiteRunner.java:330)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
	at org.testng.TestNG.runSuites(TestNG.java:1099)
	at org.testng.TestNG.run(TestNG.java:1067)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:151)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:111)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:98)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
Caused by: io.github.bonigarcia.wdm.config.WebDriverManagerException: No proper candidate URL to download geckodriver 0.31.0
	at io.github.bonigarcia.wdm.online.UrlHandler.getCandidateUrl(UrlHandler.java:287)
	at io.github.bonigarcia.wdm.WebDriverManager.download(WebDriverManager.java:1272)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:1189)
	... 42 more
Hi, I'm getting error in my project. It doesn't happen on windows but it happens on ubuntu. Could you please fix this and, more importantly, offer a solution because to the blocking issue?

**Comment by bonigarcia** [comment]
I would use the latest version of WebDriverManager (5.3.0 at the time of this writing).

Also, it seems there is no geckodriver for Linux ARM (see its [repo](https://github.com/mozilla/geckodriver/releases)). I think it is failing for that reason. You can try this to force using the _linux64_ version (although I don't know if it is going to work in your computer):

```
WebDriverManager.firefoxdriver().arch64().setup();
```
