### ISSUE TITLE
Ability to run WebDriverManager from inside a container with browserInDocker (feature request)

### ISSUE THREAD

**Issue by uterator** [bonigarcia/webdrivermanager#924]
This is a feature request.

Please add a config method (can be driverInDocker()) for cases when the WebDriverManager is run in a container and the browser is run in another container by using browserInDocker(). 

In that case the WebDriverManager should also handle the proper connection between 2 containers: the one is where the WebDriver session starts, and the other is where the browser starts.

**Description of the problem**
When we configure the WebDriverManager to start the browserInDocker and we run the WebDriverManager from a container - the WebDriver session fails with "Connection refused" to connect to the browser.

The steps are following: 
1. Run a test with WebDriverManager and `browserInDocker` from some container in bridge network.
2. The browser will start in another container as expected (let's call it second container)
3. From the first container the WebDriver session tries to connect to the browser server in the second container by `http://localhost:51349/wd/hub` address, but that is not accessible there. As both containers are in the same network, from the first container the correct address is `http://172.17.0.3:4444/wd/hub`, but WebDriverManager doesn't use it as it doesn't know that it was run in a container.
4. Also, when the `browserInDocker` is set, the `RemoteAddress` has no effect, in case if we want to find the second container's IP and somehow set it to the WebDriverManager _before_ we call create().

**WebDriverManager version**: 5.3

**WebDriverManager call**
Running this command from a container

        WebDriverManager.firefoxdriver().browserInDocker().create();

**WebDriverManager traces**:
```
DEBUG org.apache.hc.client5.http.wire - http-outgoing-3 << "[\r][\n]"
16:07:42.661 [com.example.HelloWorld.main()] DEBUG o.a.h.c.h.i.c.InternalHttpClient - ep-0000000008 releasing valid endpoint
16:07:42.662 [com.example.HelloWorld.main()] DEBUG o.a.h.c.h.i.i.PoolingHttpClientConnectionManager - ep-0000000008 releasing endpoint
16:07:42.662 [com.example.HelloWorld.main()] DEBUG o.a.h.c.h.i.i.PoolingHttpClientConnectionManager - ep-0000000008 connection http-outgoing-3 can be kept alive for 3 MINUTES
16:07:42.663 [com.example.HelloWorld.main()] DEBUG o.a.h.c.h.i.i.PoolingHttpClientConnectionManager - ep-0000000008 connection released [route: {}->unix://localhost:2375][total available: 1; route allocated: 1 of 2147483647; total allocated: 1 of 2147483647]
16:07:42.663 [com.example.HelloWorld.main()] TRACE i.g.b.wdm.docker.DockerService - Browser remote URL http://localhost:51349/wd/hub
16:07:42.669 [com.example.HelloWorld.main()] TRACE i.g.bonigarcia.wdm.WebDriverManager - The Selenium Serverl URL is http://localhost:51349/wd/hub
16:07:42.697 [com.example.HelloWorld.main()] DEBUG i.g.b.wdm.webdriver.WebDriverCreator - Creating WebDriver object for firefox at http://localhost:51349/wd/hub with Capabilities {acceptInsecureCerts: true, browserName: firefox, moz:debuggerAddress: true, moz:firefoxOptions: {}}
16:07:42.706 [com.example.HelloWorld.main()] TRACE i.g.b.wdm.webdriver.WebDriverCreator - ConnectException creating WebDriver object (Connection refused (Connection refused))
...
...
...
16:08:11.768 [com.example.HelloWorld.main()] TRACE i.g.b.wdm.webdriver.WebDriverCreator - ConnectException creating WebDriver object (Connection refused (Connection refused))
16:08:12.770 [com.example.HelloWorld.main()] TRACE i.g.b.wdm.webdriver.WebDriverCreator - ConnectException creating WebDriver object (Connection refused (Connection refused))
[WARNING] 
io.github.bonigarcia.wdm.config.WebDriverManagerException: There was an error creating WebDriver object for Firefox
    at io.github.bonigarcia.wdm.WebDriverManager.instantiateDriver (WebDriverManager.java:1774)
    at io.github.bonigarcia.wdm.WebDriverManager.create (WebDriverManager.java:424)
    at com.example.HelloWorld.main (HelloWorld.java:29)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run (ExecJavaMojo.java:279)
    at java.lang.Thread.run (Thread.java:834)
Caused by: io.github.bonigarcia.wdm.config.WebDriverManagerException: Timeout of 30 seconds creating WebDriver object
    at io.github.bonigarcia.wdm.webdriver.WebDriverCreator.createRemoteWebDriver (WebDriverCreator.java:95)
    at io.github.bonigarcia.wdm.WebDriverManager.createDockerWebDriver (WebDriverManager.java:1896)
    at io.github.bonigarcia.wdm.WebDriverManager.instantiateDriver (WebDriverManager.java:1754)
    at io.github.bonigarcia.wdm.WebDriverManager.create (WebDriverManager.java:424)
    at com.example.HelloWorld.main (HelloWorld.java:29)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run (ExecJavaMojo.java:279)
    at java.lang.Thread.run (Thread.java:834)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
    at java.net.PlainSocketImpl.socketConnect (Native Method)
    at java.net.AbstractPlainSocketImpl.doConnect (AbstractPlainSocketImpl.java:399)
    at java.net.AbstractPlainSocketImpl.connectToAddress (AbstractPlainSocketImpl.java:242)
    at java.net.AbstractPlainSocketImpl.connect (AbstractPlainSocketImpl.java:224)
    at java.net.Socket.connect (Socket.java:609)
    at java.net.Socket.connect (Socket.java:558)
    at sun.net.NetworkClient.doConnect (NetworkClient.java:182)
    at sun.net.www.http.HttpClient.openServer (HttpClient.java:474)
    at sun.net.www.http.HttpClient.openServer (HttpClient.java:569)
    at sun.net.www.http.HttpClient.<init> (HttpClient.java:242)
    at sun.net.www.http.HttpClient.New (HttpClient.java:341)
    at sun.net.www.http.HttpClient.New (HttpClient.java:362)
    at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient (HttpURLConnection.java:1253)
    at sun.net.www.protocol.http.HttpURLConnection.plainConnect0 (HttpURLConnection.java:1187)
    at sun.net.www.protocol.http.HttpURLConnection.plainConnect (HttpURLConnection.java:1081)
    at sun.net.www.protocol.http.HttpURLConnection.connect (HttpURLConnection.java:1015)
    at io.github.bonigarcia.wdm.webdriver.WebDriverCreator.createRemoteWebDriver (WebDriverCreator.java:84)
    at io.github.bonigarcia.wdm.WebDriverManager.createDockerWebDriver (WebDriverManager.java:1896)
    at io.github.bonigarcia.wdm.WebDriverManager.instantiateDriver (WebDriverManager.java:1754)
    at io.github.bonigarcia.wdm.WebDriverManager.create (WebDriverManager.java:424)
    at com.example.HelloWorld.main (HelloWorld.java:29)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run (ExecJavaMojo.java:279)
    at java.lang.Thread.run (Thread.java:834)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  48.989 s
[INFO] Finished at: 2022-10-18T16:08:12-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:3.1.0:java (default-cli) on project slf4j-logback: An exception occurred while executing the Java class. There was an error creating WebDriver object for Firefox: Timeout of 30 seconds creating WebDriver object: Connection refused (Connection refused) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

```

**Error log**: 
```
There was an error creating WebDriver object for Firefox

io.github.bonigarcia.wdm.config.WebDriverManagerException: There was an error creating WebDriver object for Firefox
    at io.github.bonigarcia.wdm.WebDriverManager.instantiateDriver(WebDriverManager.java:1774)
    at io.github.bonigarcia.wdm.WebDriverManager.create(WebDriverManager.java:424)
Caused by: io.github.bonigarcia.wdm.config.WebDriverManagerException: Timeout of 30 seconds creating WebDriver object
    at io.github.bonigarcia.wdm.webdriver.WebDriverCreator.createRemoteWebDriver(WebDriverCreator.java:95)
    at io.github.bonigarcia.wdm.WebDriverManager.createDockerWebDriver(WebDriverManager.java:1896)
    at io.github.bonigarcia.wdm.WebDriverManager.instantiateDriver(WebDriverManager.java:1754)
    ... 32 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
    at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
    at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
    at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
    at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
    at java.base/java.net.Socket.connect(Socket.java:609)
    at java.base/java.net.Socket.connect(Socket.java:558)
    at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:182)
    at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
    at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
    at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
    at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:341)
    at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:362)
    at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1253)
    at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187)
    at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
    at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1015)
    at io.github.bonigarcia.wdm.webdriver.WebDriverCreator.createRemoteWebDriver(WebDriverCreator.java:84)
    ... 34 more
```

**Comment by bonigarcia** [comment]
Please consider creating a PR for this.
