### ISSUE TITLE
Latest patch version 5.3.1 breaks Spring Boot compatibility

### ISSUE THREAD

**Issue by MediaMarco** [bonigarcia/webdrivermanager#938]
**Description of the problem**:

I use webdrivermanager within a Spring Boot project. The latest upgrade from 5.3.0 to 5.3.1 contains an update from slf4j 1.x to slf4j 2.x, which currently isn't compatible with Spring Boot. Spring Boot 3.x may fix this, but that's not released so far.
Depending on the setup and code, either an Exception or no logging at all are the results.

This dependency should not be part of a patch version, because it's breaking things.

A temporary fix for me is to exclude the transitive slf4j dependency from webdrivermanager like this:

    api("io.github.bonigarcia:webdrivermanager:5.3.1") {
      exclude group: "org.slf4j"
    }

**Browser and version**: all

**Operating system**: all

**WebDriverManager version**: 5.3.1

**WebDriverManager call**: Does not matter, including webdrivermanager dependency in gradle is sufficient.

**Error log**:
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
SLF4J: Class path contains SLF4J bindings targeting slf4j-api versions 1.7.x or earlier.
SLF4J: Ignoring binding found at [jar:file:/Users/MediaMarco/.gradle/caches/modules-2/files-2.1/ch.qos.logback/logback-classic/1.2.11/4741689214e9d1e8408b206506cbe76d1c6a7d60/logback-classic-1.2.11.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See https://www.slf4j.org/codes.html#ignoredBindings for an explanation.

or

java.lang.NoClassDefFoundError: org/slf4j/impl/StaticLoggerBinder
    at org.springframework.boot.logging.logback.LogbackLoggingSystem.getLoggerContext(LogbackLoggingSystem.java:273)
    at org.springframework.boot.logging.logback.LogbackLoggingSystem.beforeInitialize(LogbackLoggingSystem.java:99)
    at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationStartingEvent(LoggingApplicationListener.java:191)
    at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationEvent(LoggingApplicationListener.java:170)
    at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
    at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
    at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
    at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:127)
    at org.springframework.boot.context.event.EventPublishingRunListener.starting(EventPublishingRunListener.java:68)
    at org.springframework.boot.SpringApplicationRunListeners.starting(SpringApplicationRunListeners.java:48)
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:313)

**Comment by hetacz** [comment]
check mine: https://github.com/bonigarcia/webdrivermanager/issues/945 no spring, but also can't find SLF4J

**Comment by bonigarcia** [comment]
The latest versions of WebDriverManager uses the latest version of SLF4J, i.e., 2.x.x. Until it is used in Spring Boot as well, I'm afraid your workaround will do.
