### ISSUE TITLE
Issue: Chrome webdriver crashes in-between execution of when accessed browserInDocker() functionality

### ISSUE THREAD

**Issue by sandeepraina-lenze** [bonigarcia/webdrivermanager#952]
Hello,

I am continuously getting the following error when trying run my tests on Chrome browser by using the browseInDocker() functionality.

Please note the execution of the tests start but in between it stops automatically.

```
[INFO]
[INFO] Results:
[INFO]
[ERROR] Errors:
[ERROR]   Error communicating with the remote browser. It may have died.
Build info: version: '4.6.0', revision: '79f1c02ae20'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.2'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Command: [424233dc3e21227a8408f6983430cf75, getCurrentWindowHandle {}]
Capabilities {acceptInsecureCerts: true, browserName: chrome, browserVersion: 108.0.5359.94, chrome: {chromedriverVersion: 108.0.5359.71 (1e0e3868ee06..., userDataDir: /tmp/.com.google.Chrome.HfCTjV}, goog:chromeOptions: {debuggerAddress: localhost:38379}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: LINUX, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 15000, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: 424233dc3e21227a8408f6983430cf75
[ERROR]   StoreTestSuite » UnreachableBrowser Error communicating with the remote browser. It may have died.
Build info: version: '4.6.0', revision: '79f1c02ae20'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.2'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Command: [424233dc3e21227a8408f6983430cf75, quit {}]
Capabilities {acceptInsecureCerts: true, browserName: chrome, browserVersion: 108.0.5359.94, chrome: {chromedriverVersion: 108.0.5359.71 (1e0e3868ee06..., userDataDir: /tmp/.com.google.Chrome.HfCTjV}, goog:chromeOptions: {debuggerAddress: localhost:38379}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: LINUX, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 15000, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: 424233dc3e21227a8408f6983430cf75
[INFO]
[ERROR] Tests run: 4, Failures: 0, Errors: 2, Skipped: 0
[INFO]
[INFO] 
```

```
[ERROR] org.qa.functional.StoreTestSuite  Time elapsed: 131.425 s  <<< ERROR!
org.openqa.selenium.remote.UnreachableBrowserException:
Error communicating with the remote browser. It may have died.
Build info: version: '4.6.0', revision: '79f1c02ae20'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.2'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Command: [424233dc3e21227a8408f6983430cf75, quit {}]
Capabilities {acceptInsecureCerts: true, browserName: chrome, browserVersion: 108.0.5359.94, chrome: {chromedriverVersion: 108.0.5359.71 (1e0e3868ee06..., userDataDir: /tmp/.com.google.Chrome.HfCTjV}, goog:chromeOptions: {debuggerAddress: localhost:38379}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: LINUX, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 15000, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: 424233dc3e21227a8408f6983430cf75
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:565)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:596)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:600)
        at org.openqa.selenium.remote.RemoteWebDriver.quit(RemoteWebDriver.java:443)
        at net.thucydides.core.webdriver.WebdriverInstances.closeAndQuit(WebdriverInstances.java:78)
        at net.thucydides.core.webdriver.WebdriverInstances.closeCurrentDriver(WebdriverInstances.java:69)
        at net.thucydides.core.webdriver.WebdriverInstances.closeCurrentDrivers(WebdriverInstances.java:118)
        at net.thucydides.core.webdriver.SerenityWebdriverManager.closeCurrentDrivers(SerenityWebdriverManager.java:86)
        at net.thucydides.core.webdriver.ThucydidesWebDriverSupport.closeCurrentDrivers(ThucydidesWebDriverSupport.java:163)
        at net.thucydides.core.webdriver.WebdriverCloseBrowser.closeIfConfiguredForANew(WebdriverCloseBrowser.java:36)
        at net.thucydides.core.steps.BaseStepListener.testSuiteFinished(BaseStepListener.java:480)
        at net.thucydides.core.steps.StepEventBus.testSuiteFinished(StepEventBus.java:706)
        at io.cucumber.core.plugin.SerenityReporter.cleanupTestResourcesForURI(SerenityReporter.java:814)
        at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:807)
        at java.base/java.util.concurrent.CopyOnWriteArraySet.forEach(CopyOnWriteArraySet.java:425)
        at io.cucumber.core.plugin.SerenityReporter.assureTestSuiteFinished(SerenityReporter.java:804)
        at io.cucumber.core.plugin.SerenityReporter.handleTestRunFinished(SerenityReporter.java:378)
        at io.cucumber.core.eventbus.AbstractEventPublisher.send(AbstractEventPublisher.java:51)
        at io.cucumber.core.eventbus.AbstractEventBus.send(AbstractEventBus.java:12)
        at io.cucumber.core.runtime.SynchronizedEventBus.send(SynchronizedEventBus.java:47)
        at io.cucumber.core.runtime.CucumberExecutionContext.emitTestRunFinished(CucumberExecutionContext.java:111)
        at io.cucumber.core.runtime.CucumberExecutionContext.finishTestRun(CucumberExecutionContext.java:98)
        at io.cucumber.junit.CucumberSerenityRunner$RunCucumber.evaluate(CucumberSerenityRunner.java:291)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
        at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
        at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
        at org.junit.vintage.engine.execution.RunnerExecutor.execute(RunnerExecutor.java:42)
        at org.junit.vintage.engine.VintageTestEngine.executeAllChildren(VintageTestEngine.java:80)
        at org.junit.vintage.engine.VintageTestEngine.execute(VintageTestEngine.java:72)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:147)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:127)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:90)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:55)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:102)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:54)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
        at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
        at org.apache.maven.surefire.junitplatform.LazyLauncher.execute(LazyLauncher.java:55)
        at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.execute(JUnitPlatformProvider.java:223)
        at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:175)
        at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:139)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
        at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
Caused by: java.io.UncheckedIOException: org.asynchttpclient.exception.RemotelyClosedException: Remotely closed
        at org.openqa.selenium.remote.http.netty.NettyHttpHandler.makeCall(NettyHttpHandler.java:73)
        at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
        at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)
        at org.openqa.selenium.remote.http.netty.NettyHttpHandler.execute(NettyHttpHandler.java:49)
        at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
        at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)
        at org.openqa.selenium.remote.http.netty.NettyClient.execute(NettyClient.java:99)
        at org.openqa.selenium.remote.tracing.TracedHttpClient.execute(TracedHttpClient.java:55)
        at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:181)
        at org.openqa.selenium.remote.TracedCommandExecutor.execute(TracedCommandExecutor.java:51)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:541)
        ... 46 more
Caused by: org.asynchttpclient.exception.RemotelyClosedException: Remotely closed
        at org.asynchttpclient.exception.RemotelyClosedException.INSTANCE(Unknown Source)
```

Below listed is the code for the Chrome capabilities:

```
public class Chrome {
    public static ChromeOptions chromeOptions() {
        ChromeOptions chromeOptions = new ChromeOptions();

        chromeOptions.setAcceptInsecureCerts(true)
                .setHeadless(false)
                .setPageLoadTimeout(Duration.ofMinutes(5))
                .setImplicitWaitTimeout(Duration.ofSeconds(15))
                .setScriptTimeout(Duration.ofSeconds(30))
                .addArguments("--start-maximized")
                .addArguments("--test-type")
                .addArguments("--no-sandbox")
                .addArguments("--ignore-certificate-errors")
                .addArguments("--disable-popup-blocking")
                .addArguments("--disable-default-apps")
                .addArguments("--disable-extensions-file-access-check")
                .addArguments("--incognito")
                .addArguments("--disable-infobars")
                .addArguments("--disable-gpu")
                .addArguments("--user-agent=Apache")
                .addArguments("--disable-dev-shm-usage")
                .addArguments("--window-size=1920,1080")
                .addArguments("--enable-features=NetworkService");

        return chromeOptions;
    }
}
```

Code to initiate the webdriver

```
wdm = WebDriverManager.chromedriver().browserInDocker().browserVersion(System.getProperty("version")).capabilities(Chrome.chromeOptions()).clearDriverCache().clearResolutionCache();

wdm.create();
```

Please suggest how to proceed on this.

**Comment by bonigarcia** [comment]
I don't know the reason of the browser crash. Maybe you can start it without any extra arguments, and if it works, start adding one by one your arguments.
