### ISSUE TITLE
Connection reset on new chrome browser image versions

### ISSUE THREAD

**Issue by MariusDK** [bonigarcia/webdrivermanager#974]
Hello!

**Description of the problem**: 
```

We have the following configuration in our tests of browser in docker:
webDriverManager = chromedriver()
                .browserInDocker()
                .forceDownload()
                .arch64().linux()
                .browserVersion(driverProperties.getDocker().chromeImage());

DesiredCapabilities desiredCapabilities = new DesiredCapabilities();
desiredCapabilities.acceptInsecureCerts();
desiredCapabilities.setCapability(ACCEPT_INSECURE_CERTS, true);
webDriverManager.capabilities(desiredCapabilities);
List<WebDriver> webDriverList1 = webDriverManager.create(driverProperties.getDocker().count());
```

As you can see we take the chromeImage from a configuration file with value latest.
Until version 104(inclusive) all was working perfectly, but from version 105 we start to get Connection reset 

**Browser and version**: latest (105.0 -> latest)
**Operating system**: linux

**WebDriverManager version**: 5.3.1

**WebDriverManager call**: 
webDriverManager = chromedriver()
                .browserInDocker()
                .forceDownload()
                .arch64().linux()
                .browserVersion(driverProperties.getDocker().chromeImage());
DesiredCapabilities desiredCapabilities = new DesiredCapabilities();
desiredCapabilities.acceptInsecureCerts();
desiredCapabilities.setCapability(ACCEPT_INSECURE_CERTS, true);
webDriverManager.capabilities(desiredCapabilities);
List<WebDriver> webDriverList1 = webDriverManager.create(driverProperties.getDocker().count());

Here are the logs:

```
2023-01-09 17:14:09 DEBUG i.g.b.w.c.ResolutionCache:186 - Resolution chrome-container-latest=108.0 in cache (valid until 17:47:49 09/01/2023 UTC)
2023-01-09 17:14:09 INFO  i.g.b.w.d.DockerService:177 - Starting Docker container selenoid/vnc:chrome_108.0
2023-01-09 17:14:09 DEBUG i.g.b.w.w.WebDriverCreator:77 - Creating WebDriver object for chrome at http://localhost:49203/ with Capabilities {acceptInsecureCerts: true, browserName: chrome, goog:chromeOptions: {args: [--disable-gpu], extensions: []}}

Constructor threw exception; nested exception is io.github.bonigarcia.wdm.config.WebDriverManagerException: There was an error creating WebDriver object for Chrome
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:315)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:296)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1372)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1222)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:953)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
	at org.springframework.test.context.support.AbstractGenericContextLoader.loadContext(AbstractGenericContextLoader.java:127)
	at org.springframework.test.context.support.AbstractGenericContextLoader.loadContext(AbstractGenericContextLoader.java:60)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:99)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:124)
	... 43 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate : Constructor threw exception; nested exception is io.github.bonigarcia.wdm.config.WebDriverManagerException: There was an error creating WebDriver object for Chrome
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:224)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:117)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:311)
	... 59 common frames omitted
Caused by: io.github.bonigarcia.wdm.config.WebDriverManagerException: There was an error creating WebDriver object for Chrome
	at io.github.bonigarcia.wdm.WebDriverManager.instantiateDriver(WebDriverManager.java:1775)
	at io.github.bonigarcia.wdm.WebDriverManager.create(WebDriverManager.java:434)
	....................
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:211)
	... 61 common frames omitted
Caused by: io.github.bonigarcia.wdm.config.WebDriverManagerException: Timeout of 30 seconds creating WebDriver object
	at io.github.bonigarcia.wdm.webdriver.WebDriverCreator.createRemoteWebDriver(WebDriverCreator.java:95)
	at io.github.bonigarcia.wdm.WebDriverManager.createDockerWebDriver(WebDriverManager.java:1897)
	at io.github.bonigarcia.wdm.WebDriverManager.instantiateDriver(WebDriverManager.java:1755)
	... 71 common frames omitted
Caused by: java.net.SocketException: Connection reset
	at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:323)
	at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:350)
	at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:803)
	at java.base/java.net.Socket$SocketInputStream.read(Socket.java:966)
	at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:244)
	at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
	at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:343)
	at java.base/sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:824)
	at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:759)
	at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:783)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1688)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
	at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:529)
	at io.github.bonigarcia.wdm.webdriver.WebDriverCreator.createRemoteWebDriver(WebDriverCreator.java:85)
	... 73 common frames omitted


```

**Comment by MariusDK** [comment]
Strange is that if I use pin version 104.0 it's working.

**Comment by bonigarcia** [comment]
Not sure if it is related to this issue, but I experienced a problem with the latest version of Edge in Docker recently. That problem is solved in WebDriverManager 5.3.2, just released. Can you please give a try with that version?

**Comment by MariusDK** [comment]
I'm using jenkins (os linux).
I've checked also the 5.3.2 version and still from chrome image 105 the server seems to not respond:
`huc.connect();` in `WebDriverCreator`, I increased the timeout still `Connection reset`. (I added also 
`<logger name="io.github.bonigarcia" level="TRACE" />`
From chrome image bellow 105 everything is working. 

Locally the problem on (os.name: 'Mac OS X', os.arch: 'aarch64', os.version: '12.3') appears for all the chrome versions:

`Could not start a new session. Response code 500. Message: unknown error: Chrome failed to start: was killed.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.) 
`

So the process /usr/bin/google-chrome stops. 

Let me know if I'm missing something, I saw that there is another issue with the local problem same as this one.

**Comment by bonigarcia** [comment]
I am unable to reproduce this issue. I run  this [test](https://github.com/bonigarcia/webdrivermanager-basic/blob/master/src/test/java/io/github/bonigarcia/wdm/test/DockerChromeTest.java) (on Linux), which uses the latest version of Chrome in Docker at this moment (109), ant it works as expected. This is its output:

``` 
2023-01-26 09:51:25 [main] DEBUG i.g.b.wdm.docker.DockerService.getImageVersionFromDockerHub(471) - The latest version of Chrome in Docker Hub is 109.0
2023-01-26 09:51:25 [main] INFO  i.g.b.wdm.docker.DockerService.pullImageIfNecessary(330) - Pulling Docker image selenoid/vnc:chrome_109.0 (this might take some time, but only the first time)
2023-01-26 09:51:27 [main] DEBUG i.g.b.wdm.cache.ResolutionCache.putValueInResolutionCacheIfEmpty(119) - Storing resolution chrome-container-latest=109.0 in cache (valid until 10:51:27 26/01/2023 CET)
2023-01-26 09:51:27 [main] INFO  i.g.b.wdm.docker.DockerService.startContainer(177) - Starting Docker container selenoid/vnc:chrome_109.0
2023-01-26 09:51:27 [main] DEBUG i.g.b.wdm.webdriver.WebDriverCreator.createRemoteWebDriver(77) - Creating WebDriver object for chrome at http://localhost:32768/ with Capabilities {browserName: chrome, goog:chromeOptions: {args: [--disable-gpu], extensions: []}}
Jan 26, 2023 9:51:28 AM org.openqa.selenium.remote.tracing.opentelemetry.OpenTelemetryTracer createTracer
INFO: Using OpenTelemetry for tracing
2023-01-26 09:51:29 [main] DEBUG i.g.b.wdm.webdriver.WebDriverCreator.getSessionId(115) - The sessionId is 36da597033b742e394db0f42baa4d94a
2023-01-26 09:51:30 [main] DEBUG i.g.bonigarcia.wdm.WebDriverManager.quit(965) - Quitting RemoteWebDriver: chrome on LINUX (36da597033b742e394db0f42baa4d94a)
2023-01-26 09:51:30 [main] INFO  i.g.b.wdm.docker.DockerService.stopAndRemoveContainer(354) - Stopping Docker container selenoid/vnc:chrome_109.0

```

**Comment by MariusDK** [comment]
I will run the same test with jenkins to see if it's a project or a infrastructure problem.

**Comment by MariusDK** [comment]
2023-02-06 08:46:55 TRACE i.g.b.w.d.DockerService:517 - Docker image: selenoid/vnc:chrome_109.0
2023-02-06 08:46:55 DEBUG i.g.b.w.c.ResolutionCache:186 - Resolution chrome-container-latest=109.0 in cache (valid until 09:06:28 06/02/2023 UTC)
2023-02-06 08:46:55 TRACE i.g.b.w.c.Config:1142 - The memory size 256m is equivalent to 268435456 bytes)
2023-02-06 08:46:55 TRACE i.g.b.w.c.Config:1142 - The memory size 128m is equivalent to 134217728 bytes)
2023-02-06 08:46:55 INFO  i.g.b.w.d.DockerService:177 - Starting Docker container selenoid/vnc:chrome_109.0
2023-02-06 08:46:55 TRACE i.g.b.w.d.DockerService:190 - Adding sysadmin capability
2023-02-06 08:46:55 TRACE i.g.b.w.d.DockerService:196 - Using shm size: 268435456
2023-02-06 08:46:55 TRACE i.g.b.w.d.DockerService:202 - Using network: bridge
2023-02-06 08:46:55 TRACE i.g.b.w.d.DockerService:207 - Using exposed ports: [4444]
2023-02-06 08:46:55 TRACE i.g.b.w.d.DockerService:216 - Using binds: []
2023-02-06 08:46:55 TRACE i.g.b.w.d.DockerService:222 - Using mounts: [Mount(type=TMPFS, source=null, target=/tmp, readOnly=null, bindOptions=null, volumeOptions=null, tmpfsOptions=TmpfsOptions(sizeBytes=134217728, mode=null))]
2023-02-06 08:46:55 TRACE i.g.b.w.d.DockerService:228 - Using envs: [TZ=Etc/UTC, LANGUAGE=EN, SCREEN_RESOLUTION=1280x1080x24, DRIVER_ARGS=--whitelisted-ips= --allowed-origins=*]
2023-02-06 08:46:56 TRACE i.g.b.w.d.DockerService:294 - Port list {4444/tcp=[Lcom.github.dockerjava.api.model.Ports$Binding;@2d877b2c} -- Exposed port 4444/tcp = [0.0.0.0:49155]
2023-02-06 08:46:56 TRACE i.g.b.w.d.DockerService:693 - Browser remote URL http://localhost:49155/
2023-02-06 08:46:56 TRACE i.g.b.w.WebDriverManager:1893 - The Selenium Serverl URL is http://localhost:49155/
2023-02-06 08:46:56 DEBUG i.g.b.w.w.WebDriverCreator:77 - Creating WebDriver object for chrome at http://localhost:49155/ with Capabilities {browserName: chrome, goog:chromeOptions: {args: [--disable-gpu], extensions: []}}
2023-02-06 08:46:56 TRACE i.g.b.w.w.WebDriverCreator:92 - SocketException creating WebDriver object (Unexpected end of file from server)
2023-02-06 08:46:57 TRACE i.g.b.w.w.WebDriverCreator:92 - SocketException creating WebDriver object (Connection reset)
2023-02-06 08:46:58 TRACE i.g.b.w.w.WebDriverCreator:92 - SocketException creating WebDriver object (Unexpected end of file from server)
2023-02-06 08:46:59 TRACE i.g.b.w.w.WebDriverCreator:92 - SocketException creating WebDriver object (Connection reset)
2023-02-06 08:47:00 TRACE i.g.b.w.w.WebDriverCreator:92 - SocketException creating WebDriver object (Unexpected end of file from server)
2023-02-06 08:47:01 TRACE i.g.b.w.w.WebDriverCreator:92 - SocketException creating WebDriver object (Connection reset)
2023-02-06 08:47:02 TRACE i.g.b.w.w.WebDriverCreator:92 - SocketException creating WebDriver object (Unexpected end of file from server)
2023-02-06 08:47:03 TRACE i.g.b.w.w.WebDriverCreator:92 - SocketException creating WebDriver object (Connection reset)
2023-02-06 08:47:04 TRACE i.g.b.w.w.WebDriverCreator:92 - SocketException creating WebDriver object (Unexpected end of file from server)
2023-02-06 08:47:05 TRACE i.g.b.w.w.WebDriverCreator:92 - SocketException creating WebDriver object (Connection reset)
2023-02-06 08:47:06 TRACE i.g.b.w.w.WebDriverCreator:92 - SocketException creating WebDriver object (Unexpected end of file from server)
2023-02-06 08:47:07 TRACE i.g.b.w.w.WebDriverCreator:92 - SocketException creating WebDriver object (Connection reset)
2023-02-06 08:47:08 TRACE i.g.b.w.w.WebDriverCreator:92 - SocketException creating WebDriver object (Unexpected end of file from server)
2023-02-06 08:47:09 TRACE i.g.b.w.w.WebDriverCreator:92 - SocketException creating WebDriver object (Unexpected end of file from server)
2023-02-06 08:47:10 TRACE i.g.b.w.w.WebDriverCreator:92 - SocketException creating WebDriver object (Connection reset)
2023-02-06 08:47:11 TRACE i.g.b.w.w.WebDriverCreator:92 - SocketException creating WebDriver object (Connection reset)
2023-02-06 08:47:12 TRACE i.g.b.w.w.WebDriverCreator:92 - SocketException creating WebDriver object (Connection reset)
2023-02-06 08:47:13 TRACE i.g.b.w.w.WebDriverCreator:92 - SocketException creating WebDriver object (Connection reset)
2023-02-06 08:47:14 TRACE i.g.b.w.w.WebDriverCreator:92 - SocketException creating WebDriver object (Unexpected end of file from server)
2023-02-06 08:47:15 TRACE i.g.b.w.w.WebDriverCreator:92 - SocketException creating WebDriver object (Connection reset)
2023-02-06 08:47:16 TRACE i.g.b.w.w.WebDriverCreator:92 - SocketException creating WebDriver object (Unexpected end of file from server)
2023-02-06 08:47:17 TRACE i.g.b.w.w.WebDriverCreator:92 - SocketException creating WebDriver object (Unexpected end of file from server)
2023-02-06 08:47:18 TRACE i.g.b.w.w.WebDriverCreator:92 - SocketException creating WebDriver object (Unexpected end of file from server)
2023-02-06 08:47:19 TRACE i.g.b.w.w.WebDriverCreator:92 - SocketException creating WebDriver object (Connection reset)
2023-02-06 08:47:20 TRACE i.g.b.w.w.WebDriverCreator:92 - SocketException creating WebDriver object (Connection reset)
2023-02-06 08:47:21 TRACE i.g.b.w.w.WebDriverCreator:92 - SocketException creating WebDriver object (Connection reset)
2023-02-06 08:47:22 TRACE i.g.b.w.w.WebDriverCreator:92 - SocketException creating WebDriver object (Connection reset)
2023-02-06 08:47:23 TRACE i.g.b.w.w.WebDriverCreator:92 - SocketException creating WebDriver object (Connection reset)
2023-02-06 08:47:24 TRACE i.g.b.w.w.WebDriverCreator:92 - SocketException creating WebDriver object (Unexpected end of file from server)
2023-02-06 08:47:25 TRACE i.g.b.w.w.WebDriverCreator:92 - SocketException creating WebDriver object (Connection reset)
2023-02-06 08:47:26 TRACE i.g.b.w.w.WebDriverCreator:92 - SocketException creating WebDriver object (Unexpected end of file from server)
2023-02-06 08:47:26 INFO  i.g.b.w.d.DockerService:354 - Stopping Docker container selenoid/vnc:chrome_109.0
2023-02-06 08:47:26 TRACE i.g.b.w.d.DockerService:370 - Stopping container 1f89ea7c863d518404e0eb8b5387f0cf5a2a05e8d7dd28d0424cdadbcbe96018 (timeout 5 seconds)
2023-02-06 08:47:31 TRACE i.g.b.w.d.DockerService:379 - Removing container 1f89ea7c863d518404e0eb8b5387f0cf5a2a05e8d7dd28d0424cdadbcbe96018
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 37.871 s <<< FAILURE! - in tests.DockerChromeTest
[ERROR] test  Time elapsed: 37.81 s  <<< ERROR!
io.github.bonigarcia.wdm.config.WebDriverManagerException: There was an error creating WebDriver object for Chrome
	at tests.DockerChromeTest.setupTest(DockerChromeTest.java:22)
Caused by: io.github.bonigarcia.wdm.config.WebDriverManagerException: Timeout of 30 seconds creating WebDriver object
	at tests.DockerChromeTest.setupTest(DockerChromeTest.java:22)
Caused by: java.net.SocketException: Unexpected end of file from server
	at tests.DockerChromeTest.setupTest(DockerChromeTest.java:22)

**Comment by MariusDK** [comment]
Running the DockerChromeTest via jenkins logs

**Comment by ASuhail8** [comment]
> I am unable to reproduce this issue. I run this [test](https://github.com/bonigarcia/webdrivermanager-basic/blob/master/src/test/java/io/github/bonigarcia/wdm/test/DockerChromeTest.java) (on Linux), which uses the latest version of Chrome in Docker at this moment (109), ant it works as expected. This is its output:
> 
> ```
> 2023-01-26 09:51:25 [main] DEBUG i.g.b.wdm.docker.DockerService.getImageVersionFromDockerHub(471) - The latest version of Chrome in Docker Hub is 109.0
> 2023-01-26 09:51:25 [main] INFO  i.g.b.wdm.docker.DockerService.pullImageIfNecessary(330) - Pulling Docker image selenoid/vnc:chrome_109.0 (this might take some time, but only the first time)
> 2023-01-26 09:51:27 [main] DEBUG i.g.b.wdm.cache.ResolutionCache.putValueInResolutionCacheIfEmpty(119) - Storing resolution chrome-container-latest=109.0 in cache (valid until 10:51:27 26/01/2023 CET)
> 2023-01-26 09:51:27 [main] INFO  i.g.b.wdm.docker.DockerService.startContainer(177) - Starting Docker container selenoid/vnc:chrome_109.0
> 2023-01-26 09:51:27 [main] DEBUG i.g.b.wdm.webdriver.WebDriverCreator.createRemoteWebDriver(77) - Creating WebDriver object for chrome at http://localhost:32768/ with Capabilities {browserName: chrome, goog:chromeOptions: {args: [--disable-gpu], extensions: []}}
> Jan 26, 2023 9:51:28 AM org.openqa.selenium.remote.tracing.opentelemetry.OpenTelemetryTracer createTracer
> INFO: Using OpenTelemetry for tracing
> 2023-01-26 09:51:29 [main] DEBUG i.g.b.wdm.webdriver.WebDriverCreator.getSessionId(115) - The sessionId is 36da597033b742e394db0f42baa4d94a
> 2023-01-26 09:51:30 [main] DEBUG i.g.bonigarcia.wdm.WebDriverManager.quit(965) - Quitting RemoteWebDriver: chrome on LINUX (36da597033b742e394db0f42baa4d94a)
> 2023-01-26 09:51:30 [main] INFO  i.g.b.wdm.docker.DockerService.stopAndRemoveContainer(354) - Stopping Docker container selenoid/vnc:chrome_109.0
> ```

@bonigarcia can i have the dockerfile for this?

**Comment by bonigarcia** [comment]
@MariusDK I think this is not a WebDriverManager, sorry.

@ASuhail8 I did not use Docker for that execution.
