### ISSUE TITLE
WebDriverManagerException: UnknownHostException

### ISSUE THREAD

**Issue by nicholaswkc34** [bonigarcia/webdrivermanager#991]
**Description of the problem**: When i running the Selenide framework with wdm, I encounter this error
io.github.bonigarcia.wdm.config.WebDriverManagerException: java.net.UnknownHostException: chromedriver.storage.googleapis.com

**Browser and version**: Chrome 110

**Operating system**: Win 10

**WebDriverManager version**: 5.3.0

**WebDriverManager call**: Wrap inside Selenide framework

**WebDriverManager traces**: io.github.bonigarcia.wdm.config.WebDriverManagerException: io.github.bonigarcia.wdm.config.WebDriverManagerException: java.net.UnknownHostException: chromedriver.storage.googleapis.com
	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:1422)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:1203)
	at io.github.bonigarcia.wdm.WebDriverManager.fallback(WebDriverManager.java:1438)
	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:1419)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:1203)

**Error log**: N/A

**Comment by bonigarcia** [comment]
Please bump to the latest versions of Selenide/WebDriverManager. Also, that issue is a connectivity problem at your end. Review your network setup (e.g. proxy).
